src/components/Map/PlantingSiteMap.tsx
src/components/Observations/common/AggregatedPlantsStats.tsx
src/components/Observations/details/ObservationDetailsRenderer.tsx
src/components/Observations/zone/ObservationPlantingZoneRenderer.tsx
src/components/PlantsV2/components/HighestAndLowestMortalityRateZonesCard.tsx
src/components/PlantsV2/components/ZoneLevelDataMap.tsx
src/redux/features/observations/utils.ts
src/services/MapService.ts
src/types/Observations.ts

- capture this state in the model
- leverage that in components

SW-4092 Show mortality rate only when there are observed permanent plots

---

src/components/PlantsV2/index.tsx

- a site is considered full planted iff all it's planting subzones' completed time is before the most recent completed observation

SW-4093 Account for planting completed time in plants dashboard

---

package.json
yarn.lock

SW-4203 Show blobby icons

---

package.json
yarn.lock

- upgrade web-components to pick them up

SW-3618 Use Kaloko themed assets

---

package.json
src/components/People/index.tsx
src/strings/csv/en.csv
yarn.lock

- See web-components PR https://github.com/terraware/web-components/pull/438 for tooltip enhancement
- Will update package.json here once web-components PR is merged/published, Using an rc tag for now
- Also set 'Remove' button type as 'destructive'

SW-4239 Disable 'Remove' button for TF Contact, explain 'why' with a tooltip

---

src/components/Reports/LocationSection.tsx
src/components/common/OverviewItemCard.tsx
src/redux/features/observations/observationsSelectors.ts
src/strings/csv/en.csv

SW-4249 Add plant monitoring details to quarterly partner reports

---

.github/workflows/workflow.yml
src/api/types/generated-schema.ts
src/components/Observations/ObservationsEventsNotification.tsx
src/components/Observations/ObservationsHome.tsx
src/components/Observations/index.tsx
src/components/Observations/org/ActionsMenu.tsx
src/components/Observations/org/OrgObservationsListView.tsx
src/components/Observations/org/OrgObservationsRenderer.tsx
src/components/Observations/schedule/RescheduleObservation.tsx
src/components/Observations/schedule/ScheduleObservation.tsx
src/components/Observations/schedule/ScheduleObservationForm.tsx
src/components/Observations/schedule/index.tsx
src/constants.ts
src/redux/features/asyncUtils.ts
src/redux/features/observations/observationsAsyncThunks.ts
src/redux/features/observations/observationsSelectors.ts
src/redux/features/observations/observationsSlice.ts
src/redux/features/observations/observationsUtilsSelectors.tsx
src/redux/features/plantings/plantingsSlice.ts
src/redux/rootReducer.ts
src/services/ObservationsService.ts
src/strings/csv/en.csv
src/types/Observations.ts

- added service/types/redux to schedule/reschedule observations
- refactored existing code to enable reuse of async reducers

Service/Redux for Schedule/Reschedule Observations

---

src/components/Observations/ObservationsHome.tsx
src/components/Observations/index.tsx
src/components/Observations/org/OrgObservationsListView.tsx
src/features.ts

- this in case we release Tracking V2 before user scheduled observations is feature complete

SW-4274 Opt-in flag to show/hide schedule/reschedule observations

---

src/components/Observations/ObservationsHome.tsx
src/components/Observations/index.tsx
src/components/Observations/org/OrgObservationsListView.tsx

- Admin/Owner alone can access these actions

SW-4300 Gate schedule/reschedule observation actions by permitted role

---

src/components/Observations/map/TooltipContents.tsx

- missed this in my earlier PR

Use opt-in flag to gate request reassignment feature in map tooltip

---

src/components/Inventory/withdraw/BatchWithdrawFlow.tsx
src/components/Inventory/withdraw/flow/AddPhotos.tsx

- See [jira](https://terraformation.atlassian.net/browse/SW-4334) for reason
- Did not remove any strings since they will only get added back right now

SW-4334 Make nusery withdrawals photos optional

---

src/App.tsx
src/api/types/generated-schema.ts
src/components/InventoryV2/BatchDetails.tsx
src/components/InventoryV2/BatchHistory.tsx
src/components/InventoryV2/BatchSummary.tsx
src/components/InventoryV2/InventoryBatch.tsx
src/strings/csv/en.csv

This PR doesn't have the details tab or history tab. It's the details page with the summary on top and the breadcrumb

SW-4394 Create batch details page with empty components for tabs

---

src/components/InventoryV2/FilterUtils.ts
src/components/InventoryV2/InventoryCellRenderer.tsx
src/components/InventoryV2/InventoryFiltersPopover.tsx
src/components/InventoryV2/InventoryListBySpecies.tsx
src/components/InventoryV2/InventoryTable.tsx
src/components/InventoryV2/Search.tsx
src/components/InventoryV2/index.tsx
src/strings/csv/en.csv

- List inventory by species, which is the same as the V1 list
- Mostly copy/pasted from V1
- Placeholders for by-nursery and by-batch

SW-4382 List Inventory by Species

---

src/components/InventoryV2/BatchDetails.tsx
src/components/InventoryV2/BatchDetailsModal.tsx
src/components/InventoryV2/InventoryBatch.tsx
src/services/NurseryBatchService.ts
src/strings/csv/en.csv
src/types/Batch.ts

- Show all batch's details in Details tab, including photos
- Open Edit Details modal when clicking edit button
- Allow editing batch details in modal
- Allow adding/removing photos from details modal

SW-4394 Batch Details tab

---

src/components/Observations/ObservationsDataView.tsx
src/components/Observations/org/OrgObservationsListView.tsx

- See [JIRA](https://terraformation.atlassian.net/browse/SW-3999)

SW-4053 Show planting site name and end date in observations table, remove subzones

---

src/components/Observations/ObservationsHome.tsx
src/components/Observations/index.tsx
src/components/Observations/org/OrgObservationsListView.tsx
src/features.ts

SW-4430 Remove opt-in flag for user scheduled observations

---

src/components/NewNursery/index.tsx
src/components/NewSeedBank/index.tsx
src/components/Nursery/NurserySubLocations.tsx
src/components/Nursery/index.tsx
src/components/common/SubLocations/index.tsx
src/services/SubLocationService.ts
src/strings/csv/en.csv

- extracted out saving of edited sublocations to service (from seedbank component)
- added sublocations component and saving logic in nursery (create, view and edit)

SW-4443 Add sub-locations to nursery details

---

package.json
public/index.html
src/components/Inventory/InventoryCreate.tsx
src/components/NurseryWithdrawals/NurseryReassignment.tsx
src/components/Observations/org/OrgObservationsListView.tsx
src/components/Plants/components/NumberOfSpeciesPlantedCard.tsx
src/components/Plants/components/PlantsReportedPerSpeciesCard.tsx
src/components/accession2/create/Accession2Create.tsx
src/components/accession2/properties/FacilitySelector.tsx
src/components/accession2/viabilityTesting/NewViabilityTestModal.tsx
src/components/accession2/withdraw/WithdrawModal.tsx
src/components/common/FilterGroup/filters/FilterSingleSelection.tsx
src/components/common/ImportModal.tsx
src/components/seeds/database/columns.ts
src/index.css
src/redux/features/observations/observationsUtilsSelectors.tsx
src/redux/features/observations/utils.ts
src/redux/features/tracking/sitePopulationSelector.ts
src/services/axios/index.ts
yarn.lock

- latest version modified formatting on existing code

Add prettier dependency in package.json

---

src/components/Inventory/withdraw/flow/AddPhotos.tsx

SW-4409 Change withdrawal string to reflect optional photo upload

---

src/components/NurseryWithdrawals/WithdrawalDetails/sections/NonOutplantWithdrawalTable.tsx
src/components/NurseryWithdrawals/WithdrawalDetails/sections/WithdrawalRenderer.tsx
src/strings/csv/en.csv

Adding batch number to Nursery Transfer

SW-4406 Adding batch number to withdrawal log 

---

src/components/Inventory/withdraw/flow/SelectPurposeForm.tsx

- disable outplant if there are no planting sites
- disable nursery transfer if there are no nurseries to transfer to
- update initial purpose value such that it's not pointing to a disabled purpose
- refactor code to use planting sites in redux store (App already dispatches the request)
- refactor code to use memoized nurseries options so it's not calculated on every render

SW-4450 Disable withdrawal purposes that aren't relevant

---

src/components/accession2/withdraw/WeightWithdrawal.tsx

Had an error in one of the error checking conditions and needed to round the estimated count.

SW-3157 Address QA findings

---

src/components/Inventory/InventoryCreate.tsx

SW-4387 Add Sub-locations to Add inventory flow

---

src/components/Observations/map/TooltipContents.tsx
src/components/Observations/zone/index.tsx
src/features.ts

SW-4431 Remove FE opt-in flag for replace monitoring plot feature

---

src/components/InventoryV2/InventoryListByNursery.tsx
src/components/InventoryV2/InventoryTable.tsx
src/components/InventoryV2/index.tsx
src/services/NurseryInventoryService.ts

Use same InventoryTable from inventoryBySpecies but change columns and filter results according to what is needed

SW-4383 List Inventory by Nursery

---

src/api/types/generated-schema.ts
src/services/OrganizationService.ts
src/strings/csv/en.csv
src/types/Organization.ts

- also update the service functions to create/update with new properties
- this is pending BE PR approvals, just a head-start for FE

SW-4459 Update types and helper functions  in FE to capture organization type

---

src/features.ts

I probably should have asked a while ago... how do I enable this locally without modifying this file?

I accidentally committed this! Reversing it back to how it was

---

src/components/EditOrganization/index.tsx
src/components/Organization/index.tsx
src/strings/csv/en.csv

- updated view and edit components
- also fixed the reload organization data call such that it shows latest updated info

SW-4460 Support view/edit of the new organization type properties

---

src/App.tsx
src/components/InventoryV2/InventoryBatch.tsx
src/components/InventoryV2/InventoryCellRenderer.tsx
src/components/InventoryV2/InventoryListByBatch.tsx
src/components/InventoryV2/InventoryListByNursery.tsx
src/components/InventoryV2/InventoryListBySpecies.tsx
src/components/InventoryV2/index.tsx
src/constants.ts
src/services/NurseryBatchService.ts
src/strings/csv/en.csv

- Create table view for batches_by_batch
- Link batchNumber column to batch details page
- Create method in service to get all batches
- With nursery filter
- With search

SW-4384 List Nursery Batches by Batch

---

public/index.html
src/components/Home.tsx
src/components/common/PageCard.tsx

We'd like to see how much users are using the home cards vs the left nav.  This will be paired with an additional GTM tag to track clicks.

SW-4472 Add some IDs so we can track home card clicks

---

src/components/MyAccount/index.tsx

I wasn't sure if this is what we wanted here:

SW-3933 Fix input elements are as wide as the orgs table

---

src/components/InventoryV2/InventoryCellRenderer.tsx
src/components/InventoryV2/InventoryListByBatch.tsx
src/components/InventoryV2/InventoryListByNursery.tsx
src/components/InventoryV2/InventoryListBySpecies.tsx
src/components/InventoryV2/InventoryTable.tsx

- Add table row menu
- Change quantities from menu
- Row click on checkbox only
- Refresh table after changes

SW-4385 Change Batch Status

---

package.json
src/components/Species/DeleteSpeciesModal.tsx
src/strings/csv/en.csv
yarn.lock

- remove 'Nothing to delete' text
- use latest web-components for scrollable TextTruncated tooltip

SW-4431 Species delete modal updates

---

src/App.tsx
src/components/Inventory/InventoryFiltersPopover.tsx
src/components/InventoryV2/InventoryBatch.tsx
src/components/InventoryV2/InventoryFiltersPopover.tsx
src/components/InventoryV2/InventoryListByBatch.tsx
src/components/InventoryV2/InventoryListByNursery.tsx
src/components/InventoryV2/InventoryListBySpecies.tsx
src/components/InventoryV2/InventoryTable.tsx
src/components/InventoryV2/Search.tsx

SW-4386 Show/Hide Empty Batches

---

src/components/InventoryV2/InventoryCellRenderer.tsx
src/components/InventoryV2/InventoryListByBatch.tsx
src/components/InventoryV2/InventoryListBySpecies.tsx
src/components/InventoryV2/index.tsx
src/services/NurseryBatchService.ts

SW-4484 Add SubLocations Column

---

src/components/InventoryV2/InventoryFilter.tsx
src/components/InventoryV2/InventoryListByBatch.tsx
src/components/InventoryV2/InventoryTable.tsx
src/components/InventoryV2/Search.tsx
src/redux/features/subLocations/subLocationsSelectors.ts
src/redux/features/subLocations/subLocationsSlice.ts
src/redux/features/subLocations/subLocationsThunks.ts
src/redux/rootReducer.ts

- Add SubLocations Redux
- In the InventoryListByBatch page get filters from query
- Look up sublocations and apply filters
- When filters change update the URL query

SW-4484 Update Filters from URL Search Params

---

src/components/InventoryV2/InventoryListByBatch.tsx

Use multiple query params instead of a comma-separated list in one param.

Improve Batches Search Query

---

src/components/ProjectView/index.tsx
src/redux/features/projects/projectsSelectors.ts
src/redux/features/projects/projectsSlice.ts
src/redux/features/projects/projectsThunks.ts
src/services/ProjectsService.ts

Pull project data into project view and render name and description

---

src/App.tsx

This only seems to be causing issues for local development with the project feature enabled.

Fix the routing _after_ projects. All routes after projects are currently broken

---

src/App.tsx
src/components/Reports/ReportList.tsx
src/components/Reports/ReportListV2.tsx

- Add tab view to the reports page, stub out settings tab
- Put new reports view behind projects feature flag

Add tab view to the reports page, stub out settings tab

---

src/components/InventoryV2/view/InventorySeedlingsTableForNursery.tsx
src/components/InventoryV2/view/InventorySeedlingsTableForSpecies.tsx
src/services/NurseryBatchService.ts

The table does not look exactly like the mock ups, but for now we are going to allow the headers to collapse a bit and fix the table scrolling issue later

Add Project column to the inventory table for species and nursery

---

src/components/InventoryV2/InventoryFilter.tsx
src/components/InventoryV2/Search.tsx

Add showProjectsFilter to Search component used within all the inventory tables, show Projects featured filter when the property is true
Add projectIds to inventory filters type

Add showProjectsFilter to Search component used within all the inventory tables, show Projects featured filter when the property is true

---

src/redux/features/batches/batchesAsyncThunks.ts
src/redux/features/batches/batchesSelectors.ts
src/redux/features/batches/batchesSlice.ts
src/redux/rootReducer.ts

- Using the `createAsyncThunk` redux utility

Add redux state for batch creation requests, add request to create batch

---

src/components/InventoryV2/BatchDetailsModal.tsx

Fix issue with germinatingQuantity width in edit batch view modal

---

src/App.tsx
src/components/InventoryV2/InventoryCreateView.tsx
src/redux/features/batches/batchesAsyncThunks.ts
src/redux/features/batches/batchesSlice.ts

- Brings the form up to date with the batch details that we have implemented in other areas.

Implement InventoryCreateView which uses the new BatchDetailsForm

---

src/components/seeds/database/index.tsx

- fix code to maintain unique columns, typo

SW-4568 Fix redundant sublocation column in accessions table

---

src/components/InventoryV2/BatchSummary.tsx

Add Link for accession in batch details page

---

src/components/InventoryV2/InventoryTable.tsx

- to support persisting changes in column ordering

SW-4585 Use unique table ids in inventory v2 table views

---

src/components/PlantingSites/PlantingSiteSelectTypeModal2.tsx

- with new info from Chudo
- also refactored the component into 2, a selector and a button

SW-4571 Update site selection buttons with active/hover/selected styles

---

src/components/InventoryV2/index.tsx

Use user preferences to store and lookup the tab that was last visited.

SW-4575 Remember Last Inventory Tab

---

src/components/InventoryV2/form/BatchDetailsForm.tsx

- Add `.` to disabled characters for quantity textfields

SW-4580 Disallow Floating Point Quantities in Add Inventory

---

package.json
src/components/PlantingSites/BoundariesAndZones.tsx
src/components/PlantingSites/PlantingSeasonsEdit.tsx
src/components/PlantingSites/PlantingSiteCreate.tsx
src/strings/csv/en.csv
src/types/Tracking.ts
yarn.lock

Add an editable list of planting seasons to the planting site edit page for
detailed planting sites.

SW-4416 Add planting season editor

---

src/components/InventoryV2/Search.tsx
src/components/common/FilterGroup/filters/FilterBoolean.tsx

- Correctly update filter state

SW-4583 Inventory Batches Filter Reset

---

src/components/ProjectAssignModal/index.tsx
src/components/accession2/view/ProjectSelectorModal.tsx
src/strings/csv/en.csv

Create ProjectAssignModal that allows any project-assignable-entity to easily add a link and modal to assign an entity to a project from the available projects for an organization.
'Add to Project' string

SW-4494 Create ProjectAssignModal which allows for assigning entity to project

---

src/components/ProjectAssignModal/index.tsx
src/components/accession2/view/Accession2View.tsx

SW-4494 Add the ProjectAssignModal to the Accession summary view, behind feature flag

---

src/components/InventoryV2/InventoryBatch.tsx

SW-4587 Do not show withdraw button if the batch is not withdrawable

---

src/components/InventoryV2/BatchDetails.tsx
src/components/InventoryV2/InventoryTable.tsx
src/components/InventoryV2/Search.tsx
src/components/common/OverviewItemCard.tsx

Style updates to match designs.

SW-4548 / SW-4556 Fix spacing of filter pills and batch details cards

---

src/components/seeds/database/EditColumns.tsx
src/components/seeds/database/Filters.tsx
src/components/seeds/database/columns.ts
src/components/seeds/database/index.tsx

SW-4493 Add project_name column and multi select filter to the accession table

---

src/components/ProjectAssignModal/index.tsx
src/components/ProjectOverviewItemCard/index.tsx
src/components/accession2/view/Accession2View.tsx

SW-4496 Implement project edit from accession view project overview card

---

src/components/PlantingSites/PlantingSiteSelectTypeModal2.tsx

Fix planting site type selected button background color on hover/active states

---

src/components/InventoryV2/InventoryFilter.tsx
src/components/InventoryV2/InventoryListByBatch.tsx
src/components/InventoryV2/Search.tsx
src/components/InventoryV2/view/InventorySeedlingsTable.tsx
src/components/PlantingSites/PlantingSitesTable.tsx
src/components/common/FilterMultiSelect/index.tsx
src/components/common/FilterMultiSelectContainer/index.tsx

- so we can easily use the filter multi select elsewhere (planting sites incoming)

SW-4501 Refactor the InventoryFilter into FilterMultiSelectContainer

---

src/components/PlantingSites/PlantingSitesList.tsx
src/components/PlantingSites/PlantingSitesTable.tsx

SW-4501 Add projects filter and project name column to planting sites table

---

src/components/InventoryV2/BatchSummary.tsx

- use grid size of 12 for mobile

SW-4616 Fix batch details view for mobile

---

src/components/InventoryV2/form/BatchDetailsForm.tsx

SW-4621 Reduce spacing between items in the batch details form

---

src/components/InventoryV2/EventDetailsModal.tsx

SW-4618 Decrease vertical margin in batch event details modal

---

src/components/InventoryV2/InventoryCreateView.tsx
src/components/InventoryV2/form/AccessionsDropdown.tsx
src/components/InventoryV2/form/BatchDetailsForm.tsx
src/components/InventoryV2/form/useAccessions.ts
src/components/InventoryV2/view/BatchDetailsModal.tsx
src/components/InventoryV2/view/OverviewItemCardSubLocations.tsx
src/redux/features/batches/batchesAsyncThunks.ts

- Use the new accessions redux search within the useAccessions hook
- Add accession ID and species ID validation to the batch save request flow

SW-4623 Validate accession and species when saving a new batch 

---

src/components/InventoryV2/form/BatchDetailsForm.tsx
src/components/InventoryV2/form/useSubLocations.ts

- also update sublocations when the selected facility id changes
- clear selected sublocations when sublocations change

SW-4578 / SW-4646 Hide sublocations when there are no selections

---

src/utils/useQueryFilters.spec.ts
src/utils/useQueryFilters.ts
tsconfig.json

SW-4617 Added useQueryFilter hook that syncs between a consumer's filters and the query string in the address bar

SW-4617 Added useQueryFilter hook that syncs between a consumer's filters and the query string in the address bar

---

src/components/Inventory/withdraw/flow/SelectBatchesWithdrawnQuantity.tsx

SW-4518 Add project name column to 'select batch quantites for withdrawal' table

---

src/components/InventoryV2/Search.tsx

Since filters are sticky now, only show filter pills relevant to the view.

SW-4617 Only show sub locations relevant to the filtered facility in the inventory search component

---

src/components/InventoryV2/InventoryListByBatch.tsx

- The query param logic is baked into the InventoryTable (in a later PR) for all filters.
- The sub location scrubbing is baked into the Search component (in a later PR) which is where facilities are being populated and selected.

SW-4617 Remove the query param and sub location filtering within the inventory list of batches

---

src/components/seeds/database/TableCellRenderer.tsx
src/components/seeds/database/index.tsx

SW-4503 Add selection to accessions table
Only make the rows selectable when the projects feature flag is on

SW-4503 Add selection to accessions table

---

src/components/InventoryV2/InventoryBatch.tsx

- similar to accessions mobile view

SW-4616 Use full width withdraw button in mobile mode batch details view

---

src/services/SpeciesService.ts

- sort by scientific name ascending

SW-4659 Sort species entries for dropdown values

---

src/components/InventoryV2/InventoryCreateView.tsx
src/components/InventoryV2/view/BatchDetailsModal.tsx
src/components/common/PageForm.tsx

SW-4666 Add spinners to show busy state when creating nursery inventory

---

src/components/InventoryV2/InventoryBatch.tsx
src/components/InventoryV2/index.tsx

- be less vulnerable to unsupported values

Use a more robust way to initialize tab values in inventory views

---

src/components/InventoryV2/form/BatchDetailsForm.tsx

- was using the raw value for display and localized value for comparison, switched that around now

SW-4647 Fix display versus comparsion values for accession remaining quantity in inventory create validation

---

src/components/FeatureNotification/OrganizationNotification.tsx
src/components/FeatureNotification/UserNotification.tsx

- was large at 16px, fixed to 14px now

Fix link font size in app notifications

---

src/utils/useQueryFilters.ts

- the keys iteration was not working in useQueryFilters

SW-4675 Fix filters not working in nursery views

---

src/components/InventoryV2/view/InventorySummaryForSpecies.tsx

SW-4498 Add Projects overview card on species page

---

src/components/Reports/ReportsView.tsx
src/components/Reports/TableCellRenderer.tsx

SW-4521 When projects feature is on, add org name for non-project reports in report table. Show project name and org name in report table

---

src/components/InventoryV2/BatchDetails.tsx

SW-4650 Add the ability to change status of plants from batch details

---

src/components/Map/EditableMapDrawV2.tsx
src/components/Map/EditableMapV2.tsx
src/components/Map/Map.tsx
src/components/Map/PlantingSiteMap.tsx
src/components/Map/UndoRedoBoundaryControl.tsx
src/components/Map/useRenderAttributes.ts
src/components/Map/utils.ts
src/components/PlantingSites/createSite/PlantingSiteBoundary.tsx
src/components/PlantingSites/createSite/PlantingSiteCreateFlow.tsx
src/components/PlantingSites/createSite/PlantingSiteExclusions.tsx
src/hooks/useUndoRedoState.ts
src/types/Map.ts

- have basic interactions working
- more work in followup PRs
- made a copy of EditableMap code into v2 versions and worked on that
- refactored some code for reusability

SW-4544 Editable map intermediate effort with undo/redo

---

src/components/InventoryV2/BatchHistory.tsx
src/components/InventoryV2/BatchHistoryRenderer.tsx
src/components/InventoryV2/EventDetailsModal.tsx

StatusChanged are handled the same as QuantityEdited events

SW-4680 Handle StatusChanged batch history items

---

src/components/Reports/ReportEdit.tsx
src/components/Reports/ReportForm.tsx
src/components/Reports/ReportView.tsx

- Add project name to the report view and edit
- Display nursery, planting site, and seed bank name (instead of checkbox) when it is a project report

SW-4522 Add project name to the report view and edit

---

src/components/ProjectAssignModal/index.tsx
src/components/ProjectEditView/index.tsx
src/components/ProjectNewView/flow/ProjectEntitySearch.tsx
src/components/ProjectNewView/flow/SelectAccessions.tsx
src/components/ProjectNewView/flow/SelectBatches.tsx
src/components/ProjectNewView/flow/SelectPlantingSites.tsx
src/components/ProjectOverviewItemCard/index.tsx
src/components/ProjectView/DeleteConfirmationDialog.tsx
src/components/ProjectView/index.tsx
src/components/Projects/index.tsx

Lots of minor fixes for Projects feature.  Mostly styling with a couple small functional changes.

SW-4721 / SW-4722 / SW-4725 / SW-4726 / SW-4729 / SW-4738 / SW-4739 / SW-4746 / SW-4748

---

src/components/PageSnackbar.tsx

- was removed as part of removing Recoil, by mistake perhaps
- bringing it back

SW-4719 Resurrect app version checker

---

src/components/InventoryV2/BatchDetailsModal.tsx

SW-4741 Lessen batch details modal spacing

---

docker-compose.yml
src/App.tsx
src/ErrorBoundary.tsx
src/components/NavBar.tsx
src/scenes/NoOrgRouter/index.tsx
src/scenes/TerrawareRouter/index.tsx

SW-4761 Create NoOrgRouter and TerrawareRouter which each provide clean separation of their included views
Remove unused import

SW-4761 Create NoOrgRouter and TerrawareRouter which each provide clean separation of their included views

---

src/components/ProjectNewView/flow/ProjectEntitySearch.tsx

SW-4728 Do not show projects dropdown during project creation flow if there are no projects

---

src/components/seeds/database/Filters.tsx
src/components/seeds/database/index.tsx

SW-4728 Remove project filter if there are no projects within the accessions view

---

src/scenes/InventoryRouter/Search.tsx

SW-4728 Do not show projects filter in inventory table views when there are no projects, refresh projects when the component loads

---

src/components/PlantingSites/editor/Exclusions.tsx

- missed this when I refactored undo/redo

SW-4793 Fix undo/redo in exclusions flow

---

src/scenes/InventoryRouter/InventoryTable.tsx
src/scenes/InventoryRouter/view/InventorySeedlingsTable.tsx

- Make 'withdraw' the right-most button it it exists with the 'assign to project' bulk action button

SW-4754 Rearrange 'assign to project' bulk action button

---

src/components/seeds/database/Filters.tsx

SW-4730 Add 'not present' filter checkbox for projects in accessions table

---

package.json
src/components/common/FilterMultiSelect/index.tsx
src/components/common/FilterMultiSelectContainer/index.tsx
yarn.lock

SW-4772 Implement the layered onBlur effect into the FilterMultiSelectContainer

---

src/scenes/PlantingSitesRouter/edit/editor/StepTitleDescription.tsx

- the properties already existed, just needed to hook them up with preferences

SW-4838 Add user preference to not show video tutorial again

---

src/scenes/PlantingSitesRouter/edit/DetailsInputForm.tsx
src/scenes/PlantingSitesRouter/view/BoundariesAndZones.tsx
src/scenes/PlantingSitesRouter/view/GenericSiteView.tsx
src/scenes/PlantingSitesRouter/view/PlantingSiteDetailsTable.tsx
src/scenes/PlantingSitesRouter/view/PlantingSiteView.tsx
src/scenes/PlantingSitesRouter/view/SimplePlantingSite.tsx
src/services/MapService.ts
src/types/Observations.ts
src/types/Tracking.ts
src/utils/useTimeZoneUtils.ts

- generic type is lowest common denominator between sites and draft sites
- most of the planting site specific data like observations is not affected
- next step is to leverage this view to show draft sites which will have similar information

SW-4631 Refactor planting site view to accept a generic type

---

src/api/types/generated-schema.ts
src/scenes/PlantingSitesRouter/edit/editor/Editor.tsx
src/scenes/PlantingSitesRouter/edit/editor/Form.tsx
src/types/PlantingSite.ts
src/types/Tracking.ts
src/utils/draftPlantingSiteUtils.test.ts
src/utils/draftPlantingSiteUtils.ts

- integrate with BE generated types
- define client side types
- added tests for conversion to/from draft to BE payload

SW-4843 Add types for Draft Planting Sites

---

src/components/ProjectsDropdown/index.tsx
src/scenes/AccessionsRouter/Accession2CreateView.tsx

SW-4839 Add the ability to unselect the project in the accession create form

---

src/scenes/AccessionsRouter/Accession2View.tsx

SW-4839 Implement onUnAssign logic in the accession view when a user unselects the project from the summary card modal

---

src/scenes/InventoryRouter/BatchSummary.tsx

SW-4839 Implement onUnAssign for projects in the BatchSummary view

---

src/hooks/useProjects.ts
src/scenes/PlantingSitesRouter/edit/DetailsInputForm.tsx

SW-4850 Allow project unselect from within the planting site view

---

src/redux/features/asyncUtils.ts
src/redux/features/draftPlantingSite/draftPlantingSiteSelectors.ts
src/redux/features/draftPlantingSite/draftPlantingSiteSlice.ts
src/redux/features/draftPlantingSite/draftPlantingSiteThunks.ts
src/redux/rootReducer.ts
src/services/DraftPlantingSiteService.ts
src/utils/draftPlantingSiteUtils.ts

- search will be a separate effort
- also added an option to use the request arg as key when setting state in redux

SW-4844 Redux for draft planting site CRUD

---

src/features.ts

- Nick, do we want to reuse this for the Accelerator Console as well or have 2 flags?

SW-4888 Feature flag for deliverables MVP

---

src/App.tsx
src/components/TopBar/TopBarContent.tsx
src/constants.ts
src/scenes/AcceleratorRouter/AcceleratorDeliverablesEdit.tsx
src/scenes/AcceleratorRouter/AcceleratorDeliverablesList.tsx
src/scenes/AcceleratorRouter/index.tsx
src/scenes/DeliverablesRouter/DeliverablesEdit.tsx
src/scenes/DeliverablesRouter/DeliverablesList.tsx
src/scenes/DeliverablesRouter/DeliverablesView.tsx
src/scenes/DeliverablesRouter/index.tsx
src/scenes/TerrawareRouter/NavBar.tsx
src/scenes/TerrawareRouter/index.tsx

- also gate Accelerator content with feature flag

SW-4889 Add routes/placeholder-components for deliverables

---

src/components/seeds/database/Filters.tsx

- initialize variable to undefined as it was using an `variable ?? value` as assignment

SW-4912 Show filter values in accessions filters

---

src/redux/features/deliverables/deliverablesSelectors.ts
src/redux/features/deliverables/deliverablesSlice.ts
src/redux/features/deliverables/deliverablesThunks.ts
src/redux/rootReducer.ts
src/services/DeliverablesService.ts

- Implement deliverables redux feature
- Implement DeliverableService with mock data
- There are a bunch of TODOs for what needs to be updated when the BE is done
- For now just returning the same dataset regardless of whether the request is made from admin or participant side

SW-4891 Deliverable list redux and mock data

---

src/redux/features/deliverables/deliverablesSelectors.ts
src/redux/features/deliverables/deliverablesSlice.ts
src/redux/features/deliverables/deliverablesThunks.ts
src/redux/rootReducer.ts
src/services/DeliverablesService.ts

- Implement redux for single deliverable
- Add method to DeliverableService that returns mock data for now
- Only 1 mock document added for now
Wired it up in a random view to verify the dispatch / select work as expected:

SW-4891 Single Deliverable redux and mock data

---

src/components/DeliverableView/Description.tsx
src/components/DeliverableView/DocumentsList.tsx
src/components/DeliverableView/DocumentsUploader.tsx
src/components/DeliverableView/StatusBar.tsx
src/components/DeliverableView/TitleBar.tsx
src/components/DeliverableView/types.ts
src/components/DeliverableView/useFetchDeliverable.ts
src/components/Page/index.tsx
src/redux/features/deliverables/deliverablesAsyncThunks.ts
src/redux/features/deliverables/deliverablesSlice.ts
src/scenes/AcceleratorRouter/AcceleratorDeliverablesView.tsx
src/scenes/DeliverablesRouter/DeliverablesView.tsx
src/services/DeliverablesService.ts
src/strings/csv/en.csv
src/types/Deliverables.ts

- leveraged the new redux functions with mock data to fetch the deliverable
- added a hook to capture the dispatch/select
- rendered the category/name/title in TitleBar
- call to action buttons will be in another PR
- I made one small refactor, moved the types to `/types/Deliverables`

SW-4902 Show deliverable title/metadata leveraging redux + mock data

---

src/scenes/TerrawareRouter/NavBar.tsx

- check if org has deliverables and show the menu accordingly

SW-4919 Use service function to gate display of deliverables menu

---

src/components/DeliverableView/TitleBar.tsx
src/services/DeliverablesService.ts
src/types/Deliverables.ts

- this is looking ahead since fetching deliverable by id will return the deliverable schema, which has a project id

Look up project from the project id in the deliverable mock data

---

src/components/common/FilterMultiSelectContainer/index.tsx
src/components/common/SearchFiltersWrapperV2/FeaturedFilters.tsx
src/components/common/SearchFiltersWrapperV2/IconFilters.tsx
src/components/common/SearchFiltersWrapperV2/index.tsx
src/scenes/InventoryRouter/InventoryFilter.tsx
src/scenes/InventoryRouter/Search.tsx
src/scenes/PlantingSitesRouter/view/PlantingSitesTable.tsx

- Implement v2 for search filters wrapper with isolated icon filters and featured filters
- Will be used in the deliverables table in a future PR
- Story incoming in a future PR

Implement v2 for search filters wrapper with isolated icon filters and featured filters

---

src/App.tsx
src/AppBootstrap.tsx
src/components/TopBar/TopBarContent.tsx
src/providers/OrganizationProvider.tsx

Do not show the organization dropdown if we are in the accelerator console
Do not block app load for organizations bootstrap and remove org query param if we are within the accelerator console

Do not show the organization dropdown if we are in the accelerator console

---

src/components/DeliverableView/DocumentsList.tsx
src/components/DeliverableView/Metadata.tsx
src/components/DeliverableView/MobileMessage.tsx
src/components/DeliverableView/types.ts
src/components/DeliverableView/useFetchDeliverable.ts
src/components/DeliverablesTable/DeliverableCellRenderer.tsx
src/components/DeliverablesTable/index.tsx
src/hooks/useAcceleratorConsole.ts
src/scenes/AcceleratorRouter/DeliverableViewWrapper.tsx
src/scenes/AcceleratorRouter/DeliverablesList.tsx
src/scenes/AcceleratorRouter/DocumentsList.tsx

- also fixed the hook to return a boolean, otherwise it was returning the matched data whose reference changes on render, triggering re-renders
- removed isAcceleratorConsole from props and plumbing

Replace isAcceleratorConsole flags with useAcceleratorConsole hook

---

package.json
src/components/TopBar/AcceleratorBreadcrumbs.tsx
src/components/TopBar/TopBar.tsx
yarn.lock

This PR includes a quick change to replace hardcoded uses of a color with a token from the theme.

SW-4935: Update hardcoded styles to use accent tokens

---

package.json
src/scenes/AcceleratorRouter/NavBar.tsx
src/scenes/TerrawareRouter/NavBar.tsx
yarn.lock

- pick up new assets from web-components

SW-4885 Use deliverables/cohorts nav icons

---

src/api/types/generated-schema.ts
src/components/DeliverableView/DocumentsUploader.tsx
src/components/DeliverableView/FileUploadDialog.tsx
src/components/DeliverableView/TitleBar.tsx
src/redux/features/deliverables/deliverablesAsyncThunks.ts
src/redux/features/deliverables/deliverablesSlice.ts
src/scenes/AcceleratorRouter/DeliverableView.tsx
src/scenes/DeliverablesRouter/DeliverableView.tsx
src/services/DeliverablesService.ts
src/types/Deliverables.ts

- added types/redux/service
- updated component
- also added roles/guard for deliverable data

SW-4956 Integrate file upload with BE

---

src/features.ts

SW-4976 Opt-in flag for project scoring and voting

---

src/features.ts

- just that it makes more sense as that's the milestone name

Rename 'Voting' flag to 'Console'

---

src/App.tsx
src/AppBootstrap.tsx
src/components/common/BlockingSpinner.tsx
src/scenes/TerrawareRouter/index.tsx

- bringing this back since we are ok with users reloading
This reverts commit d766bebdc1e31183ed44c0e66c05839e793468a8.

Revert "Revert "SW-4960 Lazy load routes in terraware web

---

src/redux/features/cohorts/cohortsAsyncThunks.ts
src/redux/features/cohorts/cohortsSelectors.ts
src/redux/features/cohorts/cohortsSlice.ts
src/redux/rootReducer.ts
src/scenes/AcceleratorRouter/Cohorts/CohortView.tsx
src/services/CohortService.ts
src/types/Cohort.ts

- not needed at this time
- also removed other unused mock data

Remove mock cohort modules from accelerator console

---

src/constants.ts
src/scenes/AcceleratorRouter/Cohorts/index.tsx
src/scenes/AcceleratorRouter/Deliverables/index.tsx
src/scenes/AcceleratorRouter/Scoring/index.tsx
src/scenes/AcceleratorRouter/Voting/index.tsx
src/scenes/AcceleratorRouter/index.tsx

- added routes
- added empty components
- cleaned up some routing logic in cohorts and deliverables to handle fallbacks

SW-4972 / SW-4973 Page setup for scoring and voting

---

src/components/DeliverableView/useFetchDeliverable.ts
src/components/DeliverablesTable/index.tsx
src/redux/features/deliverables/deliverablesSelectors.ts
src/redux/features/deliverables/deliverablesSlice.ts
src/scenes/AcceleratorRouter/Deliverables/DeliverableViewWrapper.tsx
src/scenes/AcceleratorRouter/Deliverables/DeliverablesList.tsx
src/scenes/DeliverablesRouter/DeliverablesList.tsx
src/services/ParticipantsService.ts

- Rework the deliverable fetch since we have to pass in project ID and can't use a simple arg key anymore
- Fix the issue with the org ID being sent from the accelerator console

Sync up with deliverables backend

---

package.json
src/scenes/AcceleratorRouter/Deliverables/DeliverableViewWrapper.tsx
yarn.lock

Show menu items to set the deliverable status to the current status, but disable them

---

src/scenes/OrgRouter/NavBar.tsx

- added a route check to flag this case

SW-5027 Allow navigating back to deliverables list from detail deliverable view

---

src/scenes/OrgRouter/NavBar.tsx

SW-5029 Allow managers to see deliverables in Terraware side

---

src/scenes/InventoryRouter/InventoryListByBatch.tsx
src/scenes/InventoryRouter/InventoryListByNursery.tsx
src/scenes/InventoryRouter/InventoryListBySpecies.tsx

SW-5036 Add missing subheadings to inventory tab views

---

src/api/types/generated-schema.ts
src/redux/features/votes/votesAsyncThunks.ts
src/redux/features/votes/votesSlice.ts
src/scenes/AcceleratorRouter/Voting/VoteInfo.tsx
src/scenes/AcceleratorRouter/Voting/Voting.tsx
src/scenes/AcceleratorRouter/Voting/useFetchVotes.tsx
src/services/VotesService.ts
src/types/Votes.ts

- updated types
- removed delete api (no use-case)
- data is still mocked for now

SW-5041 Integrate with BE voting types

---

src/api/types/generated-schema.ts
src/redux/features/votes/votesSlice.ts
src/services/VotesService.ts
src/types/Votes.ts

- picked up minor changes in API payload property names

Update FE vote types from API changes

---

package.json
yarn.lock

SW-5062 Pick up photo chooser fix in terraware-web

---

src/api/types/generated-schema.ts
src/redux/features/user/usersAsyncThunks.ts
src/redux/features/user/usersSelectors.ts
src/redux/features/user/usersSlice.ts
src/redux/rootReducer.ts
src/services/UserService.ts

- Update with types from backend for https://github.com/terraware/terraware-server/pull/1767
- Implement `UserService` call for "get user" and "get user by email"
- Pipe new calls through redux

SW-4961 Add 'get user' and 'get user by email' service calls and redux

---

src/scenes/AcceleratorRouter/People/PersonContext.tsx
src/scenes/AcceleratorRouter/People/PersonProvider.tsx

- Implement `PersonContent` and `PersonProvider`, used in the subsequent "edit" and "single" views

SW-4961 Add PersonContext and PersonProvider, used later in person view and edit view

---

src/hooks/useParticipants.ts
src/redux/features/participants/participantsAsyncThunks.ts
src/redux/features/participants/participantsSelectors.ts
src/redux/features/participants/participantsSlice.ts
src/redux/rootReducer.ts
src/services/ParticipantsService.ts

Should be sufficient to start on the Participant views

SW-5078 Participant CRUD service and redux

---

src/scenes/AcceleratorRouter/Overview/index.tsx

This PR adds tabbed views in the Console Overview.

SW-4979: Created tabbed views

---

src/api/types/generated-schema.ts
src/redux/features/globalRoles/globalRolesAsyncThunks.ts
src/redux/features/globalRoles/globalRolesSelectors.ts
src/redux/features/globalRoles/globalRolesSlice.ts
src/redux/rootReducer.ts
src/services/GlobalRolesService.ts

- Use updated BE types for 'remove global roles for users' API
- Plumb API through GlobalRolesService and redux

SW-5047 'Remove global roles for users' API

---

src/scenes/AcceleratorRouter/Voting/VotingEdit.tsx
src/scenes/AcceleratorRouter/Voting/VotingView.tsx

- missed the search when setting location

Preserve phase url params in Voting views

---

src/scenes/AcceleratorRouter/Participants/ParticipantsList.tsx

- seems to work when switching locales and without the check

Remove activeLocale check from participants empty state component

---

src/redux/features/accelerator/acceleratorAsyncThunks.ts
src/redux/features/accelerator/acceleratorSelectors.ts
src/redux/features/accelerator/acceleratorSlice.ts
src/redux/features/participants/participantsAsyncThunks.ts
src/redux/features/participants/participantsSelectors.ts
src/redux/features/participants/participantsSlice.ts
src/redux/rootReducer.ts
src/services/AcceleratorService.ts
src/services/ParticipantsService.ts
src/services/index.ts
src/types/Accelerator.ts
src/types/Participant.ts

- added service and redux
- made assumptions with data model, to be synced with BE later

Redux to create participant and list accelerator orgs 

---

package.json
src/scenes/AcceleratorRouter/Scoring/PhaseScores/ScoreEntry/index.tsx
src/strings/csv/en.csv
yarn.lock

- Use `truncateConfig` on `TextField` so we can truncate the multi line text
- Ensure consistent vertical height for score entry qualitative input

SW-5091 Ensure consistent vertical height for score entries, use the new 'text truncation' functionality in TextField

---

src/utils/searchAndSort.test.ts
src/utils/searchAndSort.ts

Implement trigram similarity to reduce search results
Make sure single letter searches work as expected

Implement trigram similarity to reduce search results

---

src/App.tsx
src/components/TopBar/TopBarContent.tsx
src/features.ts
src/hooks/useAcceleratorConsole.ts
src/scenes/OrgRouter/NavBar.tsx
src/scenes/OrgRouter/index.tsx

This feature flag was hiding the console and deliverables.

SW-5103 Remove 'Accelerator' feature flag and bake it in

---

src/components/DeliverableView/DocumentCellRenderer.tsx
src/components/DeliverableView/DocumentsList.tsx
src/components/DeliverablesTable/DeliverableCellRenderer.tsx
src/components/DeliverablesTable/index.tsx
src/providers/DataTypes.ts
src/scenes/AcceleratorRouter/Deliverables/DeliverableView.tsx
src/scenes/AcceleratorRouter/Deliverables/DeliverableViewWrapper.tsx
src/scenes/AcceleratorRouter/ParticipantProjects/SingleView.tsx
src/utils/acl.test.ts
src/utils/acl.ts
src/utils/organization.tsx

- Add permissions for 'update submission status', 'create submission', and 'read deliverable', 'read submission document'
- Add `isMember` check for organization, which really just checks that the organization is loaded (only members can load an organization)

Deliverable (submission) and document permissions

---

src/scenes/AcceleratorRouter/Cohorts/CohortListView.tsx

This PR changes the add cohort button priority from primary to secondary.

SW-4987: Change add cohort button priority from primary to secondary

---

package.json
yarn.lock

SW-4662 Bump web-components to pick up fixedMenu/Dropdown fix

---

src/redux/features/participantProjects/participantProjectsAsyncThunks.ts
src/scenes/AcceleratorRouter/Cohorts/CohortCellRenderer.tsx
src/scenes/AcceleratorRouter/Overview/index.tsx
src/scenes/AcceleratorRouter/ParticipantProjects/CellRenderer.tsx
src/scenes/AcceleratorRouter/ParticipantProjects/ListView.tsx
src/scenes/AcceleratorRouter/Participants/ParticipantsList.tsx
src/services/ParticipantProjectService.ts
src/types/Cohort.ts
src/types/ParticipantProject.ts

- added table with mock data
- had to fix FeaturedFilters.tsx which was setting all search nodes to use the last set field

SW-5116 Participant Projects Table with results from Search API

---

src/api/types/generated-schema.ts
src/components/DeliverablesTable/index.tsx
src/components/ParticipantsDropdown/index.tsx
src/hooks/useNavigateTo.ts
src/hooks/useParticipant.ts
src/hooks/useParticipants.ts
src/redux/features/participants/participantsAsyncThunks.ts
src/redux/features/participants/participantsSelectors.ts
src/redux/features/participants/participantsSlice.ts
src/scenes/AcceleratorRouter/Participants/ParticipantForm.tsx
src/scenes/AcceleratorRouter/Participants/ParticipantsEdit.tsx
src/scenes/AcceleratorRouter/Participants/ParticipantsList.tsx
src/scenes/AcceleratorRouter/Participants/ParticipantsNew.tsx
src/scenes/AcceleratorRouter/Participants/ParticipantsView.tsx
src/services/ParticipantsService.ts
src/types/Participant.ts

- refactored types/services/redux to use BE schema and search
- updated code accordingly
- a few bug fixes here and there
- tested listing, exporting csv, create, edit, view

SW-5090 Remove Participants mock data/flows, sync with BE types

---

src/scenes/AcceleratorRouter/ParticipantProjects/EditView/index.tsx
src/scenes/AcceleratorRouter/ParticipantProjects/SingleView.tsx
src/utils/acl.test.ts
src/utils/acl.ts

- Add some notes to the ACL functionality
- Add some permission requirements to the participant project area of the accelerator console
- Add permission check within participant project edit view

SW-5136 Participant Project permissions

---

src/components/DeliverablesTable/index.tsx

Fast follow-up to limit projects filter options to projects represented in the table data.

SW-5094: Deliverables list table should be filtering on the available list of options based on the table

---

src/hooks/useNavigateTo.ts

Fix useNavigateTo double memoization

---

src/hooks/useParticipant.ts
src/scenes/AcceleratorRouter/ParticipantProjects/ParticipantProjectContext.tsx
src/scenes/AcceleratorRouter/ParticipantProjects/ParticipantProjectProvider.tsx
src/scenes/AcceleratorRouter/ParticipantProjects/SingleView.tsx

- added participant to the react context
- fetched participant in the provider and set the context value
- updated header to use participant name

SW-5158 Show participant name in participant project details header

---

src/scenes/AcceleratorRouter/Voting/VotingProvider.tsx
src/scenes/AcceleratorRouter/Voting/VotingView.tsx
src/scenes/AcceleratorRouter/Voting/VotingWrapper.tsx
src/strings/csv/en.csv

- removed the redirect to projects list if there are no voters, so user can still see the project details
- added a 'no voters' message box in votes view for the project if there are no voters

SW-5160 Allow viewing participant project details even if there are no voters

---

src/scenes/AcceleratorRouter/ParticipantProjects/EditView/index.tsx

- this was fixed earlier for the read-only view but missed it in the edit view

SW-5172 Show participant name in header of project edit view

---

src/scenes/AcceleratorRouter/ParticipantProjects/SingleView.tsx

This PR includes changes to display the full country name rather than the country abbreviation.

SW-5178: Project: Country abbreviation appears in Detail View instead of full country name

---

src/scenes/AcceleratorRouter/Participants/ParticipantsCellRenderer.tsx
src/scenes/AcceleratorRouter/Participants/ParticipantsList.tsx

This PR includes changes to fix a crash that was occurring in the Participants list in the Console Overview page.

SW-5191: Sorting Project tables in Console Overview crashes (Follow-up to fix Participants table sort)

---

src/redux/features/documentProducer/documents/documentsSelector.ts
src/redux/features/documentProducer/documents/documentsSlice.ts
src/redux/features/documentProducer/documents/documentsThunks.ts
src/redux/features/documentProducer/index.ts
src/redux/features/documentProducer/methodologies/methodologiesSelector.ts
src/redux/features/documentProducer/methodologies/methodologiesSlice.ts
src/redux/features/documentProducer/methodologies/methodologiesThunks.ts
src/redux/features/documentProducer/values/valuesSelector.ts
src/redux/features/documentProducer/values/valuesSlice.ts
src/redux/features/documentProducer/values/valuesThunks.ts
src/redux/features/documentProducer/variables/variablesSelector.ts
src/redux/features/documentProducer/variables/variablesSlice.ts
src/redux/features/documentProducer/variables/variablesThunks.ts
src/redux/rootReducer.ts

These are only hooked up to redux for now, currently there are no views or components that interact with them.

SW-5156 Move Documents, Methodologies, Values, and Variables redux from pdd-web into the app

---

src/redux/features/modules/modulesAsyncThunks.ts
src/redux/features/modules/modulesSelectors.ts
src/redux/features/modules/modulesSlice.ts
src/redux/rootReducer.ts
src/scenes/ModulesRouter/ModuleEventView.tsx
src/scenes/ModulesRouter/ModuleView.tsx
src/services/ModuleService.ts
src/types/Module.ts

This PR has some follow-ups including:
- Add module events to `ModuleService` & Redux
- Join Session buttons opens new browser window with event
- Add session call details box
- Update due date styles
- Connect module event links

SW-5125: FE - Full Module View (Follow-ups)

---

src/scenes/Home/ParticipantHomeView.tsx
src/scenes/Home/TerrawareHomeView.tsx
src/scenes/Home/index.tsx

- Move the current home view to `TerrawareHomeView` and stub out the `ParticipantHomeView`

SW-5122 Participant home view

---

package.json
src/providers/Participant/ParticipantContext.tsx
src/providers/Participant/ParticipantProvider.tsx
src/redux/features/participants/participantsAsyncThunks.ts
src/redux/features/participants/participantsSelectors.ts
src/redux/features/participants/participantsSlice.ts
src/scenes/Home/ParticipantHomeView/Header.tsx
src/scenes/Home/ParticipantHomeView/index.tsx
src/services/ParticipantsService.ts
yarn.lock

- Add current module and current participant project to `ParticipantProvider`

SW-5122 Create header for participant home page

---

src/components/common/DismissableWrapper/index.tsx
src/components/common/DismissibleWrapper/index.tsx
src/scenes/Home/ParticipantHomeView/WelcomeBanner.tsx
src/scenes/Home/ParticipantHomeView/index.tsx

- Make `DismissableWrapper` which makes it easy to embed components which can be dismissed according to their user preferences
- Wrap the `WelcomeBanner`

SW-5122 Make the welcome banner dismissible

---

src/hooks/useNavigateTo.ts
src/scenes/Home/ParticipantHomeView/ToDo.tsx
src/scenes/Home/ParticipantHomeView/ToDoCta.tsx
src/scenes/Home/ParticipantHomeView/ToDoDate.tsx
src/scenes/Home/ParticipantHomeView/ToDoRow.tsx
src/scenes/Home/ParticipantHomeView/ToDoSection.tsx
src/scenes/Home/ParticipantHomeView/ToDoStatusBadge.tsx
src/scenes/Home/ParticipantHomeView/index.tsx
src/strings/csv/en.csv

There are several things that might change once the back end is done, but the UI is done. Those things will be addressed later.
Will need a new component in `web-components` for fluid truncated text.

SW-5122 Implement ToDo list with mock data

---

package.json
src/scenes/AccessionsRouter/properties/CollectedReceivedDate2.tsx
yarn.lock

- min/max dates now work
- user can edit the date input
- simplified accession collected/received date component

SW-5218 Bump web-component version to pick up datepicker fixes

---

src/hooks/useModules.ts
src/redux/features/modules/modulesSelectors.ts
src/scenes/OrgRouter/NavBar.tsx

Fix modules selector to be memoized

---

src/components/NotificationsDropdown.tsx
src/components/OrganizationsDropdown.tsx
src/components/emptyStatePages/EmptyStatePage.tsx
src/constants.ts
src/hooks/useAcceleratorConsole.ts
src/providers/OrganizationProvider.tsx
src/scenes/AcceleratorRouter/Cohorts/index.tsx
src/scenes/AcceleratorRouter/Deliverables/index.tsx
src/scenes/AcceleratorRouter/ParticipantProjects/index.tsx
src/scenes/AcceleratorRouter/Participants/index.tsx
src/scenes/AcceleratorRouter/People/EditView.tsx
src/scenes/AcceleratorRouter/People/ListView.tsx
src/scenes/AcceleratorRouter/People/NewView.tsx
src/scenes/AcceleratorRouter/People/SingleView.tsx
src/scenes/AcceleratorRouter/People/index.tsx
src/scenes/AcceleratorRouter/index.tsx
src/scenes/CheckIn/index.tsx
src/scenes/PlantingSitesRouter/index.tsx
src/scenes/Species/SpeciesListView.tsx

- this still doesn't render people and deliverables not sure why

Use pathname.startsWith to detect accelerator route

---

src/components/common/PageHeaderWrapper.tsx
src/scenes/AcceleratorRouter/People/EditView.tsx
src/scenes/AcceleratorRouter/People/ListView.tsx
src/scenes/AcceleratorRouter/People/NewView.tsx
src/scenes/AcceleratorRouter/People/SingleView.tsx
src/scenes/MyAccountRouter/MyAccountView.tsx
src/scenes/MyAccountRouter/index.tsx
src/scenes/NoOrgRouter/index.tsx

- the router was doing an exact match, updated that
- also fixed styles since there is no nav
- also reverted some styles from yesterday since I had a cached build that didn't show proper syles

SW-5257 Fix my-account/edit redirect for no-org view

---

src/components/BatchWithdrawFlow/EmptyBatchesInfoModal.tsx
src/components/DeliverableView/StatusChangeConfirmationDialog.tsx
src/components/ProjectView/DeleteConfirmationDialog.tsx
src/components/ProjectView/index.tsx
src/components/Reports/ConcurrentEditorWarningDialog.tsx
src/components/Reports/ReportEdit.tsx
src/components/Reports/ReportView.tsx
src/components/Reports/SubmitConfirmationDialog.tsx
src/scenes/AcceleratorRouter/Deliverables/ApproveDeliverableDialog.tsx
src/scenes/AcceleratorRouter/People/RemoveRolesTopBarButton.tsx

- this is a small batch of refactor, there's a lot more that needs to be migrated

SW-5109 Refactor a few of the confirmation dialogs to use the 'Confirm' component

---

src/components/common/PageWithModuleTimeline/index.tsx

Fix the width of the page with the module timeline

---

playwright/e2e/suites/species.spec.ts
src/api/types/generated-schema.ts
src/components/Reports/LocationSelection/PlantingSite.tsx
src/components/Reports/LocationSelection/PlantingSitesSpeciesCellRenderer.tsx
src/scenes/Species/SpeciesDetailView.tsx
src/scenes/Species/SpeciesDetailsForm.tsx
src/scenes/Species/SpeciesEditView.tsx
src/scenes/Species/SpeciesListView.tsx
src/scenes/Species/TableCellRenderer.tsx
src/scenes/Species/types.ts
src/services/ParticipantProjectSpeciesService.ts
src/services/SpeciesService.ts
src/types/Species.ts

- Switch over to `species.growthForms` new type of `GrowthForm[]`
- Remove mock data flag for showing the MultiSelect of that fiel
Depends on https://github.com/terraware/terraware-server/pull/1880

SW-5280 Species Growth Forms type change

---

src/scenes/ModulesRouter/ListView.tsx

SW-5308 Add project picker in the "All modules view"

---

src/scenes/Species/SpeciesDetailsForm.tsx
src/services/SpeciesService.ts
src/types/Species.ts

- Fix a few fields in the species form
- Add fields to update and add request

SW-5268 New Species fields qa fixes

---

src/components/common/PageWithModuleTimeline/ModuleTimeline.tsx
src/hooks/useNavigateTo.ts
src/scenes/ModulesRouter/CurrentTimeline.tsx
src/scenes/ModulesRouter/ListView.tsx
src/scenes/ModulesRouter/index.tsx

<div class='graphite__hidden'>
<div>🎥 Video uploaded on Graphite:</div>
<a href="https://app.graphite.dev/media/video/NOxkRPuhAfT4F7nmdXtG/92da15d6-8c7c-4a2d-be32-d166ec27f5e2.mov">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/NOxkRPuhAfT4F7nmdXtG/92da15d6-8c7c-4a2d-be32-d166ec27f5e2.mov">Screen Recording 2024-05-01 at 10.26.56 AM.mov</video>

Updated module list view to use participant project data

---

src/scenes/ModulesRouter/ListModulesContent.tsx
src/scenes/ModulesRouter/ListView.tsx
src/scenes/ModulesRouter/ListViewHeader.tsx

Looks like to use the context correctly we need to wrap all the components that depends on a context change

Move header and content to new components

---

src/api/types/generated-schema.ts
src/components/common/PageWithModuleTimeline/ModuleTimeline.tsx
src/providers/Participant/ParticipantContext.tsx
src/providers/Participant/ParticipantProvider.tsx
src/redux/features/modules/modulesSelectors.ts
src/scenes/Home/ParticipantHomeView/CurrentModule.tsx
src/scenes/Home/ParticipantHomeView/Header.tsx
src/scenes/ModulesRouter/CurrentTimeline.tsx
src/scenes/ModulesRouter/ListView.tsx

<div class='graphite__hidden'>
<div>🎥 Video uploaded on Graphite:</div>
<a href="https://app.graphite.dev/media/video/NOxkRPuhAfT4F7nmdXtG/a63805a8-5eaf-430e-9595-0a26a546f078.mov">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/NOxkRPuhAfT4F7nmdXtG/a63805a8-5eaf-430e-9595-0a26a546f078.mov">Screen Recording 2024-05-01 at 3.44.32 PM.mov</video>

SW-5309 Used active modules for home page and stepper.

---

src/utils/dateFormatter.ts

A quick PR to add comments with examples for each date formatter utility function.

SW-5342: Document date/time formats used in Terraware

---

src/api/types/generated-schema.ts
src/redux/features/projectToDo/projectToDoAsyncThunk.ts
src/redux/features/projectToDo/projectToDoSelectors.ts
src/redux/features/projectToDo/projectToDoSlice.ts
src/redux/rootReducer.ts
src/scenes/Home/ParticipantHomeView/ToDo.tsx
src/scenes/Home/ParticipantHomeView/ToDoCta.tsx
src/scenes/Home/ParticipantHomeView/ToDoDate.tsx
src/scenes/Home/ParticipantHomeView/ToDoProvider/Context.tsx
src/scenes/Home/ParticipantHomeView/ToDoProvider/index.tsx
src/scenes/Home/ParticipantHomeView/ToDoRow.tsx
src/scenes/Home/ParticipantHomeView/ToDoSection.tsx
src/scenes/Home/ParticipantHomeView/ToDoStatusBadge.tsx
src/scenes/Home/ParticipantHomeView/index.tsx
src/services/CohortService.ts
src/strings/csv/en.csv
src/types/ProjectToDo.ts

Added ToDo redux, context and provider

SW-5292 Used real data via search for to do list

---

src/scenes/ModulesRouter/ListView.tsx

SW-5327 Updated all modules view text

---

src/scenes/ModulesRouter/CurrentTimeline.tsx

SW-5334 Updated timeline text

---

src/scenes/OrgRouter/NavBar.tsx

SW-5313 Move accelerator section up in the nav menu

---

src/redux/features/projectToDo/projectToDoAsyncThunk.ts
src/scenes/Home/ParticipantHomeView/ToDoProvider/Context.tsx
src/scenes/Home/ParticipantHomeView/ToDoProvider/index.tsx
src/types/ProjectToDo.ts

The following are the requirements:
1) 6 Items total
2) In To-do sections, 3 deliverables at max (to make room for events)
Screenshots:
1) Overdue item in To-Do, current event in to-do
2) 3 Overdue items, no other deliverables
3) 3 Overdue items, 2 events, 1 other deliverables, 1 deliverable cut off

SW-5325 Updated To-Do items priority logic

---

src/providers/Participant/ParticipantProvider.tsx
src/redux/features/modules/modulesAsyncThunks.ts
src/redux/features/modules/modulesSelectors.ts
src/redux/features/modules/modulesSlice.ts
src/types/Module.ts

This fixes a slow down in the home screen, which is very visible especailly when switch organizations.

SW-5331 Used search to imporve find module projects performances

---

package.json
yarn.lock

SW-5363 Bumped web-components version for icon updates

---

src/components/ModuleDetailsCard/index.tsx
src/providers/Participant/ParticipantContext.tsx
src/providers/Participant/ParticipantProvider.tsx
src/redux/features/modules/modulesAsyncThunks.ts
src/redux/features/modules/modulesSelectors.ts
src/redux/features/modules/modulesSlice.ts
src/scenes/Home/ParticipantHomeView/CurrentModule.tsx
src/scenes/Home/ParticipantHomeView/ToDoStatusBadge.tsx
src/scenes/ModulesRouter/ModuleView.tsx
src/scenes/ModulesRouter/Provider/Context.tsx
src/scenes/ModulesRouter/Provider/index.tsx
src/types/Module.ts

SW-5360 Added deliverables to modules

---

src/scenes/ModulesRouter/index.tsx
src/scenes/OrgRouter/index.tsx

This enables participant project selection in the home screen and module screen to persist.

SW-5330 Make ProviderParticipant persist over entire OrgRouter

---

src/scenes/Species/SpeciesProjectsCellRenderer.tsx
src/scenes/Species/SpeciesProjectsTable.tsx
src/services/ParticipantProjectSpeciesService.ts
src/types/Deliverables.ts

SW-5385 Add list icon on Project table in Species View

---

src/components/ModuleDetailsCard/index.tsx
src/scenes/Home/ParticipantHomeView/ToDoCta.tsx
src/scenes/Home/ParticipantHomeView/ToDoDate.tsx
src/scenes/Home/ParticipantHomeView/ToDoRow.tsx

SW-5413 Make module home page more reactive

---

src/components/Reports/ReportsView.tsx
src/scenes/AccessionsRouter/Accession2View.tsx
src/scenes/NurseryRouter/NurseryWithdrawalsDetailsView.tsx

This PR includes changes to use the `Tabs` component anywhere that tabs are being rendered with other components.

SW-5407: Use updated Tab components for Accession Details and Reports

---

src/scenes/DeliverablesRouter/DeliverablesList.tsx

This PR includes a change to only include participant projects in the project filter dropdown for the deliverables list table.

SW-5416: Deliverables: non-Participant Project appearing in Project dropdown in Deliverables List View

---

package.json
src/components/SpeciesDeliverableTable/TableCellRenderer.tsx
src/scenes/Species/SpeciesProjectsCellRenderer.tsx
yarn.lock

Depends on[ web-components PR](https://github.com/terraware/web-components/pull/565)

SW-5420 Fix column widths in species projects list view

---

src/components/AddNewOrganizationModal.tsx
src/components/DeliverableView/InternalComment.tsx
src/components/DocumentProducer/EditImagesModal/index.tsx
src/components/DocumentProducer/EditableSection/Display.tsx
src/components/DocumentProducer/EditableSection/DisplayVariableValue.tsx
src/components/LocaleSelector.tsx
src/components/MainPaper.tsx
src/components/Map/MapIcon.tsx
src/components/OrganizationsDropdown.tsx
src/components/PanelTitle.tsx
src/components/UserMenu.tsx
src/components/common/AddLink.tsx
src/components/common/BackToLink.tsx
src/components/common/DetectAppVersion.tsx
src/components/common/ErrorMessage.tsx
src/components/common/FilterGroup/filters/FilterCountWeight.tsx
src/components/common/FilterGroup/filters/FilterDateRange.tsx
src/components/common/FilterGroup/filters/FilterMultipleSelection.tsx
src/components/common/FilterGroup/filters/FilterNumberRange.tsx
src/components/common/FilterGroup/filters/FilterSearch.tsx
src/components/common/FilterGroup/filters/FilterSingleSelection.tsx
src/components/common/FilterGroup/index.tsx
src/components/common/FilterMultiSelect/index.tsx
src/components/common/MapLayerSelect/index.tsx
src/components/common/PhotosList.tsx
src/components/common/TextField.tsx
src/components/common/Title.tsx
src/components/common/VideoDialog.tsx

This PR removes uses of the deprecated `makeStyles` API.
NOTE: Will break changes for this ticket out into multiple PRs, with this being the first.

SW-5417: Remove makeStyles everywhere in Terraware web (#1)

---

src/components/DeliverableView/FileUploadDialog.tsx
src/components/DocumentProducer/EditableSection/TextVariable.tsx
src/components/DocumentProducer/PageContent/index.tsx
src/components/DocumentProducer/Search/index.tsx
src/components/Map/EditableMapV2.tsx
src/components/Map/Map.tsx
src/components/Map/MapViewStyleControl.tsx
src/components/Map/UndoRedoControl.tsx
src/components/Monitoring/SeedBankMonitoring.tsx
src/components/Monitoring/SensorKitSetup.tsx
src/components/Monitoring/dashboard/PVBatteryChart.tsx
src/components/Monitoring/dashboard/SeedBankDashboard.tsx
src/components/Monitoring/sensorKitSetup/DetectSensors.tsx
src/components/Monitoring/sensorKitSetup/InstallDeviceManager.tsx
src/components/Monitoring/sensorKitSetup/SelectPVSystem.tsx
src/components/Monitoring/sensorKitSetup/SensorKitID.tsx
src/components/Monitoring/sensorKitSetup/SensorLocations.tsx
src/components/NotificationIcon.tsx
src/components/ToastSnackbar.tsx
src/components/common/BlockingSpinner.tsx
src/components/common/EmptyMessage.tsx
src/components/common/Expandable.tsx
src/components/common/FilterMultiSelectContainer/index.tsx
src/components/common/ScrollableDialogBox.tsx
src/components/common/SearchFiltersWrapper/IconFilters.tsx
src/components/common/SearchFiltersWrapperV2/IconFilters.tsx
src/components/emptyStatePages/EmptyStatePage.tsx
src/stories/SearchFiltersWrapperV2.stories.tsx

This PR removes uses of the deprecated `makeStyles` API.
NOTE: Will break changes for this ticket out into multiple PRs, with this being the second.

SW-5417: Remove makeStyles everywhere in Terraware web (#2)

---

src/scenes/AcceleratorRouter/Deliverables/ApprovedDeliverableMessage.tsx
src/scenes/AcceleratorRouter/Deliverables/SpeciesDeliverableView.tsx

Show approved message for species deliverable when it is approved

---

src/components/common/DivotPopover.tsx
src/scenes/AccessionsRouter/Accession2View.tsx
src/scenes/AccessionsRouter/edit/EditState.tsx
src/scenes/AccessionsRouter/edit/QuantityModal.tsx
src/scenes/AccessionsRouter/viabilityTesting/ObservationsChart.tsx
src/scenes/AccessionsRouter/viabilityTesting/ViabilityTestingPanel.tsx
src/scenes/AccessionsRouter/withdraw/WithdrawModal.tsx
src/scenes/CheckIn/index.tsx
src/scenes/ContactUsRouter/ContactUsHome.tsx
src/scenes/InventoryRouter/BatchDetailsModal.tsx
src/scenes/InventoryRouter/BatchHistory.tsx
src/scenes/InventoryRouter/BatchHistoryRenderer.tsx
src/scenes/InventoryRouter/EventDetailsModal.tsx
src/scenes/InventoryRouter/InventoryBatchView.tsx
src/scenes/InventoryRouter/InventoryListByBatch.tsx
src/scenes/InventoryRouter/InventoryListByNursery.tsx
src/scenes/MonitoringRouter/MonitoringView.tsx
src/scenes/NoOrgRouter/index.tsx
src/scenes/PlantingSitesRouter/edit/PlantingSiteSelectTypeModal.tsx
src/scenes/PlantingSitesRouter/edit/PlantingSiteSelectTypeModal2.tsx
src/scenes/PlantsDashboardRouter/components/LiveDeadPlantsPerSpeciesCard.tsx
src/scenes/SeedBanksRouter/SelectSeedBankModal.tsx
src/scenes/Species/ProblemTooltip.tsx
src/scenes/Species/SpeciesListView.tsx

This PR removes uses of the deprecated `makeStyles` API.
NOTE: Will break changes for this ticket out into multiple PRs, with this being the **fourth**.

SW-5417: Remove makeStyles everywhere in Terraware web (#4)

---

src/components/common/TfMain.tsx

A quick PR to fix the error in the console.

Fix error in console

---

src/scenes/ContactUsRouter/ContactUsHome.tsx
src/strings/csv/en.csv

Added period to text, make texts with link in one line

---

src/scenes/InventoryRouter/Search.tsx

SW-5490 Added table density button to inventory table header

---

src/components/AddNewOrganizationModal.tsx
src/components/DeliverableView/FileUploadDialog.tsx
src/components/DocumentProducer/Search/index.tsx
src/components/DocumentProducer/VariableDetailsInput/index.tsx
src/components/Projects/index.tsx
src/scenes/NurseryRouter/ReassignmentRenderer.tsx
src/scenes/PeopleRouter/PeopleListView.tsx
src/scenes/SeedBanksRouter/SeedBanksListView.tsx

This PR includes changes to fix styles for the `Textfield` component, after the update to remove the deprecated `makeStyles` API.

SW-5515: FE - Search textfield for Projects and People are stretched to full width, instead of 300px

---

src/scenes/PlantingSitesRouter/edit/editor/Editor.tsx
src/scenes/PlantingSitesRouter/hooks/useDraftPlantingSiteUpdate.ts
src/scenes/PlantingSitesRouter/hooks/usePlantingSiteCreate.ts
src/scenes/PlantingSitesRouter/hooks/usePlantingSiteValidate.ts
src/services/TrackingService.ts

Added hooks for validate
Use validate BE endpoint in every step

SW-4842 Used validate in Draft update step

---

src/api/types/generated-schema.ts
src/components/DeliverablesTable/DeliverableCellRenderer.tsx
src/components/DeliverablesTable/index.tsx
src/scenes/AcceleratorRouter/Deliverables/DeliverablesList.tsx
src/scenes/DeliverablesRouter/DeliverablesList.tsx
src/strings/csv/en.csv

SW-5548 Updated deliverable lists with new columns

---

src/components/common/PageWithModuleTimeline/ModuleTimeline.tsx

SW-5475 Show module stepper in project profile view

---

src/components/Projects/index.tsx
src/components/TableWithSearchFilters/index.tsx
src/components/common/table/TableDensitySettingsButton.tsx
src/components/common/table/index.tsx
src/components/common/table/useTableDensity.ts
src/scenes/NurseriesRouter/NurseriesListView.tsx
src/scenes/PeopleRouter/PeopleListView.tsx
src/scenes/PlantingSitesRouter/view/PlantingSitesTable.tsx
src/scenes/SeedBanksRouter/SeedBanksListView.tsx
src/scenes/Species/SpeciesListView.tsx

Added density settings button to all of the tables
Combined density state to one hook

SW-5514: Added density settings button to all of the tables

---

src/components/Page/index.tsx
src/components/common/PageWithModuleTimeline/index.tsx
src/scenes/ModulesRouter/ListView.tsx

SW-5476  Remove left and top padding on main module page

---

src/components/CookieConsentBanner.tsx
src/providers/DataTypes.ts
src/providers/UserProvider.tsx
src/providers/contexts.ts
src/redux/features/user/usersAsyncThunks.ts

A quick PR to reload `user` when the cookie consent selection is made.

Reload user after cookie consent selection

---

src/components/Projects/index.tsx
src/components/TableWithSearchFilters/index.tsx
src/components/common/SearchFiltersWrapper/index.tsx
src/components/common/table/TableDensitySettingsButton.tsx
src/components/common/table/TableSettingsButton.tsx
src/components/seeds/database/Filters.tsx
src/components/seeds/database/index.tsx
src/scenes/InventoryRouter/Search.tsx
src/scenes/NurseriesRouter/NurseriesListView.tsx
src/scenes/PeopleRouter/PeopleListView.tsx
src/scenes/PlantingSitesRouter/view/PlantingSitesTable.tsx
src/scenes/SeedBanksRouter/SeedBanksListView.tsx
src/scenes/Species/SpeciesListView.tsx
src/strings/csv/en.csv

SW-5509 Move "Customize table columns" menu item to new "Settings" gear icon

---

package.json
yarn.lock

This PR bumps `web-components` to the latest published version to pickup changes that resolve the issue.

SW-5567: Species multi select fields are missing hover/active styling

---

src/scenes/PlantingSitesRouter/edit/editor/SiteBoundary.tsx
src/scenes/PlantingSitesRouter/edit/editor/Subzones.tsx
src/scenes/PlantingSitesRouter/edit/editor/Zones.tsx
src/scenes/PlantingSitesRouter/edit/editor/utils.test.ts
src/scenes/PlantingSitesRouter/edit/editor/utils.ts

SW-5569 Updated planting zone default name generation

---

src/api/types/generated-schema.ts
src/components/DocumentProducer/EditImagesModal/index.tsx
src/components/DocumentProducer/EditVariable/index.tsx
src/components/DocumentProducer/EditableSection/Container.tsx
src/components/DocumentProducer/EditableSection/Edit.tsx
src/components/DocumentProducer/EditableSection/EditVariableModal.tsx
src/components/DocumentProducer/EditableTableModal/index.tsx
src/redux/features/documentProducer/values/valuesSelector.ts
src/redux/features/documentProducer/values/valuesThunks.ts
src/scenes/AcceleratorRouter/Documents/DocumentView/DocumentTab.tsx
src/scenes/AcceleratorRouter/Documents/DocumentView/DocumentVariablesTab.tsx
src/scenes/AcceleratorRouter/Documents/PreviewView/PreviewDocument.tsx
src/scenes/AcceleratorRouter/Documents/PreviewView/PreviewImage.tsx
src/scenes/AcceleratorRouter/Documents/PreviewView/PreviewSection.tsx
src/scenes/AcceleratorRouter/Documents/PreviewView/SectionVariable.tsx
src/scenes/AcceleratorRouter/Documents/PreviewView/TitlePage.tsx
src/services/documentProducer/DocumentService.ts
src/services/documentProducer/DocumentTemplateService.ts
src/services/documentProducer/ValueService.ts
src/types/documentProducer/VariableValue.ts
src/utils/images.ts

I wasn't sure what to do with section variables.

SW-5583 Updated variable service endpoints to use projectIds

---

src/scenes/AcceleratorRouter/Deliverables/DeliverableViewWrapper.tsx
src/scenes/AcceleratorRouter/Deliverables/QuestionsDeliverableView.tsx

FE - (Internal) Questionnaire detail view

---

src/components/DocumentProducer/DeliverableEditVariable/index.tsx
src/components/DocumentProducer/DeliverableVariableDetailsInput/index.tsx
src/scenes/AcceleratorRouter/Deliverables/QuestionsDeliverableView.tsx
src/scenes/DeliverablesRouter/QuestionsDeliverableEditView.tsx

- Navigate back to the deliverable on save
- snackbar toasts for success and error
- remove error text from deliverable variables

Participant save variable value workflow

---

package.json
src/components/common/OptionsMenu.tsx
yarn.lock

Requieres this [PR](https://github.com/terraware/web-components/pull/616) to be merged

Fix actions not hiding after opening more actions

---

src/hooks/useNavigateTo.ts
src/scenes/DeliverablesRouter/QuestionsDeliverableEditView.tsx
src/scenes/DeliverablesRouter/QuestionsDeliverableView.tsx

This PR includes changes to support auto-scrolling to the same questions position when the edit button is pressed in the Questions Deliverable View.

SW-5618: Edit "In Place" for long Questionnaires

---

src/components/DocumentProducer/DeliverableDisplayVariableValue/index.tsx
src/components/DocumentProducer/EditableSection/Display.tsx
src/components/DocumentProducer/EditableSection/Edit.tsx
src/redux/features/documentProducer/values/valuesSelector.ts
src/redux/features/documentProducer/values/valuesSlice.ts
src/redux/features/documentProducer/values/valuesThunks.ts
src/redux/features/documentProducer/variables/variablesSelector.ts
src/scenes/AcceleratorRouter/Documents/DocumentView/DocumentTab.tsx
src/scenes/AcceleratorRouter/Documents/DocumentView/DocumentVariablesTab.tsx
src/scenes/AcceleratorRouter/Documents/PreviewView/PreviewDocument.tsx
src/services/documentProducer/ValueService.ts

When I originally brought the PDD code in, I missed a few commits, I did not have my local main up to date. This PR brings those missing commits into the codebase
Here are the missing commits:
https://github.com/terraware/pdd-web/pull/111
https://github.com/terraware/pdd-web/pull/112
https://github.com/terraware/pdd-web/pull/113
https://github.com/terraware/pdd-web/pull/114
https://github.com/terraware/pdd-web/pull/115
https://github.com/terraware/pdd-web/pull/116
https://github.com/terraware/pdd-web/pull/117
This PR does not contain any of the missing commits related to the preview, since that entire area will be getting an overhaul.

Bring in missing PDD code

---

src/components/DocumentProducer/DocumentMetadataEdit/index.tsx
src/components/ParticipantsDropdown/index.tsx
src/components/ProjectsDropdown/index.tsx
src/scenes/AcceleratorRouter/Documents/DocumentsAddView/index.tsx

This PR includes changes to add Participant & Project dropdown fields to the Add New Document View.

Doc Producer - Add New Doc - Add Participant & Project Dropdowns

---

src/components/DocumentProducer/DocumentMetadataEdit/helpers.ts
src/components/DocumentProducer/DocumentMetadataEdit/index.tsx
src/redux/features/documentProducer/variables/variablesSlice.ts
src/scenes/AcceleratorRouter/Documents/DocumentView/DocumentMetadata.tsx
src/scenes/AcceleratorRouter/Documents/DocumentView/DocumentTab.tsx
src/scenes/AcceleratorRouter/Documents/DocumentsView/helpers.ts

- Use "users with global roles" for populating list of available document owners

Wire up the document owners portion of the "new document" form

---

src/components/DocumentProducer/MultiLineComponentNonEditable/index.tsx
src/components/common/CompleteIncompleteBatch.tsx
src/scenes/AcceleratorRouter/Documents/DocumentView/DocumentTab.tsx
src/scenes/ApplicationRouter/portal/Overview/ListApplicationModulesContent.tsx

SW-5633 Add status badge to numbered sections

---

src/hooks/useNavigateTo.ts
src/scenes/ApplicationRouter/portal/Overview/ListApplicationModulesContent.tsx

Add "View" section button navigation

SW-5647 Application overview navigation

---

src/api/types/generated-schema.ts
src/scenes/DeliverablesRouter/QuestionsDeliverableView.tsx
src/utils/documentProducer/variables.ts

- Updated types from BE
- Add dependency check for variable visibility
Currently supported dependencies (we may need to add more):
- Number type variable - **=, >=, >, <, <=, !=**
- Text type variable - **=, !=**
- Select type variable - **= (in), != (not in)**

Implement variable dependencies in the questionnaire UI

---

src/components/DocumentProducer/DeliverableEditImages/index.tsx
src/components/DocumentProducer/DeliverableVariableDetailsInput/index.tsx
src/components/DocumentProducer/EditImagesModal/PhotoSelector.tsx
src/hooks/useProjectVariablesUpdate/index.ts
src/hooks/useProjectVariablesUpdate/util.ts
src/redux/features/documentProducer/values/valuesThunks.ts
src/scenes/AcceleratorRouter/Deliverables/QuestionsDeliverableView.tsx
src/scenes/DeliverablesRouter/QuestionsDeliverableEditView.tsx

This PR includes changes to support editing image fields for Questions Deliverables.

SW-5650: FE - Add editing support for Image field

---

src/redux/features/documentProducer/values/valuesSlice.ts
src/redux/features/documentProducer/variables/variablesSelector.ts
src/redux/features/documentProducer/variables/variablesSlice.ts
src/redux/features/documentProducer/variables/variablesThunks.ts
src/scenes/AcceleratorRouter/Documents/DocumentView/DocumentTab.tsx
src/services/documentProducer/VariableService.ts

- Since the variables are "system wide" now, we need to pull "all variables" to populate the variables dropdown within the document editor

Hook up the "all variables" dropdown to new BE API that returns all non-section variables in the system

---

src/components/DocumentProducer/EditVariable/index.tsx
src/components/DocumentProducer/EditableSection/Container.tsx
src/components/DocumentProducer/EditableSection/Edit.tsx
src/components/DocumentProducer/PageWorkflow/index.tsx
src/redux/features/documentProducer/variables/variablesSelector.ts
src/redux/features/documentProducer/variables/variablesSlice.ts
src/scenes/AcceleratorRouter/Documents/DocumentView/DocumentTab.tsx

Fix the variable edit modal within the document producer, it was going into an infinite reload

---

src/scenes/AcceleratorRouter/Documents/DocumentView/DocumentVariablesTab.tsx

Show all variables with the project specific values in the document variables tab

---

src/scenes/AcceleratorRouter/Documents/DocumentView/DocumentVariablesTab.tsx

Hook up search to all variables tab

---

src/components/DocumentProducer/EditableSection/Edit.tsx

Update icon for variables and empty state text

---

package.json
src/components/common/NewBadge.tsx
src/scenes/OrgRouter/NavBar.tsx
yarn.lock

Requires this PR to be merged: https://github.com/terraware/web-components/pull/621/

SW-5651 Nav Item "NEW" tag

---

src/api/types/generated-schema.ts
src/components/DocumentProducer/EditableSection/DisplayVariableValue.tsx
src/components/DocumentProducer/EditableSection/Edit.tsx
src/components/DocumentProducer/EditableSection/TextVariable.tsx
src/components/DocumentProducer/EditableSection/helpers.ts
src/stories/TextVariable.stories.tsx

- Update the UI for the variable when it is attached to a deliverable
- Update the rest of the variable UI to match Figma

Update the UI for the variable when it is attached to a deliverable

---

src/api/types/generated-schema.ts
src/components/DocumentProducer/EditableSection/Container.tsx
src/components/DocumentProducer/EditableSection/DisplayVariableValue.tsx
src/components/DocumentProducer/EditableSection/Edit.tsx
src/components/DocumentProducer/EditableSection/TextVariable.tsx
src/components/DocumentProducer/EditableSection/helpers.ts
src/scenes/AcceleratorRouter/Deliverables/VariableInternalComment.tsx
src/stories/TextVariable.stories.tsx

- Only applies in edit mode
- Hook up to 'update workflow details' flow

SW-5635 Add internal comments for non-numbered sections

---

src/components/DocumentProducer/VariableDetailsInput/index.tsx

Update the multi text variable UI

---

src/App.tsx
src/scenes/OrgRouter/index.tsx

Put router behind feature flag
Added to App.tsx
Put router behind feature flag

Put router behind feature flag

---

src/scenes/AcceleratorRouter/Deliverables/QuestionsDeliverableView.tsx
src/scenes/DeliverablesRouter/QuestionsDeliverableEditView.tsx

This PR includes changes to allow editing text fields in Questions Deliverables on both the console and participant sides.

SW-5691: Can't type in single line text fields (console and participant view)

---

src/scenes/AcceleratorRouter/Documents/DocumentView/DocumentOutlinePanel.tsx
src/scenes/AcceleratorRouter/Documents/DocumentView/index.tsx

This PR adds a new document outline panel in the doc producer tool.

SW-5638: FE - Add document outline

---

src/api/types/generated-schema.ts
src/components/DocumentProducer/MultiLineComponentNonEditable/index.tsx
src/components/ProjectNewView/index.tsx
src/components/common/CompleteIncompleteBadge.tsx
src/redux/features/application/applicationAsyncThunks.ts
src/redux/features/application/applicationSelectors.ts
src/redux/features/application/applicationSlice.ts
src/scenes/ApplicationRouter/ApplicationsList.tsx
src/scenes/ApplicationRouter/NewApplicationModal.tsx
src/scenes/ApplicationRouter/portal/NavBar.tsx
src/scenes/ApplicationRouter/portal/Overview/ListApplicationModulesContent.tsx
src/scenes/ApplicationRouter/portal/Prescreen/ResultView.tsx
src/scenes/ApplicationRouter/portal/Prescreen/index.tsx
src/scenes/ApplicationRouter/portal/Review/ReviewCard.tsx
src/scenes/ApplicationRouter/portal/Sections/SectionView.tsx
src/scenes/ApplicationRouter/portal/Sections/index.tsx
src/scenes/ApplicationRouter/provider/Context.tsx
src/scenes/ApplicationRouter/provider/index.tsx
src/services/ApplicationService.ts
src/services/ProjectsService.ts
src/strings/csv/en.csv
src/types/Application.ts

DO NOT SUBMIT: pending BE changes
Implemented services for every API endpoint for application, and only some redux.
Integrated backend calls for 
- Create
- List 
- List Modules
- List Deliverables
Not integrated yet: 
- Submit
- Review
- Restart
- Boundary

SW-5665 Implemented application service

---

src/components/DeliverableView/Metadata.tsx
src/components/DeliverableView/QuestionsDeliverableCard.tsx
src/components/DeliverableView/QuestionsDeliverableEditForm.tsx
src/components/DeliverableView/types.ts
src/constants.ts
src/hooks/useNavigateTo.ts
src/scenes/ApplicationRouter/portal/ApplicationPage.tsx
src/scenes/ApplicationRouter/portal/Deliverable/index.tsx
src/scenes/ApplicationRouter/portal/DeliverableEdit/index.tsx
src/scenes/ApplicationRouter/portal/Deliverables/index.tsx
src/scenes/ApplicationRouter/portal/Overview/index.tsx
src/scenes/ApplicationRouter/portal/index.tsx

SW-5657 Added deliverable and deliverable edit view to application

---

package.json
src/components/KnowledgeBaseLink/index.tsx
src/components/TopBar/TopBarContent.tsx
src/knowledgeBaseLinks.ts
yarn.lock

For features that have documentation, send users to the right Knowledge Base page.

SW-5526 Add context aware help link

---

package.json
src/scenes/AcceleratorRouter/People/NewView.tsx
src/scenes/AcceleratorRouter/People/PersonForm.tsx
yarn.lock

This requires a [web-components change](https://github.com/terraware/web-components/pull/624) in < MultiSelect > component to allow showing errors

SW-5606 Accerlator Console: No required field(s) indicated/enforced for adding a person

---

package.json
src/components/DeliverablesTable/DeliverableCellRenderer.tsx
src/scenes/AcceleratorRouter/ParticipantProjects/CellRenderer.tsx
src/scenes/AcceleratorRouter/Participants/ParticipantsCellRenderer.tsx
src/scenes/AcceleratorRouter/People/PersonCellRenderer.tsx
src/scenes/NurseriesRouter/TableCellRenderer.tsx
src/scenes/ObservationsRouter/details/ObservationDetailsRenderer.tsx
src/scenes/ObservationsRouter/zone/ObservationPlantingZoneRenderer.tsx
src/scenes/PeopleRouter/TableCellRenderer.tsx
src/scenes/PlantingSitesRouter/view/PlantingSiteDetailsTable.tsx
src/scenes/PlantingSitesRouter/view/PlantingSitesCellRenderer.tsx
src/scenes/SeedBanksRouter/TableCellRenderer.tsx
src/scenes/Species/TableCellRenderer.tsx
yarn.lock

Requires [this web-components PR](https://github.com/terraware/web-components/pull/625) to be merged

SW-5701 Add 'title' attribute to all table cells that contain links

---

package.json
src/components/TableWithSearchFilters/index.tsx
src/redux/features/cohorts/cohortsSlice.ts
src/scenes/AcceleratorRouter/Cohorts/CohortCellRenderer.tsx
src/scenes/AcceleratorRouter/Cohorts/CohortsListView.tsx
src/services/CohortService.ts
src/types/Cohort.ts
yarn.lock

Move sorting of participants number to the FE

SW-5738 Sort number of participants on the FE

---

src/components/DeliverableView/QuestionsDeliverableEditForm.tsx
src/components/DocumentProducer/DeliverableVariableDetailsInput/index.tsx
src/components/common/OptionsMenu.tsx
src/scenes/AcceleratorRouter/Deliverables/QuestionsDeliverableView.tsx
src/scenes/AcceleratorRouter/Deliverables/VariableInternalComment.tsx

This PR includes a set of changes to resolve items discovered during an informal design audit of the Q&A block in the Questionnaire Deliverable.

SW-5723: Q&A block design audit

---

src/components/DocumentProducer/DeliverableEditImages/index.tsx

This PR includes changes to remove a redundant field label/name in the image input field.

SW-5711: Upload Photo field types have redundant header/body copy

---

src/api/types/generated-schema.ts
src/components/SpeciesDeliverableTable/index.tsx
src/scenes/Species/SpeciesProjectsTable.tsx

- Always show add species to project button for participants
- Add the button back to the species projects table ([source](https://github.com/terraware/terraware-web/pull/2780/files))

SW-5672 Alow species to be added to participant project even when there is no active deliverable

---

src/scenes/AcceleratorRouter/Deliverables/QuestionsDeliverableView.tsx

This PR includes a change to scroll back to any question that was just updated.

SW-5760: Updating status of question should not bring user back to the top of the page

---

src/scenes/AcceleratorRouter/Species/SpeciesEditView.tsx
src/scenes/AcceleratorRouter/Species/SpeciesInternalFieldsForm.tsx

SW-5542 visual separator when editing Species in console

---

src/components/ProjectField/VotingDecisionCard.tsx

SW-5756 Include "See IC Votes" link even when voting hasn't yet occurred

---

src/components/DocumentProducer/DeliverableEditImages/index.tsx

This PR includes changes to decrease vertical spacing between the image field label & input.

SW-5711: Upload Photo field types have redundant header/body copy (follow-up)

---

src/scenes/AcceleratorRouter/Applications/ApplicationReview.tsx

This was left out in a previous rebase.

Added review modal to review component

---

src/components/Map/MapSearchBox.tsx
src/utils/useMapboxSearch.ts

This fixed 3 errors:
1) Session tokens were generated per call and tied to component lifecycles
2) Mapbox Autofill API calls were delayed instead of debounced
3) Mapbox Autofill API calls were firing on a loop

SW-5734 Implemented debouncing, value diffing, and session token management to limit Mapbox API calls

---

src/scenes/AcceleratorRouter/Documents/DocumentsView/index.tsx

Depends on https://github.com/terraware/terraware-server/pull/2240

SW-5763 Replace organization column with project name

---

src/api/types/generated-schema.ts
src/scenes/AcceleratorRouter/Documents/DocumentView/DocumentMetadata.tsx

Depends on https://github.com/terraware/terraware-server/pull/2242

SW-5765 Use project name at the top of document pages

---

src/components/AcceleratorDeliverableView/DeliverableCard.tsx
src/components/AcceleratorDeliverableView/QuestionsDeliverableCard.tsx
src/constants.ts
src/hooks/useAcceleratorConsole.ts
src/hooks/useNavigateTo.ts
src/scenes/AcceleratorRouter/Applications/ApplicationDeliverable.tsx
src/scenes/AcceleratorRouter/Applications/ApplicationView.tsx
src/scenes/AcceleratorRouter/Applications/index.tsx

SW-5771 Added deliverable view for application console

---

src/components/AcceleratorDeliverableView/QuestionsDeliverableCard.tsx

This PR includes a follow-up to SW-5760 to improve the UX by scrolling the question into roughly the center of the viewport.

SW-5760: Updating status of question should not bring user back to the top of the page (Follow-up)

---

src/scenes/AcceleratorRouter/Documents/DocumentView/DocumentMetadata.tsx

From https://github.com/terraware/terraware-web/pull/2966

Revert changes for SW-5765, use participant name at top of page

---

src/components/DocumentProducer/PageListView/index.tsx
src/components/Page/index.tsx
src/components/TableWithSearchFilters/index.tsx
src/redux/features/documentProducer/documents/documentsSelector.ts
src/redux/features/documentProducer/documents/documentsSlice.ts
src/redux/features/documentProducer/documents/documentsThunks.ts
src/scenes/AcceleratorRouter/Documents/DocumentsView/index.tsx
src/services/documentProducer/DocumentService.ts

- Switch the documents table to use TableWithSearchFilters
- Add redux for documents search, plumb into documents table through `TableWithSearchFilters`
Depends on https://github.com/terraware/terraware-server/pull/2248

SW-5767 Implement search and project filter into documents table

---

src/scenes/ModulesRouter/ListView.tsx

This PR increases the vertical padding on application instructions from 16px to 24px.

SW-5786: Increase padding in application instructions to 24px

---

src/scenes/ApplicationRouter/portal/Overview/index.tsx

This PR includes a copy update in the Overview page.

SW-5810: Overview page: Update text to clarify that viewing the Application sections is not available until Pre-screen approval

---

src/components/DeliverableView/QuestionsDeliverableEditForm.tsx
src/components/DocumentProducer/DeliverableVariableDetailsInput/index.tsx

This PR includes some follow-up style adjustments to vertical spacing between form elements within Questionnaire Deliverables.

SW-5723: Q&A block design audit (Follow up #1)

---

src/scenes/ObservationsRouter/ObservationsEventsNotification.tsx

Fix React error with rendered elements within a loop

---

src/scenes/ApplicationRouter/portal/Overview/index.tsx

This PR includes a quick follow-up to increase vertical padding in the correct view for application instructions.

SW-5786: Increase padding in application instructions to 24px (Follow-up #1)

---

src/scenes/ObservationsRouter/zone/index.tsx

SW-5813 Add subzone name to plots table

---

src/scenes/ApplicationRouter/portal/Prescreen/index.tsx

This PR includes a quick follow-up to remove a rogue semicolon rendering in the app UI.

SW-5829: Visual bugs for Prescreen module details page & rejected page (Follow-up #1)

---

src/scenes/AcceleratorRouter/Applications/ApplicationsList.tsx

This PR adds a table filter for the 'status' column to the applications list table.

SW-5824: User should be able to filter applications by status in Console

---

src/scenes/ApplicationRouter/portal/Prescreen/index.tsx
src/scenes/ApplicationRouter/portal/PrescreenResult/index.tsx

This PR includes a change to navigate the user to the pre-screen module details page when the application pre-screen is restarted.

SW-5822: When the user restarts a prescreen they should end up on the prescreen module details page

---

src/scenes/ApplicationRouter/portal/DeliverableEdit/index.tsx
src/scenes/ApplicationRouter/portal/Prescreen/index.tsx

This PR includes changes to hide the application feedback page message on some application pages:
- Pre-screen Details
- Edit Deliverable

SW-5819: Page Message Issues

---

src/scenes/ApplicationRouter/NewApplicationModal.tsx

Auto select first available project that does not have an associated application

---

src/scenes/ApplicationRouter/NewApplicationModal.tsx

This PR includes changes to resolve an issue where the "Select Existing Project" option is auto-selected when there are no available projects without an application.

SW-5814: An org with no projects that are not currently associated with an application autoselects "Select Existing Project" option

---

src/components/AcceleratorDeliverableView/QuestionsDeliverableCard.tsx
src/components/DeliverableView/QuestionsDeliverableEditForm.tsx
src/types/documentProducer/Variable.ts
src/types/documentProducer/VariableValue.ts
src/utils/documentProducer/variables.spec.ts
src/utils/documentProducer/variables.ts

- Add variable dependency checker to missing locations where dependent variables can be shown. 
- Fix issue with select equality check. 
- Add tests for `variableDependencyMet`

SW-5817 Fix variable dependencies

---

src/components/DeliverableView/QuestionsDeliverableEditForm.tsx
src/components/DocumentProducer/DeliverableVariableDetailsInput/index.tsx

This PR includes some minor spacing adjustments to Questionnaire Deliverable Q& blocks.

SW-5723: Q&A block design audit (Follow up #2)

---

src/providers/Application/index.tsx
src/scenes/ApplicationRouter/ApplicationsList.tsx

SW-5876 Automatically show new application modal if no applications

---

src/components/Application/ApplicationCard.tsx

This PR includes a minor change to modify the date format to use YYYY-MM-DD in the applications list.

Sw-5847: Update date format from YYYY/MM/DD to YYYY-MM-DD

---

src/components/AcceleratorDeliverableView/QuestionsDeliverableCard.tsx

This PR includes a fix for an issue that resulted in a layout shift when hovering over application question blocks.

SW-5858: [Visual] Question block shifts on hover

---

src/components/ProjectsDropdown/index.tsx
src/scenes/DeliverablesRouter/DeliverablesList.tsx

Make project dropdown a selector instead of a filter.
For single-Project Participants, the Project is automatically selected.
Change the “No Project” value text to “All”.

SW-5596 Deliverables List in PartEx: Address issues with Project dropdown behavior

---

src/components/AcceleratorDeliverableView/QuestionsDeliverableCard.tsx
src/components/DocumentProducer/DeliverableVariableDetailsInput/index.tsx

SW-5864 Hide description in console

---

package.json
yarn.lock

This PR includes a small change to bump `web-components` to pickup a `min-width` style added to the optional `icon` in `NavItem`.

SW-5846: [Visual Bug] Icon in Application progress nav is the wrong size

---

src/scenes/AcceleratorRouter/Applications/ApplicationReview.tsx
src/scenes/AcceleratorRouter/Applications/ApplicationReviewModal.tsx
src/scenes/AcceleratorRouter/Applications/ApplicationStatusBadge.tsx
src/types/Application.ts

SW-5868 Added "Waitlist - "as prefix to status labels

---

src/providers/Participant/ParticipantContext.tsx
src/providers/Participant/ParticipantProvider.tsx
src/providers/Participant/useSpeciesDeliverableSearch.ts
src/redux/features/modules/modulesAsyncThunks.ts
src/redux/features/modules/modulesSlice.ts
src/redux/features/projectSpecies/projectSpeciesAsyncThunks.ts
src/redux/features/projectSpecies/projectSpeciesSelectors.ts
src/redux/features/projectSpecies/projectSpeciesSlice.ts
src/redux/rootReducer.ts
src/scenes/Home/ParticipantHomeView/CurrentModule.tsx
src/scenes/ModulesRouter/ModuleView.tsx
src/scenes/ModulesRouter/Provider/Context.tsx
src/scenes/ModulesRouter/Provider/index.tsx
src/scenes/Species/AddToProjectConfirmModal.tsx
src/scenes/Species/AddToProjectModal.tsx
src/services/ModuleService.ts
src/services/ProjectSpeciesService.ts
src/types/Module.ts
src/types/ProjectSpecies.ts

This also separated out search species deliverables redux since that is a one off requirement.

SW-5842 Update module list deliverables to use deliverables endpoint

---

src/components/DocumentProducer/DeliverableVariableDetailsInput/index.tsx

This PR includes changes to how state is managed for text values in Questionnaire Deliverables. These changes resolve two issues:
- SW-5825: Can't type accents in Questionnaire Deliverable inputs
- SW-5853: Typing mid-word will automatically moved the cursor to the end of the text after one letter is typed

SW-5825: Can't type accents in Questionnaire Deliverable inputs

---

src/components/DeliverableView/Metadata.tsx

SW-5790 Updated css styles for due dates

---

package.json
src/scenes/AcceleratorRouter/Organizations/AddAcceleratorOrganizationModal.tsx
yarn.lock

Depends on [this PR ](https://github.com/terraware/web-components/pull/633) from web-components

SW-5754 improvement - Use autocomplete for org selector

---

src/components/DocumentProducer/EditVariable/index.tsx
src/components/DocumentProducer/VariableDetailsInput/index.tsx

This PR includes changes to fix several issues with inputs for text variables in the Doc Producer tool, bringing it inline with the Questionnaire Deliverables.

SW-5888: Various cursor position issues in Doc Producer text inputs

---

src/components/DocumentProducer/DeliverableVariableDetailsInput/index.tsx
src/components/DocumentProducer/VariableDetailsInput/index.tsx

This PR includes changes to add support for multi-select fields in Doc Producer, bringing it inline with the recent changes in Deliverables.
This PR includes the same set of functional changes as [the PR that added multi-select support for deliverables](https://github.com/terraware/terraware-web/pull/3079).
https://github.com/user-attachments/assets/66ad534b-3515-4114-a509-dbe0fd191105

SW-5826: Add support for multi-select

---

src/components/Application/ApplicationCard.tsx
src/scenes/AcceleratorRouter/Applications/ApplicationReview.tsx
src/scenes/AcceleratorRouter/Applications/ApplicationReviewModal.tsx

SW-5885 Removed feedback from review. Updated application statuses to show in review

---

src/components/DocumentProducer/DeliverableVariableDetailsInput/index.tsx
src/strings/csv/en.csv

SW-5932 Remove extra "Value" label for questionnaire variables

---

src/scenes/AcceleratorRouter/ParticipantProjects/ListView.tsx
src/services/ParticipantProjectService.ts
src/types/ParticipantProject.ts

SW-5783 Add file naming column to project table and search

---

src/components/DocumentProducer/DeliverableVariableDetailsInput/index.tsx

Added missing return statement for required variable check

---

package.json
src/components/DocumentProducer/DeliverableVariableDetailsInput/index.tsx
src/components/DocumentProducer/EditImagesModal/index.tsx
src/components/DocumentProducer/EditVariable/index.tsx
src/components/DocumentProducer/EditableSection/Container.tsx
src/components/DocumentProducer/EditableSection/Display.tsx
src/components/DocumentProducer/EditableSection/DisplayVariableValue.tsx
src/components/DocumentProducer/EditableSection/Edit.tsx
src/components/DocumentProducer/EditableSection/EditVariableModal.tsx
src/components/DocumentProducer/EditableTableModal/index.tsx
src/components/DocumentProducer/VariableDetailsInput/index.tsx
yarn.lock

This PR includes changes to:
- Render the variable popover in display mode
- Show Edit button in variable popover in display mode (when enabled)
- Show all variable values in variable popover in display mode (when enabled)

SW-5918: Doc producer - Missing section display mode variable popover

---

src/scenes/ApplicationRouter/ApplicationsList.tsx
src/scenes/Home/TerrawareHomeView.tsx

This PR includes changes to limit the starting a new application to users who are admins.

SW-6001: Limit "start application" to Admins and above

---

src/hooks/useProjectVariablesUpdate/util.ts

SW-5999 Implemented method to delete cell value and row if all columns are empty

---

src/api/types/generated-schema.ts
src/components/DeliverableView/QuestionsDeliverableEditForm.tsx
src/components/DeliverableView/useCompleteDeliverable.ts
src/redux/features/deliverables/deliverablesAsyncThunks.ts
src/redux/features/deliverables/deliverablesSlice.ts
src/services/DeliverablesService.ts

When modifying a questionnaire, if some required field is missing, mark deliverable as incomplete

SW-5985 Previously Completed Deliverables not marked as Incomplete 

---

src/components/DocumentProducer/EditableSection/TextVariable.tsx

Added styles suggested by Chudo in the ticket

SW-5930 Better visual display of multiline text variables in document producer

---

src/scenes/ApplicationRouter/portal/ApplicationPage.tsx
src/scenes/ApplicationRouter/portal/Prescreen/index.tsx
src/scenes/ApplicationRouter/portal/PrescreenResult/index.tsx
src/scenes/ApplicationRouter/portal/Review/ReviewCard.tsx
src/scenes/ApplicationRouter/portal/Review/index.tsx

This PR includes changes to implement a loading indicator when submitting and/or restarting the application pre-screen or the application proper.

SW-6013: Display spinner while Success! page is loading after Application submit button is clicked

---

src/components/Map/utils.ts

SW-5816 Added text halo width to mapbox text

---

src/api/types/generated-schema.ts
src/components/Map/EditableMapV2.tsx
src/components/Map/useRenderAttributes.ts
src/components/ProjectField/CountrySelect.tsx
src/components/RegionSelector/index.tsx
src/providers/DataTypes.ts
src/providers/LocalizationProvider.tsx
src/providers/contexts.ts
src/redux/features/location/locationAsyncThunks.ts
src/redux/features/location/locationSelectors.ts
src/redux/features/location/locationSlice.ts
src/redux/rootReducer.ts
src/scenes/AcceleratorRouter/Applications/ApplicationsList.tsx
src/scenes/AcceleratorRouter/ParticipantProjects/SingleView.tsx
src/scenes/AccessionsRouter/properties/Accession2Address.tsx
src/scenes/AccessionsRouter/view/DetailPanel.tsx
src/scenes/ApplicationRouter/portal/MapUpdate/index.tsx
src/scenes/MyAccountRouter/MyAccountView.tsx
src/scenes/OrganizationRouter/OrganizationView.tsx
src/services/LocationService.ts
src/types/Map.ts

SW-6045 Expanded locale provider to provide countries and timezones. Use country boundary for application map.

---

src/api/types/generated-schema.ts
src/scenes/Species/SpeciesAddView.tsx
src/scenes/Species/SpeciesEditView.tsx
src/scenes/Species/SpeciesListView.tsx
src/services/test/SpeciesService.test.ts

Temp fix to resolve species with timestamp types.
It is likely worth taking a deeper diver into the species types, and make sure that we are not adding extra payloads to operations. For example update now will input created/modified times even though they will be discarded.

Updated species types

---

src/components/TableWithSearchFilters/index.tsx
src/components/common/SearchFiltersWrapperV2/index.tsx
src/scenes/AcceleratorRouter/Overview/index.tsx
src/scenes/AcceleratorRouter/ParticipantProjects/ListView.tsx
src/utils/filterHooks/index.ts
src/utils/filterHooks/useSessionFilters.ts
src/utils/useStickyTabs.ts

These changes allows using sticky filter in any TableWithSearchFilters setting the prop: stickyFilters = true

SW-6159 Sticky filters for project table

---

package.json
src/components/DeliverableView/DocumentCellRenderer.tsx
src/components/DeliverablesTable/DeliverableCellRenderer.tsx
src/components/common/TextTruncated.tsx
src/components/seeds/database/TableCellRenderer.tsx
src/scenes/AcceleratorRouter/Applications/ApplicationCellRenderer.tsx
src/scenes/AcceleratorRouter/ParticipantProjects/CellRenderer.tsx
src/scenes/AcceleratorRouter/ParticipantProjects/SingleView.tsx
src/scenes/AcceleratorRouter/Participants/ParticipantsCellRenderer.tsx
src/scenes/AcceleratorRouter/People/PersonCellRenderer.tsx
src/scenes/InventoryRouter/InventoryCellRenderer.tsx
src/scenes/InventoryRouter/view/InventorySummaryForNursery.tsx
src/scenes/NurseryRouter/WithdrawalLogRenderer.tsx
src/scenes/ObservationsRouter/org/OrgObservationsRenderer.tsx
src/scenes/Species/TableCellRenderer.tsx
yarn.lock

Use the new functionality to truncate some existing columns that tend to have long names.

SW-5707 Make some table columns use TextTruncated

---

src/scenes/Home/TerrawareHomeView/index.tsx
src/strings/csv/en.csv

This PR includes a few follow-up changes requested from QA feedback:
- Add "View Species List" CTA for Contributors
- Hide Plants Card (Row) unless user is Admin
- Remove unnecessary horizontal padding

SW-6092: Home page dashboard (Follow-up #2)

---

src/scenes/AcceleratorRouter/Applications/ApplicationListTab.tsx
src/scenes/AcceleratorRouter/Applications/ApplicationListView.tsx
src/scenes/AcceleratorRouter/Applications/index.tsx

<div class='graphite__hidden'>
<div>🎥 Video uploaded on Graphite:</div>
<a href="https://app.graphite.dev/media/video/NOxkRPuhAfT4F7nmdXtG/4acfd9aa-764b-47ca-9c44-db1d3497a61f.mov">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/NOxkRPuhAfT4F7nmdXtG/4acfd9aa-764b-47ca-9c44-db1d3497a61f.mov">Screen Recording 2024-11-21 at 1.49.46 PM.mov</video>

SW-6284 Implemented tabs for prescreen/applications

---

src/utils/searchAndSort.test.ts
src/utils/searchAndSort.ts

Improve the FE fuzzy search adding Levenshtein distance algorithm to allow for minor typos

SW-6150 Improve FE search

---

src/components/AcceleratorDeliverableView/QuestionsDeliverableCard.tsx
src/components/DeliverableView/QuestionsDeliverableEditForm.tsx
src/components/DocumentProducer/DeliverableVariableDetailsInput/index.tsx
src/hooks/useProjectVariablesUpdate/index.ts

Keep track of the variable errors so we can disable the form if there are errors.

SW-6342 Keep track of variable errors in the useProjectVariablesUpdate hook

---

src/scenes/Home/OnboardingHomeView/OnboardingCard.tsx

This style may has been messed up during branches merge

SW-6355 CTAs aren't clickable

---

src/components/common/PlantingSiteSelector.tsx
src/scenes/Home/TerrawareHomeView/PlantingSiteStats.tsx
src/strings/csv/en.csv

Also save last planting site visited preference in org instead of user

SW-6363 Locations of Area and Date Last Observation swapped

---

docker-compose.yml

Reverts terraware/terraware-web#3458

Revert "Update postgis/postgis Docker tag to v15"

---

package.json
src/components/DocumentProducer/EditImagesModal/index.tsx
src/components/DocumentProducer/EditVariable/index.tsx
src/components/DocumentProducer/EditableTableModal/index.tsx
src/components/Variables/VariableHistoryModal.tsx
yarn.lock

Requires [this web-components PR](https://github.com/terraware/web-components/pull/650)

SW-6382 Doc Producer: when viewing/editing a variable closing "View History" should not close the variable modal

---

src/scenes/AcceleratorRouter/ParticipantProjects/EditView/index.tsx

This works in theory but Autocomplete seems to be kind of wonky for some reason. Not sure what our matching method is.

Used autocomplete for project lead dropdown

---

src/components/common/Chart/Chart.tsx
src/scenes/PlantsDashboardRouter/components/PlantingDensityPerZoneCard.tsx
src/scenes/PlantsDashboardRouter/components/PlantingSiteTrendsCard.tsx
src/scenes/PlantsDashboardRouter/components/htmlLegendPlugin.ts

SW-6311 Plants Dashboard: update Observed Density graph colors

---

src/components/Map/Map.tsx
src/components/Map/PlantingSiteMap.tsx

When switching map style, images used in the map need to be re-added

SW-6507 Mortality rate overlay disappears after switching between satellite and outdoor map styles

---

src/hooks/useObservationSummaries.ts
src/scenes/PlantsDashboardRouter/components/HighestAndLowestMortalityRateSpeciesCard.tsx
src/scenes/PlantsDashboardRouter/components/HighestAndLowestMortalityRateZonesCard.tsx
src/scenes/PlantsDashboardRouter/components/PlantingDensityCard.tsx
src/scenes/PlantsDashboardRouter/components/PlantingDensityPerZoneCard.tsx
src/scenes/PlantsDashboardRouter/components/PlantingSiteDensityCard.tsx
src/scenes/PlantsDashboardRouter/components/PlantingSiteTrendsCard.tsx

Also moved observation summaries to a hook, and changed up some syntaxes to be consistent.

SW-5880 use planting density from observation summaries

---

dump/dump.sql
src/api/types/generated-schema.ts
src/strings/csv/en.csv
src/types/Species.ts

Adds Likely Intermediate values to Seed Storage Behavior field

SW-6197 Add Likely Intermediate values to Seed Storage Behavior field

---

src/scenes/PlantsDashboardRouter/PlantsDashboardView.tsx
src/scenes/PlantsDashboardRouter/components/ZoneLevelDataMap.tsx
src/services/MapService.ts

Also fixed geometry changed message

SW-6477 Plants Dashboard not showing correct geometry and plots

---

src/AppBootstrap.tsx
src/AppError.tsx
src/api/types/generated-schema.ts
src/components/TopBar/TopBarContent.tsx
src/constants.ts
src/providers/DataTypes.ts
src/providers/FundingEntityProvider.tsx
src/providers/OrganizationProvider.tsx
src/providers/contexts.ts
src/providers/hooks.ts
src/providers/index.ts
src/redux/features/funder/fundingEntitiesAsyncThunks.ts
src/redux/features/funder/fundingEntitiesSelectors.ts
src/redux/features/funder/fundingEntitiesSlice.ts
src/redux/rootReducer.ts
src/services/FundingEntityService.ts
src/services/UserService.ts
src/services/test/CachedUserService.test.ts
src/types/FundingEntity.ts
src/utils/acl.test.ts

Add `userType` to User definition
Create FundingEntityProvider and useFundingEntity hook
Add Funding Entity to top bar content if user is Funder
Screenshot:

SW-6621 Add Funding Entity to top bar

---

src/components/TopBar/TopBar.tsx
src/components/TopBar/TopBarContent.tsx
src/scenes/TerrawareRouter/index.tsx

Redirect Funders to home page once Funding Entity is retrieved.
Could alternatively use `user.userType === 'Funder'` to determine if we should navigate

SW-6621 Redirect Funder to home page

---

src/components/SeedFundReports/ReportEdit.tsx
src/components/SeedFundReports/ReportForm.tsx
src/components/SeedFundReports/ReportFormAnnual.tsx
src/components/SeedFundReports/ReportList.tsx
src/components/SeedFundReports/ReportView.tsx
src/components/SeedFundReports/ReportsView.tsx
src/components/SeedFundReports/Router.tsx
src/components/SeedFundReports/ViewPhotos.tsx
src/components/SeedFundReports/useReportFiles.ts
src/constants.ts
src/scenes/OrgRouter/NavBar.tsx
src/scenes/OrgRouter/index.tsx
src/scenes/Reports/ReportsList.tsx
src/scenes/Reports/ReportsTargets.tsx
src/scenes/Reports/ReportsView.tsx
src/scenes/Reports/index.tsx
src/services/SeedFundReportService.ts

This PR adds a new "Reports" page and nav bar item.
Additional changes:
- Rename Service: `ReportService` --> `SeedFundReportService`

SW-6678: FE - Reports View with Tabs [Participant]

---

src/components/ListMapView/index.tsx
src/scenes/NurseryRouter/PlantingProgressMap.tsx
src/scenes/NurseryRouter/PlantingProgressMapDialog.tsx
src/scenes/NurseryRouter/PlantingProgressTabContent.tsx

- Add the total site area and planting complete area in the same place as on the planting site detail map.
- Add the subzone area to the pop-up

SW-6674 Add map areas to planting progress map view

---

src/AppBootstrap.tsx
src/components/TopBar/TopBarContent.tsx
src/providers/DataTypes.ts
src/providers/FundingEntityProvider.tsx
src/providers/UserFundingEntityProvider.tsx
src/providers/contexts.ts
src/providers/hooks.ts
src/providers/index.ts
src/redux/features/funder/fundingEntitiesAsyncThunks.ts
src/redux/features/funder/fundingEntitiesSelectors.ts
src/redux/features/funder/fundingEntitiesSlice.ts
src/scenes/AcceleratorRouter/FundingEntities/SingleView.tsx
src/scenes/AcceleratorRouter/FundingEntities/index.tsx
src/scenes/TerrawareRouter/index.tsx
src/services/FundingEntityService.ts

Create Funding Entity Provider for getting funding entity from path param
Renamed other Funding Entity Provider to `UserFundingEntityProvider` (along with associated context, state variable, etc)

SW-6608 Create Funding Entity Provider

---

src/components/ProjectsDropdown/index.tsx
src/scenes/AcceleratorRouter/FundingEntities/MultiProjectsEdit.tsx

Remove "No Project" option from Project selector dropdown
Add optional placeholder text to ProjectsDropdown component

SW-6608 Remove No Project option

---

src/scenes/AcceleratorRouter/ParticipantProjects/Reports/ReportsList.tsx
src/scenes/Reports/ReportsList.tsx

Re-used Reports List view from Participant Side to show in Console side

SW-6667 Reports Table [Console]

---

src/providers/OrganizationProvider.tsx
src/scenes/FunderRouter/index.tsx

If a non-funder hits `/funder/home`, redirect to the welcome page (this can happen when a non-funder logs in from the funder login page).

SW-6599 Fix funder home redirect for non funders

---

src/components/AcceleratorReports/MetricBox.tsx
src/types/AcceleratorReport.ts

SW-6739 Edit Metric Comments and Status fields

---

src/scenes/OrgRouter/NavBar.tsx
src/utils/acl.ts

This page includes a change to conditionally show the Reports nav item for users with the correct permission.

SW-6761: Reports page should not be accessible by Contributors & Managers

---

src/components/AcceleratorReports/AchievementsBox.tsx
src/components/AcceleratorReports/ChallengesMitigationBox.tsx
src/components/AcceleratorReports/EditableReportBox.tsx
src/components/AcceleratorReports/HighlightsBox.tsx
src/components/AcceleratorReports/MetricBox.tsx
src/components/AcceleratorReports/ReportBox.ts
src/scenes/AcceleratorRouter/ParticipantProjects/Reports/ReportView.tsx
src/scenes/Reports/AcceleratorReportEditForm.tsx
src/scenes/Reports/AcceleratorReportView.tsx

Allow only one box in edit at a time
Simplify unnecessary props

SW-6743 Allow only one box in edit at a time

---

src/api/types/generated-schema.ts
src/redux/features/organizations/organizationsAsyncThunks.ts
src/redux/features/organizations/organizationsSelectors.ts
src/redux/features/organizations/organizationsSlice.ts
src/scenes/OrgRouter/NavBar.tsx
src/services/OrganizationService.ts
src/types/Organization.ts

This PR includes changes to use the new organization features API for dynamically rendering select nav items.

SW-6762: In TW, Reports nav item should not show up for Projects that have no report start & end date

---

src/scenes/AcceleratorRouter/Documents/DocumentsView/index.tsx

As part of the Project Profile update, we need to link to the Documents page filtered to just the project's deal name. To support that functionality, this PR adds the deal name as a query param such that navigating to the page with the query set will filter the page, and the query gets updated whenever the Deal Name dropdown gets modified.

SW-6792 Add deal name to documents page query

---

src/components/ProjectField/FluidEntryWrapper.tsx
src/components/ProjectField/Footer.tsx
src/components/ProjectField/InlineMeta.tsx
src/components/ProjectField/Meta.tsx
src/scenes/AcceleratorRouter/ParticipantProjects/ProjectProfileView.tsx

Add project lead and footer to project profile.

SW-6780 Add project lead and footer to project profile

---

src/components/ProjectField/InvertedCard.tsx
src/components/ProjectField/index.tsx
src/scenes/AcceleratorRouter/ParticipantProjects/ProjectProfileView.tsx

Add Project country and project size to project profile. 
Project size will display either Eligible Area, Min Project Area, or Project Area depending on what phase the project is in.

SW-6780 Add project size and country to project profile

---

src/scenes/OrgRouter/NavBar.tsx
src/scenes/Reports/index.tsx

This PR includes follow-up changes to enable Reports for Org admins.

SW-6761: Reports page should not be accessible by Contributors & Managers (Follow-ups)

---

src/scenes/Reports/AcceleratorReportView.tsx

This PR includes a change to refresh the Accelerator Report View and disable CTA buttons on report submission.

SW-6806: Need to refresh after submitting a report to view status update

---

src/scenes/AccessionsRouter/edit/QuantityModal.tsx

The validation for both count and weight positive is already done in the FE. In the count field there was no min, as in the weight one, so just added that.

SW-6821 Accession subset count/weight validation

---

yarn.lock

This PR is the result of running `npx update-browserslist-db@latest` to update the browserslist DB.

Update Browserslist DB

---

src/redux/features/documentProducer/variables/variablesSelector.ts
src/scenes/AcceleratorRouter/ParticipantProjects/EditView/ProjectProfileEdit.tsx
src/scenes/AcceleratorRouter/ParticipantProjects/ProjectPage.tsx
src/scenes/AcceleratorRouter/ParticipantProjects/index.tsx

Initial version of upload photos with virtually no styling.
Edit page is nearly the same for now, with minor modifications to handle multiple requests on save. This page will be restyled in future stories, and is currently behind a feature flag.
This initial work is being done in order to unblock QA on some of the view Project Profile tasks (SW-6814, SW-6815).

SW-6820 Initial version of upload photos with no styling

---

src/providers/DocumentProducer/Context.ts
src/providers/DocumentProducer/Provider.tsx
src/providers/Participant/ParticipantContext.tsx
src/providers/ParticipantProject/ParticipantProjectSpeciesContext.tsx
src/providers/Project/ProjectContext.tsx
src/providers/Project/ProjectProvider.tsx
src/redux/features/accessions/accessionsThunks.ts
src/redux/features/documentProducer/documentTemplates/documentTemplatesThunks.ts
src/redux/features/observations/observationsThunks.ts
src/redux/features/plantings/plantingsThunks.ts
src/redux/features/projects/projectsThunks.ts
src/redux/features/reports/reportsThunks.ts
src/redux/features/reportsSettings/reportsSettingsThunks.ts
src/redux/features/species/speciesProjectsThunks.ts
src/redux/features/species/speciesThunks.ts
src/redux/features/subLocations/subLocationsThunks.ts
src/redux/features/tracking/trackingThunks.ts
src/scenes/AcceleratorRouter/ParticipantProjects/ParticipantProjectContext.tsx
src/scenes/AcceleratorRouter/ParticipantProjects/ParticipantProjectProvider.tsx
src/scenes/AccessionsRouter/viabilityTesting/ViabilityResultModal.tsx
src/scenes/Species/SpeciesListView.tsx
src/services/test/HttpService.test.ts
src/strings/export.js
src/utils/filterHooks/index.ts
src/utils/useMapboxToken/storage.ts
src/utils/useStickyTabs.ts

Replace tslint rule disabling comments with their eslint counterparts.

Replace tslint disables with eslint

---

src/scenes/AccessionsRouter/edit/QuantityModal.tsx
src/strings/csv/en.csv

Previously the validation was added only when the quantity was set by weight. Added to both cases and also add validation for negative numbers in subset count as in subset weight field

SW-6821 Add validation to subset count by count

---

src/components/ProjectField/ProjectMap.tsx
src/components/ProjectField/ProjectProfileImage.tsx
src/scenes/AcceleratorRouter/ParticipantProjects/ProjectProfileView.tsx

Also add the hand icon back to the map

SW-6814 Vertically center project images

---

src/components/AcceleratorReports/AcceleratorReportTargetsTable.tsx
src/components/AcceleratorReports/AcceleratorReportsTable.tsx
src/hooks/useProjectReports.ts
src/scenes/AcceleratorRouter/ParticipantProjects/Reports/ReportView.tsx

Add useProjectReports hook in preparation for using it in Project Profile view.
Refactor usages of `requestListAcceleratorReports` to use the new hook.

Add useProjectReports hook

---

src/components/ProjectField/Footer.tsx
src/hooks/useProjectFundingEntities.ts
src/redux/features/funder/fundingEntitiesAsyncThunks.ts
src/redux/features/funder/fundingEntitiesSelectors.ts
src/redux/features/funder/fundingEntitiesSlice.ts
src/scenes/AcceleratorRouter/ParticipantProjects/ProjectProfileView.tsx
src/services/FundingEntityService.ts

SW-6785 Add Project Profile Funding Entities

---

src/components/AcceleratorReports/AcceleratorReportTargetsTable.tsx
src/components/AcceleratorReports/EditAcceleratorReportTargetsModal.tsx
src/redux/features/reports/reportsSelectors.ts
src/redux/features/reports/reportsSlice.ts
src/redux/features/reports/reportsThunks.ts
src/types/AcceleratorReport.ts
src/utils/acl.ts

This PR includes a fix for an issue that was preventing Org-Admins from editing Report Targets.

SW-6807: Project Org Admin should be able to edit metric targets (Follow-up)

---

src/components/AddNewOrganizationModal.tsx
src/components/CookieConsentBanner.tsx
src/components/LocaleSelector.tsx
src/components/NotificationsDropdown.tsx
src/components/OrganizationsDropdown.tsx
src/components/SmallDeviceUserMenu.tsx
src/hooks/useAppVersion.ts
src/hooks/useCohorts.ts
src/hooks/useOrgNurserySummary.ts
src/hooks/useProjectScore.ts
src/hooks/useSeedBankSummary.ts
src/providers/LocalizationProvider.tsx
src/providers/OrganizationProvider.tsx
src/providers/UserFundingEntityProvider.tsx
src/providers/UserProvider.tsx
src/services/UserService.ts

The [upstream PR](https://github.com/terraware/terraware-web/pull/3925) fixed these linting issues specific to react-router v7's new version of `navigate`; this PR fixes them everywhere else.

Fix no-floating-promises and no-misused-promise linting issues

---

src/components/DocumentProducer/EditImagesModal/PhotoSelector.tsx
src/components/Photo/PhotoPreview.tsx
src/components/Photo/PhotoSelectorWithPreview.tsx
src/scenes/AcceleratorRouter/ParticipantProjects/EditView/ProjectProfileEdit.tsx

A later PR will support more modification of the preview, such as size and location relative to the drag and drop selector.

SW-6820 Refactor Photo Selector to allow preview to show an existing photo

---

src/api/types/generated-schema.ts

This is just updating the BE schema, because FE was already expecting progress notes to come in the response

SW-6852 Progress Notes not appearing in Funder Report

---

src/components/DocumentProducer/EditImagesModal/PhotoSelector.tsx
src/components/Photo/PhotoPreview.tsx
src/components/Photo/PhotoSelectorWithPreview.tsx
src/components/common/PlacementWrapper.tsx
src/scenes/AcceleratorRouter/ParticipantProjects/EditView/ProjectProfileEdit.tsx

Allow placement of preview photo in various locations

Allow placement of preview photo

---

src/components/DocumentProducer/EditImagesModal/PhotoSelector.tsx
src/components/Photo/PhotoPreview.tsx
src/components/Photo/PhotoSelectorWithPreview.tsx
src/components/ProjectField/ProjectProfileImage.tsx
src/scenes/AcceleratorRouter/ParticipantProjects/EditView/ProjectProfileEdit.tsx

Make Project Profile images display consistently with aspect ratio of 3:2.
Fix Edit page to also display 3:2.

SW-6820 Make Project Profile images display consistently with aspect ratio of 3:2

---

src/components/AcceleratorReports/EditAcceleratorReportTargetsModal.tsx

This PR removes unnecessary data from requests when updating report targets.

SW-6807: Project Org Admin should be able to edit metric targets (Follow-up #2)

---

src/scenes/ObservationsRouter/common/DetailsPage.tsx

There is a bug currently with double formatting of a date which causes an error.

Fixed bug with formatting date

---

src/components/AcceleratorReports/EditProgressModal.tsx
src/components/DeliverableView/SpeciesDeliverableStatusMessage.tsx
src/components/DocumentProducer/MultiLineComponentNonEditable/index.tsx
src/components/Map/MapSearchBox.tsx
src/scenes/AcceleratorRouter/Applications/ApplicationDeliverable.tsx
src/scenes/AcceleratorRouter/Cohorts/AddModuleModal.tsx
src/scenes/AcceleratorRouter/Documents/DocumentView/InternalComment.tsx
src/scenes/AcceleratorRouter/FundingEntities/MultiProjectsEdit.tsx
src/scenes/AcceleratorRouter/Modules/AddEventModal.tsx
src/scenes/AcceleratorRouter/Modules/EventsTable.tsx
src/scenes/AcceleratorRouter/Organizations/AddAcceleratorOrganizationModal.tsx
src/scenes/AcceleratorRouter/ParticipantProjects/Reports/InternalComment.tsx
src/scenes/AcceleratorRouter/People/useUpdatePerson.tsx
src/scenes/ApplicationRouter/portal/Deliverable/index.tsx
src/scenes/ApplicationRouter/portal/DeliverableEdit/index.tsx
src/scenes/ApplicationRouter/portal/MapUpdate/index.tsx
src/scenes/HelpSupportRouter/provider/index.tsx
src/scenes/Home/ParticipantHomeView/ToDoProvider/index.tsx
src/scenes/ModulesRouter/CurrentTimeline.tsx
src/scenes/ObservationsRouter/biomass/BiomassMeasurementsDetails.tsx
src/scenes/Species/SpeciesProjectsTable.tsx
src/services/ModuleService.ts
src/utils/searchAndSort.ts

Fix no-shadow linting issues

---

src/components/common/ErrorMessage.tsx
src/scenes/AcceleratorRouter/Documents/DocumentView/Metadata.tsx
src/scenes/AcceleratorRouter/Modules/AddEventModal.tsx
src/scenes/AcceleratorRouter/Species/index.tsx
src/scenes/HelpSupportRouter/AttachmentRow.tsx
src/scenes/Home/TerrawareHomeView/index.tsx
src/scenes/ObservationsRouter/schedule/ObservationSubzoneSelector.tsx
src/scenes/PlantingSitesRouter/edit/DetailedPlantingSiteHelpModal.tsx
src/scenes/PlantingSitesRouter/edit/editor/utils.test.ts
src/scenes/Species/types.ts
src/services/test/HttpService.test.ts

Fix no-unused-vars and no-unused-expressions linting issues

---

src/api/helpers/addQueryParams.ts
src/components/BatchWithdrawFlow/flow/SelectPurposeForm.tsx
src/components/BatchWithdrawFlow/flow/WithdrawalBatchesCellRenderer.tsx
src/components/ProjectField/Link.tsx
src/components/ProjectField/MinMaxCarbonTextfield.tsx
src/components/ProjectField/TextAreaEdit.tsx
src/components/ProjectField/Textfield.tsx
src/components/SpeciesDeliverableTable/AddSpeciesModal.tsx
src/components/seeds/database/Filters.tsx
src/components/seeds/database/TableCellRenderer.tsx
src/redux/features/documentProducer/variables/variablesSelector.ts
src/redux/hooks/useMultiSelectorProcessor/index.ts
src/scenes/CheckIn/index.tsx
src/scenes/InventoryRouter/InventoryBatchView.tsx
src/scenes/InventoryRouter/view/InventorySeedlingsTable.tsx
src/scenes/InventoryRouter/view/InventorySeedlingsTableForSpecies.tsx
src/scenes/ObservationsRouter/details/ObservationDetailsRenderer.tsx
src/scenes/ObservationsRouter/org/OrgObservationsRenderer.tsx
src/scenes/ObservationsRouter/zone/ObservationPlantingZoneRenderer.tsx
src/utils/documentProducer/variables.ts
src/utils/searchAndSort.ts

Fix `no-base-to-string` and `restrict-template-expressions` linting issues. 
Some cases were just disabled, but if someone knows more about those situations, an alternative fix can be implemented as well.

Fix no-base-to-string and restrict-template-expressions linting issues

---

src/api/types/generated-schema.ts
src/components/ProjectField/ProjectOverviewCard.tsx
src/redux/features/funder/projects/funderProjectsAsyncThunks.ts
src/redux/features/funder/projects/funderProjectsSelectors.ts
src/redux/features/funder/projects/funderProjectsSlice.ts
src/redux/rootReducer.ts
src/scenes/AcceleratorRouter/ParticipantProjects/ProjectPage.tsx
src/scenes/AcceleratorRouter/ParticipantProjects/ProjectProfileView.tsx
src/scenes/FunderHome/index.tsx
src/services/funder/FunderProjectService.ts
src/types/FunderProject.ts

Refactor ProjectProfile view to use `projectDetails` prop which has common elements of both `ParticipantProject` and `FunderProjectDetails`.
Add Project Profile view to funder portal.
Can't be merged until after [the server code](https://github.com/terraware/terraware-server/pull/3096) is merged

SW-6893 Add Funder Portal Project Profile view

---

src/components/AcceleratorReports/AcceleratorReportCellRenderer.tsx
src/components/ProjectField/Card.tsx
src/components/ProjectField/Display.tsx
src/components/ProjectField/InvertedCard.tsx
src/components/ProjectField/ProjectDataDisplay.tsx
src/components/ProjectField/ProjectOverviewCard.tsx
src/components/ProjectField/ReportMetricCard.tsx
src/components/ProjectField/index.tsx

Fixes 10 new linting errors introduced in https://github.com/terraware/terraware-web/pull/4029

Fix rules-of-hooks lint errors from react-hooks

---

src/App.tsx
src/components/AcceleratorReports/AcceleratorReportTargetsTable.tsx
src/components/AcceleratorReports/AcceleratorReportsTable.tsx
src/components/AcceleratorReports/AchievementsBox.tsx
src/components/AcceleratorReports/ChallengesMitigationBox.tsx
src/components/AcceleratorReports/EditAcceleratorReportTargetsModal.tsx
src/components/AcceleratorReports/HighlightsBox.tsx
src/components/AcceleratorReports/MetricBox.tsx
src/components/AcceleratorReports/MetricStatusBadge.tsx
src/components/CookieConsentBanner.tsx
src/components/DeliverableView/FileUploadDialog.tsx
src/components/DeliverableView/Metadata.tsx
src/components/DeliverableView/QuestionsDeliverableCard.tsx
src/components/DeliverableView/QuestionsDeliverableEditForm.tsx
src/components/DeliverableView/SpeciesDeliverableCard.tsx
src/components/DeliverablesTable/index.tsx
src/components/DocumentProducer/DeliverableEditTable/index.tsx
src/components/DocumentProducer/DeliverableVariableDetailsInput/index.tsx
src/components/DocumentProducer/DocumentMetadataEdit/index.tsx
src/components/DocumentProducer/EditImagesModal/index.tsx
src/components/DocumentProducer/EditVariable/index.tsx
src/components/DocumentProducer/EditableSection/Container.tsx
src/components/DocumentProducer/EditableSection/Edit.tsx
src/components/DocumentProducer/EditableSection/TextVariable.tsx
src/components/DocumentProducer/EditableTableModal/index.tsx
src/components/DocumentProducer/MultiLineComponentNonEditable/index.tsx
src/components/FundersTable/index.tsx
src/components/ListMapView/index.tsx
src/components/Map/EditableMapV2.tsx
src/components/Map/Map.tsx

Fix 65 `react-hooks/exhaustive-deps` errors.

Fix more exhaustive-deps errors

---

src/scenes/AcceleratorRouter/ParticipantProjects/ProjectProfileView.tsx

This was fixed already for the other Project Links and External Project Links, but not for View Reports.

SW-6956 Fix View Reports button not scrolling to top of screen

---

src/components/Map/PlantingSiteMap.tsx
src/services/MapService.ts

SW-6981 Added recency gradient based on diffs from today

---

src/components/ProjectField/ProjectMap.tsx
src/scenes/AcceleratorRouter/ParticipantProjects/ProjectProfileView.tsx

Also fix some react hook dependency linting issues in the same files.

SW-6982 Remove map label on funder portal

---

src/components/SmallDeviceUserMenu.tsx

SW-6989 Remove irrelevant items from funder portal small device menu

---

src/api/types/generated-schema.ts
src/scenes/ObservationsRouter/map/ObservationMapView.tsx
src/scenes/PlantingSitesRouter/view/BoundariesAndZones.tsx
src/scenes/PlantsDashboardRouter/components/ZoneLevelDataMap.tsx
src/services/MapService.ts

[Screen Recording 2025-05-22 at 3.27.06 PM.mov <span class="graphite__hidden">(uploaded via Graphite)</span> <img class="graphite__hidden" src="https://app.graphite.dev/api/v1/graphite/video/thumbnail/NOxkRPuhAfT4F7nmdXtG/19ade2c3-df93-4c11-b3de-db3b9238e93b.mov" />](https://app.graphite.dev/media/video/NOxkRPuhAfT4F7nmdXtG/19ade2c3-df93-4c11-b3de-db3b9238e93b.mov)
Planting completed and target planting density will show only current data (since we do not have historical data for those).

SW-6974 Added planting site history slider

---

src/scenes/HelpSupportRouter/ContactUsForm.tsx

Remove unnecessary useEffect that was causing app to freeze.
Request type is already set when initializing the supportRequest

SW-7003 Bug report form does not close after submission

---

src/features.ts
src/scenes/AcceleratorRouter/ParticipantProjects/index.tsx

Later tasks will remove the usage of this feature flag in the tests, and will remove the code of the old profile page (display and edit).

SW-7032 Remove Project Profile Feature Flag

---

src/scenes/ObservationsRouter/biomass/BiomassMeasurementListView.tsx
src/scenes/ObservationsRouter/biomass/BiomassMeasurementRenderer.tsx
src/scenes/ObservationsRouter/biomass/BiomassMeasurementsDetails.tsx
src/scenes/ObservationsRouter/biomass/useExportBiomassDetailsZip.ts

Add an action menu item to the biomass observation list
view to export the observation's details in a zipfile.

SW-6844 Export biomass details from list view

---

.github/workflows/workflow.yml
src/scenes/ObservationsRouter/biomass/DescriptionModal.tsx

Fix no-redeclare lint error

---

.github/workflows/workflow.yml
src/services/test/HttpService.test.ts

Disable eslint unbound-method lint error in test

Disable eslint unbound-method lint error in test

---

.github/workflows/workflow.yml
src/services/test/CachedUserService.test.ts

Fix await-thenable lint error

---

.github/workflows/workflow.yml
src/components/SeedFundReports/ReportForm.tsx

Fix no-constant-binary-expression lint error

Fix no-constant-binary-expression lint error

---

.github/workflows/workflow.yml
src/components/common/TextField.tsx
src/types/Application.ts
src/utils/searchAndSort.ts

This is just one approach to these errors. Open to other ideas

Fix no-redundant-type-constituents lint error

---

src/scenes/AccessionsRouter/withdraw/WithdrawModal.tsx

An incident occurred on July 10 where a user had a successful withdrawal but then sent the same request 6 more times within 7 seconds of the original request. Most likely, the first request took a couple seconds, so by the time it returned the user had already clicked a second time, thus stopping the dialog from closing once the first request finished. From there they kept clicking the button, each time returning an error because the withdrawal had already been created. 
Disable the button while request is pending.

SW-7165 Disable Withdraw button when request is already pending

---

.github/workflows/main.yml

This generates a message on Slack as follows: 
The Slack bot is easily configurable on Slack to customize the message, and the channel it posts to.

SW-1142 Post release notes on Slack

---

src/scenes/AcceleratorRouter/Deliverables/DeliverableView.tsx

This PR includes changes to disable the CTA buttons while questions data is loading for Questionnaire Deliverables.

SW-7143: Questionnaire Deliverables allow submitting before variables have loaded

---

src/scenes/InventoryRouter/form/BatchDetailsForm.tsx

Small refactor to clean up `BatchDetailsForm`.

SW-7211 Follow-up

---

src/components/MapDrawerTable/index.tsx
src/components/MapDrawerTable/styles.scss
src/scenes/PlantsDashboardRouter/components/MapStatsDrawer.tsx
src/scenes/PlantsDashboardRouter/components/PlantDashboardMap.tsx
src/scenes/PlantsDashboardRouter/components/styles.scss

Added MapDrawerTable component, and implemented planting site stats drawer

---

src/scenes/AcceleratorRouter/MatrixView/index.tsx

I removed the done button and added a listener for saving when clicking outside

SW-7283 Update multi-select in-cell editing

---

src/scenes/InventoryRouter/BatchDetails.tsx

This PR includes a quick fix to include the hardening off quantity in the total quantity.

SW-7292: Batch: "Total Quantity" in detail view does not include "Hardening Off Quantity"

---

src/scenes/PeopleRouter/PeopleListView.tsx

This PR includes changes to append any internal user roles in the People table.

SW-7232: FE: Append internal contact designation to Terraformation Contact name in Role column in People table

---

package.json
src/components/ProjectField/InlineMeta.tsx
yarn.lock

This PR includes a style change so the Internal Leads tooltip will honor line break characters.

SW-7327: Project Profile: Other users in the Internal Contacts field are not appearing in the Detail View (FOLLOW-UP)

---

src/redux/features/matrixView/matrixViewThunks.ts
src/scenes/AcceleratorRouter/MatrixView/index.tsx

- Fix Mix-max number filtering not working correctly. Use raw values instead of formatted values for filtering, and format number only for display.
- Add select filter for Country
- Add min-max filter for eligible land
- Remove column filter when hiding it
- Remove "show all columns" option in column actions menu

SW-7305 Follow-up Fix filters in some columns

---

dump/dump.sql
src/features.ts
src/scenes/AcceleratorRouter/NavBar.tsx
src/scenes/AcceleratorRouter/index.tsx

The matrix view is ready to go live. Remove the feature flag and its usages.

Remove Matrix View Feature Flag

---

src/components/NewMap/MapBox.tsx
src/components/NewMap/MapDateSliderControl.tsx
src/components/NewMap/MapLegend.tsx
src/components/NewMap/index.tsx

Fixed ghosting due to markers and clusters not having correct key props. Also fixed other deps issues in the Map components that cause excess renders.

SW-7381 Fixed Map Markers and Legneds re-render issues

---

src/components/ActivityLog/ActivitiesListView.tsx
src/components/ActivityLog/FilterDateRange.tsx

This PR moves the date range filter to a new location above the list of activities and also makes some minor style adjustments.

SW-7315: FE: Activity Log View (Part 1)

---

src/components/ActivityLog/ActivityDetailsForm.tsx

This PR updates the Activity Details Form to perform validation and submit the create activity request to the API.

Activity Details Form: Validate form & send create request to API

---

src/scenes/AcceleratorRouter/ParticipantProjects/ProjectPage.tsx
src/scenes/ActivityLogRouter/ActivityLogView.tsx
src/scenes/ActivityLogRouter/index.tsx
src/scenes/OrgRouter/NavBar.tsx
src/utils/acl.ts

This PR defines permissions for accessing activities and limits access to some parts of the app.

Activity Log Permissions

---

src/scenes/AcceleratorRouter/NavBar.tsx

This PR adds a permission check missed in [my previous PR for activity permissions](https://github.com/terraware/terraware-web/pull/4504).

Activity Log: Add permission check in console nav

---

src/components/ActivityLog/ActivityDetailsForm.tsx
src/components/ActivityLog/ActivityMediaForm.tsx
src/redux/features/activities/activitiesAsyncThunks.ts
src/redux/features/activities/activitiesSelectors.ts
src/redux/features/activities/activitiesSlice.ts

This PR implements the Edit Activity View.

SW-7319: FE: Edit Activity View (Part 1)

---

src/components/ActivityLog/ActivitiesListView.tsx
src/components/ActivityLog/ActivityDetailView.tsx
src/components/ActivityLog/ActivityDetailsForm.tsx
src/components/ActivityLog/ActivityMediaForm.tsx
src/components/ActivityLog/MapSplitView.tsx

Changes:
- On photo click, move to the marker
- On marker click, scroll to and highlight media
- On hovering media, highlight the marker
- Details screen photos are highlighted via a purple border
- Edit screen photos are highlighted by a background color on the row

Implemented map interactions on details and edit screen

---

src/components/ActivityLog/ActivitiesListView.tsx
src/components/ActivityLog/ActivityDetailView.tsx
src/components/ActivityLog/ActivityDetailsForm.tsx
src/components/ActivityLog/ActivityStatusBadges.tsx

This PR includes the following changes: 
- Adjust placement of activity status badges on the activity log list view
- Add activity status badges on edit activity view
- Refactor activity badges code

Adjust activity status badge placement
