cypress/integration/01-accessions.js
src/App.tsx
src/api/types/generated-schema.ts
src/components/accession2/index.tsx
src/components/seeds/newAccession/index.tsx
src/constants.ts
src/strings/index.tsx

Add accessions2 component

---

src/components/seeds/lab/NewCutTest.tsx
src/components/seeds/lab/NewGermination.tsx
src/components/seeds/lab/NewTest.tsx
src/components/seeds/nursery/NewTest.tsx
src/components/seeds/withdrawal/NewWithdrawal.tsx

Replace old cancel button with new button component

---

src/components/seeds/database/DownloadReportModal.tsx

Replace old texfield component with new one on download report modal

---

src/App.tsx
src/AppError.tsx
src/ErrorBoundary.tsx
src/ErrorContent.tsx

Create error content component

---

src/components/Species/ProblemTooltip.tsx
src/components/Species/TableCellRenderer.tsx

Fix styles on species suggestion dialog box

---

package.json
yarn.lock

This avoids pulling in dev dependencies from web-components

bump web-components version to get changes to package.json

---

src/ErrorContent.tsx

@rachel-tf-design wants the messages together.

Squish text in error message/page

---

cypress/integration/10-database.js
src/components/seeds/database/EditColumns.tsx
src/components/seeds/database/columns.ts
src/strings/index.tsx

Not in PRD and this unblocks SW-1353
The test related changes may need some tweaking in case I misunderstood the test.

SW-1547 Remove searching primaryCollectors in FE accessions table

---

src/App.tsx
src/api/accessions2/accession.ts
src/components/accession2/Accession2Edit.tsx
src/components/accession2/DetailPanel.tsx
src/constants.ts
src/strings/index.tsx

This view is not the final view. I know that for detail info we are going to have an Edit button that opens a long form (there is no hover pencil). But this will be updated when designs are finished.

Edit accession v2

---

src/api/types/generated-schema.ts
src/components/seeds/newAccession/index.tsx

SW-1553 Remove all references to primary/secondary collectors in FE code

---

src/components/accession2/Accession2View.tsx

- Added the status, the location and the notification sections at the top
- Also added the add quantity, age and viability links.
- Styles are not finished, I asked for more details on the Jira ticket. Also missing location icon.

View Status location on Accession

---

src/components/accession2/DetailPanel.tsx

Show photos on details view

---

src/api/species/species.ts
src/components/Species/AddSpeciesModal.tsx

In the add species modal if the user has entered fewer than 2 characters, clear the suggested species list.

SW-1538 Clear suggested species names when less than 2 chars

---

package.json
src/App.tsx
src/api/accessions2/accession.ts
src/api/facility/facility.ts
src/api/types/facilities.ts
src/api/types/generated-schema.ts
src/components/accession2/Accession2Create.tsx
src/components/accession2/Collectors2.tsx
src/components/accession2/SeedBank2Selector.tsx
src/components/accession2/Species2Dropdown.tsx
src/components/accession2/StorageLocationSelector.tsx
src/components/accession2/StorageSubLocationSelector.tsx
src/components/accession2/index.tsx
src/components/common/DetectAppVersion.tsx
src/components/seeds/lab/NewTest.tsx
src/components/seeds/newAccession/SpeciesDropdown.tsx
src/components/seeds/nursery/NewTest.tsx
src/strings/index.tsx
yarn.lock

- Wanted to do this in smaller chunks
- Current effort will not save successfully yet

SW-1524 Intermediate work for creating new Accession2 

---

package.json
src/components/accession2/DetailPanel.tsx
src/components/accession2/ViewPhotosModal.tsx
src/strings/index.tsx
yarn.lock

Add view photos modal

---

src/components/accession2/Accession2Create.tsx
src/components/common/FormBottomBar.tsx

Use 'Add' as save button text in create accession form.

---

src/components/AddNewOrganizationModal.tsx
src/components/accession2/Accession2Address.tsx
src/components/accession2/Accession2Create.tsx
src/components/accession2/Collectors2.tsx
src/strings/index.tsx

- The UX has country last, maybe we should have that up ahead for logical flow of selection.. but... lets go according to design for now

SW-1525 Address support for Accession2 Create

---

src/api/clock.ts
src/api/species/species.ts
src/components/SeedBanks/index.tsx
src/components/Species/AddSpeciesModal.tsx
src/components/accession2/ViewPhotosModal.tsx
tslint.json

Lets catch this in builds in case we cannot in code review.
If we need a console.* we can use the `// tslint:disable-next-line: no-console` directive.

Disallow console.* unless explicitly permitted with a pragma directive

---

src/components/AddNewOrganizationModal.tsx
src/components/EditOrganization/index.tsx
src/state/snackbar.ts
src/utils/useSnackbar.ts

- added some replaced examples to illustrate
- we can replace the other use-cases in smaller chunks

SW-1568 Extract snackbar as an easier to use utility

---

src/components/accession2/Accession2View.tsx

Set styles for Status on Accession view page

---

src/components/accession2/Accession2View.tsx

Display quantity correctly

---

src/components/OptInFeatures/index.tsx

- make it simple for now, we can make it fancy later
-

simplify opt-in features UI

---

src/components/Person/NewPerson.tsx

Name is now pre-filled on edit person screen.  Sorry for the noise on main.

SW-1523 - Fill in name on edit person screen

---

src/components/UserMenu.tsx
src/constants.ts
src/strings/index.tsx

Privacy policy link in user menu. Opens the privacy policy in a new tab.

SW-1648 Add privacy policy link in user menu

---

public/index.html

I don't think there's anything else in there needing an update.

SW-313 Update content metdata in public.html with Terraware info

---

src/components/accession2/Accession2View.tsx
src/components/accession2/NewTestModal.tsx
src/components/accession2/ViabilityTestingPanel.tsx
src/strings/index.tsx

Add Viability Testing empty state

---

src/components/accession2/viabilityTesting/NewViabilityTestModal.tsx
src/types/Accession.ts

Also remove Cut tests temporarily

Show substrates according to test method

---

src/components/accession2/view/Accession2View.tsx
src/utils/organization.tsx

- also show seed bank name instead of storage location name

Add pending-tests indicator to tab label

---

cypress/integration/10-database.js
src/components/accession2/edit/ViabilityModal.tsx
src/components/accession2/viabilityTesting/ViabilityTestingPanel.tsx
src/components/accession2/view/Accession2View.tsx
src/components/accession2/view/DetailPanel.tsx
src/strings/index.tsx

Edit viability rate

---

package.json
src/api/types/accessions.ts
src/components/accession2/viabilityTesting/ObservationsChart.tsx
src/components/accession2/viabilityTesting/ViewViabilityTestModal.tsx
yarn.lock

Add observations chart

---

src/api/accessions2/withdrawals.ts
src/components/accession2/withdraw/WithdrawModal.tsx

- updated to use new withdrawals endpoint
- having issues withdrawing-all need to test that more

SW-1705 Use withdrawals API for new withdrawals

---

src/components/accession2/viabilityTesting/NewViabilityTestModal.tsx
src/components/accession2/viabilityTesting/ViabilityResultModal.tsx
src/components/accession2/view/Accession2View.tsx
src/strings/index.tsx

SW-1672 Set viability percentage in accession

---

src/components/accession2/viabilityTesting/NewViabilityTestModal.tsx
src/strings/index.tsx

There are too many validations here, and I'm still testing if this is working correctly

SW-1716 Add validations to create viability flow

---

src/components/accession2/viabilityTesting/NewViabilityTestModal.tsx

Disable test type dropdown when editing existing viability test

---

src/components/accession2/view/Accession2View.tsx

- this is WIP, waiting on clarification

SW-1736 allow editing quantity only when status is Drying or In Storage

---

src/components/accession2/withdraw/WithdrawModal.tsx

Validations and spacing to withdrawal modal

---

src/components/accession2/viabilityTesting/NewViabilityTestModal.tsx
src/components/accession2/viabilityTesting/TableCellRenderer.tsx
src/components/accession2/view/Accession2View.tsx

- also some fixes for data validation

SW-1737 show cut test percentage in database

---

cypress/integration/10-database.js
package.json
src/api/accessions2/accession.ts
src/api/types/generated-schema.ts
src/components/seeds/database/ImportAccessionsModal.tsx
src/components/seeds/database/index.tsx
src/strings/index.tsx
yarn.lock

This has a lot of repeated code. I could try to make a component to reuse code.
I don't see accessions created after import, and I couldn't test the repeated accession number either.

Import accessions data

---

cypress/integration/01-accessions.js
cypress/integration/10-database.js
src/api/seeds/search.ts
src/components/seeds/checkin/index.tsx
src/components/seeds/database/EditColumns.tsx
src/components/seeds/database/columns.ts
src/components/seeds/newAccession/index.tsx

- replaced landowner, siteLocation and environmentalNotes with newer fields
- accessions v2 flows are already using the newly introduced fields
- tested in the database table and creation of new accession (using old v1 flow)

SW-1403 Update FE to use new collection site API fields

---

src/components/accession2/edit/Accession2EditModal.tsx

- pass speciesId prop to component

SW-1802 edit accession 2 should initialize with species id

---

package.json
src/components/accession2/view/DetailPanel.tsx
yarn.lock

TODO: Use file icon instead of folder icon

Add styles for details and show site notes

---

src/components/seeds/database/index.tsx

Fix menu styles

---

src/components/accession2/view/Accession2View.tsx
src/components/accession2/view/DetailPanel.tsx

Show buttons correctly for mobile

---

src/components/common/ImportModal.tsx

SW-1593 Change "Cancel Import" to "Cancel" on import species modal

---

src/components/Monitoring/sensorKitSetup/ConfigureSensorKit.tsx
src/strings/index.tsx

After sensor kit dashboard change button text

SW-1594 Replace "Take me there" with "Go to Dashboard"

---

src/components/accession2/properties/Accession2Address.tsx
src/components/accession2/properties/Accession2GPS.tsx
src/components/accession2/view/DetailPanel.tsx
src/utils/country.tsx

- switch country and subdivision ordering
- fix edit view to populate country (clearing of fields is broken, filed another ticket for that)
- fix edit view to populate GPS entries
- fix detail panel to show user friendly country/subdivision names

SW-1799 Country/subdivision dropdown fixes

---

src/api/accessions2/accession.ts
src/api/accessions2/utils.ts
src/api/accessions2/viabilityTest.ts
src/api/accessions2/withdrawals.ts
src/components/accession2/create/Accession2Create.tsx
src/components/accession2/edit/QuantityModal.tsx
src/components/accession2/viabilityTesting/NewViabilityTestModal.tsx
src/components/accession2/withdraw/WithdrawModal.tsx

- surface errors from server
- We have generic errors and sometimes the extra context helps the user
- Attaching a sample screenshot
- Open to suggestions here (this is not i18n friendly but perhaps a stop-gap)

SW-1823 surface accession/withdrawals/viability-test errors in web-app

---

package.json
src/components/People/CannotRemovePeopleModal.tsx
src/components/People/RemovePeopleModal.tsx
src/components/People/index.tsx
src/components/Species/DeleteSpeciesModal.tsx
src/components/Species/index.tsx
yarn.lock

Add trash can icon to delete and remove buttons. Also make delete and remove buttons icon only in mobile (except for dialog boxes).

SW-1590 Add trash can icon to delete and remove buttons

---

src/components/accession2/viabilityTesting/NewViabilityTestModal.tsx
src/strings/index.tsx

SW-1832 Add missing subset weight error

---

src/utils/withdrawalPurposes.tsx

- Nursery first, Other last
- Waiting for PM decision on this list

SW-1839 Reorder list of withdrawal purposes

---

src/components/accession2/withdraw/WithdrawModal.tsx

- defaulting withdrawnQuantity to undefined
- some code refactor

SW-1840 Remove forced 0 in withdrawals modal

---

package.json
src/components/accession2/view/DetailPanel.tsx
src/components/seeds/database/index.tsx
src/components/seeds/summary/index.tsx
yarn.lock

- Clicking on accessions by status in the dashboard works only once
- Subsequent clicks don't show the correct response because the previous filter isn't cleared
- Added a fix to clear filters if we have a new filter request
- Also added fix for SW-1833 (don't show notes icon if there are no notes)

SW-1827 Fix see all accessions results + related fixes

---

src/components/accession2/properties/Accession2Address.tsx

Save typed value (before selecting the option) to allow editing State on Accession edit

SW-1820 Allow clearing address fields

---

src/components/accession2/view/Accession2View.tsx
src/strings/index.tsx

Fix styles for quantity, age and viability to be:
- Label: 14px
- Value: important 20px bold, less important 14px

SW-1905 Fix styles for quantity, age and viability

---

src/types/Accession.ts

SW-1917 Reorder Viability Test Treatment options

---

src/components/accession2/view/DetailPanel.tsx

In detail panel make right side closer to the left side

SW-1915 Decrease distance between left and right side

---

src/components/accession2/view/Accession2View.tsx

Show "+ Add" in disabled state when not allowed to add:

SW-1908 Show Add link disabled

---

src/components/accession2/view/Accession2View.tsx
src/strings/index.tsx

SW-1903 Show bagIds on View accession

---

cypress/integration/10-database.js
src/components/accession2/viabilityTesting/TableCellRenderer.tsx
src/components/accession2/view/Accession2View.tsx
src/components/seeds/database/index.tsx

- back button from database table should work (removed the url update with url replace)
- show viability test id as a link
- remove inactive row semantics in database
- adjust vertical padding for status badge

SW-1922 / SW-1926 / SW-1918 / SW-1930 Misc visual fixes in accessions 2

---

src/components/accession2/view/Accession2View.tsx

- Fix viability to not be added or changed when state is used up
- Allow showing quantity 0 on quantity values

SW-1921 Disable edit viability on Used Up state and allow showing quantity 0

---

src/components/accession2/view/Accession2View.tsx

SW-1933 Increase spacing between delete icon and withdraw button

---

src/components/Monitoring/SeedBankMonitoring.tsx
src/components/People/index.tsx
src/components/SeedBanks/index.tsx
src/components/Species/AddSpeciesModal.tsx
src/components/Species/index.tsx
src/components/accession2/viabilityTesting/ViabilityTestingDatabase.tsx
src/components/accession2/viabilityTesting/ViabilityTestingPanel.tsx
src/components/emptyStatePages/EmptyStateContent.tsx
src/components/emptyStatePages/EmptyStatePage.tsx
src/components/seeds/database/index.tsx
src/strings/index.tsx

Add plus icon to add buttons on desktop.  Make all add buttons (except for empty state) only plus icon on mobile.

SW-1580 Clean up Add buttons

---

src/components/accession2/view/Accession2View.tsx

Increase font size for +Add links

---

src/components/MyAccount/DeleteOrgModal.tsx
src/components/Organization/index.tsx
src/components/Person/index.tsx
src/components/SeedBank/index.tsx
src/components/Species/index.tsx
src/components/accession2/edit/DeleteAccessionModal.tsx
src/components/accession2/viabilityTesting/DeleteViabilityTestModal.tsx
src/components/accession2/viabilityTesting/ViewViabilityTestModal.tsx

Add pencil icon to all edit buttons and make edit buttons only pencil icon on mobile (except for empty states).  Also add trash can icon to some newer delete buttons from seeds v2.

SW-1585 Clean up Edit buttons and some newer Delete buttons

---

src/components/accession2/withdraw/WithdrawModal.tsx
src/strings/index.tsx

SW-1844 Show error when withdrawn quantity exceeds remaining quantity

---

src/components/accession2/view/DetailPanel.tsx

SW-1972 Fix plants note style

---

src/components/accession2/viabilityTesting/NewViabilityTestModal.tsx
src/components/accession2/withdraw/WithdrawModal.tsx
src/utils/viabilityTest.tsx

Substrates differ on lab test and nursery test. Show correct options for each type on withdrawal modal

SW-1973 Get correct substrate options on withdrawal modal

---

package.json
yarn.lock

Use new web-components version. Adding right/left margins on mobile dialog box

Bump web-components version

---

src/components/accession2/view/DetailPanel.tsx

Title should be consistent on the three panels

SW-1935 Add font size to title on detail panel

---

src/components/accession2/view/DetailPanel.tsx

Fix fontSize of accession detail on desktop

---

src/App.tsx
src/components/common/EmptyMessage.tsx
src/components/seeds/database/index.tsx
src/strings/emptyMessageModal.tsx
src/strings/index.tsx

- implement both species and seedbanks onboarding

SW-1980 Fix accessions onboarding page

---

package.json
src/components/NavBar.tsx
src/constants.ts
src/strings/index.tsx
yarn.lock

SW-1851 Add nursery menu item and route

---

src/components/seeds/summary/index.tsx

- remove production environment guards from newer accession statuses in the dashboard

SW-1996 Show all statuses in dashboard summary in production

---

src/App.tsx
src/api/types/facilities.ts
src/components/Nurseries/index.tsx
src/components/SeedBanks/index.tsx
src/utils/organization.tsx

SW-1849 Nursery table with search

---

src/components/seeds/database/index.tsx
src/strings/index.tsx

- remove total
- wrap summary when there's not enough width

SW-1900 / SW-2008 Fixes to accessions summary information 

---

src/App.tsx
src/api/batch/batch.ts
src/api/types/batch.ts
src/components/Inventory/InventoryCreate.tsx
src/components/Inventory/NurseryDropdown.tsx
src/components/emptyStatePages/EmptyStatePage.tsx
src/constants.ts
src/strings/index.tsx
src/utils/organization.tsx

SW-1858 Workflow to add to the inventory

---

package.json
src/components/seeds/nursery/index.tsx
src/components/seeds/withdrawal/index.tsx
yarn.lock

- pull in new web-components
- this includes improved numerical sort behavior
- correct some comparator return types

SW-2016 Fix Sorting Behavior

---

src/components/Inventory/InventoryCreate.tsx
src/components/Inventory/NurseryDropdown.tsx

Make new inventory inputs same width on desktop

---

src/components/Inventory/InventoryTable.tsx
src/components/Inventory/TableCellRenderer.tsx
src/components/Inventory/index.tsx
src/strings/index.tsx

SW-1861 Add Inventory database table

---

src/api/species/species.ts
src/api/types/generated-schema.ts
src/components/Species/ProblemTooltip.tsx

- Add snackbar to problem tooltip
- Get the error message from the database call
- Display in an error toast if exists

SW-1603 Show Species Database Error to User

---

src/components/Inventory/InventoryCreate.tsx
src/components/Inventory/InventoryFiltersPopover.tsx
src/components/Inventory/InventoryTable.tsx
src/components/Inventory/NurseryDropdown.tsx
src/components/Inventory/index.tsx

SW-1863 Add search filters to inventory table

---

package.json
src/components/Species/ProblemTooltip.tsx
src/components/TopBar/TopBar.tsx
src/components/accession2/edit/EditState.tsx
src/components/accession2/viabilityTesting/ViewViabilityTestModal.tsx
src/components/common/EmptyMessage.tsx
src/components/seeds/database/index.tsx
src/components/seeds/summary/AccessionByStatus.tsx
src/components/seeds/summary/index.tsx
src/theme.ts
yarn.lock

- Part 1 of ??
working spreadsheet: [here](https://docs.google.com/spreadsheets/d/1nAaoqbf8DoSoLI389HYXHcZya3NnzG1RFUeYSBr3GQA/edit#gid=324615937)

SW-1739 Replace Hardcoded Colors

---

src/api/types/generated-schema.ts
src/components/Inventory/view/WithdrawalModal.tsx
src/strings/index.tsx

Batch is automatically created.

SW-1885 Withdraw with Nursery Transfer purpose

---

src/components/Inventory/view/WithdrawalModal.tsx

SW-1880 Withdraw with Other/Dead purpose

---

src/components/Inventory/InventoryTable.tsx

This doesn't do anything. Just adds the button to the UI

SW-1948 Add import button

---

src/components/Inventory/InventoryTable.tsx
src/components/Inventory/view/InventorySeedlingsTable.tsx

- all org users can create/edit/delete batches

SW-1878 Remove editable check for Contributors in Inventory batches

---

.github/scripts/gitlog.sh

Cleaned this up because previous solution wouldn't have worked for branched releases

Go with simplified approach to get last tag

---

package.json
src/components/Inventory/InventoryCellRenderer.tsx
yarn.lock

- import and use the TextTruncated component

SW-1860 Nurseries with Show More in Inventory Table 

---

src/components/Inventory/InventoryCellRenderer.tsx
src/components/Inventory/view/WithdrawalModal.tsx

- also removed some dupe keys
- rest of the web-app seems to use 16px, something we should address with designers' help

SW-2062 use 14px font-size in inventory table

---

src/components/Inventory/InventoryView.tsx
src/components/Inventory/view/InventorySeedlingsTable.tsx

- extract query parameter
- open batch details modal on batch number if found
- callback to update the query param when select or close

SW-1888 Deeplink to Batch Details

---

.github/scripts/vercel-ignore.sh

This is now done with a simpler command in the vercel settings

SW-1978 Remove script to check for gh-pages deployment

---

src/api/inventory/inventory.ts
src/api/types/generated-schema.ts
src/components/Inventory/ImportInventoryModal.tsx
src/components/Inventory/InventoryTable.tsx
src/components/Inventory/index.tsx
src/components/common/ImportModal.tsx
src/components/emptyStatePages/EmptyStatePage.tsx
src/strings/index.tsx

SW-1949 Implement csv import for inventory

---

src/components/Inventory/InventoryCreate.tsx
src/components/Inventory/view/BatchDetailsModal.tsx

A small PR to add a tooltip for the Total Quantity field on the Add Inventory page and Seedling Batch Details dialog.

SW-1769: Inventory Tooltips Follow-ups

---

package.json
src/components/Species/index.tsx
yarn.lock

SW-1695 Replace old export icon with new on species page

---

src/components/Inventory/view/BatchDetailsModal.tsx
src/components/Inventory/view/InventorySeedlingsTable.tsx
src/components/Inventory/view/InventorySummary.tsx
src/components/Inventory/view/WithdrawalModal.tsx

- updated search field to pull in accession number
- fixed withdraw form to show correct content

SW-2083 / SW-2082 : fix accession number display + remove ready-by-date from withdrawal form

---

src/components/seeds/database/DownloadReportModal.tsx

- id is specific to the database and not relevant info for an export

SW-2086 : Skip accession id in exported accession csv

---

src/App.tsx
src/components/EditOrganization/index.tsx
src/components/Home.tsx
src/components/Inventory/InventoryCreate.tsx
src/components/MyAccount/index.tsx
src/components/NewNursery/index.tsx
src/components/NewSeedBank/index.tsx
src/components/NotificationsDropdown.tsx
src/components/OptInFeatures/index.tsx
src/components/Organization/index.tsx
src/components/OrganizationsDropdown.tsx
src/components/Person/NewPerson.tsx
src/components/TopBar/TopBar.tsx
src/components/TopBar/TopBarContent.tsx
src/components/UserMenu.tsx
src/components/accession2/create/Accession2Create.tsx
src/components/common/TfMain.tsx

This PR is the first in a series of PRs to update `NavBar` & `TopBar` as part of the [FE visual update epic](https://terraformation.atlassian.net/browse/SW-2025).

SW-2066: Update Navigation & TopBar

---

package.json
src/components/Inventory/view/BatchesCellRenderer.tsx
src/components/Inventory/view/ChangeQuantityModal.tsx
src/components/Inventory/view/InventorySeedlingsTable.tsx
src/components/Inventory/view/QuantitiesMenu.tsx
src/strings/index.tsx
yarn.lock

SW-2074 Nursery Fast Follow - edit status of seedlings batch

---

src/components/TopBar/TopBar.tsx
src/components/common/PageHeaderWrapper.tsx
src/utils/useDebounce.tsx

- Add debounce to sticky and scroll state
- Animate in and out
- useLayoutEffect to avoid some flickering
- make TopBar opaque

SW-2077 Animate and Delay Header

---

package.json
yarn.lock

- pick up web-components version

SW-2119 fix disabled appearance on dropdown components

---

src/components/accession2/view/Accession2View.tsx

SW-1835 Add a back button to accession detail page

---

src/components/common/DetectAppVersion.tsx

- updates happen after component is dismounted, potential memory-leak
- error was seen in js console

SW-1815 Fix unnecessary react update in app-version detector

---

src/components/Monitoring/sensorKitSetup/SelectPVSystem.tsx
src/components/Monitoring/sensorKitSetup/SensorLocations.tsx
src/components/Species/AddSpeciesModal.tsx
src/components/accession2/create/Accession2Create.tsx
src/components/accession2/edit/EditState.tsx
src/components/accession2/properties/CollectionSource.tsx
src/components/accession2/properties/StorageLocationSelector.tsx
src/components/accession2/properties/StorageSubLocationSelector.tsx
src/components/accession2/viabilityTesting/NewViabilityTestModal.tsx
src/components/accession2/withdraw/WithdrawModal.tsx

- fix usages
- readonly flag was renamed as editable which defaults to false

SW-2162 Fix readonly related dropdown errors

---

src/components/Inventory/view/ChangeQuantityModal.tsx

- use the close handler that resets modal data

SW-2163 Don't persist quantity when changing inventory status

---

src/components/Inventory/InventoryTable.tsx
src/components/Inventory/Search.tsx
src/components/Inventory/index.tsx
src/components/Monitoring/index.tsx
src/components/Species/index.tsx
src/components/accession2/view/Accession2View.tsx
src/components/common/PageHeaderWrapper.tsx
src/components/seeds/PageHeader.tsx
src/components/seeds/checkin/index.tsx
src/components/seeds/database/Filters.tsx
src/components/seeds/database/index.tsx

- Added the header wrapper to several more pages:
- species list
- accessions list
- check-in accessions
- monitoring
- inventory list
- rearrange accessions mobile view to have cta buttons in header

SW-2076 Add PageHeaderWrapper to Pages

---

src/App.tsx
src/components/TopBar/TopBar.tsx

- Allow scrolling naavbar
- Remove white space on the top
- Cookies are not removed yet, waiting PMs approval

SW-2166 See full menu on mobile

---

src/components/Inventory/ImportInventoryModal.tsx
src/components/Inventory/InventoryCreate.tsx
src/components/Inventory/NurseryDropdown.tsx
src/components/Inventory/view/BatchDetailsModal.tsx
src/components/common/ImportModal.tsx

- add component prop (optional) in ImportModal to validate import
- use validate flag in NuseryDropdown to mark selection as required

SW-2165 Validate selection in inventory import modal

---

src/features.ts

- to be used in gating tracking v1 workflows

SW-2099 Add opt-in preference for tracking v1

---

.github/workflows/workflow.yml

Transition Jiras to "Released to Production" status after a release

SW-2068 Use github action to automatically transition Jira issues after release

---

src/components/NavBar.tsx
src/constants.ts
src/strings/index.tsx

This just adds the item to the menu, but doesn't add the Locations submenu

SW-2100 Adding planting sites menu item

---

src/App.tsx
src/components/PlantingSites/index.tsx

Adding a placeholder component to be replaced later with the planting site UI

SW-2101 Adding placeholder component for planting site route

---

src/components/NotificationsDropdown.tsx
src/components/OrganizationsDropdown.tsx
src/components/UserMenu.tsx
src/components/common/PageCard.tsx

- Change specified TopBar icon to medium
- Change Home page card icons to medium

SW-2177 Update Icon Sizes

---

src/components/NavBar.tsx
src/components/PlantingSites/index.tsx
src/components/emptyStatePages/EmptyStateContent.tsx
src/components/emptyStatePages/EmptyStatePage.tsx
src/strings/index.tsx

TODO: Replace with correct icon

SW-2103 Add Planting Sites empty state

---

package.json
src/App.tsx
src/api/types/generated-schema.ts
src/components/PlantingSites/index.tsx
src/components/emptyStatePages/EmptyStatePage.tsx
yarn.lock

Use search api for planting sites. Update site icon

---

src/components/Inventory/InventoryCellRenderer.tsx

- check for species id in renderer
- we can no longer show species info or details by species with a link
- awaiting PM response on this fix

SW-2208 handle inventory when species no longer exists

---

src/components/Inventory/InventoryCellRenderer.tsx
src/strings/index.tsx

- as per discussion here https://terraformation.atlassian.net/browse/SW-2208

show <deleted species> in inventory where species was deleted

---

package.json
src/components/Monitoring/dashboard/PVBatteryChart.tsx
src/components/Monitoring/dashboard/SeedBankDashboard.tsx
src/components/Monitoring/dashboard/TemperatureHumidityChart.tsx
src/components/Monitoring/index.tsx
src/components/common/PageHeaderWrapper.tsx
yarn.lock

SW-2186 Sensor Monitoring Dashboard

---

src/App.tsx
src/components/seeds/database/index.tsx

- so user can see them after loading app again later

SW-1361 save accessions database configured columns 

---

src/App.tsx
src/components/PlantingSites/PlantingSiteCreate.tsx
src/components/PlantingSites/index.tsx
src/strings/index.tsx

SW-2106 Flow to add a planting site

---

src/components/PlantingSites/PlantigSitesTable.tsx
src/components/PlantingSites/PlantingSitesCellRenderer.tsx
src/components/PlantingSites/PlantingSitesList.tsx
src/strings/index.tsx

Added search input UI but is not functional yet

SW-2109 Planting site database table

---

src/components/Map/Map.tsx
src/components/Map/PlantingSiteMap.tsx

- use the on(error) callback
- clean up some assumed style

Allow refreshing mapbox token

---

src/App.tsx
src/components/PlantingSites/PlantingSiteView.tsx
src/components/PlantingSites/PlantingSitesCellRenderer.tsx
src/constants.ts

SW-2112 View name and description of planting site

---

src/components/Inventory/withdraw/WithdrawBatch.tsx
src/components/Map/PlantingSiteMap.tsx
src/components/accession2/view/Accession2View.tsx
src/utils/useSnackbar.ts

- snackbar was returning a copy of the functions every time
- this is not needed, there is no scoped data to protect
- return an initialized value that doesn't change

SW-2270 Make snackbar less mutating

---

src/components/Inventory/withdraw/WithdrawBatch.tsx
src/components/Map/PlantingSiteMap.tsx
src/components/accession2/view/Accession2View.tsx
src/utils/useSnackbar.ts

This reverts commit 09051ca835398f560fd5d41fd1e4a805fb172089.
This code is breaking the minified build somehow.

Revert "SW-2270 Make snackbar less mutating (#772)"

---

package.json
src/App.tsx
src/components/Home.tsx
src/components/accession2/create/Accession2Create.tsx
src/components/common/TextField.tsx
src/components/common/TfMain.tsx
src/components/seeds/PageHeader.tsx
src/components/seeds/database/Filters.tsx
src/components/seeds/database/filters/FilterDateRange.tsx
src/components/seeds/database/filters/FilterNumberRange.tsx
src/components/seeds/database/filters/FilterSearch.tsx
src/components/seeds/database/index.tsx
src/components/seeds/summary/index.tsx
src/strings/index.tsx
yarn.lock

SW-2262 Accession Table Updates

---

src/components/Inventory/withdraw/flow/SelectPurposeForm.tsx

SW-2298 Hide 'Out Plant' purpose for Contributors

---

package.json
src/components/People/index.tsx
yarn.lock

* Adding a searchbar is more feature work that I want to put in for this visual update

SW-2265 People Table Updates

---

package.json
src/components/Species/SpeciesFiltersPopover.tsx
src/components/Species/index.tsx
yarn.lock

SW-2264 Species Table Updates

---

src/components/Nurseries/index.tsx

SW-2279 Nurseries Table

---

src/components/Inventory/view/DeleteBatchesModal.tsx
src/components/MyAccount/AssignNewOwnerModal.tsx
src/components/MyAccount/CannotRemoveOrgModal.tsx
src/components/MyAccount/DeleteOrgModal.tsx
src/components/MyAccount/LeaveOrganizationModal.tsx
src/components/People/CannotRemovePeopleModal.tsx
src/components/People/RemovePeopleModal.tsx
src/components/Species/DeleteSpeciesModal.tsx
src/components/accession2/edit/DeleteAccessionModal.tsx
src/components/accession2/viabilityTesting/DeleteViabilityTestModal.tsx

- apply skrim to dialogs with destructive actions
example:

SW-2159 Skrim

---

src/components/Inventory/InventoryFiltersPopover.tsx
src/components/Inventory/InventoryView.tsx
src/components/Inventory/Search.tsx
src/components/Inventory/view/InventorySeedlingsTable.tsx
src/components/Inventory/view/InventorySummary.tsx
src/components/common/OverviewItemCard.tsx

SW-2133 Seedlings View

---

package.json
yarn.lock

Oops! I forgot to push up these local changes in [my original PR](https://github.com/terraware/terraware-web/pull/792) updating the `web-components` package.

SW-2123: Responsive Page Layouts -> Onboarding

---

src/api/tracking/tracking.ts
src/api/types/batch.ts
src/api/types/generated-schema.ts
src/components/Inventory/withdraw/BatchWithdrawFlow.tsx
src/components/Inventory/withdraw/flow/SelectPurposeForm.tsx
src/components/PlantingSites/PlantingSitesCellRenderer.tsx
src/components/PlantingSites/PlantingSitesList.tsx
src/components/PlantingSites/PlantingSitesTable.tsx
src/strings/index.tsx

- refactored some models
- added sites/zones/plots mappings
- tested with real withdrawals

SW-2328 Support 'Outplant' in nursery withdrawals

---

src/components/Inventory/InventoryTable.tsx
src/components/Inventory/view/InventorySeedlingsTable.tsx
src/components/Inventory/withdraw/BatchBulkWithdrawWrapperComponent.tsx
src/components/Inventory/withdraw/BatchWithdrawFlow.tsx
src/components/Inventory/withdraw/SpeciesBulkWithdrawWrapperComponent.tsx

- keep it in url param
- also handle error cases where someone messes with url incorrectly

SW-2304 Return to originating page after saving or when canceling a withdrawal

---

src/App.tsx
src/components/Home.tsx
src/components/TopBar/TopBar.tsx
src/components/common/PageHeaderWrapper.tsx

- fixed background-attachment (background doesn't scroll)
- changed gradient based on design guidance

Background Updates

---

src/api/batch/batch.ts
src/components/Inventory/withdraw/BatchWithdrawFlow.tsx
src/components/Inventory/withdraw/flow/SelectPurposeForm.tsx
src/strings/index.tsx

- some singular/plural adjustment which we should ideally get from a 3rd party library

SW-2330 Format success message for batch withdrawals

---

src/components/Inventory/InventoryTable.tsx
src/components/Inventory/view/BatchDetailsModal.tsx
src/components/Inventory/view/BatchesCellRenderer.tsx
src/components/Inventory/view/InventorySeedlingsTable.tsx
src/components/Inventory/view/InventorySummary.tsx
src/components/Inventory/view/QuantitiesMenu.tsx
src/components/Inventory/withdraw/BatchWithdrawFlow.tsx
src/components/Inventory/withdraw/flow/AddPhotos.tsx
src/components/common/SelectPhotos.tsx
src/strings/index.tsx

- also fixed add batch entry form remembering entries

SW-2344 / SW-2343 / SW-2345 / SW-2331 Misc fixes around showing/hiding withdraw buttons when relevant

---

package.json
src/App.tsx
src/components/NavBar.tsx
src/components/Plants/index.tsx
src/constants.ts
yarn.lock

SW-2309 / SW-2310 - Nav menu and routing for Plants/Dashboard

---

src/components/Person/index.tsx

SW-2136 Person View

---

src/components/Inventory/withdraw/flow/SelectBatchesWithdrawnQuantity.tsx
src/components/Inventory/withdraw/flow/WithdrawalBatchesCellRenderer.tsx
src/strings/index.tsx

SW-2355 Fix withdraw batch quantities view styling issues

---

src/components/common/SelectPhotos.tsx

- scale image
- fit image in parent box
- center image
- as per design changes

SW-2358 Adjust imgae thumbnail display style

---

src/api/types/generated-schema.ts
src/api/types/tracking.ts
src/components/Map/Map.tsx
src/components/Map/MapModels.ts
src/components/Map/MapUtils.ts
src/components/Map/PlantingSiteMap.tsx

- MultiPolygon alone is supported
- to avoid ambiguity

SW-2261 Update map polygon types with recent backend changes that removes points/lines, etc.

---

src/components/seeds/PageHeader.tsx
src/components/seeds/checkin/index.tsx
src/strings/index.tsx

Note: I will be looking into the button overlay issue next.

SW-2137 Accession Check-in

---

package.json
src/components/Nursery/index.tsx
src/components/Person/index.tsx
src/components/SeedBank/index.tsx
src/strings/index.tsx
yarn.lock

SW-2136 SeedBank and Nursery Views

---

src/api/types/batch.ts
src/components/Inventory/view/WithdrawalModal.tsx
src/components/Inventory/withdraw/BatchWithdrawFlow.tsx
src/components/Inventory/withdraw/flow/AddPhotos.tsx
src/components/Inventory/withdraw/flow/SelectBatchesWithdrawnQuantity.tsx
src/components/Inventory/withdraw/flow/SelectPurposeForm.tsx

- easier to update values if/when they change
- avoid mistakes in string literals

SW-2353 Extract withdrawal purposes into constants/types

---

src/components/Organization/index.tsx

SW-2136 Organization View

---

src/components/Plants/PlantBySpeciesChart.tsx
src/components/Plants/SpeciesByPlotChart.tsx

SW-2374 Remove legend box from chart tooltip

---

src/components/Plants/PlantBySpeciesChart.tsx
src/components/Plants/SpeciesByPlotChart.tsx
src/utils/generateRandomColor.tsx

SW-2322 Pick colors for the bar chart from base color 300s

---

package.json
src/App.tsx
src/components/PlantingSites/PlantingSiteCreate.tsx
yarn.lock

- update padding
- update background and scrollbar thumb styles
- add transparent background for empty states:
- species, seedbanks, nurseries, planting-sites
color and padding around scrollbar:

NavBar Updates

---

src/components/NavBar.tsx

Just a quick PR to update items in the `NavBar` to align with [the newer designs for nested navigation](https://www.figma.com/file/DftqOeGx8irCdRf7IZ4lbc/Navigation?node-id=5005%3A199381&viewport=-688%2C-4385%2C0.64&t=Nfdhwq0T8QReDDIM-0).
Changes include:
- Nest **Inventory** under **Seeds**
- Remove duplicate un-nested **Monitoring**

Update NavBar items

---

src/components/Inventory/view/InventorySeedlingsTable.tsx
src/components/Nurseries/index.tsx
src/components/PlantingSites/PlantingSitesList.tsx

- in inventory seedlings batches and nurseries tables
- this is expensive and not ideal

SW-2384/SW-2385 Fix fuzzy searches that were using empty strings

---

src/components/Inventory/withdraw/flow/SelectPurposeForm.tsx
src/components/common/ErrorMessage.tsx
src/components/common/FormBottomBar.tsx
src/strings/index.tsx

SW-2345 Show error on select-purpose-form if ouptlant has no ready seedlings

---

src/components/Plants/DashboardChart.tsx
src/components/Plants/PlantBySpeciesChart.tsx
src/components/Plants/SpeciesByPlotChart.tsx

This allows removing duplicate code

SW-2381 Refactor plants dashboard charts for reusability

---

src/components/Map/Map.tsx
src/components/Map/PlantingSiteMap.tsx
src/components/Plants/PlantBySpeciesChart.tsx
src/components/Plants/PlantingSiteDashboardMap.tsx
src/components/Plants/PlantingSiteDetails.tsx
src/components/Plants/SpeciesByPlotChart.tsx

- show sorted plots that only have plants
- show map without polygons if site has no polygons
- show disabled plot dropdown when there are no plots

SW-2401 / SW-2398 / SW-2399 Empty state updates

---

src/components/NewNursery/index.tsx
src/components/NewSeedBank/index.tsx

SW-2138 SeedBank and Nursery Forms

---

src/components/accession2/history/Accession2History.tsx
src/components/accession2/viabilityTesting/ViabilityTestingDatabase.tsx
src/components/accession2/view/DetailPanel.tsx

Added titles to tabs in the accession view.

SW-2386 Add Titles to Tabs

---

src/components/Map/GenericMap.tsx
src/components/Map/index.tsx
src/components/Plants/PlantingSiteDashboardMap.tsx
src/components/Plants/index.tsx

Defined a new generic map component

SW-2400 Empty state of plants dashboard for org with no planting sites

---

src/App.tsx
src/components/Map/GenericMap.tsx
src/components/PlantingSites/PlantingSiteCreate.tsx
src/components/PlantingSites/PlantingSiteView.tsx
src/components/Plants/DashboardChart.tsx
src/components/Plants/PlantingSiteDashboardMap.tsx
src/components/Plants/PlantingSiteDetails.tsx
src/components/Plants/index.tsx
src/components/common/TfMain.tsx

- set aspect ratio of map and charts
- set height of charts
- don't show plot/species chart if site has no plots
- fix some margin bottom issues

SW-2397 / SW-2405 More empty state updates for plants dashboard 

---

src/components/Plants/DashboardChart.tsx

Add minBarLength to ensure all values (including very small ones) draw a bar in the chart

SW-2383 Show small values in chart when the range of values is wide

---

src/components/MyAccount/index.tsx

SW-2296 Add role column to the Organization table under My Account

---

src/components/Person/NewPerson.tsx

On Create new person, remove internal scrollbar

SW-2299 Remove double scroll bar when opening dropdown

---

src/components/accession2/view/Accession2View.tsx
src/strings/index.tsx

SW-2300 Add tooltip for disabled quantity field in the accession detail page

---

src/components/Map/GenericMap.tsx
src/components/Map/PlantingSiteMap.tsx
src/components/Plants/PlantingSiteDashboardMap.tsx

- The map id was not changing because we were using the function instead of it's value (silly mistake)
- The function does not change, hence map did not change even after token was refreshed, fixed that.
- Also refactored the code to avoid making duplicate token requests
- Refactored PlantingSiteMap to use shared logic in GenericMap (PlantingSiteMap now calls GenericMap instead of Map)
- We have one place that handles all token logic now

SW-2390 Fix mapbox token expiration behavior

---

src/components/Person/NewPerson.tsx

Add/Edit Person Form

---

src/components/Map/Map.tsx

- use `initialViewState` set to bbox
- remove zoom to boundary code

SW-2410 Planting site map should start with the site boundary

---

src/api/tracking/withdrawals.ts
src/api/types/generated-schema.ts
src/api/types/tracking.ts
src/types/Device.ts

- listNurseryWithdrawals
- hasNurseryWithdrawals (to gate nav menu)
- getNurseryWithdrawal by id
- reassignments is a separate ticket
Example response for `listNurseryWithdrawals`
```
[
{
"id": "3",
"withdrawnDate": "2022-11-01",
"purpose": "Nursery Transfer",
"facility_name": "yo",
"destinationName": "test",
"totalWithdrawn": "2",
"hasReassignments": "false",
"speciesScientificNames": [
"Abelia graebneriana var. deutziifoliaada"
]
},
{
"id": "4",
"withdrawnDate": "2022-11-21",
"purpose": "Dead",
"facility_name": "yo",
"totalWithdrawn": "2",
"hasReassignments": "false",
"speciesScientificNames": [
"Dodonaea viscosa"
]
},
{
"id": "6",
"withdrawnDate": "2022-11-21",
"purpose": "Dead",
"facility_name": "yo",
"totalWithdrawn": "16",
"hasReassignments": "false",
"speciesScientificNames": [ …
```

SW-2408 API Wrappers for nursery withdrawals

---

src/components/NurseryWithdrawals/NurseryWithdrawals.tsx
src/components/NurseryWithdrawals/WithdrawalLogRenderer.tsx
src/strings/index.tsx

SW-2412 Initial withdrawal log table view with withdrawal-id link and reassign button

---

package.json
yarn.lock

- consume web-components 2.0.26

SW-2449 NavBar Errors

---

src/api/types/batch.ts
src/components/NurseryWithdrawals/NurseryWithdrawals.tsx
src/components/NurseryWithdrawals/NurseryWithdrawalsFiltersPopover.tsx
src/strings/index.tsx

SW-2334 Search and filters to withdrawal log table

---

src/components/NurseryWithdrawals/NurseryWithdrawals.tsx
src/components/NurseryWithdrawals/WithdrawalLogRenderer.tsx

Species names rendering on withdrawal log table

---

src/components/Monitoring/index.tsx
src/components/common/Expandable.tsx

- also fixed the title bar with dropdown

SW-2430 / SW-2431 Visual Updates for Sensor Kit Setup flows

---

src/components/PlantingSites/BoundariesAndPlots.tsx
src/components/PlantingSites/PlantingSitesList.tsx
src/components/PlantingSites/PlantingSitesTable.tsx
src/components/emptyStatePages/EmptyStatePage.tsx

- as per spec in other lists/tables

SW-2414 Visual updates for planting sites list/table and empty state

---

src/App.tsx
src/components/Map/Map.tsx
src/components/PlantingSites/BoundariesAndPlots.tsx
src/components/PlantingSites/PlantingSiteCreate.tsx
src/components/PlantingSites/PlantingSiteView.tsx
src/components/Plants/index.tsx
src/components/common/TfMain.tsx
src/strings/index.tsx

- used suggestions from Hannah here https://terraformation.atlassian.net/browse/SW-2421

SW-2415 / SW-2416 Visual Updates for Add/EditView Planting Site

---

src/components/Monitoring/sensorKitSetup/FlowStep.tsx
src/components/Plants/PlantingSiteDetails.tsx

- add 24px spacing between cards

Fix visual updates for plants dashboard

---

src/components/Inventory/withdraw/BatchWithdrawFlow.tsx
src/components/Inventory/withdraw/flow/AddPhotos.tsx
src/components/Inventory/withdraw/flow/SelectBatchesWithdrawnQuantity.tsx
src/components/Inventory/withdraw/flow/SelectPurposeForm.tsx
src/components/Plants/index.tsx
src/components/common/SelectPhotos.tsx
src/components/emptyStatePages/EmptyStateContent.tsx
src/strings/index.tsx

- as per Hannah's comments here https://terraformation.atlassian.net/browse/SW-2420
- and here https://terraformation.atlassian.net/browse/SW-2419
- also fixed padding issues from https://terraformation.atlassian.net/browse/SW-2434
- bulk withdrawals quantity input will be a separate PR

SW-2418 Visual Updates for new withdrawals flows

---

src/components/Inventory/withdraw/BatchWithdrawFlow.tsx

- see video
@chudo76 thoughts on this spinner?

SW-2469 Add spinner when withdraw is happening

---

src/components/Inventory/withdraw/flow/SelectPurposeForm.tsx

SW-2445 Include quantities in single Withdrawal form

---

src/api/tracking/deliveries.ts
src/api/types/tracking.ts
src/components/NurseryWithdrawals/NurseryReassignment.tsx
src/components/NurseryWithdrawals/ReassignmentRenderer.tsx
src/components/common/Card.tsx
src/components/common/TitleDescription.tsx
src/strings/index.tsx

- api wrappers
- table with partial info
- basic styling etc.

SW-2427 Intermediate effort of reassignment flow

---

src/components/Monitoring/dashboard/PVBatteryChart.tsx
src/components/Monitoring/dashboard/SeedBankDashboard.tsx
src/components/Monitoring/dashboard/TemperatureHumidityChart.tsx

SW-2483 Icons on the sensor monitoring page should be using the secondary color token

---

src/components/common/PageCard.tsx

- allow click on box (for links only, not button based cards such as on the contact-us page)
- add wrapper around link so we can prevent bubbling of click - this preserves cmd+click behavior

SW-2482 Home page cards should redirect user to target page

---

src/components/Inventory/InventoryCellRenderer.tsx
src/components/Inventory/view/BatchesCellRenderer.tsx
src/components/common/Link.tsx

- to be used across the web-app next
- use 14px size and 600 font-weight
- use no underline except when hover

SW-2484 Introduce a generic/consistent Link component and use in batches

---

src/components/Inventory/withdraw/flow/SelectPurposeForm.tsx

SW-2445 Add quantity validations for single single withdrawal

---

src/components/common/ImportModal.tsx
src/components/common/PageCard.tsx
src/components/emptyStatePages/EmptyStateContent.tsx

- kept the original font size of 16px

SW-2475 Update link styles on Home and Species pages

---

src/components/Inventory/view/BatchDetailsModal.tsx
src/components/Inventory/view/WithdrawalModal.tsx
src/components/Inventory/withdraw/flow/WithdrawalBatchesCellRenderer.tsx
src/components/Nurseries/TableCellRenderer.tsx
src/components/People/TableCellRenderer.tsx
src/components/PlantingSites/PlantingSitesCellRenderer.tsx
src/components/SeedBanks/TableCellRenderer.tsx
src/components/common/Link.tsx

Use new Link component on inventory/people and location pages

---

src/components/EditOrganization/index.tsx

This PR adjust styles for the Edit Organization page.

SW-2486: Edit organization page card inconsistent

---

package.json
src/components/Nurseries/TableCellRenderer.tsx
src/components/People/TableCellRenderer.tsx
src/components/SeedBanks/TableCellRenderer.tsx
yarn.lock

- bump web-components version
- see vercel for changes

Render tables in 14px, fix font color on nav

---

src/components/Inventory/withdraw/flow/SelectPurposeForm.tsx

- Added NaN validation
- Convert strings to number before comparing

Fix validations on single withdraw flow

---

src/components/Plants/PlantingSiteDetails.tsx
src/components/Plants/index.tsx

SW-2516 / SW-2417 Add page header wrapper to plants dashboard and fix nav spacing

---

src/App.tsx
src/api/tracking/withdrawals.ts
src/components/NurseryWithdrawals/NurseryWithdrawalsDetails.tsx
src/components/NurseryWithdrawals/WithdrawalDetails/DeadContent.tsx
src/components/NurseryWithdrawals/WithdrawalDetails/NurseryTransferContent.tsx
src/components/NurseryWithdrawals/WithdrawalDetails/OtherContent.tsx
src/components/NurseryWithdrawals/WithdrawalDetails/ReassignmentTabPanelContent.tsx
src/components/NurseryWithdrawals/WithdrawalDetails/WithdrawalTabPanelContent.tsx
src/components/NurseryWithdrawals/WithdrawalDetails/sections/Photos.tsx
src/components/NurseryWithdrawals/WithdrawalDetails/sections/ReassignmentTable.tsx
src/components/NurseryWithdrawals/WithdrawalDetails/sections/SpeciesTable.tsx
src/strings/index.tsx

SW-2338 Withdrawal Details

---

src/components/Inventory/InventoryView.tsx
src/components/Nursery/index.tsx
src/components/NurseryWithdrawals/NurseryWithdrawalsDetails.tsx
src/components/Person/index.tsx
src/components/PlantingSites/PlantingSiteView.tsx
src/components/SeedBank/index.tsx
src/components/accession2/view/Accession2View.tsx
src/components/common/BackToLink.tsx
src/components/common/Link.tsx
src/components/seeds/PageHeader.tsx

- created a BackToLink component (extracted out)
- used this component in all places
- couple snapshots attached, (use vercel to check them all)

SW-2527 Update all back-to links with correct styles

---

cypress/integration/10-database.js
package.json
src/components/Inventory/index.tsx
src/components/OrganizationsDropdown.tsx
src/components/Species/index.tsx
src/components/UserMenu.tsx
src/components/common/PopoverMenu.tsx
src/components/seeds/database/index.tsx
yarn.lock

- Create a new PopoverMenu component and use it in all menus (organization menu, user menu, and kabob menus) 
- This new menu has similar styles to a dropdown component

SW-2491 New menu component with dropdown styles

---

src/components/Monitoring/index.tsx

- fix header padding on monitoring page

SW-2447 Header Spacing Fix

---

src/components/OrganizationsDropdown.tsx
src/components/UserMenu.tsx

- add radius and padding to dropdown buttons

SW-2519 Topbar Dropdown Hover States

---

src/components/NurseryWithdrawals/ReassignmentRenderer.tsx
src/components/accession2/properties/Accession2Address.tsx
src/components/accession2/properties/Collectors2.tsx
src/components/accession2/viabilityTesting/NewViabilityTestModal.tsx
src/components/accession2/viabilityTesting/TableCellRenderer.tsx

- the checkbox was not being initialized for already saved tests
- was mostly working for newly created/edited tests

SW-2517 Show completed tests as 'marked as complete'

---

src/components/Plants/PlantingSiteDashboardMap.tsx
src/components/Plants/PlantingSiteDetails.tsx
src/components/Plants/SpeciesByPlotChart.tsx
src/components/PlotSelector/index.tsx

- disabled preselection for now

SW-2494 Use plot selector in plots chart

---

src/components/NavBar.tsx

- use hasWithdrawals API to make this decision

SW-2409 Show withdrawal log nav menu item only if org has nursery withdrawals

---

src/api/tracking/withdrawals.ts
src/api/types/generated-schema.ts
src/components/NurseryWithdrawals/NurseryWithdrawalsDetails.tsx
src/components/NurseryWithdrawals/WithdrawalDetails/WithdrawalTabPanelContent.tsx
src/components/NurseryWithdrawals/WithdrawalDetails/sections/Photos.tsx
src/components/accession2/view/DetailPanel.tsx
src/components/common/ViewPhotosModal.tsx

- do not show Reassign button if there are no plots
- query for photo ids
- display the photos in a thumbnail
- show the photos in a carousel when clicked

SW-2338 Withdrawal Log Details Photos

---

src/components/Map/Map.tsx
src/components/Map/MapModels.ts
src/components/Map/PlantingSiteMap.tsx

- as per specs in the jira
- this PR does not cover selected plots from the chart
- that will be a follow up PR

SW-2470 Add support for hover and select state fill colors on plots 

---

src/components/common/TitleDescription.tsx

Old (16px description):
New (14px description):

SW-2510 Update Description FontSize to 14px

---

src/components/Inventory/withdraw/flow/SelectPurposeForm.tsx
src/components/Map/GenericMap.tsx
src/components/Map/Map.tsx
src/components/Map/MapModels.ts
src/components/Map/PlantingSiteMap.tsx
src/components/Plants/PlantingSiteDashboardMap.tsx
src/components/Plants/PlantingSiteDetails.tsx
src/components/Plants/SpeciesByPlotChart.tsx
src/components/Plants/index.tsx
src/components/PlotSelector/index.tsx

- plumb the active object through

SW-2470 Highlight the selected plot in maps dashboard

---

package.json
src/components/Map/GenericMap.tsx
src/components/Map/Map.tsx
src/components/Map/MapModels.ts
src/components/Map/PlantingSiteMap.tsx
src/components/Plants/PlantingSiteDashboardMap.tsx
src/components/Plants/PlantingSiteDetails.tsx
src/components/Plants/SpeciesByPlotChart.tsx
src/components/PlotSelector/index.tsx
src/features.ts
yarn.lock

- rename active to highlight
- use new web-components version with autocomplete fix

SW-2470  Pan to selected zone in plants dashboard

---

src/components/NurseryWithdrawals/NurseryWithdrawalsDetails.tsx

- fix Reassign button disable criterion
- create and assign button click handler

SW-2340 Reassign Button Handler

---

src/components/Inventory/withdraw/flow/SelectPurposeForm.tsx
src/components/Plants/SpeciesByPlotChart.tsx
src/components/PlotSelector/index.tsx
src/strings/index.tsx

- show selected species (filtered by from: nursery)
- show total ready quantity for single batch outplant purpose
- see figma https://www.figma.com/file/yRSfer1xtWKAJr4IETPml1/Tracking-by-Sampling?node-id=2325%3A530101&t=K6QLnMAreJXQYNKa-4

SW-2444 Improvements to outplant withdraw flow

---

src/components/Inventory/withdraw/flow/SelectBatchesWithdrawnQuantity.tsx
src/components/Inventory/withdraw/flow/WithdrawalBatchesCellRenderer.tsx

SW-2443 Disable non-numeric and negative entries on withdrawal flow

---

src/components/NurseryWithdrawals/ReassignmentRenderer.tsx

- number did not work previously but seems to work now...

Use number texfield for reassignment flow

---

src/components/NurseryWithdrawals/ReassignmentRenderer.tsx
src/components/PlotSelector/index.tsx

- use localeCompare with numeric = true

Fix sort order of zone and plot names

---

src/App.tsx
src/components/Inventory/withdraw/BatchBulkWithdrawWrapperComponent.tsx
src/components/Inventory/withdraw/BatchWithdrawFlow.tsx
src/components/Inventory/withdraw/SpeciesBulkWithdrawWrapperComponent.tsx
src/components/Inventory/withdraw/flow/SelectPurposeForm.tsx
src/components/NavBar.tsx

- previously was checking on org change only
- also check once a withdrawal is created
- also fixed an infinite planting sites fetch error

SW-2584 Show withdrawal log menu after a withdrawal is created

---

package.json
src/components/NavBar.tsx
src/strings/index.tsx
yarn.lock

- allow opening nav root without selection
- fix strings
- fix selected route missing batch withdrawals and reassignment
- test in vercel

SW-2575 Hierarchical nav updates from web-components

---

src/components/NurseryWithdrawals/NurseryWithdrawalsDetails.tsx

No Reassignments:
Reassignments Present:

SW-2595 Hide Reassignment Panel if no Reassignments

---

src/api/tracking/withdrawals.ts

- show <deleted species> just like we do in the inventory table

SW-2600 Handle deleted species in list withdrawals wrapper

---

src/components/Inventory/InventoryCreate.tsx
src/components/Inventory/withdraw/BatchWithdrawFlow.tsx

SW-2598 Fix single batch flow switching to bulk, also fix inventory create view styles

---

package.json
src/components/Inventory/InventoryTable.tsx
yarn.lock

- show disabled withdraw button if selected rows don't have any quantities to withdraw
- we were hiding the button, show the button disabled instead

SW-2596 Show disabled withdraw button in inventory table when relevant

---

package.json
src/components/PlotSelector/index.tsx
yarn.lock

When zone dropdown has values, the width of the field was increasing. Set flex={1} to both fields (zone and plot) to ensure width doesn't change

SW-2594 Fix Zone field's width changing when selecting planting site

---

src/components/Inventory/withdraw/flow/SelectPurposeForm.tsx

- same for batches so we don't show batches with 0 ready quantity on the batch-quantity page

SW-2601 Withdrawal flow: filter nurseries by ready quantity (if outplant)

---

src/components/accession2/viabilityTesting/NewViabilityTestModal.tsx
src/strings/index.tsx

SW-2569 Add missing validations to dates when creating viability test

---

src/components/People/index.tsx

SW-659 Add search functionality to users list

---

public/index.html

Move cookie script to GTM
Support staging and prod

SW-2608 Replace Google analytics global site tag with Google tag manager

---

public/index.html

Fix GTM init

---

src/components/Species/AddSpeciesModal.tsx

SW-2609 Remove error box from add species modal

---

package.json
src/components/accession2/edit/EditLocationModal.tsx
src/components/accession2/properties/SeedBank2Selector.tsx
src/components/accession2/properties/Species2Dropdown.tsx
src/components/accession2/properties/StorageLocationSelector.tsx
src/components/accession2/properties/StorageSubLocationSelector.tsx
yarn.lock

In GTM we have some triggers on appearance of error text labels.  When reporting which label appeared it is useful to have a value in the "for" attribute.

SW-2608 Add IDs to some components to allow for easier tracking

---

src/components/Plants/PlantBySpeciesChart.tsx
src/components/Plants/PlantingSiteDashboardMap.tsx
src/components/Plants/PlantingSiteDetails.tsx

- change layout and data being shown

SW-2607 Updates to plants dashboard for sites without zones/plots

---

kb.js
src/components/Plants/PlantingSiteDetails.tsx

- previous version was spinning around 2 async calls.. basically spinner stopped spinning before calls completed
- added spinner around 2 blocking checks

Fix spinner logic in plants dashboard

---

src/components/OptInFeatures/index.tsx
src/features.ts

- mark feature as enabled
- clean up tracking-v1 flags etc will be a followup PR (Jira SW-2356)
- added a change to show enabled features as disabled for selection in the opt-in page

SW-2612 Ungate Tracking-V1 feature in the web-app

---

src/providers/hooks.ts
src/providers/index.ts

- this is temporary
- localization provider will replace this with it's time zones

SW-2687 Temporary time zones hook to unblock selector component and other page views

---

src/App.tsx
src/components/seeds/checkin/index.tsx
src/providers/DataTypes.ts
src/providers/LocalizationProvider.tsx
src/providers/contexts.ts
src/providers/hooks.ts
src/providers/index.ts
src/strings/index.tsx
src/types/TimeZones.ts

- create the data types, context, provider, and modify the useTimeZones hook
- at the App layer, wrap the component tree in the provider
- add a useEffect to fetch the time zone data from the backend
- default the locale to "en"

SW-2660 Create Localization Provider Layer

---

src/components/MyAccount/index.tsx
src/components/TimeZoneSelector.tsx
src/strings/index.tsx

- Create an initial time zone selector
- Have to update this changes when localization provider is merged
- Used the selector in my account page for testing

SW-2670 Time zone selector - initial revision with alphabetical sort

---

src/components/Inventory/view/InventorySummary.tsx
src/components/Inventory/withdraw/BatchWithdrawFlow.tsx
src/components/Inventory/withdraw/flow/SelectPurposeForm.tsx
src/components/Map/GenericMap.tsx
src/components/Map/PlantingSiteMap.tsx
src/components/NurseryWithdrawals/NurseryReassignment.tsx
src/components/NurseryWithdrawals/NurseryWithdrawals.tsx
src/components/NurseryWithdrawals/NurseryWithdrawalsDetails.tsx
src/components/NurseryWithdrawals/NurseryWithdrawalsFiltersPopover.tsx
src/components/NurseryWithdrawals/WithdrawalDetails/sections/Photos.tsx
src/components/Plants/PlantingSiteDashboardMap.tsx
src/components/Plants/index.tsx
src/components/accession2/view/Accession2View.tsx
src/utils/useSnackbar.ts

- leverage useMemo
- tested in all views

Make useSnackbar return a constant object so it doesn't trigger useEffects

---

src/utils/useTimeZoneUtils.ts

- for now just one, to get the default time zone
- this will be used across the board

SW-2683 Time zones utils

---

src/api/facility/facility.ts
src/api/organization/organization.ts
src/api/types/facilities.ts
src/components/NewNursery/index.tsx
src/components/Nurseries/TableCellRenderer.tsx
src/components/Nurseries/index.tsx
src/components/Nursery/index.tsx
src/components/TimeZoneSelector.tsx
src/strings/index.tsx
src/utils/useTimeZoneUtils.ts

- Tooltip is missing because Autocomplete component doesn't accept tooltipTitle as Textfield.

SW-2648 Add time zone display and selection to the Nursery view/edit page

---

package.json
src/components/LocationTimeZoneSelector.tsx
src/components/NewNursery/index.tsx
src/components/Nursery/index.tsx
src/components/TimeZoneSelector.tsx
src/strings/index.tsx
yarn.lock

Adding tooltips to time zone selector

---

src/components/MyAccount/index.tsx
src/components/Nursery/index.tsx
src/components/PlantingSites/PlantingSiteView.tsx
src/components/SeedBank/index.tsx
src/strings/index.tsx

- to be consistent with other views

Use textfield to show time zone in My Account details view

---

src/components/Monitoring/dashboard/SeedBankDashboard.tsx

- moved it to the right most card

Update monitoring chart time zone picker location

---

package.json
yarn.lock

This reverts commit fd3b4d8d390d313e5cd00172da5c34e7f25c8b9b.
Accidental commit on `/main`

Revert "bump web-components and remove date-io"

---

package.json
src/App.tsx
yarn.lock

SW-2504 left nav width/padding/scroll-width updates

---

src/components/Inventory/withdraw/flow/SelectPurposeForm.tsx

- Added time zone (from nursery) to withdrawnDate
- Fix value not updating for readyByDate
- Fix validations for withdrawnDate

SW-2659 Default date/time in nursery time zone for inventory withdraw

---

src/components/accession2/edit/CalculatorModal.tsx
src/components/accession2/edit/QuantityModal.tsx
src/components/accession2/withdraw/WithdrawModal.tsx
src/components/seeds/database/filters/FilterCountWeight.tsx
src/components/seeds/database/filters/FilterNumberRange.tsx
src/strings/strings-en.ts
src/units.ts

Look up strings from the strings table at render time for:
- The field labels on count/weight range and number range filter popovers
- The list of weight units in filter popovers, the "edit quantity" popover,
and the withdrawal modal

SW-2721 Look up accession quantity strings at render time

---

package.json
src/App.tsx
yarn.lock

- as per Hannah's request
- test in vercel
- also pick up scroll bar changes mentioned here https://terraformation.atlassian.net/browse/SW-2504 towards the end

SW-2751 Use 4px width on all scrollbars in web-app

---

src/components/seeds/database/filters/FilterCountWeight.tsx

onChange method on fields of filter was incorrectly used, so the input value was never set. Fix the onChange method to set the value correctly

SW-2732 Fix textfield for seeds remaning filter doesn't allow input

---

src/App.tsx

- adjust bottom margin for footer in desktop mode
- tested locally, looks good

Redo left-nav fix for rounded scrollbar

---

src/components/MyAccount/index.tsx

SW-2768 Hide MyAccount edit button when in edit mode

---

src/components/TimeZoneSelector.tsx

SW-2780 Replace autocomplete of TimeSelector with textfield when it's state is disabled

---

src/components/AddNewOrganizationModal.tsx
src/components/EditOrganization/index.tsx
src/components/TimeZoneSelector.tsx

- use country code to find relevant time zones

SW-2782 Show time zones relevant to the selected country ahead in the time zones list

---

src/components/EditOrganization/index.tsx

SW-2785 Make country and state required if available in org edit

---

package.json
src/components/NurseryWithdrawals/ReassignmentRenderer.tsx
src/components/PlotSelector/index.tsx
src/components/RegionSelector/index.tsx
src/components/TimeZoneSelector.tsx
src/components/accession2/properties/Accession2Address.tsx
src/components/accession2/properties/Collectors2.tsx
yarn.lock

- some fixes and some consistency related changes
- requires PR https://github.com/terraware/web-components/pull/269 from web-components

Use refactored dropdown props in terraware-web

---

src/App.tsx
src/components/PageSnackbar.tsx
src/providers/DataTypes.ts
src/providers/OrganizationProvider.tsx
src/providers/contexts.ts
src/state/snackbar.ts
src/utils/useSnackbar.ts

- new types are user and org
- we now have 4 types, app version, generic page, user notification, org notification

SW-2783 Refactor page message component to support types of page messages

---

src/components/common/DetectAppVersion.tsx

Tested locally for both stale and non-stale versions.

DetectAppVersion Returns null if App Version is Stale

---

src/components/accession2/edit/CalculatorModal.tsx
src/components/accession2/edit/QuantityModal.tsx
src/components/accession2/withdraw/WithdrawModal.tsx
src/units.ts

SW-2746 Order weight units according to preference

---

src/components/ConvertedValue.tsx
src/components/accession2/edit/QuantityModal.tsx
src/components/accession2/view/Accession2View.tsx
src/units.ts

SW-2752 Add converted value to edit quantity modal

---

src/api/organization/organization.ts
src/components/AddNewOrganizationModal.tsx
src/components/EditOrganization/index.tsx
src/components/Inventory/FilterUtils.ts
src/components/MyAccount/index.tsx
src/components/Nurseries/index.tsx
src/components/OrganizationsDropdown.tsx
src/components/SeedBanks/index.tsx
src/components/SmallDeviceUserMenu.tsx
src/providers/DataTypes.ts
src/providers/OrganizationProvider.tsx
src/providers/contexts.ts
src/types/Organization.ts
src/utils/organization.tsx

- **no** other changes but this touches many files

rename ServerOrganization type to just Organization

---

src/App.tsx
src/components/seeds/database/EditColumns.tsx
src/components/seeds/database/columns.ts

Change default preset, to include estimatedWeightOunces column instead of estimatedWeightGrams.
Also order columns according to preferred system

SW-2756 Change default preset for imperial preference

---

src/components/Organization/index.tsx
src/components/RegionSelector/index.tsx
src/components/accession2/properties/Accession2Address.tsx
src/components/accession2/view/DetailPanel.tsx

When the user switches locales, we need to show the new locale's country names.

SW-2797 Update country names on locale change

---

src/components/accession2/view/DetailPanel.tsx

SW-2819 Fix accession collecting site name spacing with location

---

src/components/LocaleSelector.tsx

SW-2866 Use popover component in locale selector

---

src/api/types/generated-schema.ts
src/strings/strings-en.ts
src/types/Accession.ts

SW-2823 Add option “none” to substrate viability fields

---

src/components/LocaleSelector.tsx
src/components/MyAccount/index.tsx
src/components/NavBar.tsx
src/strings/strings-en.ts

Didn't add language, since language will remain on left menu for now

SW-2864 Region category under My Account

---

package.json
src/components/seeds/checkin/index.tsx
src/components/seeds/database/index.tsx
yarn.lock

- date picker is handled in web-components

remove dependency @mui/x-date-pickers from web

---

src/components/seeds/database/Filters.tsx
src/components/seeds/database/index.tsx
src/utils/useDebounce.tsx

Add a searchbar to the accession table. This searches over the Accession,
Scientific Name, and Collecting Site columns. The `useDebounce` hook
was modified to accept a callback.

Add Searchbar to Accessions Table

---

cypress/e2e/10-database.cy.js
src/api/types/generated-schema.ts
src/components/accession2/edit/EditLocationModal.tsx
src/components/accession2/properties/SeedBank2Selector.tsx
src/components/seeds/database/EditColumns.tsx
src/components/seeds/database/columns.ts
src/components/seeds/database/index.tsx
src/services/SeedBankService.ts
src/strings/strings-en.ts
src/types/Facility.ts

There is a new API for listing a facility's storage locations; use it instead of
the old one. The new API doesn't support storage conditions; remove all references
to them from the code.
The code still has references to "Freezer" and "Refrigerator" but they are only
used in the context of sensor kit setup and monitoring.

SW-2905 Use new API for storage locations

---

src/components/accession2/edit/CalculatorModal.tsx

Allow inserting '.' when typing on subset weight field

SW-2716 Seed weight calculator not recognizing decimal point

---

src/components/Plants/DashboardChart.tsx
src/components/Plants/PlantBySpeciesChart.tsx
src/components/Plants/PlantingSiteDetails.tsx
src/components/Plants/TotalCount.tsx

- use number parser
- use number formatter
- create chart only when all data is available.. to avoid constructing charts in parallel

SW-2917 make plants dashboard work

---

src/components/Inventory/InventoryCreate.tsx
src/components/Inventory/view/BatchDetailsModal.tsx
src/components/Inventory/view/ChangeQuantityModal.tsx
src/components/Inventory/view/InventorySummary.tsx
src/components/Inventory/withdraw/BatchWithdrawFlow.tsx
src/components/Inventory/withdraw/flow/SelectPurposeForm.tsx
src/components/Map/GenericMap.tsx
src/components/NavBar.tsx
src/components/NurseryWithdrawals/NurseryReassignment.tsx
src/components/NurseryWithdrawals/NurseryWithdrawalsDetails.tsx
src/components/NurseryWithdrawals/NurseryWithdrawalsFiltersPopover.tsx
src/components/NurseryWithdrawals/WithdrawalDetails/sections/Photos.tsx
src/components/Plants/PlantingSiteDashboardMap.tsx
src/components/Plants/index.tsx
src/components/Species/AddSpeciesModal.tsx
src/components/Species/ProblemTooltip.tsx
src/components/Species/index.tsx
src/components/accession2/create/Accession2Create.tsx
src/components/accession2/edit/QuantityModal.tsx
src/components/accession2/viabilityTesting/NewViabilityTestModal.tsx
src/components/accession2/withdraw/WithdrawModal.tsx

- skip showing errors from api responses for now

SW-2931 Use generic error messages

---

src/components/Inventory/withdraw/flow/SelectPurposeForm.tsx
src/components/NurseryWithdrawals/NurseryReassignment.tsx
src/components/NurseryWithdrawals/NurseryWithdrawals.tsx
src/components/NurseryWithdrawals/NurseryWithdrawalsDetails.tsx
src/components/NurseryWithdrawals/ReassignmentRenderer.tsx
src/components/NurseryWithdrawals/WithdrawalDetails/ReassignmentTabPanelContent.tsx
src/components/NurseryWithdrawals/WithdrawalDetails/sections/NonOutplantWithdrawalTable.tsx
src/components/NurseryWithdrawals/WithdrawalDetails/sections/OutplantReassignmentTable.tsx
src/components/NurseryWithdrawals/WithdrawalDetails/sections/OutplantWithdrawalTable.tsx
src/components/NurseryWithdrawals/WithdrawalLogRenderer.tsx

- format table values
- parse formatted values in certain places, such as in reassignment for validation to work
- table sort by quantity is now fixed

SW-2934 Misc updates for nursery withdrawals in withdrawal log

---

src/components/FeatureNotification/OrganizationNotification.tsx
src/components/FeatureNotification/UserNotification.tsx
src/components/FeatureNotification/index.tsx
src/components/NotificationsDropdown.tsx
src/services/UserService.ts
src/types/Notifications.ts

@karthikbtf is something like this the idea you have? 
I still need to figure out how to allow each "feature notification" to have their own "markAsRead" function

Create a 'FeatureNotifications' component to use in Notifications component

---

src/components/Species/index.tsx

- Allow sorting on the BE
- seedStorageBehavior and ecosystemType are sort in the FE.

SW-2940 Species table should use BE sorted results when sort order/field changes

---

src/components/FeatureNotification/OrganizationNotification.tsx
src/components/FeatureNotification/UserNotification.tsx

SW-2958 Use time zone's localized name instead of it's id in the notification

---

src/components/NurseryWithdrawals/ReassignmentRenderer.tsx
src/components/SeedBank/StorageLocations.tsx
src/components/SeedBank/StorageLocationsCellRenderer.tsx
src/components/SeedBank/index.tsx
src/components/accession2/edit/EditLocationModal.tsx
src/components/accession2/properties/SeedBank2Selector.tsx
src/components/seeds/database/index.tsx
src/components/seeds/summary/index.tsx
src/features.ts
src/services/SeedBankService.ts
src/strings/strings-en.ts
src/types/Accession.ts
src/types/Facility.ts
src/types/Number.ts
src/utils/useNumber.ts

- allow clicking on a location name to see accessions view

SW-2911 / SW-2947 / SW-2953 Show storage locations in seed bank details view

---

src/components/Nurseries/TableCellRenderer.tsx
src/components/Nurseries/index.tsx
src/components/PlantingSites/PlantingSitesCellRenderer.tsx
src/components/PlantingSites/PlantingSitesList.tsx
src/components/SeedBanks/TableCellRenderer.tsx
src/components/SeedBanks/index.tsx
src/services/FacilityService.ts
src/utils/useTimeZoneUtils.ts

- also fix search to use localized facility enum value

SW-2962 / SW-2963 Sort timezones by display name, use localized facility type in searches

---

src/AppBootstrap.tsx

Avoid using display flex to center the spinner, because that was adding scrollbars apparently.

SW-2955 Remove scrollbars during progress circle animation

---

src/components/seeds/database/Filters.tsx

SW-2621 Add Pills to Accession Filters

---

src/components/Inventory/InventoryCreate.tsx
src/components/Inventory/InventoryTable.tsx
src/components/Inventory/index.tsx
src/components/Inventory/view/BatchDetailsModal.tsx
src/components/Inventory/view/InventorySeedlingsTable.tsx
src/components/Inventory/withdraw/BatchWithdrawFlow.tsx
src/components/Inventory/withdraw/SpeciesBulkWithdrawWrapperComponent.tsx
src/components/Inventory/withdraw/flow/SelectBatchesWithdrawnQuantity.tsx
src/components/Inventory/withdraw/flow/SelectPurposeForm.tsx
src/components/NurseryWithdrawals/NurseryReassignment.tsx
src/components/NurseryWithdrawals/ReassignmentRenderer.tsx
src/components/Plants/PlantingSiteDashboardMap.tsx
src/components/Plants/PlantingSiteDetails.tsx
src/components/Plants/SpeciesByPlotChart.tsx
src/services/NurseryBatchService.ts
src/services/NurseryInventoryService.ts
src/services/TrackingService.ts
src/types/PlantingSite.ts

- remove parsing logic
- cleaned up a whole bunch of semantics help in components, moved then to services
- updated plants dashboard to use raw fields

SW-2949 Use (raw) fields for inventory quantity based logic

---

src/components/NewNursery/index.tsx
src/components/NewSeedBank/index.tsx
src/components/PlantingSites/PlantingSiteCreate.tsx
src/components/PlantingSites/PlantingSiteView.tsx
src/strings/strings-en.ts

- used copy from Allison
- My Account tooltip is my own.. will update as I hear from Allison

SW-2761 Tooltips for timezones

---

src/components/common/FilterGroup/filters/FilterMultipleSelection.tsx

Use MultiSelect Component in FilterGroup

---

src/api/types/generated-schema.ts
src/components/SeedBank/StorageLocations.tsx
src/components/accession2/edit/EditLocationModal.tsx
src/components/accession2/properties/SeedBank2Selector.tsx
src/services/SeedBankService.ts
src/services/StorageLocationService.ts
src/services/index.ts
src/services/utils.ts
src/types/Id.ts

- introduced storage location service
- added some bulk API handling in anticipation of related UX

SW-2966 Storage locations API wrappers

---

src/services/UserService.ts

This behavior was happening with new users because when timezone feature is activated we initialize the timezone and set 'updated' value to 'true' to show the timezone notification. The problem was that after updating the timezone, the 'reloadUser' was called, and the validation to show or not the notification was being executed again, and because the 'updated' value was always true (because it comes from a chached promise) the user was being reloaded all the time (calling reloadUser), making the options for timeZones reload all the time because we need the selected timezone for the user.
The fix was to set 'updated' value to true the first time the timezone is set, and after that make the cached promise null, so the 'updated' value can be refreshed (to false, after timezone is already …

SW-2969 Fix strange scroll behavior in time zone selector

---

package.json
src/components/accession2/edit/CalculatorModal.tsx
src/components/accession2/edit/QuantityModal.tsx
yarn.lock

This require the new web-components version to work

Don't allow users enter decimals for the seed count

---

src/components/accession2/view/Accession2View.tsx
src/utils/useTimeZoneUtils.ts

- accession age
- acession drying end date

SW-2985 use seedbank's time zone in accession details' relative time displays

---

src/services/test/HttpService.test.ts
src/services/test/OrganizationService.test.js

- moved service tests under src/services/test
- need to refactor OrganizationService.test.js will do that separately

SW-2835 unit tests for HttpService

---

src/components/Inventory/withdraw/BatchWithdrawFlow.tsx
src/components/Inventory/withdraw/flow/AddPhotos.tsx
src/components/NewSeedBank/index.tsx
src/components/common/BusySpinner.tsx
src/components/common/FormBottomBar.tsx
src/components/common/PageForm.tsx

Testing in create seedbank. 
Still have to add it to others pages

SW-2739 Disable call-to-action buttons while processing

---

src/components/NewNursery/index.tsx
src/components/NewSeedBank/index.tsx
src/components/PlantingSites/PlantingSiteCreate.tsx

- locations => nursery, seed bank, planting site
- send user to new location upon add
- send user to same location upon edit
- send user to list view on cancel of add
- send user to same location on cancel of edit

SW-3024 Add/edit locations flows should redirect user to recent context

---

src/components/accession2/edit/CalculatorModal.tsx
src/strings/strings-en.ts

- use number type inputs so we can avoid text<-->number processing issues
- also show validation so we don't send bad data to BE and error out

SW-3017 Allow decimals in total weight / calculator 

---

src/api/types/generated-schema.ts
src/services/ReportService.ts
src/types/Report.ts

Add a report service with all the apis
Files and photos management may be reviewed when using it

Reports service to abstract APIs

---

src/services/test/MapService.test.ts
src/services/test/NurseryWithdrawalService.test.ts
src/services/test/data/nurseryWithdrawalsProcessed.json
src/services/test/data/nurseryWithdrawalsRaw.json
src/services/test/utils.ts

- list withdrawals and has withdrawals

SW-2837 Nursery withdrawal service unit tests

---

package.json
src/components/NurseryWithdrawals/NurseryWithdrawals.tsx
src/components/Species/index.tsx
src/components/accession2/create/Accession2Create.tsx
src/components/seeds/database/Filters.tsx
yarn.lock

Change some icon buttons to 'ghost' priority.  Change 'Create' to 'Save' for accessions

SW-2037 / SW-2448 Various button style updates

---

src/components/Reports/ReportEdit.tsx
src/components/Reports/ReportFormAnnual.tsx
src/components/Reports/ReportView.tsx
src/components/Reports/useReportFiles.ts
src/services/ReportService.ts

SW-3124 Add Upload Budget File(s) to Report

---

src/components/Reports/LocationSection.tsx
src/components/Reports/ReportEdit.tsx
src/components/Reports/ReportForm.tsx

- Adding required validation only to first report step

SW-2890 Adding required validation to quarterly fields when submitting

---

docker-compose.yml
src/components/Reports/LocationSection.tsx

SW-3182 Add `%` to Mortality Rate Fields

---

src/components/Reports/ReportEdit.tsx

SW-3200 Add Save Confirmation

---

src/components/Reports/ReportForm.tsx

Only selected seedbanks/nurseries/planting sites should be included in counts.

SW-3245 Facility Count Only Selected

---

src/App.tsx
src/components/NavBar.tsx
src/types/Organization.ts

- Don't show the reports nav item if there are no reports yet
- Don't show reports nav item if org isn't tagged reporter
- If the org is not tagged 'reporter' don't allow it to access reports

SW-3218, SW-3267 Require Reporter Tag and Existing Reports to Access Reports

---

src/components/Reports/ReportFormAnnual.tsx

SW-3195 Match Annual Report Input Field Heights to Page Size

---

src/components/Reports/ReportView.tsx
src/strings/csv/en.csv

SW-3206 View Annual/Quarterly Report Page Buttons

---

src/components/accession2/view/Accession2View.tsx
src/components/common/OverviewItemCard.tsx
src/components/common/PageCard.tsx

Additionally, don't display edit icon for viability for mobile until we have a viability to edit.

SW-2501 Make cards on home page clickable again

---

src/components/Reports/ReportForm.tsx
src/components/Reports/ReportFormAnnual.tsx
src/components/common/FormBottomBar.tsx

- fix margin around report content frame
- fix mobile button layout (stacked instead of horizontal)

SW-3268 Visual Bugfixes

---

src/api/types/generated-schema.ts
src/components/Reports/LocationSection.tsx

References removal of the field in https://github.com/terraware/terraware-server/pull/1054

SW-3352 Update generated-types and completely remove mortalityRateInNursery

---

package.json
src/App.tsx
src/components/SmallDeviceUserMenu.tsx
src/strings/csv/en.csv
yarn.lock

Make account menu look more like nav on mobile.
Fix slide-in on navbar, which wasn't happening

SW-2704 / SW-2705 Update styles of nav and user menus on mobile

---

src/components/Reports/ReportEdit.tsx

SW-3366 Busy Spinner w/ Skrim for Save and Submit

---

src/components/Reports/ReportEdit.tsx
src/components/Reports/ReportForm.tsx
src/components/Reports/ReportFormAnnual.tsx

- omit showing the changes saved toast when switching pages for an error
- add ids to all fields and scroll to the first id with an error

SW-3367 Error Toast and Scroll to Error

---

.phrase.yml

Configure Phrase to import strings from the English strings CSV and export them to
CSV files for each supported locale.

SW-3272 Add Phrase config file

---

src/strings/csv/en.csv
src/strings/csv/es.csv

Exported the most recent locale files from Phrase

Updated translations from Phrase

---

src/strings/locales.ts

Allow users to select Spanish in the language selector.

Add Spanish to list of locales

---

src/components/NotificationsDropdown.tsx
src/components/SmallDeviceUserMenu.tsx
src/components/accession2/edit/QuantityModal.tsx
src/components/common/DivotPopover.tsx

Notifications menu, seed quantity modal, user menu style updates for mobile

SW-2705 / SW-2706 / SW-3384 Mobile style fixes

---

src/App.tsx
src/components/Reports/ReportEdit.tsx

Must reload org after submitting for changes in https://github.com/terraware/terraware-server/pull/1080 to appear.

SW-3433 Save SeedBank and Nursery Info on Submit

---

package.json
src/components/Reports/LocationSection.tsx
src/components/Reports/ReportForm.tsx
src/components/Reports/ReportFormAnnual.tsx
yarn.lock

SW-3434 Preserve Newlines in Report Textfields

---

src/components/Reports/ReportEdit.tsx
src/strings/csv/en.csv

- wait for quarterly page nav to finish before showing error toast
- update error message verbiage

SW-3474 SW-3475 Reporting QA Updates

---

src/components/Inventory/InventoryFiltersPopover.tsx
src/components/NurseryWithdrawals/NurseryWithdrawals.tsx
src/components/Species/index.tsx
src/components/accession2/edit/QuantityModal.tsx
src/components/seeds/database/Filters.tsx

This allows for longer button labels which are needed for Spanish.

SW-3405 / SW-3406 Increase widths of popups

---

package.json
yarn.lock

Update typescript to 5.0.0

---

src/components/Inventory/view/BatchesExportModal.tsx
src/components/Inventory/view/InventorySeedlingsTable.tsx
src/components/common/ExportCsvModal.tsx
src/components/seeds/database/DownloadReportModal.tsx
src/services/NurseryBatchService.ts

- reused modal from accessions download (refactored it for reuse)
- verified the download works as required by the jira ticket, result csv attached
[test_ggggaaa_facilities.csv](https://github.com/terraware/terraware-web/files/11391773/test_ggggaaa_facilities.csv)

SW-3099 Export/download inventory batches from the seedlings table

---

cypress/e2e/10-database.cy.js
src/components/accession2/viabilityTesting/ViewViabilityTestModal.tsx
src/components/seeds/database/DownloadReportModal.tsx
src/components/seeds/database/EditColumns.tsx
src/components/seeds/database/TableCellRenderer.tsx
src/components/seeds/database/columns.ts
src/components/seeds/database/index.tsx
src/strings/csv/en.csv
src/strings/csv/es.csv

- We have a [new list and order](https://docs.google.com/spreadsheets/d/163ZfE71_o-iRHjKFF4Uoboc8oEdNDpml0PXLBpus03Y/edit#gid=0) from Ming 
- Removed and updated the order as per Ming's request
- also persist columns when they are reordered
- add viability percent as new column
- there's an outstanding task to keep the column order when columns are added/removed (don't append to the end), will be a follow-up
- best to preview this in vercel to see changes

SW-3529 Update accessions columns configuration 

---

src/strings/csv/en.csv

- as discussed in jira
- since this can get bigger over time, there is a new plan to have roles information point to a more detailed page of information (that's a follow up for another time)

SW-2766 Update roles descriptions to cover nursery and planting sites

---

src/services/FacilityService.ts

- pass the capacity in the api payload, it was missed somehow

SW-3409 Save nursery capacity on new nursery creation

---

src/components/AddNewOrganizationModal.tsx
src/strings/csv/en.csv

- refer to correct position of menus

SW-3431 Re-orient organization-created message content

---

package.json
yarn.lock

terraware-web: bump web-components to pick up mobile nav changes

---

.storybook/main.ts
.storybook/preview.tsx
package.json
src/stories/TfMain.stories.tsx
yarn.lock

- Added storybook using `npx storybook init`
- Correctly initialize theme in preview.tsx
- Add a story for the TfMain component to prove things are working

SW-3626 Storybook Integration

---

package.json
src/components/common/MapDateSelect/DateSlider.tsx
src/components/common/MapDateSelect/index.tsx
src/stories/MapDateSelect.stories.tsx
yarn.lock

SW-3632 Observation Date Selection Slider

---

src/components/Map/Map.tsx
src/components/Map/PlantingSiteMap.tsx
src/components/PlantingSites/BoundariesAndZones.tsx
src/components/common/MapLayerSelect/index.tsx
src/stories/MapLayerSelect.stories.tsx

TODO: update the planting site map to be able to display monitoring plots

SW-3715 Add Layer Selection to Planting Site Map

---

package.json
src/components/Observations/ObservationsDataView.tsx
src/components/Observations/ObservationsHome.tsx
src/components/Observations/index.tsx
src/components/PlantsPrimaryPage/index.tsx
src/redux/features/observations/observationsSelectors.ts
src/redux/features/observations/observationsSlice.ts
src/redux/features/observations/observationsThunks.ts
src/redux/features/species/speciesSelectors.ts
src/redux/features/species/speciesSlice.ts
src/redux/features/species/speciesThunks.ts
src/redux/features/tracking/trackingSelectors.ts
src/redux/features/tracking/trackingSlice.ts
src/redux/features/tracking/trackingThunks.ts
src/redux/rootReducer.ts
src/services/ObservationsService.ts
src/types/Observations.ts
yarn.lock

- merge observations with sites data
- add species/planting-sites redux code
- refactor wrapper for observations to centralize request dispatch

Merge observations with sites data

---

src/components/Observations/ObservationsDataView.tsx
src/components/Observations/org/OrgObservationsListView.tsx
src/components/Observations/search/index.tsx
src/redux/features/observations/observationsSelectors.ts
src/utils/search.ts

- search only searches zone names (as per design annotation)
- added a search selector
- search filters will be added later on

SW-3718 add search input to observations page

---

src/components/Observations/ObservationsDataView.tsx
src/components/Observations/map/ObservationMapView.tsx

- need to get copy from Rachel etc.

Add placeholder content for map view with 'All planting sites

---

src/components/Map/Map.tsx
src/components/Map/PlantingSiteMap.tsx
src/components/Observations/map/ObservationMapView.tsx
src/services/MapService.ts
src/types/Map.ts

- Make the topmost layer interactive
- Dynamically subscribe and unsubscribe map event handlers
- Show annotations for topmost layer
- Show a tooltip with placeholder text upon click

SW-3733 Make Map Layers Dynamically Interactive

---

src/components/Observations/common/DetailsPage.tsx
src/components/Observations/details/index.tsx
src/components/Observations/map/ObservationMapView.tsx
src/components/Observations/org/OrgObservationsListView.tsx
src/components/Observations/org/OrgObservationsRenderer.tsx
src/components/Observations/zone/index.tsx
src/redux/features/observations/utils.ts
src/types/Observations.ts

- keep completedTime as-is
- introduce completedDate for more correct semantics

redo completedTime vs completedDate for observations in FE

---

src/components/Observations/map/ObservationMapView.tsx
src/components/Observations/map/TooltipContents.tsx
src/strings/csv/en.csv

SW-3753 Map Tooltip Data

---

src/components/Observations/map/ObservationMapView.tsx

Per request from Rachel on figma

Zoom to Full Scene When Clearing Search/Filters

---

src/App.tsx
src/components/PlantsV2/index.tsx

- create PlantsDashboardV2 with placeholder
- conditionally render V1 or V2 depending on opt-in

SW-3689 Old vs New Plants Dashboard

---

package.json
yarn.lock

SW-3771 Consume React Hook Violation Fix

---

src/strings/csv/en.csv

- see https://terraformation.atlassian.net/browse/SW-3769

Update tooltip for active accessions in dashboard to include awaiting check-in

---

src/strings/csv/en.csv

- in case this is more machine readable
- removed comment from OUTSTANDING, we could leave that as 'exceptional'

try another comment/hint for outstanding

---

src/components/Species/TableCellRenderer.tsx
src/components/Species/index.tsx
src/types/Species.ts

- ecosystem type is returned translated from the BE
- do not try to do the lookup for translation on the FE

SW-3802 Render Translated Ecosystems in Species Table

---

src/strings/csv/en.csv

Fix observation event notification string

---

src/redux/features/tracking/sitePopulationSelector.ts
src/redux/features/tracking/trackingSelectors.ts
src/redux/features/tracking/trackingSlice.ts
src/redux/features/tracking/trackingThunks.ts
src/redux/rootReducer.ts

- reported planting population will be needed for plants dashboard v2
- add slice, thunk, and selectors to get this data
- code is currently dark but compiles

SW-3747 Add Redux to Select Site Populations

---

src/api/types/generated-schema.ts
src/components/TooltipLearnMoreModal/index.tsx
src/strings/csv/en.csv
src/types/Species.ts

The forestry team requested some additional seed storage behavior
options for cases where the behavior hasn't yet been scientifically
confirmed.

SW-3819 Add new seed storage behaviors

---

package.json
src/components/PlantsV2/components/NumberOfSpeciesPlantedCard.tsx
src/components/PlantsV2/components/TotalReportedPlantsCard.tsx
src/components/PlantsV2/index.tsx
src/components/common/Chart/BarChart.tsx
src/strings/csv/en.csv
yarn.lock

- add yLimits to the bar chart props
- add barAnnotations and the chartjs-plugin-annotation library

SW-3774 Number of Species Card

---

src/api/types/generated-schema.ts
src/components/PlantsV2/components/TotalMoratlityRateCard.tsx
src/components/PlantsV2/index.tsx
src/strings/csv/en.csv

SW-3781 Total mortality rate card

---

src/components/PlantsV2/components/PlantingSiteProgressCard.tsx
src/components/PlantsV2/index.tsx
src/strings/csv/en.csv

SW-3775 Planting Site Progress Card

---

src/components/PlantingSites/PlantingSiteCreate.tsx
src/components/PlantingSites/PlantingSiteView.tsx
src/strings/csv/en.csv
src/utils/dateFormatter.ts

- added start/end months which are read-only
- added util to return month
- moved boundaries/zones inside the panel

SW-3680 / SW-3852 Planting start/end months in planting site details page

---

src/components/PlantsV2/components/PlantingProgressPerZoneCard.tsx
src/components/PlantsV2/components/PlantingSiteProgressCard.tsx
src/components/PlantsV2/components/PlantsReportedPerSpeciesCard.tsx
src/components/PlantsV2/index.tsx
src/components/common/Chart/BarChart.tsx
src/components/common/Chart/Chart.tsx
src/strings/csv/en.csv
src/utils/text.tsx

SW-3776 Planting Progress Per Zone Card

---

src/strings/csv/en.csv

Based on feedback from seed banking team

SW-3847 / SW-3848 Update seed and plant type descriptions

---

src/components/PlantsPrimaryPage/PlantsPrimaryPageView.tsx
src/components/PlantsPrimaryPage/index.tsx
src/components/PlantsV2/index.tsx
src/strings/csv/en.csv

SW-3787 Adding dashboard header text

---

src/components/PlantsV2/components/PlantingDensityPerZoneCard.tsx
src/components/PlantsV2/index.tsx
src/components/common/Chart/Chart.tsx
src/strings/csv/en.csv

SW-3777 SW-3786 Planting Density by Zone Card

---

src/components/PlantsV2/index.tsx

The cards have come particular arrangement requirements based on whether there are observations, planting is complete, etc. Do some rearrangement based on those conditions.

SW-3770 Rearrange Cards

---

src/components/PlantsV2/index.tsx
src/strings/csv/en.csv

SW-3684 Empty state when no planting sites

---

src/components/MyAccount/index.tsx
src/components/RegionSelector/index.tsx
src/strings/csv/en.csv

Show the user's country in My Account, and allow them to choose a different one.

SW-3868 Add country to My Account

---

src/components/Observations/map/ObservationMapView.tsx
src/components/PlantingSites/BoundariesAndZones.tsx
src/components/common/PlantingSiteMapLegend.tsx
src/services/MapService.ts
src/strings/csv/en.csv
src/types/Observations.ts

- generate map data from aggregated info
- no popups yet, separate PR

SW-3858 map view for planting site details page

---

src/components/Map/PlantingSiteMap.tsx
src/components/PlantingSites/BoundariesAndZones.tsx
src/components/PlantingSites/PlantingSiteCreate.tsx
src/components/PlantingSites/PlantingSiteView.tsx

- add focus/highlight props
- also fix map height to fit in view area

SW-3911 Add zone search/zoom in planting site details map view

---

src/components/PlantsV2/components/TotalReportedPlantsCard.tsx
src/components/PlantsV2/index.tsx
src/strings/csv/en.csv

SW-3875 Update Reported Plants Card When Planting Complete

---

src/components/PlantsV2/components/ObservedNumberOfSpeciesCard.tsx
src/components/PlantsV2/index.tsx
src/strings/csv/en.csv

SW-3876 Observed Number of Species Card

---

src/components/PlantsV2/components/HectaresPlantedCard.tsx
src/components/PlantsV2/components/HighestAndLowestMortalityRateSpeciesCard.tsx
src/components/PlantsV2/components/HighestAndLowestMortalityRateZonesCard.tsx
src/components/PlantsV2/components/LiveDeadPlantsPerSpeciesCard.tsx
src/components/PlantsV2/components/ObservedNumberOfSpeciesCard.tsx
src/components/PlantsV2/components/PlantingDensityPerZoneCard.tsx
src/components/PlantsV2/components/PlantingSiteDensityCard.tsx
src/components/PlantsV2/components/TotalMoratlityRateCard.tsx
src/components/PlantsV2/components/TotalReportedPlantsCard.tsx
src/components/PlantsV2/components/ZoneLevelDataMap.tsx
src/components/PlantsV2/index.tsx
src/redux/features/observations/observationsSelectors.ts

- Take the latest observation logic out of the dashboard index
- Put into a selector
- Select the latest observation in the card components

SW-3682 Convert Latest Observation to a Selector and use in Cards

---

src/components/LocaleSelector.tsx
src/components/MyAccount/index.tsx
src/components/RegionSelector/index.tsx
src/components/WeightSystemSelector.tsx

SW-3919 MyAccount language and preferred units selectors should be full width

---

src/components/NurseryWithdrawals/NurseryPlantingsAndWithdrawals.tsx
src/components/NurseryWithdrawals/NurseryWithdrawalsTabContent.tsx
src/components/NurseryWithdrawals/PlantingProgressList.tsx
src/components/NurseryWithdrawals/PlantingProgressMap.tsx
src/components/NurseryWithdrawals/PlantingProgressTabContent.tsx
src/strings/csv/en.csv

- added list/map view
- added search props and filter for planting complete
- some style fixes

SW-3894 Add title/description and map/list view components in Planting Progress

---

src/components/NurseryWithdrawals/NurseryPlantingsAndWithdrawals.tsx
src/components/PlantsV2/components/PlantingSiteDensityCard.tsx
src/components/PlantsV2/components/TotalReportedPlantsCard.tsx
src/components/PlantsV2/index.tsx
src/redux/features/plantings/plantingsSelectors.ts
src/redux/features/plantings/plantingsThunks.ts

- the scope here is all plantings and we select site using a selector
- used observations pattern here to select all plantings and select a single site off that
- this will also be reused for withdrawals plantings
- updated selectors and calls
- also some code fixes to only listen to org id

Refactor plantings redux to fetch all plantings

---

package.json
src/components/NurseryWithdrawals/NurseryPlantingsAndWithdrawals.tsx
yarn.lock

- allow preserving tabs in url deep links and upon reload of page
- similar to what we do in the accessions view page (code lifted from there)

SW-3935 Store withdrawals tab in url params

---

src/components/NurseryWithdrawals/PlantingProgressMap.tsx
src/components/NurseryWithdrawals/PlantingProgressTabContent.tsx
src/strings/csv/en.csv

SW-3903 Display Map for Selected Planting Site

---

package.json
src/components/NurseryWithdrawals/PlantingProgressList.tsx
src/redux/features/plantings/plantingsSelectors.ts
yarn.lock

- bump web-components to get boolean rendering fix
- fix search to show the correct number of columns (this is a one-time setting for the org not for every search data change)
- update selector to filter out sites that have 0 plantings progress

SW-3909 Fix search and rendering of boolean in planting progress table

---

src/components/Map/Map.tsx
src/components/NurseryWithdrawals/PlantingProgressMap.tsx
src/components/NurseryWithdrawals/PlantingProgressMapDialog.tsx
src/components/PlantsV2/components/NumberOfSpeciesPlantedCard.tsx
src/components/PlantsV2/components/ObservedNumberOfSpeciesCard.tsx
src/components/PlantsV2/components/PlantsReportedPerSpeciesCard.tsx
src/components/PlantsV2/components/TotalReportedPlantsCard.tsx
src/components/PlantsV2/index.tsx
src/redux/features/tracking/sitePopulationSelector.ts
src/strings/csv/en.csv
src/types/Map.ts

- define popup renderer
- popup gets population data to display number of seeds by species
- include button to update whether planting is complete for subzone

SW-3905 SW-3907 Show Modal When Subzone is Clicked

---

package.json
src/components/NavBar.tsx
src/components/NurseryWithdrawals/NurseryPlantingsAndWithdrawals.tsx
yarn.lock

- also redo tabs SW-3940, this is pending another PR https://github.com/terraware/web-components/pull/411

SW-3892 Rename menu item to 'Withdrawals'

---

src/components/NurseryWithdrawals/PlantingProgressList.tsx
src/components/NurseryWithdrawals/StatsWarningModal.tsx
src/strings/csv/en.csv

- Added modal when undoing planting complete
- TODO: Verify if selected subzones have statistics

SW-3898 Show modal warning if observations stats exist

---

src/components/NurseryWithdrawals/PlantingProgressMap.tsx
src/components/PlantsV2/components/PlantingSiteDensityCard.tsx
src/components/PlantsV2/components/TotalReportedPlantsCard.tsx
src/components/PlantsV2/index.tsx
src/redux/features/plantings/plantingsSelectors.ts
src/redux/features/tracking/trackingSelectors.ts
src/redux/features/tracking/trackingSlice.ts
src/redux/features/tracking/trackingThunks.ts
src/redux/rootReducer.ts
src/services/TrackingService.ts
src/types/Tracking.ts

- create service
- create redux
- replace plantings date range selector with new selector
- delete extraneous calculations

SW-3950 Use Site Reported Plants Endpoint

---

src/components/NurseryWithdrawals/PlantingProgressList.tsx
src/strings/csv/en.csv

The snackbar in design is only shown when subzone is marked as planting complete.
Adding messages for both cases

SW-3960 Show Success planting complete snackbar

---

src/components/PlantsV2/components/NumberOfSpeciesPlantedCard.tsx

SW-3955 Limit decimal places in percentage bar charts

---

src/components/NurseryWithdrawals/PlantingProgressMap.tsx
src/strings/csv/en.csv

SW-3954 Display Message When No Map Data

---

src/components/NurseryWithdrawals/PlantingProgressList.tsx
src/components/NurseryWithdrawals/PlantingProgressMap.tsx
src/components/NurseryWithdrawals/PlantingProgressMapDialog.tsx
src/components/NurseryWithdrawals/PlantingProgressTabContent.tsx
src/components/NurseryWithdrawals/StatsWarningModal.tsx

- refactored passing of id/val in a more constrained context
- moved reloadTracking into a useCallback so map doesn't go into an infinite rendering/reloading loop

SW-3908 Changes to PR 1597 (warning dialog on update planting complete on map)

---

src/components/PlantsV2/components/NumberOfSpeciesPlantedCard.tsx
src/strings/locales.ts
src/utils/useNumber.ts

This allows showing ' , or . ' in chart label

Add locale to chart label

---

src/components/NurseryWithdrawals/PlantingProgressList.tsx
src/components/NurseryWithdrawals/PlantingProgressMap.tsx
src/components/NurseryWithdrawals/PlantingProgressMapDialog.tsx
src/components/NurseryWithdrawals/PlantingProgressTabContent.tsx
src/components/NurseryWithdrawals/StatsWarningModal.tsx

Reverts terraware/terraware-web#1601

Revert "SW-3908 Changes to PR 1597 (warning dialog on update planting complete on map)"

---

src/components/PlantsV2/index.tsx

Hide planting density chart if site has no observations

SW-3967 site planting density is shown even when no observations have occurred

---

src/components/PlantsV2/components/PlantsReportedPerSpeciesCard.tsx

SW-3490 Dashboard plants per species empty state

---

src/utils/dateFormatter.ts

SW-4003 Map planting site season start/end months to string keys

---

src/components/Map/PlantingSiteMap.tsx
src/components/PlantingSites/BoundariesAndZones.tsx

SW-4008 Hide Monitoring Plots Layer if None Exist

---

src/components/NurseryWithdrawals/PlantingProgressList.tsx
src/components/NurseryWithdrawals/PlantingProgressTabContent.tsx
src/redux/features/plantings/plantingsSelectors.ts
src/redux/features/tracking/trackingSelectors.ts

SW-3966 Adding plating site filter to planting progress list

---

src/components/PlantsV2/components/LiveDeadPlantsPerSpeciesCard.tsx

- add Math.round() because only whole numbers make sense here

SW-4020 Whole Numbers for Live/Dead Plants per Species

---

src/components/PlantsV2/index.tsx

- refactored the code to be explicit on how to layout the cards (using the figma design as a template)
- this may seem repetitive but is more readable and i suspect less prone to error

SW-4029 Fix disappearing cards in plants dashboard when there are no observations on planting-completed subzones

---

src/components/PlantsV2/components/NumberOfSpeciesPlantedCard.tsx

- also check for 'CR' category

SW-4052 Include critically endangered species in endangered tally bar chart (plants v2 dashboard)

---

src/components/Observations/common/SpeciesMortalityRateChart.tsx
src/components/Observations/common/SpeciesTotalPlantsChart.tsx

SW-4051 Use scientific names where available in the observation details species charts

---

src/components/accession2/properties/Species2Dropdown.tsx

Sort species list alphabetically

SW-4056 Nursery inventory add species dropdown should be alphabetized

---

src/components/Observations/plot/index.tsx

SW-4074 Don't show mortality information for temporary plots

---

src/components/Observations/index.tsx

- remove filter intialization with Completed state

SW-4061 Don't default observations to 'completed' observations

---

src/components/PlantingSites/PlantingSiteView.tsx
src/components/PlantingSites/SimplePlantingSite.tsx
src/components/PlantsV2/components/SimplePlantingSiteMap.tsx

Make the simple planting site map grow to fill the viewport if
the window is tall, rather than using a fixed height.

SW-3932 Expand simple planting site map

---

src/components/Observations/common/AggregatedPlantsStats.tsx
src/components/Observations/details/ObservationDetailsRenderer.tsx
src/components/Observations/org/OrgObservationsRenderer.tsx
src/components/Observations/plot/index.tsx
src/components/Observations/zone/ObservationPlantingZoneRenderer.tsx

SW-4079 Don't show the default 0's for observations that were not recorded

---

src/components/PlantsV2/components/HectaresPlantedCard.tsx
src/strings/csv/en.csv

- see Jira for Rachel's latest changes

SW-4023 Update planted area card text and footer changes
