- .github/workflows/workflow.yml
> Cancel in-progress builds of previous commits on branches that aren't main

- src/components/Species/TableCellRenderer.tsx
MUI was setting a maxWidth of 300px, and for our 3 button tooltip we need a bit more space.
> Fix style to species problem Dialog Box

- package.json
- src/api/types/generated-schema.ts
- src/components/accession2/Accession2Create.tsx
- src/components/accession2/Accession2PlantSiteDetails.tsx
- src/strings/index.tsx
- src/types/Accession.ts
- yarn.lock
The icon for tooltip will be followed up, pending this review https://github.com/terraware/web-components/pull/53
Also, the collectionSiteNotes property is being used here and in address view textareas.
The address view property will be supported soon in BE.
> SW-1527 Add accession, enter plant/site details

- src/components/accession2/Accession2PlantSiteDetails.tsx
- src/components/accession2/CollectionSource.tsx
- src/components/accession2/DetailPanel.tsx
- src/components/common/Select/Select.tsx
- src/strings/index.tsx
- added a new Select utility that has a { label, value } type for options but string for selectedValue and onChange
- we could maybe move this into web-components as a new Dropdown component? the Current one is outdated
> SW-1605 Show in-situ/ex-situ suffixes for collection source

- src/components/accession2/history/Accession2History.tsx
- src/components/accession2/view/Accession2View.tsx
- don't shift elements to the right when showing edit icon
- show edit icon in mobile views + layout updates according to designs
- style fix for history in mobile
> SW-1677 Update edit/hover state in accession2 for desktop/web

- cypress/integration/10-database.js
- package.json
- src/api/types/accessions.ts
- src/api/types/generated-schema.ts
- src/components/People/TableCellRenderer.tsx
- src/components/accession2/viabilityTesting/NewViabilityTestModal.tsx
- src/components/accession2/viabilityTesting/TableCellRenderer.tsx
- src/components/accession2/viabilityTesting/ViabilityTestingDatabase.tsx
- src/components/accession2/viabilityTesting/ViabilityTestingPanel.tsx
- src/strings/index.tsx
- yarn.lock
- this version shows data as required/specified in designs
- ability to create a new test from database, triggers the new test modal in the parent component
- added new hook to view existing tests
- version 2 will be iterations on top of this if any are needed
> SW-1666 Viability testing database - version 1

- src/components/seeds/database/index.tsx
- src/types/Accession.ts
- Permit 'Processing' as a V2 accession state
> SW-1722 Remove 'Cleaning' from V2 accession states in FE

- src/api/appVersion/index.ts
- src/components/accession2/view/Accession2View.tsx
- to help fix the cached build-version fetch in production
- also added the page message component to accessions2 view
I didn't test using an nginx setup but can do that.
```
Request URL: http://localhost:3000/build-version.txt?timestamp=1663793133662
Request Method: GET
Status Code: 200 OK
```
> SW-1717 Fetch build-version file with dynamic query param to bust the cache

- src/components/accession2/view/Accession2View.tsx
- show edit state only if accession is checked-in
- noticed that some accessions are already checked in but status is still awaiting check-in, these are mostly v1 accessions
- added a box to fill up space when we are not showing the edit icon so the spacing looks even
> SW-1726 show edit state only if accession is checked-in

- src/api/accessions2/viabilityTest.ts
- src/api/types/generated-schema.ts
- src/components/accession2/viabilityTesting/DeleteViabilityTestModal.tsx
- src/components/accession2/viabilityTesting/ViewViabilityTestModal.tsx
- src/components/accession2/view/Accession2View.tsx
- src/strings/index.tsx
- i reused the accessions delete modal code
- the text message for deleting viability test may need to be iterated on later
> SW-1669 Add support to delete a viability test

- src/components/accession2/create/Accession2Create.tsx
- src/components/accession2/history/Accession2History.tsx
- also plugged in fix for SW-1813 history content breaking all of word
> SW-1807 create button accession v2 should saw 'create' instead of 'add'

- src/components/accession2/create/Accession2Create.tsx
- src/utils/date.tsx
See bug video here https://www.loom.com/share/538d106e11b84e9e9345a03a967ac19e
- update util to use same code that other modals use
> SW-1801 Use same default date for withdraw modal as other modals like create accession

- src/components/Monitoring/sensorKitSetup/SensorLocations.tsx
- src/strings/index.tsx
When assigning sensor locations, change button text from "Finish" to "Done" as a part of sensor kit setup flow.
> SW-1595 Change "Finish" to "Done" on sensor kit setup screen

- src/components/accession2/viabilityTesting/NewViabilityTestModal.tsx
- src/components/accession2/viabilityTesting/TableCellRenderer.tsx
- src/components/accession2/viabilityTesting/ViabilityResultModal.tsx
- src/components/accession2/viabilityTesting/utils.ts
- moved viability percent calculation to a util
- removed cut tests seedsTested validation (since this is implied and not user supplied)
> SW-1818 Allow user to apply viability percent from cut test on the accession.

- src/components/accession2/view/Accession2View.tsx
- src/components/seeds/summary/index.tsx
- SW-1830 - end-drying reminder to be shown only when accession is in status 'Drying'
- SW-1829 - expand clickable area for accession info (status, location, etc.)
- SW-1826 - Get Started banner to be shown in empty state only
-
> Accession 2 misc tiny UI fixes

- src/components/accession2/view/Accession2View.tsx
When hovering on an editable field, shadow was misplaced. Fix to show it in the right position
Mobile:
Desktop:
> SW-1841 Fix hover pencil shadow

- src/components/accession2/viabilityTesting/TableCellRenderer.tsx
- remove link style
- add `#<n>` with bold weight
> SW-1918 Change display of viability test ID in database row

- src/components/accession2/view/Accession2View.tsx
- src/strings/index.tsx
- show relative time left/passed for end-drying reminder
- update padding on mobile view as per spec, current horizontal padding was too big
- update alignment to be `flex-start` on mobile, `center` on desktop - to match the spec
> SW-1904 Fix end-drying reminder date display on accessions view

- src/components/accession2/edit/Accession2EditModal.tsx
If accession was updated outside the Edit Modal, the record used in edit modal was not being updated with last values. So the fix is to update the record used in the edit modal every time the accession changes
> SW-1920 Fix bug on saving accession from edit modal

- package.json
- src/components/accession2/view/DetailPanel.tsx
- src/components/seeds/database/TableCellRenderer.tsx
- src/components/seeds/database/columns.ts
- src/components/seeds/database/index.tsx
- src/strings/index.tsx
- yarn.lock
- based on comments in PR (the headers use up some space for sort icon - which makes the right align a bit iffy)
- snuck in SW-1923 fix (rename Plant and Site => Plant)
> SW-1919 Right align certain columns in accessions table

- src/components/accession2/edit/CalculatorModal.tsx
- src/components/accession2/edit/EditState.tsx
- src/components/accession2/edit/EditStateModal.tsx
- src/components/accession2/edit/QuantityModal.tsx
- src/strings/index.tsx
- show warning only when status changes
- disable button if save is not relevant
- change button text to Save
- also update quantity update ux (involved with used-up state changes)
- add margin left to units dropdowns
> SW-1932 / SW-1929 change accession state UX updates 

- src/components/accession2/view/DetailPanel.tsx
Put the notes icon inside the div so text can go under the icon.
> SW-1931 Show notes icon inside the notes div

- src/components/accession2/edit/EditState.tsx
- don't wrap the text on next line (Ming's request)
> fix padding on edit status warning

- src/components/seeds/database/index.tsx
- sometimes the slower search (of all accessions) finishes last and it's results get used in the table
- use a state that is reset on unmount, which indicates if a search result is to be used or not
> SW-1953 Fix race condition in accessions database search when coming from dashboard quick-links

- src/components/accession2/edit/EditLocationModal.tsx
- src/strings/index.tsx
- default value of empty-string is considered invalid by BE
- use undefined
> SW-1964 Allow updating seed bank for accession without a storage location

- src/components/accession2/viabilityTesting/NewViabilityTestModal.tsx
- src/components/accession2/view/Accession2View.tsx
- disallow editing status of accession that is awaiting check in (the edit icon was hidden but status badge was clickable)
- default viability start and recording dates to today
> SW-1837 / SW-1965 Misc UI fixes

- src/components/Species/index.tsx
The hover style is added when the table receives a "onSelect" function. Don't pass on select function to species table when user is a contributor
> SW-1963 Disable hover on species table when there is no edit allowed

- src/components/accession2/view/DetailPanel.tsx
We don't want to display collection source if it is "other", because it doesn't make sense
> SW-1843 Hide collectionSource if it is "Other"

- src/components/accession2/view/Accession2View.tsx
- hide them if accession is already checked in
> SW-1991 Show bag IDs for accessions awaiting check-in only

- src/components/OptInFeatures/index.tsx
- src/features.ts
- src/utils/useEnvironment.ts
- added a set/get property pair in opt-in-feature config
- set/get can be defined in specific context
- introduced a new feature 'show production view'
- useEnvironment provides set/get semantics for 'show production view'
- uses session storage for property persistence
- not using BE preferences here since we have no way of clearing it if production view is enabled, we don't show opt-in features in production view
- clearing "productionView" from session storage will restore default view
- this is only for testing and not production end-user facing
> SW-1997 enable a way to test production view in staging

- src/components/TooltipLearnMoreModal/index.tsx
This PR includes a quick fix for learn more modal text content not being visible when viewing a viability test.
> SW-1766: Viability Test Tooltips Follow Up

- src/components/seeds/database/index.tsx
- was previously wrapping by the single word
- make the wrapping units a pair of count/type
> SW-2008 Allow summary sub-section to wrap with count and type info

- src/api/types/generated-schema.ts
- src/components/Inventory/InventoryView.tsx
- src/components/Inventory/index.tsx
- src/components/Inventory/view/InventorySeedlingsTable.tsx
- src/components/Inventory/view/InventorySummary.tsx
- remove v1 accessions generated types
- move inventory summary fetch into summary component
- block the flashing empty state in inventory table
Cleanup would be ideal before starting on the seedlings table
> misc refactor/cleanup

- src/components/Inventory/InventoryFiltersPopover.tsx
- src/components/Inventory/InventoryTable.tsx
- src/components/Inventory/index.tsx
- centered spinner
- adjusted position of page snackbar
- updated filters to be multiple-select
- filters will next be used in the seedlings table (follow up)
-
> SW-1863 add multiple-select nursery filters for inventory

- src/components/Species/TableCellRenderer.tsx
- src/components/Species/index.tsx
Table component orders rows according to the different values of each property of the row. Species rows were not including any value for Conservation Status, the Renderer was in charge of showing that value. So the fix is to include the conservations status value in the rows (and remove it from the Renderer), so that the table has values to order by this field.
> SW-2023 Fix conservation status sorting in species list

- src/components/accession2/edit/QuantityModal.tsx
When changing the count value in the quantity modal (by using the calculator) when grams value is already set, save button is disabled. Enable it when count value change
> Don't disable save button if estimated count change

- src/components/Inventory/InventoryView.tsx
- src/components/Inventory/view/InventorySeedlingsTable.tsx
- src/components/Inventory/view/InventorySummary.tsx
- seedlings view does not lift state of summary and table into parent component
- need a way to reload data from parent view across child components
- mocked message passing using a modified timestamp
> Add a way to reload data in seedlings view

- src/api/batch/batch.ts
- src/components/Inventory/view/DeleteBatchesModal.tsx
- src/components/Inventory/view/InventorySeedlingsTable.tsx
- src/strings/index.tsx
- added a confirmation modal (which wasn't in the design - but this is an assumption)
- copied confirmation modal from species modal deletion
- we can iterate on the confirmation as needed
- deletion supports batch delete (client side, not BE side)
> SW-1876 support deletion of seedlings batches

- src/components/People/index.tsx
This error was because the removed row was still "selected" after removing, and modal was still open.
Fix is to clean selectedRows after deleting and close the modal.
> SW-1928 Fix attempting to remove the last person in an org generates error on first attempt

- .github/scripts/vercel-ignore.sh
This script will be called from Vercel config so that we don't do a bunch of extra deployments for the new gh-pages branch.
> SW-1978 Skip vercel deploy for gh-pages commits

- src/components/accession2/view/Accession2View.tsx
- src/components/common/PageHeaderWrapper.tsx
- src/components/common/TfMain.tsx
- src/index.css
- Create wrapper component
- Define class for fixed header
- On scrolling below header fix header to top
- Add padding to immediate sibling below header
- On scroll-down hide the header
- On scroll-up show the header
- Currently only implemented for Accession view
Desktop:
Mobile:
> SW-2065 Interactive Header

- src/components/Inventory/index.tsx
- removed container from Grid which was introducing a negative margin left
- don't see any impact of this on desktop view or non-empty states
> SW-2080 fix mobile view of empty state inventory

- package.json
- src/components/Inventory/view/BatchesCellRenderer.tsx
- src/components/Inventory/view/ChangeQuantityModal.tsx
- src/components/Inventory/view/InventorySeedlingsTable.tsx
- src/components/Inventory/view/QuantitiesMenu.tsx
- yarn.lock
New version of web-components, when rows are not clickable, only clicking on the checkbox is allowed. This is why we are removing all the stopPropagations that are not necessary anymore
> SW-2093 Use new table version and remove unnecessaries stopPropagations

- cypress/integration/10-database.js
I don't think we need to add a value for each filter, because search api is including all the fields, so if api doesn't fail (still returns results) then it means that each field added to the search exists. I tested adding a column with a search value that doesn't exist and search fails after selecting it.
Also, we are redoing filters at some point, so if we test adding a value to each filter then we will have to redo all tests
> Create test to select all columns on database

- src/utils/withdrawalPurposes.tsx
- mapping usage was removed as part of v1 accessions code deletion
- the mapping function was left around, removing that now
> SW-1416 Remove mapping from old withdrawal purpose to new

- src/App.tsx
- src/components/TopBar/TopBar.tsx
- Unfortunately the hex colors are not yet specified as tokens.
e.g.:
> SW-2168 Update the Background Gradient

- src/components/Monitoring/index.tsx
Using a `Container` for the monitoring contents was the wrong choice.
Instead add a class to make it display full width.
with `Container`:
> Fix Monitoring Display

- src/components/common/FormBottomBar.tsx
This PR resolves an issue where changes from a previous PR threw the alignment off for the bottom action bar on mobile in many of the New Entity pages: 
- New Accession
- New Inventory
- New Person
- New Seed Bank
- New Nursery
> SW-2171: User Reported: Save bar not lined up on mobile app

- src/App.tsx
This PR removes some styles overrides, restoring underlying updated styles for active & selected nav items.
> SW-2066: Update Navigation Styles (hover, active)

- src/App.tsx
This PR adjusts content padding.
> SW-2203: Web-App page content lacks left and top padding

- src/ErrorContent.tsx
- src/index.tsx
- fix the main element positioning
- wrap error page in ThemeProvider to get text color
> SW-2209 Render Error Page

- src/components/accession2/edit/CalculatorModal.tsx
- show error only when user clicks 'get total count'
- we don't clear the entered subset weight on close if there is an error, wondering what the behavior should be here
> SW-2215 Clear subset weight error in calculate on close

- src/components/accession2/edit/CalculatorModal.tsx
When values have decimals the comparison using ( > ) was incorrect because values were not numbers. Adding (+) in front of values to ensure comparison is correct
> SW-2215 Convert string values to number before comparing

- src/components/Inventory/view/InventorySeedlingsTable.tsx
- src/components/accession2/withdraw/WithdrawModal.tsx
- use estimatedCount instead of remaining quantity, similar to viability testing purpose
- also fixed notes display on batch details
> SW-2255 Fix accessions to nursery transfer withdrawal when selecting-all

- src/components/accession2/edit/CalculatorModal.tsx
If selected units on calculator are different, execute count calculation on backend, and use grams values to see if subset weight is bigger than total weight
> SW-2215 Fix different unit error when calculating count

- public/index.html
- src/components/Map/Map.tsx
- src/components/Map/MapModels.ts
- src/components/Map/MapUtils.ts
- src/components/Map/PlantingSiteMap.tsx
- src/components/Map/index.tsx
- add map component for planting site which provides data to the Map component
- introduced some models and utilities
- Map works around these models with no dependency on actual planting site semantics
- this is still an intermediate step, hoping to get this in and we continue to make improvements
- the calculation from polygon coords (EPSG 3857) to lat/long (EPSG 4326) is done in client for now, this will be handled by BE soon and we can remove that code next
- we can make changes to this code over time, just an initial version of the map for planting site
- on click etc we can continue updating
- Example usage 
```
<PlantingSiteMap siteId={siteId} />
```
image here is based on testing using contactus page and admin ui to upload shapes to a planting site
> SW-2219 More map enhancements

- src/components/seeds/database/EditColumns.tsx
- src/components/seeds/database/columns.ts
The field `collectionNotes` was renamed to `collectionSiteNotes` for consistency.
The code uses the new name in its request payloads, but was still using the old
name for searches. Both names are supported; switch to the new one so we can remove
the old one on the server side.
> SW-1405 Use collectionSiteNotes search field

- src/components/SmallDeviceUserMenu.tsx
- src/components/TopBar/TopBarContent.tsx
This PR updates a couple of elements of the `TopBar` on mobile devices:
- use icon-only Terraformation logo
- update user menu icon: smiley face --> first letter of name
> SW-2066: Update Navigation & TopBar

- package.json
- src/components/seeds/summary/SummaryPaper.tsx
- src/components/seeds/summary/index.tsx
- yarn.lock
- Seeds dashboard icons should be medium
- Icon colors should be `TwClrIcnSecondary`
> SW-2218 Update Icon Sizes and Color

- src/components/accession2/view/Accession2View.tsx
- use react state for snackbar - since it was used as a dependency in useEffect, which was being triggered more often than desired
- reduced fetches from 10 to 2
> SW-2267 reduce # of fetches to BE for accession, in accession view

- package.json
- src/components/NavBar.tsx
- yarn.lock
This PR updates the navigation to use a nested hierarchy, viewable [here in the designs](https://www.figma.com/file/DftqOeGx8irCdRf7IZ4lbc/Navigation?node-id=5005%3A199381&viewport=-688%2C-4385%2C0.64).
> SW-2251: Update NavBar for nested hierarchy navigation

- src/components/Map/Map.tsx
- src/components/Map/PlantingSiteMap.tsx
- src/components/PlantingSites/BoundariesAndPlots.tsx
- src/components/PlantingSites/PlantingSiteCreate.tsx
- src/components/PlantingSites/PlantingSiteView.tsx
- the way we were setting the map's key (needed for recreating the map) was generating the map twice
- the mapboxAccessToken is not reactive, meaning, changes to the token will not recreate the map, hence the map key property (assigned to mapId)
- moved mapId assignment to the parent since we have more control there
- fixed layout of map in planting site view and create - now the map uses up remaining height and changes as you resize the browser
> SW-2268 Fix double-load of map, fix map height

- src/components/Map/Map.tsx
- src/components/Map/MapModels.ts
- src/components/Map/MapRenderUtils.tsx
- src/components/Map/PlantingSiteMap.tsx
- needed so we can have different rendering passed into the Map
- needed for withdrawal log at some point
- for now enabled a default popup renderer (which we will remove once withdrawal log rendering works using default as example)
- NO changes to map, just refactored popup rendering to a prop
> SW-2274 Define a popup renderer prop for Map

- src/components/Map/Map.tsx
- src/components/Map/MapModels.ts
- src/components/Map/PlantingSiteMap.tsx
- colors are picked from figma using color meter where necessary
- actual tokens are not available today
- have filed jira https://terraformation.atlassian.net/browse/SW-2275 for Chudo
Added labels (label to be used is still being decide on, we can iterate on that):
> SW-2259 / SW-2260 Render fills, outlines and labels for map polygons

- src/components/common/PageHeaderWrapper.tsx
The change in the padding in the main window to 96px caused the
header to no longer line up when transitioning between sticky and
fixed. Add some padding to cause it to line up again.
> Add Padding to Match Main Padding

- src/App.tsx
- src/components/Inventory/InventoryTable.tsx
- enabled if tracking opt-in is enabled
- moved /inventory/withdraw up in App.tsx so it doesn't get routed to /inventory/:item
> SW-2146 Enable multiple selection for withdraw on inventory page

- src/components/emptyStatePages/NoOrgLandingPage.tsx
This PR updates the no organization landing page to align with the new [visual updates](https://www.figma.com/file/aLIG1C6uIMyBWiTopSluxe/Visual-Refresh?node-id=853%3A108782&t=TqgSlECxJ34AklsU-0).
Desktop:
Tablet:
Mobile:
> SW-2123: Responsive Page Layouts -> Onboarding

- src/components/Map/Map.tsx
- src/components/Map/MapModels.ts
- src/components/Map/PlantingSiteMap.tsx
- Code was overzealous creating Mapbox Layers
- One layer per plot was being created.. this was not necessary
- One layer encompassing all plots should be the correct approach
- One layer per rendering style is the purpose of a Layer
- With large number of layers, mapbox was slow in rendering and creating tileset data on the fly
> SW-2351 Fix rendering performance issues on planting site maps

- src/App.tsx
- src/components/Monitoring/index.tsx
- src/components/common/EmptyMessage.tsx
- src/components/common/ImportModal.tsx
- src/components/common/Title.tsx
- src/components/emptyStatePages/EmptyStateContent.tsx
- src/components/emptyStatePages/EmptyStatePage.tsx
- src/strings/index.tsx
This PR includes a handful of changes to support the visual updates.
Changes include:
- Update link color for import CSV and similar actios in empty state page content
- Update link color in import modal
- Remove title & description from single empty state item in Nurseries empty state
- Update title component to render as `h1` & inherit color from body rather than being incorrectly set to black
- Adjust spacing (margin & padding) of Monitoring page empty state
- Show background image through `NavBar` for empty state pages
> Misc Empty State Pages Updates

- src/components/Plants/index.tsx
- don't render until we have a selection
> Fix temporary rendering of a generic map in plants dashboard

- package.json
- src/components/ToastSnackbar.tsx
- yarn.lock
- toast position 32px from bottom on mobile
- otherwise 32px from top
- consume style updates from web-components
> SW-2153 Message Updates

- nginx/default.conf.template
Currently, Nginx is configured to pass requests whose URL paths start with
`/admin/` through to terraware-server. But people sometimes forget the trailing
slash, and `/admin` doesn't match the passthrough rule so they get redirected to
the web app's home page.
Update the rule so that it matches URL paths that start with `/admin` if there
are no more characters in the path or if the next character is `/` or `?`. That
way if we add, say, `/administration` as a path, it won't match the rule.
> Allow access to admin UI without trailing slash

- src/components/emptyStatePages/EmptyStatePage.tsx
- src/components/seeds/PageHeader.tsx
- src/components/seeds/database/index.tsx
- src/components/seeds/summary/index.tsx
- extra spacing was added to PageHeader for some empty states
- remove it from PageHeader
- add spacing to appropriate empty state components
- fix PageHeader child spacing
example extra spacing:
before:
after:
> SW-2447 Fix Extra Header Spacing

- src/components/Monitoring/sensorKitSetup/FlowStep.tsx
- src/components/common/Expandable.tsx
Use padding on outer card alone.
Align buttons
> Fix visual updates for sensor kit monitoring

- src/components/Map/MapRenderUtils.tsx
- use a table for a better fit of content
> SW-2439 Fix visual format of plants tooltip in map view

- package.json
- src/components/common/PageCard.tsx
- yarn.lock
- moved margin to the wrapper around link
- otherwise the margin was within wrapper which does not allow clicks to escape
- also update npm version for web-components
> SW-2482 Fix ghost area where page card was not clickable

- package.json
- yarn.lock
This PR applies the style `mix-blend-mode: multiply` to the `NavBar` to make it easier for users to see the Contact Us nav item.
> SW-2432: Fix Contact Us Navigation Item is Difficult to See

- src/components/Plants/SpeciesByPlotChart.tsx
Labels and values of species by plot chart were being calculated again every time notifications api refresh. To avoid this, we need to save the labels and values on state and pass them to the chart
> SW-2440 Avoid species by plot chart re-draw

- src/components/common/PageHeaderWrapper.tsx
This PR fixes some styles in the page header:
- Page header box shadow should stop 32px from the right edge of the screen
- Page header box shadow & stroke should match cancel/save action bar
> SW-2481: Page header styling fixes

- src/components/MyAccount/index.tsx
Per spec:
- put the body content in a card to match the rest of the pages
- change the subtitles (general, notifications, organizations) to be 20px, so they aren’t the same size as the header
- remove the horizontal rules (we’re no longer using that component)
- update the header and description text sizes to match the rest of the pages (eg seeds dashboard, accessions)
- the edit button should be a primary button, and it should include the edit icon.
> SW-2510 My Account Page Visual Updates

- src/App.tsx
- src/components/NotificationsDropdown.tsx
- src/components/TopBar/TopBarContent.tsx
- notifications state was being held in the root level App
- probably an artifact of previous notifications design
- every time notifications were fetched (every minute), the app would re-render unnecessarily (due to notifications state change)
- moved notifications state into the notifications dropdown
- removed all the plumbing to App
> SW-2534 Clean up notifications context

- src/components/NurseryWithdrawals/NurseryReassignment.tsx
- src/components/NurseryWithdrawals/ReassignmentRenderer.tsx
- show numplants in same column as quantity edit
- no longer a column on its own
- this is consistent with batch withdrawals design
> SW-2538 Reassignments table column changes

- src/components/Map/Map.tsx
- src/components/Plants/PlantingSiteDashboardMap.tsx
- src/components/Plants/PlantingSiteDetails.tsx
- src/components/Plants/index.tsx
- removed map render while data is loading, so there's no double render of maps
- added flex height since that design want the map to use full height even if charts don't
- added a re-render hook on map to fit map to size (solution online)
> SW-2465 Fix map resize issues

- src/components/NurseryWithdrawals/WithdrawalDetails/sections/Photos.tsx
- set `cursor: pointer` for the `Box` containing the `img`
> Set Cursor for Withdrawal Details Photos

- src/components/Inventory/withdraw/flow/WithdrawalBatchesCellRenderer.tsx
When focusing on input field, the border increases to 2px and takes more space, so the fix was remove overflow: hidden to avoid cutting off the border
> SW-2441 Fix Error focus active input field on withdrawal form batches cut off on left

- src/components/PlotSelector/index.tsx
- switched to Box instead of Grid which did not work well for wrapping
- finer control with Box gives us better wrapping for all breakpoints in all use-cases of the selectors
- screenshots attached
> SW-2437 Fix wrapping of zone and plot selectors

- src/components/Map/Map.tsx
- src/features.ts
- Rachel chose zoom over pan, both were functional
- removed the feature based if/else and default to zoom
- Pan-to will center the zone but won’t change the zoom level. If you are zoomed in or out that won’t change.
- With new change the map will fit the sleeted zone boundary on screen
> SW-2470 Use zoom instead of pan - to zone, in plants dashboard

- src/components/EditOrganization/index.tsx
- src/components/Inventory/InventoryCreate.tsx
- src/components/Inventory/withdraw/flow/AddPhotos.tsx
- src/components/Inventory/withdraw/flow/SelectBatchesWithdrawnQuantity.tsx
- src/components/Inventory/withdraw/flow/SelectPurposeForm.tsx
- src/components/MyAccount/index.tsx
- src/components/NewNursery/index.tsx
- src/components/NewSeedBank/index.tsx
- src/components/NurseryWithdrawals/NurseryReassignment.tsx
- src/components/Person/NewPerson.tsx
- src/components/PlantingSites/PlantingSiteCreate.tsx
- src/components/accession2/create/Accession2Create.tsx
- src/components/common/PageForm.tsx
- created a PageForm components that instantiates children + FormBottomBar with consistent spacing (height of bottom bar + 32px)
- refactored code to use PageForm
- removed margin/padding bottom from various components that were using form bottom bar
- kept a theme spacing(8) in some components that had a dropdown as last element to allow for the dropdown
- ideally would have preferred to remove the fixed position in formbottombar and use some Box magic between the bottom bar and children
- will save that for another review, for now the code is managed in one-place which will make it easier
- tested all those pages in desktop and mobile view
> SW-2467 Use consistent spacing between page and bottom cancel/save bar

- src/components/Map/Map.tsx
- src/components/NurseryWithdrawals/NurseryWithdrawalsDetails.tsx
- match figma design
- also updated a padding on the map (unrelated change)
> SW-2558 Change font size on withdrawals details pages

- .github/workflows/docs.yml
- .github/workflows/workflow.yml
With this PR, I don't see any of the deprecation warnings anymore.
Compare [new build](https://github.com/terraware/terraware-web/actions/runs/3736048733) vs [old build](https://github.com/terraware/terraware-web/actions/runs/3735661301).
1. Use newer versions of github actions that support newer Nodejs versions
2. Replace set-output with GITHUB_OUTPUT workflow (see references)
3. Remove usage of satackey/action-docker-layer-caching, use github action buildx support `cache-from` and `cache-to` tags for docker layers caching. Tested by resubmitting a build and saw cached docker layers being used.
References:
1. https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
5. https://depot.dev/blog/docker-layer-caching-in-github-actions
> Fix github workflow deprecations in terraware-web

- src/components/Plants/DashboardChart.tsx
- src/components/Plants/SpeciesByPlotChart.tsx
The bottom part of the Species by plot chart could not be hovered, because it was "out" of the limits of the chart.
The fix was moving the height of the chart to the chart itself and not to the box containing the chart, so that any part of the chart can be hovered.
> SW-2442 Fix popover behavior on chart inconsistent

- src/api/tracking/withdrawals.ts
- src/components/NurseryWithdrawals/NurseryWithdrawals.tsx
Add sortOrder to search nursery withdrawals api to allow sorting by date.
MUI front end default sorter doesn't work for dates.
> SW-2586 Fix date column on withdrawal log not sortable

- src/components/Plants/PlantingSiteDashboardMap.tsx
- src/components/Plants/PlantingSiteDetails.tsx
- src/components/Plants/SpeciesByPlotChart.tsx
- code was only processing zones/plots driven info
- using a separate query now for totals and by species
- also show map on mobile for planting sites with plots even if there are no plants
- also show the plot selector for empty state in species chart
> SW-2583 / SW-2574 Show planting site data for sites that don't have zones/plots

- src/components/Inventory/withdraw/flow/SelectPurposeForm.tsx
Add quantity validation for single withdrawal with outplant purpose. Previously, the validation was happening on the backend in the last step of the flow (after photo upload)
> SW-2582 Validate withdrawal quantity for single/outplant withdrawal

- .github/version: 2 updates:   - package-ecosystem: "npm"     directory: "/"     schedule:       interval: "weekly"       day: "sunday"     ignore:       - dependency-name: "example-name"         # For Lodash, ignore all updates     open-pull-requests-limit: 15
Enable dependabot opening PRs for version upgrades. Let's see how this works. Charlie did something similar, wondering if this will interfere.
> terraware-web: Enable version upgrades to dependencies

- .github/dependabot.yml
- .github/version: 2 updates:   - package-ecosystem: "npm"     directory: "/"     schedule:       interval: "weekly"       day: "sunday"     ignore:       - dependency-name: "example-name"         # For Lodash, ignore all updates     open-pull-requests-limit: 15
- The previous diff commit some strange file name, reverting that change and recreating the file
Revert "terraware-web: Enable version upgrades to dependencies (https://github.com/terraware/terraware-web/pull/972)"
This reverts commit https://github.com/terraware/terraware-web/commit/72fd2194f0a878a24975f78d3c170962a53bf6d6.
> Fix file name for dependabot

- src/index.css
- we don't need this style, probably an artifact from initial project setup
- all our pages are styled by themes and override this index.css background
> SW-2056 Remove hardcoded colors from index.css

- src/components/Map/PlantingSiteMap.tsx
- zoom into zone on new zone selection only
- bug was from useEffect triggerring even when there were no changes to selected zone
- behavior was due to parent prop being reconstructed from scratch even if a plot was changed
- fixed that by using separate memoization for plot and zone objects
> SW-2614 Avoid zooming into zone on plot selection

- package.json
- src/api/search/index.ts
- src/components/PlantingSites/BoundariesAndPlots.tsx
- src/components/PlantingSites/PlantingSiteCreate.tsx
- src/components/PlantingSites/PlantingSiteSelectTypeModal.tsx
- src/components/PlantingSites/PlantingSiteTypeSelect.tsx
- src/components/PlantingSites/PlantingSiteView.tsx
- src/components/PlantingSites/PlantingSiteWithMapHelpModal.tsx
- src/components/PlantingSites/PlantingSitesList.tsx
- src/components/emptyStatePages/EmptyStateContent.tsx
- src/components/emptyStatePages/EmptyStatePage.tsx
- src/strings/index.tsx
- yarn.lock
- add modal to choose between having map data or not when creating
a new planting site.
- when 'with map' is selected, show a modal with a link to a contact 
form page saying that they will need help from Terraformation
- when 'without map' is selected, proceed to the planting site creation
flow
- don't show the Boundaries and Plot section for planting sites without
map data during creating, viewing, or editing
> SW-2628 Planting Site Creation Map vs No-Map

- src/App.tsx
- src/components/MyAccount/index.tsx
- src/components/NavBar.tsx
- src/components/SmallDeviceUserMenu.tsx
- src/components/TopBar/TopBarContent.tsx
- src/components/UserMenu.tsx
- src/components/accession2/view/Accession2View.tsx
- src/providers/DataTypes.ts
- src/providers/UserProvider.tsx
- src/providers/contexts.ts
- src/providers/hooks.ts
- src/providers/index.ts
- this PR primarily introduces how to use a provider
- introduced a directory and export structure, this is totally changeable and not set in stone
- application of user provider is a bit forced at this point since we don't have that many uses
- we can re-evaluate this later, good start for now
- tested all occurrences of user/reloadUser
- cleaned up props
> SW-2667 Add a user-provider in the web-app react tree

- src/strings/index.tsx
- the banner is no longer shown on maps (we won't show the map if there's no shapefile)
- the banner property is still useful if we want to show something there later? keeping it for now.. unless anyone feels otherwise
> remove unused strings

- package.json
- src/components/LocationTimeZoneSelector.tsx
- src/components/NewSeedBank/index.tsx
- src/components/Nurseries/TableCellRenderer.tsx
- src/components/Nursery/index.tsx
- src/components/PlantingSites/PlantingSiteCreate.tsx
- src/components/PlantingSites/PlantingSiteView.tsx
- src/components/PlantingSites/PlantingSitesCellRenderer.tsx
- src/components/PlantingSites/PlantingSitesList.tsx
- src/components/PlantingSites/PlantingSitesTable.tsx
- src/components/SeedBank/index.tsx
- src/components/SeedBanks/TableCellRenderer.tsx
- src/components/SeedBanks/index.tsx
- src/utils/useTimeZoneUtils.ts
- yarn.lock
- copied boilerplate stuff from Constanza's PR for nursery
- add time zone display to seed bank and planting site tables
- add time zone selection in create/edit flows for seed bank and planting site
- updated nursery view to use a Textfield replacing the disabled selector
- updated all views to use the useLocationTimeZone hook which handles location vs default time zones, for reusability across views
- screenshots are for planting sites but same applies to nursery and seed bank (test in vercel)
> SW-2647 / SW-2649 Add time zone display/selection to seed bank and planting site workflows

- src/api/tracking/withdrawals.ts
- src/components/NurseryWithdrawals/NurseryWithdrawals.tsx
At page load, we query the backend to find out if there are any nursery
withdrawals; if not, we don't show the "Withdrawal Log" item in the left nav.
Previously, this was searching for all the withdrawal details, but really we
only need to know if a withdrawal exists. Change it to just search for the ID.
> SW-2714 Simplify "has withdrawals?" search request

- src/api/seeds/search.ts
- src/components/Inventory/InventoryTable.tsx
- src/components/Inventory/view/InventorySeedlingsTable.tsx
- src/components/Nurseries/index.tsx
- src/components/NurseryWithdrawals/NurseryReassignment.tsx
- src/components/NurseryWithdrawals/NurseryWithdrawals.tsx
- src/components/NurseryWithdrawals/WithdrawalDetails/sections/NonOutplantWithdrawalTable.tsx
- src/components/NurseryWithdrawals/WithdrawalDetails/sections/OutplantReassignmentTable.tsx
- src/components/NurseryWithdrawals/WithdrawalDetails/sections/OutplantWithdrawalTable.tsx
- src/components/People/index.tsx
- src/components/PlantingSites/PlantingSitesTable.tsx
- src/components/SeedBanks/index.tsx
- src/components/emptyStatePages/EmptyStatePage.tsx
- src/components/seeds/database/EditColumns.tsx
- src/components/seeds/database/columns.ts
- src/components/seeds/database/index.tsx
Update the table views so they look up the display names of the columns at the
time the render function is called rather than at the time the module is imported.
For most of the tables, this is a simple matter of moving the column list from the
top level of the module into the body of the render function.
The list of columns on the accessions table, though, is referenced in multiple
places and is also pretty large. Change it from a constant to a function and call
the function in the places that used to reference the constant.
No user-visible behavior change here; the English strings table is still imported
statically as before.
> SW-2721 Look up column labels at render time

- src/api/tracking/withdrawals.ts
- src/components/Inventory/InventoryCellRenderer.tsx
- src/strings/strings-en.ts
On the nursery withdrawal log, we show a client-rendered placeholder instead of
a species name if the species was deleted. Look it up at render time so it uses
the correct translation, and move the angle brackets to the translatable string
so they can be replaced with other symbols as needed in other languages.
> SW-2721 Look up deleted-species placeholder at render time

- src/components/Inventory/InventoryCreate.tsx
- src/components/Inventory/view/BatchDetailsModal.tsx
- src/utils/organization.tsx
- Added timezone to create inventory and add batch.
- Noticed that updating the "addedDate" when editing a batch doesn't update it in the backend, the api doesn't accept an addedDate. Is it correct that "addedDate" is editable in the frontend?
> SW-2658 Default date/time in nursery time zone for inventory add batch

- src/components/Species/AddSpeciesModal.tsx
- src/components/Species/SpeciesFiltersPopover.tsx
- src/strings/strings-en.ts
- src/types/Species.ts
Use the strings table instead of the English enum values for dropdowns on the
species page:
- Growth forms, storage behaviors, and conservation statuses in the filter popover.
- Growth forms and storage behaviors in the Add Species modal.
> SW-2721 Look up species dropdown values at render time

- src/App.tsx
- src/components/AddNewOrganizationModal.tsx
- src/components/People/index.tsx
- src/providers/DataTypes.ts
- src/providers/OrganizationProvider.tsx
- src/providers/contexts.ts
- previously the organizations list was undefined as initial state
- url based org navigation waited until orgs was populated
- with provider refactor, the orgs list is an empty list as initial state
- the org based navigation check did not account or this new initial state
- fixed that
- also removed some unnecessary checks
- also updated org create to switch user to new org
- i believe this may be new behavior and never worked before
> SW-2741 Fix web-app url based org navigation

- src/components/Inventory/withdraw/flow/SelectPurposeForm.tsx
When no seeds are ready, instead of selecting OUTPLANT purpose and show an error, disable that option and default selection to NURSERY_TRANSFER.
Error message is now shown in an info tooltip
> SW-2613 Disable outplant option on withdraw when no seeds are ready

- src/components/MyAccount/index.tsx
Tooltip was not showing on time selector because tooltip shows next to the label. Remove Title and add label to allow showing tooltip
> SW-2762 Add label to allow showing tooltip

- src/api/organization/organization.ts
- src/components/AddNewOrganizationModal.tsx
- src/components/TimeZoneSelector.tsx
- src/strings/strings-en.ts
- required input
- use time zone when creating org
- known error: user is informed that time zone was set in info message after org switch (to be addressed separately)
> SW-2735 show time zone selector in org create form

- src/components/AddNewOrganizationModal.tsx
- src/components/EditOrganization/index.tsx
- src/components/LocationTimeZoneSelector.tsx
- src/components/MyAccount/index.tsx
- src/components/Nursery/index.tsx
- src/components/Organization/index.tsx
- src/components/PlantingSites/PlantingSiteView.tsx
- src/components/SeedBank/index.tsx
- src/strings/strings-en.ts
- renamed the string constants to keep with the `TOOLTIP_XYZ_ABC` pattern used elsewhere
- switched to using default placeholder content for all time zone tool tips
- updated use-cases in the JIRA instead https://terraformation.atlassian.net/browse/SW-2761
- will get Ming to supply the copy
- happy to revert any changes here if anyone has suggestions
- I will assign the JIRA to Ming after this gets in, otherwise it will be super confusing for Ming to see the tooltips in the various scenarios
> SW-2761 default all time zone tooltips to lorem ipusum, in preparation for design copy

- craco.config.js
- package.json
- yarn.lock
To make it easier to test web-components changes in the web app, start using a
react-scripts wrapper that allows overriding the Webpack configuration, and
configure Webpack to stop assuming that the web-components package never changes
and that it's thus safe to minify it once and then ignore it thereafter.
Instead, `yarn start:dev` will now watch web-components for changes and recompile
the app as needed.
> Use Craco to override Webpack caching config

- .gitignore
- .prettierignore
To make it easier to use Yalc to test web-components changes locally, add
Yalc's cache directory and its lockfile to the Git and Prettier ignore lists.
> Ignore Yalc files

- src/api/index.ts
eslint was warning that we should assign a value to a const before
exporting it as a module default, so do what it suggests.
> Fix eslint warning

- src/App.tsx
- src/AppBootstrap.tsx
- src/providers/DataTypes.ts
- src/providers/LocalizationProvider.tsx
- src/providers/contexts.ts
- src/providers/hooks.ts
- src/strings/index.tsx
Use dynamic import instead of a static import to load the strings table for the
user's locale.
Currently, only the default locale of English is supported, but this change is
a prerequisite for loading other locales.
> SW-2721 Load strings dynamically

- src/components/LocaleSelector.tsx
- src/components/NavBar.tsx
- src/features.ts
- src/providers/LocalizationProvider.tsx
- src/strings/index.tsx
- src/strings/locales.ts
- src/strings/strings-gx.ts
Add an opt-in feature to show a locale selector in the left nav footer.
A selector is no good without things to select, so add a programmatically
generated "gibberish" locale that transforms the English strings.
> SW-2737 Add locale selector and gibberish locale

- src/components/MyAccount/index.tsx
- src/components/Species/index.tsx
In a few places, a change of locale wouldn't trigger an update of localizable
content because React couldn't tell the content needed to change.
> Update My Account and species list on locale change

- src/components/People/TableCellRenderer.tsx
- src/components/People/index.tsx
In people table in people page:
- Make email clikable instead of Name and Last Name to allow editing users with no name/lastname
- Sort rows on table by email
> SW-2736 Fix can't edit newly-invited user

- src/api/types/generated-schema.ts
The TypeScript OpenAPI code generator now renders comments in a different
format. Generate a new set of type definitions.
No actual API schema change here, just comments.
> Update generated types

- src/api/timezones/timezones.ts
- src/providers/LocalizationProvider.tsx
The server looks at the `Accept-Language` header to figure out which locale to use
in its API responses. Update the client to set that header on outgoing requests.
> Set Accept-Language header to current locale

- src/api/types/generated-schema.ts
- src/api/user/user.ts
- src/components/MyAccount/index.tsx
- src/providers/LocalizationProvider.tsx
- src/types/User.ts
At initialization time, use the locale from the user's profile, if any.
When the user changes locales, save the new selection to their profile.
When the user edits their profile, save the currently-selected locale along with
the other profile data.
> SW-2776 Load and save user locale selection

- src/components/LocaleSelector.tsx
- src/providers/LocalizationProvider.tsx
Commit fe1261459 introduced a bug: if the user's profile had a non-English locale,
the UI would flap back and forth between English and the selected locale.
This was because LocalizationProvider was treating any update of the locale as a
trigger to save the new value to the user's profile. So when the user's profile
was loaded and the locale was set based on that, it triggered a write to the
user's profile, which then triggered another locale update, and so on.
Fix it by only updating the user's profile when they actually change the locale
selector.
> Fix flapping when non-English locale is selected

- src/components/NotificationsDropdown.tsx
The Notifications dropdown's title was using a hardwired English string.
> SW-2820 Look up title of Notifications dropdown

- src/App.tsx
- src/api/facility/facility.ts
- src/api/search/index.ts
- src/components/NewNursery/index.tsx
- src/components/NewSeedBank/index.tsx
- src/components/Nurseries/index.tsx
- src/components/Nursery/index.tsx
- src/components/SeedBank/index.tsx
- src/components/SeedBanks/index.tsx
- src/services/FacilityService.ts
- src/services/SearchService.ts
- src/services/index.ts
- moved existing code into a search service
- re-exporting search types and functions in original file to avoid breaking other use-cases that rely on a direct search.. until refactored
- introduced a facility service which leverages search service, updated seedbanks and nurseries views to use this service and rely less on how search works
- refactored seed banks view to always search (avoid using cached seed banks) similar to nurseries
> SW-2814 Facilty service to search/get/create/update facilities - reused in Nursery and Seedbank views

- src/components/accession2/properties/Accession2Address.tsx
- src/components/accession2/view/DetailPanel.tsx
Show dropdown for state only when country has subdivisions, and show textfield for other countries.
Show value on detail page.
> SW-2822 Save user inputted values for all countries outside the us

- src/components/ConvertedValue.tsx
- src/components/accession2/edit/QuantityModal.tsx
- src/components/accession2/view/Accession2View.tsx
According to Ming's feedback:
- Add parenthesis for converted weight
- Remove info icon because user is already informed in the quantity form
- Increase vertical spacing to separate weight and count display
> Improve accession weight quantity styles

- src/components/NotificationsDropdown.tsx
- src/components/common/Timestamp.tsx
Currently, the timestamps on notifications are rendered using MomentJS with a
fixed format string. Replace that with a component that renders a timestamp
using the browser's built-in `Intl.DateTimeFormat` class. Since it's not possible
to add custom locales to `Intl`, the component has some special-case code for
the gibberish locale that can be used to test that dates are in fact localized.
Timestamps are rendered in the user's time zone, if one is set.
The default US English date format is similar to the one we were using before,
but not identical.
- Old: `January 21st 2023 at 12:14:54 am`
- New: `January 21, 2023 at 12:14:54 AM`
> SW-2806 Localize notification timestamps

- package.json
- src/components/PlantingSites/PlantingSiteWithMapHelpModal.tsx
- src/components/common/TextWithLink.tsx
- src/strings/strings-en.ts
To make it easier to translate strings with embedded links, add a new component
that replaces delimiter characters with the HTML link tags. This will allow
translators to use the grammatically correct text for the link based on its
surrounding context.
This initial implementation is pretty limited; it only supports a single link
per string.
We no longer need the `html-react-parser` library, which was only being used
to construct an embedded link.
> SW-2869 Add component for text with embedded link

- src/providers/OrganizationProvider.tsx
- the setSelectedOrg within callback function was being executed twice every time, this is absurd
- figured we don't need this to be in a callback, moved it out and we don't have the duplicate writes
> SW-2872 avoid redundant preference write when switching orgs

- src/components/Monitoring/dashboard/htmlLegendPlugin.ts
The chart rendering code was checking for English dataset names to determine
whether or not the labels in the legend should be right-aligned.
> SW-2858 Right-align non-English monitoring chart labels

- src/components/accession2/history/Accession2History.tsx
- the useEffect was capturing changes to the id alone
- updated that to capture any accession change, this may be redundant but captures all cases
> SW-2898 accession history should refresh when there are changes to the accession

- public/index.html
- src/providers/LocalizationProvider.tsx
- src/providers/UserProvider.tsx
We want the cookie consent UI to show in Spanish for Spanish-speaking users. It
gets its initial locale from the `lang` attribute of the `<html>` tag, so update
the code to set that attribute before initializing Google Analytics (which is
what triggers loading the cookie consent UI).
> SW-2897 Pass locale to cookie consent UI

- src/components/accession2/properties/Species2Dropdown.tsx
- src/utils/text.tsx
Some species common names have accented characters, but we don't want to force
users to type the correct accent marks in the species typeahead when adding
accessions or seedling batches.
> SW-1828 Ignore diacritics in species typeahead

- public/index.html
The W3C recommendation is to always include a `lang` attribute on `<html>`
tags.  We can't set it to the user's locale in our static `index.html` since
it's not known until after we fetch the user's profile information from the
server, so hardwire it to English on initial page load. The default will be
overwritten by the application code once it loads the user's information.
> Revert index.html change that removed lang attribute

- src/components/accession2/view/Accession2View.tsx
The relative number of days until the drying end date ("in 7 days") on the
accession details page wasn't localized.
> SW-2922 Localize relative drying end date

- src/components/Inventory/InventoryCreate.tsx
- src/components/Inventory/InventoryTable.tsx
- src/components/Inventory/view/BatchDetailsModal.tsx
- src/components/Inventory/view/InventorySeedlingsTable.tsx
- src/components/Inventory/withdraw/BatchWithdrawFlow.tsx
- src/components/Inventory/withdraw/flow/SelectBatchesWithdrawnQuantity.tsx
- src/components/Inventory/withdraw/flow/SelectPurposeForm.tsx
- src/components/Inventory/withdraw/flow/WithdrawalBatchesCellRenderer.tsx
- src/utils/useNumber.ts
- src/utils/useNumberParser.ts
- Add util to parse a number from a locale/formatted number-string. See https://observablehq.com/@mbostock/localized-number-parsing (there may be a better way to do this (npm package)? but i like the simple reverse-engineered approach in the above article)
- Add util to format a number using locale (leverage Intl.. not sure if this is totally correct for fixed precision)
- Inventory create/edit/withdraw flows had inconsistent display formatting, BE provided numbers were formatted correctly, UI generated numbers (running totals, etc.) were not formatted. Leverage above utils to render in correct format.
- UI allowed user to enter formatted numbers in the various quantity input elements - but was also sending this back to the BE as the number data, which generated format errors since BE was …
> SW-2921 fix inventory withdraw math on formatted numbers

- src/components/NurseryWithdrawals/NurseryWithdrawalsDetails.tsx
- src/components/NurseryWithdrawals/WithdrawalLogRenderer.tsx
- src/components/Species/index.tsx
- src/strings/strings-en.ts
- src/utils/boolean.ts
Boolean search fields, like all search fields, return string values. Currently,
these are assumed to be the English words `'true'` and `'false'`.
Update the application code to handle booleans being rendered as localized
strings.
This fixes a bug in the species list UI in English: if you had a search filter,
it could erroneously show species as rare and/or endangered because the string
`'false'` evaluates as true in JavaScript.
> SW-2925 Handle localized booleans in search results

- src/components/Monitoring/dashboard/PVBatteryChart.tsx
- src/components/Monitoring/dashboard/TemperatureHumidityChart.tsx
- src/components/common/Chart/index.tsx
- src/components/common/DatePicker.tsx
- src/components/common/Timestamp.tsx
- src/utils/useNumber.ts
The goal of the gibberish locale is to be visually distinct from English so we
can spot places in the UI that we haven't localized. Initially, that included
using custom formatting rules for numbers and dates, but that has turned out to
be annoying to implement in practice. Update the code to use French formatting
instead; it serves the purpose of being distinct from English but requires less
special-case code.
Also fixes SW-2918.
> SW-2933 Use French date/number formatting for gibberish

- src/api/types/generated-schema.ts
- src/components/accession2/history/Accession2History.tsx
If an accession withdrawal has notes, show them below the system-generated
description of the history event.
> SW-2681 Show withdrawal notes in accession history

- src/components/Inventory/InventoryTable.tsx
- src/components/Inventory/index.tsx
- src/components/Inventory/view/InventorySeedlingsTable.tsx
- src/components/NurseryWithdrawals/NurseryReassignment.tsx
- src/components/NurseryWithdrawals/NurseryWithdrawals.tsx
- src/components/NurseryWithdrawals/WithdrawalLogRenderer.tsx
- also applies to batch details table
- nurseries columns is a client defined column and uses it's own sort mechanism
- common name is not working so using client side for now
- the detail views within withdrawal log are static and will use client side sorting for now
> SW-2941 / SW-2942 Sort inventory/withdrawals table using BE sort order

- src/AppError.tsx
- src/index.tsx
The error page was not showing the labels, this was because locale was not set for the error page.
Adding AppBootstrap to error page to allow setting the locale
> SW-2883 Error page copy is missing

- src/AppBootstrap.tsx
- src/components/LocaleSelector.tsx
- src/components/Monitoring/dashboard/PVBatteryChart.tsx
- src/components/Monitoring/dashboard/TemperatureHumidityChart.tsx
- src/components/MyAccount/index.tsx
- src/components/Organization/index.tsx
- src/components/People/index.tsx
- src/components/Plants/DashboardChart.tsx
- src/components/RegionSelector/index.tsx
- src/components/Species/index.tsx
- src/components/accession2/edit/EditLocationModal.tsx
- src/components/accession2/properties/Accession2Address.tsx
- src/components/accession2/properties/SeedBank2Selector.tsx
- src/components/accession2/viabilityTesting/ObservationsChart.tsx
- src/components/accession2/view/Accession2View.tsx
- src/components/accession2/view/DetailPanel.tsx
- src/components/common/DatePicker.tsx
- src/components/common/Timestamp.tsx
- src/components/seeds/database/index.tsx
- src/providers/DataTypes.ts
- src/providers/LocalizationProvider.tsx
- src/providers/contexts.ts
The names of the locale context properties were not very clear. Rename them to
make their meanings more obvious.
> Rename locale properties

- src/components/NotificationsDropdown.tsx
The bottom padding is given by the notification date, so add padding when no date
> SW-2965 Add bottom padding to feature notifications

- src/components/seeds/database/EditColumns.tsx
- The status column is used for the pre-exposed filter
- Removing it causes the filter values to not be loaded and also errors
- Don't allow it to be removed, as it is a "privileged" column because of the above properties
> SW-2936 Disable Removing Status Column from Accessions

- src/components/accession2/view/DetailPanel.tsx
- Buttons will take all the space of their container now (because of web-components change). 
- Add a container with height to edit button in accession detail to limit its height
> Fix button height on accession detail

- src/App.tsx
- src/components/seeds/database/index.tsx
- src/providers/DataTypes.ts
- src/providers/OrganizationProvider.tsx
- src/providers/contexts.ts
- also fix case where we restoring defaults for an org
- refactored code a bit to set the useEffect order correctly
- we will be saving the columns to preferences for now, for any changes to this we can talk with product
> SW-2961 / SW-2979 Show seed-bank/sub-location columns when going from seed bank details to accessions table

- src/components/SeedBank/StorageLocationsCellRenderer.tsx
the content was not being encoded correctly, fixed that
> SW-2816 encode user provided data before sticking in accessions table url query param

- src/components/seeds/database/Filters.tsx
- currently clears the input search bar but the results show last search term applied
- fixed the default state of search term to be initialized from the filters
> SW-2989 restore accessions search bar value when user navigates back

- src/components/NavBar.tsx
- src/strings/strings-en.ts
- as per jira suggestions (renamed cleaning as processing)
> SW-2929 / SW-2999 Fix locations icon, fix total-active-accessions tootip

- src/components/common/BackToLink.tsx
- content alone should be link-able
- was using a flex property that gave it full width, mostly for the align items property
- inline-flex was giving it a bit more height, not suitable
- fix width to fit content
> SW-3002 Fix back to link effective area

- src/components/accession2/properties/CollectedReceivedDate2.tsx
Now when setting an invalid value on the datepicker of accession / collected date or received date, and then changing focus to other field, the value of the datepicker is reset. 
This was happening because when the record changed one of its fields, the collected date and received date where set to the record value that is null (because the invalid value doesn't change the record value) 
So the fix to avoid "reseting" the value, is not refreshing the temporal values when the record changes.
> Don't update collected/received value when changing other field

- src/components/accession2/view/DetailPanel.tsx
- pretty much all editable fields were sticking
- the open property on the modal is not working to our advantage here
- also using open for conditional rendering which is really the best solution here
- i propose we do similar conditional rendering in other places where we have stickiness instead of so much cleanup code with little ROI
> SW-3025 fix edit accession view stickiness upon cancel

- src/components/NurseryWithdrawals/NurseryWithdrawals.tsx
It seems like we're currently using the "or" logic across different filters but we should be using the "and" logic. In other words, if a user filters by the species Koa and the destination Site A on the withdrawal log page, then the results should show all withdrawals with Koa as the species AND Site A as the destination.
The only time we use the "or" logic should be within a single filter. For example, if a user filters by the status Awaiting Check-In, Drying, and In Storage then we should show all results whose status is any of those options.
* This has been fixed on the Withdrawal Log filters. It was already being done correctly in the Species and Accessions filters
> SW-3010 Use AND Logic Across Different Filters

- .github/workflows/workflow.yml
Only transition to "Released to Production" if the Jira is already marked as "Done"
> SW-2994 Limit Jira transitions on production releases

- src/components/Inventory/InventoryTable.tsx
- src/components/Inventory/index.tsx
- keep one banner for all inventory views
> SW-3057 Show reload-app banner outside the inventory table container

- src/components/accession2/create/Accession2Create.tsx
- src/components/accession2/edit/Accession2EditModal.tsx
- src/components/accession2/properties/CollectedReceivedDate2.tsx
Having a dateErrors object to manage both date errors (collected and received) was causing a lot of unwanted state changes/refreshes when one of the values changed. Some times collected error was overwrited with an empty error, when received error changed. So, to fix this, the component will render only one datepicker for each and manage its own value/error
This also fix the date validation not stopping the save action, when it was the only error in the form.
> SW-2982 Fix error management for collected/received date

- src/components/Species/index.tsx
- src/services/SpeciesService.ts
This bug was introduced with the new species service. Species upload file api uses organizationId instead of faciityId. This was causing the error
> SW-3071 Fix Can't upload species list

- src/api/types/generated-schema.ts
- src/components/seeds/database/Filters.tsx
- Now `Fuzzy` searches are always fuzzy, even if an exact match is found
- A new search type, `ExactOrFuzzy`, will show only an exact match if it
exists, otherwise it will show fuzzy results
- In the Accessions list page apply `ExactOrFuzzy` to the Accession
Number column only.
> SW-3070 Apply ExactOrFuzzy Search to Accession Number Only

- src/services/SystemService.ts
- this was accidentally removed as part of the service refactor 😿
> SW-3102 query param to bust cache when requesting app version data

- src/api/types/generated-schema.ts
- src/components/Reports/ReportEdit.tsx
- src/components/Reports/ReportForm.tsx
- src/components/Reports/ReportView.tsx
- src/components/Reports/SeedbankSection.tsx
- src/services/ReportService.ts
- src/strings/strings-en.ts
- Seedbanks have the "selected" field, which we toggle to show whether a
seedbank is included in the report or not
- Let the seedbank InfoField component use the useStyles hook directly
instead of passing the className through props
- No longer need two copies, report and draftReport, in ReportEdit
- Do not let the polling for lock status change the report data out from
under the ReportEdit component
> Updates to Report Seedbanks

- src/components/accession2/withdraw/WithdrawModal.tsx
When withdrawing for Nursery purpose, we were not setting the correct unit to validate, and it was using 'Grams' instead of 'Seeds'. Fix that, and also added a useEffect to set unit value correctly when changing purpose
> SW-3129 Withdrawing seeds to nursery with weight based accessions

- src/components/Inventory/InventoryCreate.tsx
Timezone was not set correctly, so when manually entering dates, they were off by one
> SW-3151 Fix add inventory manually entered dates

- src/components/seeds/database/Filters.tsx
- src/components/seeds/database/index.tsx
- when going from a dashboard quick filter to accessions table, the status does not stick with the pre-exposed filter
- update code such that it sticks, previously the filters were keyed off different names `state` and `preExpFilter`.. converge them all to use `state`
> SW-3152 Dashboard status filters should stick with pre-exposed-filter setup

- src/components/Reports/ReportEdit.tsx
- src/components/Reports/ReportForm.tsx
- src/components/Reports/ReportFormAnnual.tsx
- quarterly section is validated first and navigated to if there are problems
- then the annual section is validated
- added quarterly project summary to required fields
- turn off validation when switching pages until submit retry
> Report Annual Validation

- .github/workflows/workflow.yml
- cypress.config.ts
- cypress/e2e/10-database.cy.js
Some changes to make the e2e cypress tests more robust and debuggable:
- Capture screenshots and store them in the event of a test failure
- These can be found on the workflow summary page after the run completes
- Increase the `pageLoadTimeout` and `responseTimeout` ([ref](https://docs.cypress.io/guides/references/configuration#Timeouts))
- Passing tests were sometimes running close to these limits, so increasing ought to help with the flakiness
- Add a dummy test to visit `/accessions` at the beginning of the `10-database` tests
- Noticed that the first attempt to `cy.visit('/accessions')` often fails, with subsequent attempts succeeding
- The dummy tests ignores exceptions thrown by the visit, so the idea is to clear any network issues before running the actual tests.
> E2e Cypress Test Improvements

- package.json
- src/components/Reports/PlantingSitesSpeciesCellRenderer.tsx
- yarn.lock
- onRowClick was being called on every change, which caused the input to
lose focus.
- break the input out into a separate component
- the input component keeps track of its own input value state
- onRowClick is only called on "confirming" the input, which we define as
when the input is blurred
- the UX is good in testing, blur happens when anything else in the form is
clicked, including the save and quit button
> SW-3194 Fix Input Behavior on Planting Site Species Table

- src/components/Reports/ReportEdit.tsx
- Switch validation to before showing the submit confirmation
- Show a toast message if there are missing required fields
> SW-3201, SW-3196 Some Updates to Report Validation

- src/components/Inventory/InventoryTable.tsx
- src/components/Inventory/Search.tsx
- src/components/NurseryWithdrawals/NurseryWithdrawals.tsx
- src/components/People/index.tsx
- src/components/Species/index.tsx
- src/components/seeds/database/Filters.tsx
Various tweaks to make spacing consistent across pages.
> SW-3140 Make spacing between table headers and search/filters consistent

- src/components/common/BusySpinner.tsx
The skrim and spinner that are there when, e.g., uploading or deleting photos were stuck at the top of the page, even when scrolled. To fix this, and make them always visible and blocking interactions, change to `'fixed'` positioning.
> SW-3177 Fix Positioning of Skrim and Spinner

- src/components/Reports/ReportEdit.tsx
- src/components/Reports/TableCellRenderer.tsx
- unlock was being called unnecessarily after submitting
- this kicked the report into InProgress status
- the BE should not have allowed this, and I will put up a fix for that
- also prettified the submit date display in the table
> SW-3360 Fix Submission Status

- src/components/Reports/ReportEdit.tsx
- src/components/Reports/ReportForm.tsx
- src/components/Reports/ReportView.tsx
- src/components/common/PageForm.tsx
- Container width should be fit-content to ensure table displays
within the container properly
- Add more bottom padding to accomidate buttons
- Rearrange 'Show Quarterly/Annual' and 'Edit Report' buttons
> SW-3368, SW-3369 Report Mobile Style Fixes

- src/components/Reports/ReportEdit.tsx
Forgot to remove the popstate event handler when ReportEdit unmounts.
Remove it so that it does not affect other pages.
> Remove popstate Event Handler

- src/strings/csv/en.csv
- src/strings/export.js
Phrase's GitHub export includes the English strings file as well as the files
for other languages. To avoid cluttering Phrase's PRs with no-op edits to the
English strings file, update the file to match what would be exported by Phrase.
This differs from the previous version of the file in two main ways:
1. The comment column is omitted for strings without comments. That is, if a
string has a comment, its CSV row will have 3 columns. If a string does not
have a comment, its CSV row will have 2 columns.
2. Underscores are treated as spaces when Phrase sorts the strings, so they
come earlier than letters. This differs from the "sort by ASCII" sort order,
which sorts underscores between the upper and lower case letters.
> SW-3272 Use Phrase export format for English strings

- src/strings/export.js
If we have CSV files for multiple locales, we generate a JavaScript source file
with the strings for each locale. Previously, this was just an alternate rendering
locale's CSV file.
Unfortunately, that simple approach means that if you add or remove an English
string, the JS strings objects for the other locales won't have the same keys as
the English one. At best, this will cause a TypeScript error because the type
signatures don't match; at worst, it'll be a runtime error.
Instead, generate each locale's JS file using both the English and localized CSV
files. The list of keys will always be based on the English file. The values will
be the localized strings if available, or the original English strings if not,
such that the app effectively falls back to English for strings that aren't …
> SW-3272 Include all English keys in JS strings

- src/components/Reports/PlantingSitesSpeciesCellRenderer.tsx
The method getGrowthFormString was expecting a Species type
argument, but was mistakenly being send the growthForm. This
caused an error when the growthForm was undefined. Correct this
by sending the row as a Species.
> SW-3400 Growth Form Errors

- src/components/Species/ImportSpeciesModal.tsx
- src/services/SpeciesService.ts
- the response needed to be parsed for csv template
- the payload for import resolutions needed to be an entity instead of search param
> SW-3430 Fix species template download and species import resolutions

- src/components/Reports/LocationSection.tsx
- src/components/Reports/ReportForm.tsx
- src/components/Reports/ReportFormAnnual.tsx
- src/strings/csv/en.csv
- Show fields as "Display" state when Report is in View Mode
- Help text shouldn't be visible for "display" state of fields
- Project Summary word count grammar fix
- Tooltip text contradicts required field (Mortality Rate (%) *)
---
---
---
> SW-3265, SW-3412, SW-3432, SW-3439 Various Visual Fixes

- src/ErrorContent.tsx
- src/components/ContactUs.tsx
- src/components/PlantingSites/PlantingSiteWithMapHelpModal.tsx
- src/components/UserMenu.tsx
- src/components/common/HelpEmail.tsx
- src/constants.ts
- src/docLinks.ts
- src/strings/csv/en.csv
- src/strings/locales.ts
- refactored links to use selectedLocale
- added new card for contact us
- confirmed the doc links are correct for locales, using english docs for gibberish
> SW-2760/SW-3486 Add contact us card on help page, show links by locale

- cypress/e2e/10-database.cy.js
- src/components/seeds/database/EditColumns.tsx
- src/components/seeds/database/columns.ts
- src/components/seeds/database/index.tsx
- in a previous commit, we added support to persist shuffled columns
- same commit introduced the new/updated preferred system order of column names
- in this commit, we try to preserve the shuffled columns and system order when columns are added/removed.. as much as possible using simple math
- approach is documented in the code
- a) when editing columns, preserve the current order (minus removed columns)
- b) determine which columns were shuffled and keep track of shuffled index
- b) sort new columns by order of appearance in the preferred system order, remove shuffled columns from this list
- c) re-insert shuffled columns at shuffled index
- this works well for most common cases without requiring us to persist any more information, after many attempts i like the latest version of the …
> SW-3541 Preserve system order of accession columns where possible

- src/components/Inventory/view/BatchesCellRenderer.tsx
- src/components/Inventory/view/ChangeQuantityModal.tsx
- code was using the localized display value (with commas) for math instead of the raw values..
- switched to raw
- also fixed some UX issues like error validation and spinner
> SW-3440 Fix change status/quantities modal in seedlings batches when the numbers are large

- package.json
- src/components/seeds/database/Filters.tsx
- src/components/seeds/database/columns.ts
- yarn.lock
Set "exact or fuzzy" search for accessions table "Accession Number" and "Collection Site Name" columns.
Exact search now matches exact substrings.
> SW-3070 Update Exact Matching in Accessions Search

- .storybook/preview.tsx
- src/App.tsx
- src/components/Observations/index.tsx
- src/components/Plants/index.tsx
- src/components/PlantsPrimaryPage/PlantsPrimaryPageView.tsx
- src/components/PlantsPrimaryPage/index.tsx
- src/stories/PlantsPrimaryPage.stories.tsx
- src/strings/csv/en.csv
- Plants dashboard and plants observations have the same page structure
- extracted out plants dashboard page into a wrapper page component
- reused that for observations
- added a concept of 'All' as a selection
- added a story for the page view
> SW-3666 Add planting site selector to observations page

- src/App.tsx
- src/components/Monitoring/SeedBankMonitoring.tsx
- src/components/NavBar.tsx
- src/components/Observations/index.tsx
- src/components/emptyStatePages/EmptyStateContent.tsx
- src/components/emptyStatePages/EmptyStatePage.tsx
- src/strings/csv/en.csv
- added empty state
- updated empty state content component to make some props optional
- for now no-observations flag is set to true
- once we have redux to fetch real observations, we will have different content
- i have an open question on figma regarding what to show if there are no planting sites (follow up)
> SW-3664 Empty state message for no observations in planting site(s)

- src/components/BreadCrumbs/index.tsx
- src/stories/BreadCrumbs.stories.tsx
- simple component built over existing `BackTo` and `Link` components
- added an option `hierarchical` if we want to build the hieararchical url paths for each crumb
- defaults to false => each path specific with crumb is absolute
- stories
> SW-3675 bread crumbs navigation wrapper component

- package.json
- yarn.lock
- warning is
```
TypeError: Cannot set property mark of #<Object> which has only a getter
TypeError: Cannot set property mark of #<Object> which has only a getter
at Object.connectTypeScriptPerformance
```
- fix offending package version
- see https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/797
> fix build warnings in terraware-web related to typescript version

- src/components/ListMapView/index.tsx
- src/components/common/ListMapSelector.tsx
- src/stories/ListMapSelector.stories.tsx
- as per Chudo's request
- we have views where the default view is a map, and the selector needs to show map first in those cases
> Set map/view selector icon order based on initial/default view

- src/components/Map/PlantingSiteMap.tsx
- src/components/PlantingSites/BoundariesAndZones.tsx
- src/components/Plants/PlantingSiteDashboardMap.tsx
- src/services/MapService.ts
- src/services/test/MapService.test.ts
- src/types/Map.ts
We change the way that map data flows into the PlantingSiteMap. Instead of
passing in the planting site, we pass in a more generic MapData object, which
contains data for the various map objects (site, zone, subzone, permanentPlot,
temporaryPlot). This will help make the component more reusable where, for
instance, one does not have a planting site object, but observation results
from which the map data object may be created. Behavior for existing maps, such
as the ones in the Planting Site or Plants Dashboard pages, is unchanged.
> Planting Site Map Data

- src/components/Inventory/InventoryTable.tsx
- src/components/Inventory/view/InventorySeedlingsTable.tsx
- src/components/Inventory/withdraw/flow/SelectBatchesWithdrawnQuantity.tsx
- src/components/MyAccount/index.tsx
- src/components/Nurseries/index.tsx
- src/components/NurseryWithdrawals/NurseryReassignment.tsx
- src/components/NurseryWithdrawals/NurseryWithdrawals.tsx
- src/components/NurseryWithdrawals/WithdrawalDetails/WithdrawalOverview.tsx
- src/components/NurseryWithdrawals/WithdrawalDetails/sections/NonOutplantWithdrawalTable.tsx
- src/components/NurseryWithdrawals/WithdrawalDetails/sections/OutplantReassignmentTable.tsx
- src/components/NurseryWithdrawals/WithdrawalDetails/sections/OutplantWithdrawalTable.tsx
- src/components/NurseryWithdrawals/WithdrawalLogRenderer.tsx
- src/components/People/index.tsx
- src/components/PlantingSites/PlantingSitesTable.tsx
- src/components/Reports/LocationSection.tsx
- src/components/Reports/ReportList.tsx
- src/components/SeedBank/StorageLocations.tsx
- src/components/SeedBanks/index.tsx
- src/components/common/table/index.tsx
- src/types/Batch.ts
- table columns were not updating on locale change except for accessions and species tables
- render withdrawal purpose using strings
- withdrawal log filters update with locale
- fix reassign button not showing up in withdrawal table
- see changes in vercel
> SW-3724 Make table columns i18n friendly, plus other i18n fixes

- src/App.tsx
- src/components/OptInFeatures/index.tsx
- src/components/SmallDeviceUserMenu.tsx
- src/components/Species/TableCellRenderer.tsx
- src/components/common/ListMapSelector.tsx
There were several places where hexRgb was being used to apply an opacity to
a color. Replace with the utility function, getRgbaFromHex.
> SW-3736 Replace hexRgb Calls with Utility

- src/components/Inventory/InventoryTable.tsx
- src/components/Inventory/view/InventorySeedlingsTable.tsx
- src/components/Inventory/withdraw/flow/SelectBatchesWithdrawnQuantity.tsx
- src/components/MyAccount/index.tsx
- src/components/Nurseries/index.tsx
- src/components/NurseryWithdrawals/NurseryReassignment.tsx
- src/components/NurseryWithdrawals/NurseryWithdrawals.tsx
- src/components/NurseryWithdrawals/WithdrawalDetails/sections/NonOutplantWithdrawalTable.tsx
- src/components/NurseryWithdrawals/WithdrawalDetails/sections/OutplantReassignmentTable.tsx
- src/components/NurseryWithdrawals/WithdrawalDetails/sections/OutplantWithdrawalTable.tsx
- src/components/Observations/org/OrgObservationsListView.tsx
- src/components/People/index.tsx
- src/components/PlantingSites/PlantingSitesTable.tsx
- src/components/Reports/LocationSection.tsx
- src/components/Reports/ReportList.tsx
- src/components/SeedBank/StorageLocations.tsx
- src/components/SeedBanks/index.tsx
- src/components/accession2/viabilityTesting/ViabilityTestingDatabase.tsx
- src/components/common/table/index.tsx
- wasn't too thrilled about the last fix
- extracted out changed-locale semantics and moved it into the table wrapper
- now each component supplies a function that returns the table names, function has to be outside scope of the component so it doesn't change on every render
- this will scale more easily without bugs, etc.
> Redo table columns for i18n in terraware-web

- src/api/types/generated-schema.ts
- src/components/Observations/common/AggregatedPlantsStats.tsx
- src/components/Observations/common/SpeciesMortalityRateChart.tsx
- src/components/Observations/common/SpeciesTotalPlantsChart.tsx
- src/components/Observations/details/index.tsx
- src/components/Observations/zone/index.tsx
- src/components/Plants/PlantBySpeciesChart.tsx
- src/components/Plants/SpeciesBySubzoneChart.tsx
- src/components/common/Chart/BarChart.tsx
- src/components/common/OverviewItemCard.tsx
- src/redux/features/observations/utils.ts
- src/strings/csv/en.csv
- src/types/Observations.ts
- info cards for observation details' and zone level details' plants stats
- extracted out plants dashboard chart for reusability
- added charts for root level observation details and planting zone observations
- updated generated types to account for species in observation details (requires a [BE PR](https://github.com/terraware/terraware-server/pull/1205) to be merged.. to build)
> observations plants stats info cards + charts

- src/components/Observations/ObservationsDataView.tsx
- src/components/Observations/common/DetailsPage.tsx
- src/components/Observations/details/index.tsx
- src/components/Observations/plot/index.tsx
- src/components/Observations/zone/index.tsx
- when a site didn't have a timezone set, code fallsback to the default time zone
- the default time zone was being passed as an object.. leading to incorred date/time generation by Intl
- pass the time zone id from the object instead
> Fix 'invalid date time' display in observations tables

- src/components/Observations/plot/MonitoringPlotPhotos.tsx
- src/components/Observations/plot/index.tsx
- src/components/common/PhotosList.tsx
- mostly a copy of what we do in nursery withdrawals details plus some customization for monitoring plots
- added photos in staging, switch to dev org and go here /observations/56/3/106/270028
> Display monitoring plot observation photos

- .github/scripts/deploy.sh
- .github/scripts/set-environment.sh
- .github/workflows/workflow.yml
When deploying to the AWS hosts, connect to the VPC network using Tailscale and
ssh directly to the hosts rather than bouncing through a bastion host.
> SW-3394 Deploy using Tailscale instead of bastion

- package.json
- src/components/Observations/common/AggregatedPlantsStats.tsx
- src/components/Observations/details/index.tsx
- src/components/Observations/plot/index.tsx
- src/strings/csv/en.csv
- yarn.lock
- Rachel asked to show tooltip instead of '--'
- also the monitoring plot details will have all the data, removed '--' from there and not showing any tooltips there either
- don't know if we want to show tooltips only when data is missing, for now we show it all the time
> Tooltips for planting density and total plants cards

- src/components/Observations/ObservationsDataView.tsx
- src/components/Observations/details/index.tsx
- src/components/Observations/map/ObservationMapView.tsx
- src/redux/features/observations/observationDetailsSelectors.ts
- src/redux/features/observations/observationsSelectors.ts
- src/redux/features/observations/utils.ts
- src/redux/features/tracking/trackingSelectors.ts
- preserve zone names in drill down if possible
- drill down may lose zone names that don't exist in the context
- updated search in map view
- best to test in vercel
> Add zone-name filters for observations results, detail view and map view

- src/strings/csv/en.csv
The word "outstanding" was previously translated as "destacado," which seems to be the wrong sense of the word.
> Add a Comment to Note the Sense of the Word "Outstanding" to Translators

- src/components/Observations/ObservationsDataView.tsx
- src/components/Observations/details/index.tsx
- src/components/Observations/index.tsx
- src/redux/features/observations/observationsSelectors.ts
- src/redux/features/observations/observationsSlice.ts
- src/redux/features/observations/observationsThunks.ts
- src/redux/rootReducer.ts
- src/services/ObservationsService.ts
- list observations which returns a response payload around the observation (not the results)
- returns end dates, includes observations for all statuses
- added hooks in components where we would do follow up UI work
> SW-3748 redux to list observations (not results)

- src/components/Observations/common/AggregatedPlantsStats.tsx
- src/components/Observations/details/index.tsx
- previously we were showing these tooltips only when data was missing
- Rachel provided feedback that we should show the tooltips for context all the time
- note that total plants tooltip is only relevant for the site level observations
> Show tooltips for total plants and planting density even when there is data

- src/components/FeatureNotification/UserNotification.tsx
- src/components/LocaleSelector.tsx
- src/components/MyAccount/index.tsx
- src/providers/LocalizationProvider.tsx
- src/strings/index.tsx
- src/strings/locales.ts
- added an optional inDevelopment flag for locales
- added a hook to fetch supported locales which filters out inDevelopment locales in production
- tested by flipping the inProduction condition locally
> SW-3795 react hook to export supported locales for the FE environment (prod vs non-prod)

- src/components/Species/index.tsx
- src/types/Species.ts
- the BE returns translated values in search responses
- FE was attempting to translate those values again and it failed
- removed util to get seed storage behavior
- re util to get growth form it is used in reports and in a valid use-case
> SW-3798 translate species growth-form and seed-storage-behavior

- src/components/Species/AddSpeciesModal.tsx
- src/components/Species/index.tsx
- src/services/SpeciesService.ts
- add/edit modal was auto searching for the scientific name and updating the form when it was open
- this search was only intended when user actually types something
- updated code to have search trigger after has typed something
- also the species details code was incorrect and returning undefined, fixed that to return valid data
- also added conditional rendering on the modal so we don't have cross contamination issues across last opened species states
> SW-3799 fix species edit modal clearing data

- src/api/types/generated-schema.ts
- src/components/Observations/common/SpeciesTotalPlantsChart.tsx
- src/components/Species/AddSpeciesModal.tsx
- src/components/Species/index.tsx
- src/components/TooltipLearnMoreModal/index.tsx
- src/services/SpeciesService.ts
- src/strings/csv/en.csv
- src/strings/csv/es.csv
- src/types/Species.ts
Remove the "endangered" flag from the species data and replace it with
the IUCN conservation category.
The change affects a few parts of the species UI:
* The table view now has separate columns for IUCN Conservation Category
and Rare; previously the two values were combined in one column.
* The filter list also breaks these two fields out into separate settings.
* The add/edit species dialog now has a dropdown for conservation category.
The checkbox for "Rare" is still present.
* The "conservation status" grouping is gone since it only existed to tie
Endangered and Rare together.
> SW-3127 Replace Endangered with Conservation Category

- src/api/types/generated-schema.ts
- src/components/Species/AddSpeciesModal.tsx
- src/components/TooltipLearnMoreModal/index.tsx
- src/strings/csv/en.csv
- src/types/Species.ts
The forestry team requested some new growth forms; add them.
Start sorting the list of growth forms in drop-down menus and the
Learn More popup to make it easier for users to find the growth form
they're looking for, since the list is now too long to take in at a
glance all at once.
> SW-3818 Add new growth forms

- src/components/Species/AddSpeciesModal.tsx
- src/components/Species/index.tsx
Add a "Learn More" link to the IUCN Conservation Category tooltip
that opens the landing page for the official IUCN Red List
Categories and Criteria documentation.
> SW-3127 Add link to IUCN categories page

- src/api/types/generated-schema.ts
- src/components/seeds/database/index.tsx
- src/services/SeedBankService.ts
The seedbank API has two endpoints to list all the values of a field. One of
them lists all the values that are currently present on any accessions, and
the other lists all possible values, even if they're not used.
In early versions of the app, there was a list of seed collectors that was
maintained separately from the accession data; you could add names to the list
and they would show up as available collectors when creating a new accession.
The app thus called the "list all possible values" endpoint since it needed to
include collectors that hadn't yet been associated with any accessions.
But we moved away from that model, and the collector name is now freeform text
with a typeahead that suggests the existing collector names. There is no list
of names separate from the accession data, …
> SW-3683 Stop using /api/v1/seedbank/values/all

- src/components/PlantsV2/components/TotalReportedPlantsCard.tsx
- previously the calculation was extremely cumbersome
- it sometimes produced the wrong result
- simplify it
> Perform Population Summation Calculation Differently

- src/api/types/generated-schema.ts
- src/components/accession2/edit/Accession2EditModal.tsx
- src/components/accession2/properties/Species2Dropdown.tsx
- src/strings/csv/en.csv
In preparation for an upcoming change that causes changes to an accession's
species to be propagated to seedling batches that come from that accession,
add logic to prevent editing an accession's species if the accession's seeds
have already been sent to a nursery, and seedlings have already been withdrawn
from the nursery and delivered to a planting site.
This prevents accession species changes from causing inconsistencies between
nursery withdrawals and the species populations at planting sites. In the
future we may remove this restriction and make the species changes propagate to
planting site data too, but doing so would introduce a number of edge cases
that would require more detailed requirements definition.
If the species dropdown is disabled, there is a tooltip explaining why.
> SW-3647 Accession species only editable if no deliveries

- src/components/Observations/ObservationsDataView.tsx
- src/components/Observations/ObservationsEventsNotification.tsx
- src/components/Observations/common/DetailsPage.tsx
- src/components/Observations/common/SpeciesMortalityRateChart.tsx
- src/components/Observations/common/SpeciesTotalPlantsChart.tsx
- src/components/Observations/details/ObservationDetailsRenderer.tsx
- src/components/Observations/org/OrgObservationsRenderer.tsx
- src/components/Observations/zone/ObservationPlantingZoneRenderer.tsx
- src/strings/csv/en.csv
- map and notifications were assembled horizontally, make that vertical
- remove extra spacing in notifications
- update copy for map view when all planting sites are selected
> Misc fixes in observations view

- src/components/Observations/common/SpeciesMortalityRateChart.tsx
- src/components/Observations/common/SpeciesTotalPlantsChart.tsx
- src/components/Plants/PlantBySpeciesChart.tsx
- src/components/Plants/SpeciesBySubzoneChart.tsx
- src/components/PlantsV2/components/LiveDeadPlantsPerSpeciesCard.tsx
- src/components/PlantsV2/components/NumberOfSpeciesPlantedCard.tsx
- src/components/PlantsV2/components/PlantingProgressPerZoneCard.tsx
- src/components/PlantsV2/components/PlantsReportedPerSpeciesCard.tsx
- src/components/common/Chart/BarChart.tsx
- src/components/common/Chart/Chart.tsx
- src/components/common/Chart/PieChart.tsx
- Allow multiple datasets per series
- For bar charts, this allows multiple bars per x-label
- Each datum is grouped with a second bar that is half the height and the same color
> Chart Grouping

- src/redux/features/observations/observationsSlice.ts
- src/redux/features/observations/observationsThunks.ts
- src/redux/features/observations/plantingSiteObservationsSelectors.ts
- src/redux/rootReducer.ts
- src/services/ObservationsService.ts
- Redux to dispatch/select planting-site observations results, advanced selectors to aggregate information will be in subsequent PRs
- This will be used on the location->PlantingSites->PlantingSite page
- We already have redux for the org-wide results, which is a superset of what this PR does
- We could theoretically leverage the org-wide redux for this view but it seems wasteful to fetch all the data when not needed
- Optionally we could trigger the fetching of org-wide data during App initialization and select what we want in this view (and for the observations views), downside is we may have stale data over time unless we periodically refresh the data, another downside is the load on server because app load guarantees we fetch observations results for all sessions
- Downside to this …
> SW-3857 Initial redux to fetch observations results for a single planting site

- src/App.tsx
- src/components/PlantingSites/PlantingSiteSubzoneView.tsx
- src/components/PlantingSites/PlantingSiteZoneView.tsx
- src/components/PlantingSites/index.tsx
- src/constants.ts
- similar to observations routing, refactor planting sites routing
- App.tsx now calls the root planting sites component for any route starting with `/planting-sites`
- the root planting sites component handles the various routing for planting sites view, edit, create, drill downs
- this also simplifies App.tsx context
- added placeholder content for zone/subzone views
> SW-3869 Refactor routing for planting sites views to support drill downs

- .github/workflows/workflow.yml
Tailscale now supports OAuth for client authentication; use it instead
of API-key-based authentication.
> Upgrade to latest Tailscale GitHub Action

- src/api/types/generated-schema.ts
- src/components/LocaleSelector.tsx
- src/components/MyAccount/index.tsx
- src/services/UserService.ts
- src/strings/locales.ts
- src/types/User.ts
To support variation of number formatting rules in different Spanish-speaking
countries, we're going to keep track of users' countries. If the user has selected
a country, their locale will include a country code as well as a language.
For the most part, locales with country codes work transparently because they're
well supported by browsers. However, our application code currently expects the
locale to only include a language. If the server sends back a locale like `es-MX`,
the client doesn't know which item in the locale selector it should use.
We could just strip off the country code, but in the future, we'll likely need to
support languages where the country code is more significant, e.g., Chinese.
Instead, update the client to pick the longest match from its list of supported …
> SW-3868 Handle locales with country codes

- src/App.tsx
- src/components/ListMapView/index.tsx
- src/components/Observations/index.tsx
- src/components/PlantingSites/BoundariesAndZones.tsx
- src/components/PlantingSites/PlantingSiteCreate.tsx
- src/components/PlantingSites/PlantingSiteView.tsx
- src/components/PlantingSites/index.tsx
- was working on the tv2 updates for planting sites and had a need to fetch planting sites list
- realized we are already overfetching (in the App, in the Observations page, etc.)
- update the App to dispatch a redux request
- all components now rely on the dispatched request in the App to select planting sites
- also, when we update (edit/create) planting sites, the app reloads planting sites
- simplifies code
- added initial map/list view for planting site details page
> Refactor planting-sites fetch to use redux + initial map/list view in planting sites details page

- src/components/Species/index.tsx
Users want to share species lists between organizations by exporting and importing
them, but currently, the export format isn't the same as the import format so they
have to manually edit the files first.
Change the species list UI so the columns appear in the same order as in the
import template, and change the export code so it omits a couple of ID columns
that are required by the UI code but aren't needed for import.
> SW-3828 Use import format for species CSV export

- src/components/Map/MapRenderUtils.tsx
- src/components/PlantingSites/BoundariesAndZones.tsx
- reused styles/layout from existing render utils that shows simple stats
- refactored some for reusability
> SW-3880 Add map tooltip popups on planting site details page

- src/components/BreadCrumbs/index.tsx
- src/components/Map/MapRenderUtils.tsx
- src/components/Map/PlantingSiteMap.tsx
- src/components/Observations/common/DetailsPage.tsx
- src/components/PlantingSites/BoundariesAndZones.tsx
- src/components/PlantingSites/PlantingSiteDetailsTable.tsx
- src/components/PlantingSites/PlantingSiteSubzoneView.tsx
- src/components/PlantingSites/PlantingSiteZoneView.tsx
- src/components/PlantingSites/index.tsx
- src/redux/features/observations/plantingSiteDetailsSelectors.ts
- src/stories/BreadCrumbs.stories.tsx
- src/strings/csv/en.csv
- extract out a common page framework with crumbs (from Observations DetailsPage.tsx)
- add search selectors for zone/subzone/monitoring-plots in planting site details
- added tables/renderers
- the zone/subzone content was very similar so added into one PR also to see refactor/componentizing opportunities
- fixed a monitoring plots population error in planting site observation results aggregation selector
> SW-3850 / SW-3851 Add Planting Site details' zone/subzone views with bread crumbs

- src/components/Map/Map.tsx
Previously, the map could get into a state where the highlight from
selection of a map entity was stuck. This was due to the select state
being cleared when the map data changed and a map popup was still open.
In the code for updating callbacks on map data change, only clear the
select map feature if the popup is not open. This allows the popup
close handler to properly reset this feature state.
> SW-3914 Fix Highlight for Map

- src/components/Map/MapRenderUtils.tsx
- src/components/PlantingSites/BoundariesAndZones.tsx
- src/services/TrackingService.ts
- demo'd to Chudo, found some missing tooltip properties and style issues
- added missing tooltips
- give more width to tooltip based on content
- added back a field in service which is needed in the previous plants dashboard map tooltip (totalPlants as localized by server)
> SW-3921 Feedback changes, add missing tooltips + fix tooltip style

- src/components/NurseryWithdrawals/PlantingProgressMap.tsx
- src/components/NurseryWithdrawals/PlantingProgressTabContent.tsx
- src/components/common/PlantingSiteSelector.tsx
- create a common PlantingSiteSelector component
- create a component that variably displays search or the selector based on view
- keep track of the selected planting site id and pass to map
> SW-3903 Add Planting Site Selector for Map View

- src/components/NurseryWithdrawals/PlantingProgressList.tsx
- src/components/NurseryWithdrawals/PlantingProgressTabContent.tsx
- src/redux/features/plantings/plantingsSelectors.ts
- src/strings/csv/en.csv
- src/types/PlantingSite.ts
- added table
- table selection etc is a follow up
- renderer with link to withdrawals (this requires more work on withdrawals component as a follow up)
- cleaned up some selectors
- linked with search
> SW-3895-table Add plantings progress table

- src/App.tsx
- src/components/NurseryWithdrawals/NurseryPlantingsAndWithdrawals.tsx
- src/components/NurseryWithdrawals/PlantingProgressList.tsx
- src/components/NurseryWithdrawals/PlantingProgressTabContent.tsx
- src/components/NurseryWithdrawals/index.tsx
- src/redux/features/plantings/plantingsAsyncThunks.ts
- src/redux/features/plantings/plantingsSelectors.ts
- src/redux/features/plantings/plantingsSlice.ts
- src/redux/rootReducer.ts
- src/strings/csv/en.csv
- Allow selecting rows in table
- Show "Planting Complete" and "Undo planting complete" buttons on top bar
- Add bulk set planting complete thunk
- Refresh table after success
> SW-3897 Add "planting complete / undo" functionality

- src/components/NurseryWithdrawals/NurseryWithdrawalsTable.tsx
- src/services/NurseryWithdrawalService.ts
- parse subzones filter options in service (sort values)
- enable subzones filter option
- this will be used in a follow up PR to set filters based on url params
> SW-3900 Add subzone filter to nursery withdrawals table

- src/components/NurseryWithdrawals/PlantingProgressMap.tsx
- prevent updating map data more than once
- set focus to site when updating map data
- set focus to none when dispatching update subzone request
(site and site2 have the same map)
> SW-3942 Prevent Zoom to Site on Marking Subzones Complete

- src/components/PlantingSites/index.tsx
- skip observations results status check if tracking v2 is disabled
- we were not showing data while observations data was not requested, this should only happen with trackingv2 enabled
> SW-3953 Show planting site details page when tracking-v2 is disabled

- src/components/NurseryWithdrawals/NurseryWithdrawalsTable.tsx
- src/components/NurseryWithdrawals/PlantingProgressList.tsx
- src/components/NurseryWithdrawals/PlantingProgressMapDialog.tsx
- this is when user clicks on the seedlings sent from table, or the 'see withdrawal history' link in map dialog
- best to test in vercel
> SW-3951 Show withdrawals filtered to the query/params

- src/components/PlantsV2/components/PlantingDensityPerZoneCard.tsx
I think this was happening for no observations, because if we have observations, we are showing two bars per zone in the Target Planting Density chart and bar-width necessarily has to be smaller.
In the case of no observations, we were setting the width to be responsive for this chart and fixed for the planting progress. So, the fix is to make it fixed for both charts (when no observations).
> SW-3956 Bar width should be consistent

- src/components/Map/Map.tsx
- src/components/NurseryWithdrawals/NurseryPlantingsAndWithdrawals.tsx
- src/components/NurseryWithdrawals/PlantingProgressTabContent.tsx
- See Jira for video of behavior
- onRender hook was resizing on every render, which happens a lot and leads to some undesirable behavior
- added state in onRender to only resize the first time
- also added more height for the map in desktop mode, fill up remaining height in browser
> SW-3957 Fix odd zoom-to-fit behavior on map when switching between list and map views

- src/components/Observations/ObservationsHome.tsx
- fix distance from page title
- fix border radius
- fix height of content
- the layout here is a bit different from our older pages, hence different way to style
> SW-3996 Fix positioning of empty state message in Observations view

- src/components/PlantsV2/components/PlantingSiteProgressCard.tsx
- src/redux/features/tracking/trackingSelectors.ts
We were previously calculating the progress based on how much subzone area was
marked as completed planting. This was incorrect. Instead use the planting
progress percentages reported by the BE for each zone and the site.
> SW-3978 Get Correct Planting Site Progress %

- src/App.tsx
- src/components/NurseryWithdrawals/NurseryPlantingsAndWithdrawals.tsx
- src/components/NurseryWithdrawals/NurseryReassignment.tsx
- src/components/NurseryWithdrawals/NurserySiteWithdrawals.tsx
- src/components/NurseryWithdrawals/NurseryWithdrawalsDetails.tsx
- src/components/NurseryWithdrawals/NurseryWithdrawalsTable.tsx
- src/components/NurseryWithdrawals/PlantingProgressMap.tsx
- src/components/NurseryWithdrawals/PlantingProgressTabContent.tsx
- src/components/NurseryWithdrawals/index.tsx
- src/components/Observations/ObservationsDataView.tsx
- src/constants.ts
- src/redux/features/plantings/plantingsSelectors.ts
- src/services/NurseryWithdrawalService.ts
- src/strings/csv/en.csv
- fixed width/height of tab content (removed snackbar and content ref, this is handled in the primary page wrapper)
- fixed selector to apply matching site id and return earlier, avoid extra matching checks
- added map view message when selected site is All (same as in observations view)
- added non-zero component for search so list/map view selector shows up on right hand side for map view
- renamed back to links from withdrawals details and reassignment pages to saw 'Withdrawals' instead of 'Withdrawal Log'
- enhanced routing as follows:
`/withdrawals/details/<detail-id>` goes to details
`/withdrawas/<site-id>` goes to new withdrawals page if tracking v2 is enabled
`/withdrawals/` goes to new withdrawals page if tracking v2 is enabled, otherwise goes to old withdrawals page
> SW-3966-amended Misc fixes on top of Constanza's PR #1616

- src/App.tsx
- src/components/NurseryWithdrawals/NurseryPlantingsAndWithdrawals.tsx
- src/components/NurseryWithdrawals/NurseryReassignment.tsx
- src/components/NurseryWithdrawals/NurserySiteWithdrawals.tsx
- src/components/NurseryWithdrawals/NurseryWithdrawalsDetails.tsx
- src/components/NurseryWithdrawals/NurseryWithdrawalsTabContent.tsx
- src/components/NurseryWithdrawals/NurseryWithdrawalsTable.tsx
- src/components/NurseryWithdrawals/PlantingProgressList.tsx
- src/components/NurseryWithdrawals/PlantingProgressMap.tsx
- src/components/NurseryWithdrawals/PlantingProgressTabContent.tsx
- src/components/NurseryWithdrawals/index.tsx
- src/components/Observations/ObservationsDataView.tsx
- src/components/PlantsPrimaryPage/index.tsx
- src/constants.ts
- src/redux/features/plantings/plantingsSelectors.ts
- src/services/NurseryWithdrawalService.ts
- src/strings/csv/en.csv
Missing: Remove “Destination” filter from Withdrawal History tab’s table filters to avoid conflict with top-of-page Planting Site selector.
> SW-3966 Add planting site selector on withdrawal log

- src/redux/features/plantings/plantingsSelectors.ts
For org with no shape files, we were allowing to write the siteName in the search field to do a fuzzy search, but if a siteName is selected in filter, then just return the exacts coincidence with the siteName selected
> Improve planting progress search

- src/components/PlantingSites/PlantingSiteCreate.tsx
- src/components/PlantingSites/PlantingSiteView.tsx
- src/components/PlantingSites/SimplePlantingSite.tsx
- src/components/PlantsV2/components/SimplePlantingSiteMap.tsx
- src/components/PlantsV2/index.tsx
- src/strings/csv/en.csv
For planting sites with site boundaries but without planting zones or subzones
(which we refer to as "simple" planting sites), show a map view that doesn't
mention zones and subzones.
There is currently no way to create a simple planting site from the UI; that
will be added in a later change.
> SW-3932 Map view for simple planting sites

- src/components/PlantsV2/components/PlantingDensityPerZoneCard.tsx
This will avoid the case where an observation has been completed, but no zone has had all its subzones marked as complete, resulting in a series of `null`s in the actual planting density dataset.
> SW-4016 Do Not Add Actual Density Series if All Values are Null

- src/components/PlantsV2/components/LiveDeadPlantsPerSpeciesCard.tsx
Before (on initial dashboard load):
After:
> SW-4017 Auto-Select First Species for Live/Dead Plants Chart

- src/components/common/Chart/Chart.tsx
> SW-4019 Remove Axes on Pie Chart

- src/components/Map/GenericMap.tsx
- src/utils/useMapboxToken.ts
In preparation for adding a new React component that renders maps, move the logic
for fetching and refreshing Mapbox API tokens into a reusable hook.
> SW-3932 Extract Mapbox token fetching into hook

- src/components/Observations/ObservationsDataView.tsx
- src/components/Observations/ObservationsHome.tsx
- src/components/PlantingSites/PlantingSiteView.tsx
- was previously only included in the list/map views
- move it up so it shows for the empty state as well
> SW-4021 Move scheduled observations notification to the observations root page

- src/api/types/generated-schema.ts
- src/components/PlantsV2/components/LiveDeadPlantsPerSpeciesCard.tsx
- BE API now returns live / dead counts, live specific to permanent plots
- requirement is to use those counts in the pie chart
> SW-4020 Use live/dead counts in species pie chart

- src/components/NurseryWithdrawals/PlantingProgressMap.tsx
- this was a race condition in the planting progress map component
- removed race condition by skipping the dispatch on site id -1 (which was probably not intended anyways)
- in many cases the response from dispatching on -1 was completing after the actual selected site's dispatch, and yielding no results
- also created https://terraformation.atlassian.net/browse/SW-4044 for longer term cleanup
> SW-4010 Fix stale withdrawal numbers in planting progress map popup

- src/redux/features/observations/utils.ts
- fix merge/species util to factor in those species, were previously being filtered out
> SW-4034 Show other/can't-tell species in observations bar charts

- src/components/Observations/ObservationsDataView.tsx
- src/components/Observations/ObservationsHome.tsx
- src/components/Observations/index.tsx
- src/components/Observations/map/ObservationMapView.tsx
- src/components/Observations/map/TooltipContents.tsx
- src/components/Observations/org/OrgObservationsRenderer.tsx
- src/redux/features/observations/observationsSelectors.ts
- src/redux/features/observations/utils.ts
- src/strings/csv/en.csv
- to satisfy PRD requirement allowing users to see which observations are not completed, check out zones, monitoring plots info, etc.
> SW-4045 Add support for InProgress and Overdue observations in the Observations page

- src/components/PlantsPrimaryPage/PlantsPrimaryPageView.tsx
- the selector top was being cut off (since the outline was extending beyond the container)
- added a top/bottom padding and aligned peers by 'center'
> SW-4022 Adjust padding and alignment for site selector in plants primary page

- src/redux/features/observations/observationDetailsSelectors.ts
- src/redux/features/observations/observationsSelectors.ts
- had made a change last week that broke this
- observation details selectors will now pass all the relevant states for selection
> SW-4060 Fix issue where observations without a completed time were not clickable

- src/components/Observations/common/SpeciesMortalityRateChart.tsx
- src/components/Observations/common/SpeciesTotalPlantsChart.tsx
- cleaned up earlier fix, removed commonName since it isn't relevant
> SW-4051 Show scientific names instead of common in plot species charts 

- src/components/common/PhotosList.tsx
- this will use correct aspect ratio to display thumbnail, with the downside that there will be horizontal empty space for portrait images
> SW-4028 Use 'contain' object fit for thumbnail images

- src/components/Inventory/index.tsx
- src/services/NurseryInventoryService.ts
Allow searching inventories by different nurseries and getting its corresponding quantities. Previously we were getting the totals for all nurseries, not considering nursery filter.
Query executed to the backend changes depending on if nurseries are selected or not. From backend, response comes by species id, so sum all same species id quantities to show the number of each quantity for selected nurseries (and not total as before)
This PR requires a backend change: https://github.com/terraware/terraware-server/pull/1326
> SW-3993 Quantity not accurate with nursery filter

- src/components/Observations/common/AggregatedPlantsStats.tsx
- src/components/Observations/details/index.tsx
- src/components/Observations/org/OrgObservationsListView.tsx
- src/redux/features/observations/utils.ts
- src/types/Observations.ts
- introduced total plants data member (looks like observation details no longer has a total plants field in the BE)
- sum total plants in the selector
- removed tooltip
> SW-4073 Show total plants in observations details page regardless of planting complete state

- src/App.tsx
- src/components/Observations/details/index.tsx
- src/components/Observations/zone/index.tsx
- src/redux/features/observations/observationsSelectors.ts
- fix styles of container
- also make the navbar bg translucent when there are observations, navbar was always transparent for observations and scrolling the table showed overlapping content in the navbar
> SW-4072 Observations details table backgrounds should extend to scrolled region

- src/components/PlantsV2/components/PlantsReportedPerSpeciesCard.tsx
- use 'flex' bar width
- bar charts are not updating with data changes, using a key property to re-create the bar chart when we have update values, fixes the y-values race condition of creating bar chart before we have all the data
> SW-4050 Fix overlapping bars in reported plants by species chart

- src/components/PlantingSites/DetailedPlantingSiteHelpModal.tsx
- src/components/PlantingSites/PlantingSiteSelectTypeModal.tsx
- src/components/PlantingSites/PlantingSiteTypeSelect.tsx
- src/strings/csv/en.csv
Update the wording of the "select a planting site type" dialog to refer to
planting sites as "simple" and "detailed" rather than as "without map" and
"with map" to reflect the fact that we will soon allow simple planting
sites to have maps.
> SW-3932 Use simple/detailed site types in dialog

- src/components/PlantsV2/components/HighestAndLowestMortalityRateSpeciesCard.tsx
- src/components/PlantsV2/components/HighestAndLowestMortalityRateZonesCard.tsx
- src/strings/csv/en.csv
- show species name as provided in the observation instead of looking up by id, we may have unknown species entered by user
- show mortality rate of '0' only if the monitoring plot has permanent plots
- hide lowest zone/species mortality rate and use info blurb if highest and lowest are the same (see screenshot)
> SW-4064 Fix mortality rate display issues in plants dashboard

- src/components/Map/Map.tsx
- this happens a lot of the time where the zoom does not take effect, even though it is being called
- suspect this could be a react event vs non-react underlying map implementation event latency issue, unsure
- added a set timeout of 0 so the zoom happens on next time slice, open to other suggestions
- see before/after gifs
> SW-4049 Fix map zoom into boundary when switching site in observations page

- src/components/Inventory/index.tsx
If species has common name, we were not showing it for the InventoryResultWithFacilityNames. Add it
> Show species common name in inventory search

- src/redux/features/observations/observationsSelectors.ts
- we were sorting by `completedDate` (yyyy-mm-dd format), there were 2 observations on that date, the earlier one was used
- sort by `completedTime` instead which has millisecond level granularity
> SW-4096 Use latest observations data in plants dashboard

- src/components/common/Chart/ProgressChart.tsx
If value is more than 100, MUI starts filling the progress again. Fix it to be 100% for values bigger than 100
Before:
After:
> SW-4101 Fix Site plant density >100%

- src/components/Species/index.tsx
- src/components/emptyStatePages/EmptyStatePage.tsx
- src/state/species.ts
Recoil was used to show the review errors modal in species list when coming from the empty state.
Remove recoil usage and replace it using a query param to show the modal in those cases.
> SW-3740 Remove recoil usage from species list page

- src/components/Map/Map.tsx
When screen is small (some mobiles), the info text wraps into two lines and it also shows under the buttons. To fix this, move the info botton to the top
> SW-4124 Move Mapbox info pop-up to the top

- src/api/types/generated-schema.ts
- src/components/NavBar.tsx
- src/components/Nurseries/index.tsx
- src/components/People/TableCellRenderer.tsx
- src/components/People/index.tsx
- src/components/SeedBanks/index.tsx
- src/strings/csv/en.csv
- src/types/Organization.ts
- src/utils/organization.tsx
- show TF contact role string value in people table if there is such a user
- disallow deletion/edit of TF contact
- adding TF Contact as a role is disallowed by default since we hard-code the roles and TF Contact was not there
- note: these capture the basic requirements for TF contact jira, there may be a follow up task around UX (jira created for design)
- this PR is dependent on BE PRs https://github.com/terraware/terraware-server/pull/1370 & https://github.com/terraware/terraware-server/pull/1372
- another outstanding issue is how delete org works when there is a Tf contact, this may be unrelated to FE and completely handled with BE but currently not done
- fixed another issue where we show a warning when all removable users are selected (the org's total users includes non humans, …
> SW-4240 Add 'Terraformation Contact' semantics in FE

- src/components/Observations/ObservationsEventsNotification.tsx
- src/components/Observations/ObservationsHome.tsx
- src/components/Observations/index.tsx
- src/components/Observations/org/ActionsMenu.tsx
- src/components/Observations/org/OrgObservationsListView.tsx
- src/components/Observations/org/OrgObservationsRenderer.tsx
- src/components/Observations/schedule/RescheduleObservation.tsx
- src/components/Observations/schedule/ScheduleObservation.tsx
- src/components/Observations/schedule/ScheduleObservationForm.tsx
- src/components/Observations/schedule/index.tsx
- src/constants.ts
- src/redux/features/observations/observationsUtilsSelectors.tsx
- src/strings/csv/en.csv
- show buttons to schedule/reschedule as per requirements in PRD
- same for validation of dates
- a bunch of refactor to enable reuse of selectors
- this PR is built on top of two other PRs https://github.com/terraware/terraware-web/pull/1718 and https://github.com/terraware/terraware-web/pull/1719
> SW-4255 / SW-4256 UI to schedule/reschedule observations

- .storybook/preview.tsx
- src/api/types/generated-schema.ts
- src/components/Observations/ObservationsEventsNotification.tsx
- src/components/Observations/ObservationsHome.tsx
- src/components/Observations/index.tsx
- src/components/Observations/org/ActionsMenu.tsx
- src/components/Observations/org/OrgObservationsListView.tsx
- src/components/Observations/org/OrgObservationsRenderer.tsx
- src/components/Observations/schedule/RescheduleObservation.tsx
- src/components/Observations/schedule/ScheduleObservation.tsx
- src/components/Observations/schedule/ScheduleObservationForm.tsx
- src/components/Observations/schedule/index.tsx
- src/components/PlantsPrimaryPage/PlantsPrimaryPageView.tsx
- src/components/PlantsPrimaryPage/index.tsx
- src/constants.ts
- src/redux/features/asyncUtils.ts
- src/redux/features/observations/observationsAsyncThunks.ts
- src/redux/features/observations/observationsSelectors.ts
- src/redux/features/observations/observationsSlice.ts
- src/redux/features/observations/observationsUtilsSelectors.tsx
- src/redux/features/plantings/plantingsSlice.ts
- src/redux/rootReducer.ts
- src/services/ObservationsService.ts
- src/stories/PlantsPrimaryPage.stories.tsx
- src/strings/csv/en.csv
- src/types/Observations.ts
- to support schedule observation use-case
- fixed storybook not loading due to `store` not defined
- added a story to capture the primary action button
> Add primary action button to PlantsPrimaryPage

- src/components/PlantsV2/components/PlantingSiteDensityCard.tsx
- src/components/common/OverviewItemCard.tsx
> SW-4250 Fix planting density card not taking the whole space

- src/components/Reports/LocationSection.tsx
Fixes in this PR include: 
- Planting progress is not populating at all
- Planting progress should not be shown when we have planting density for the whole site
- Planting density per zone should not be shown if we don’t have any values
- Planting density should be labeled with the units (Plants/ha)
> SW-4249 - Improvements to plant monitoring details in reports

- src/api/types/generated-schema.ts
- src/redux/features/asyncUtils.ts
- src/redux/features/observations/observationsAsyncThunks.ts
- src/redux/features/observations/observationsSelectors.ts
- src/redux/features/observations/observationsSlice.ts
- src/redux/rootReducer.ts
- src/services/ObservationsService.ts
- src/strings/csv/en.csv
- src/types/Observations.ts
- Generated types using branch `replace-api` from [PR](https://github.com/terraware/terraware-server/pull/1397)
- Added service functions
- Added redux
- Refactored `buildReducers` to accept a type, to store data other than just the request status (new use-case)
- Added strings and a type/util to return string for plot replacement duration
> SW-4319 Redux/service/types for replacing an observation monitoring plot

- src/components/Map/EditableMap.tsx
- src/strings/csv/en.csv
Based on user feedback, update the instructions for the planting site map editor
to tell people to zoom in first, and move the instructions above the map.
> SW-3932 Update editable map instructions

- src/components/common/ImportModal.tsx
- src/strings/csv/en.csv
Currently, if the user uploads a species list CSV that has validation failures, we
show an error dialog that only includes the first failure and doesn't say where in
the file the offending row is.
Update the dialog so it shows all the errors and says which row each one is on.
> SW-3271 Show all errors on species list upload failure

- src/components/Map/Map.tsx
- src/components/Map/MapRenderUtils.tsx
- src/components/Map/PlantingSiteMap.tsx
- src/components/Observations/map/ObservationMapView.tsx
- src/components/Observations/map/TooltipContents.tsx
- src/components/Observations/replacePlot/ReplaceObservationPlotModal.tsx
- src/components/common/MapLayerSelect/index.tsx
- src/types/Map.ts
- Created a custom hook that informs when a map is in fullscreen and which container to use for modal portals
- Integrated this hook with map tooltip so reassign request modal shows in full screen mode as well (uses the full screen container as the parent for the modal)
- popovers (such as layers and outdoors-vs-satellite) are still not functional, added a change to not render these in fullscreen mode for now (since they won't work)
- will follow up later with a web-component change if we can get popovers to work
- refactored the top-right/bottom-left control components to be rendered inside of the map hierarchy otherwise they get hidden in fullscreen mode, top-right for now is not rendered until popovers work, the bottom-left observation date slider now works in fullscreen mode
> SW-4330-continued Allow reassign-request modal to show in full screen

- src/components/Map/Map.tsx
- src/components/Map/MapRenderUtils.tsx
- src/components/Map/PlantingSiteMap.tsx
- src/components/Observations/map/ObservationMapView.tsx
- src/components/Observations/map/TooltipContents.tsx
- src/components/Observations/replacePlot/ReplaceObservationPlotModal.tsx
- src/components/common/MapLayerSelect/index.tsx
- src/strings/csv/en.csv
- src/types/Map.ts
- Added switcher on top left for Outdoors/Satellite, not using an IControl at this point, being consistent with how we added the layers and zoom-to-fit controls
- update map view style based on selection
- currently storing selection in localStorage, not distinguished by site id or any other key
- we should discuss best approach for storing this preference (site wide option vs user specific option vs user/site option, etc.)
- outstanding issue is the selector is not clickable in full screen mode because the popover is not viewable in full screen mode (not part of the dom hierarchy).. i could switch this to a radio button
> SW-4330 Add 'Outdoors' map view style option

- src/components/Inventory/view/BatchDetailsModal.tsx
- src/components/Inventory/view/InventorySeedlingsTable.tsx
- don't use the `open` modal parameter, which required us to clean the modal state across batch selections
- conditionally show/render the batch details modal when user clicks on a batch
- this approach is cleaner and we won't have to add a bunch of logic in the modal to update the fields
> SW-4372 Create batch details modal without keeping state of previous batch selection

- src/components/Map/EditableMap.tsx
- src/components/Map/Map.tsx
- src/components/Map/MapRenderUtils.tsx
- src/components/Map/MapViewStyleControl.tsx
- extracted out the map view style component for reuse
- added a react hook to share the set/get map view style properties, for reuse
- added map view style and fullscreen controls to the editable map view
- the color contrast can be off in outdoors view sometimes
> SW-4330-followup Add map style dropdown and fullscreen button to editable map view

- src/api/types/generated-schema.ts
- src/components/Inventory/view/ChangeQuantityModal.tsx
- src/services/NurseryBatchService.ts
Calculating germination and loss rates will require that we distinguish between
the user overwriting the quantities of a batch and the user moving seedlings from
one status to another.
Update the "change status" dialog so it calls a newly-added API endpoint for
changing seedling statuses.
> SW-4376 Distinguish status changes from quantity edits

- src/components/Observations/ObservationsEventsNotification.tsx
- src/components/Observations/org/OrgObservationsRenderer.tsx
- src/redux/features/observations/utils.ts
- src/strings/csv/en.csv
- src/types/Observations.ts
- also change criteria for which observations in the table can be rescheduled (in-progress/overdue and no observed plots)
- added a hasObservedTemporaryPlots to capture whether any type of plot was observed (in tandem with hasObservedPermanentPlots)
- refactor layout of page message that shows upcoming observations for reschedule, the site names have permalinks now and had to be constructed programmatically (removed from the string representation)
> SW-4402 Allow upcoming observations to be rescheduled 

- src/components/Observations/ObservationsEventsNotification.tsx
- use font size 16 for Reschedule link
> Fix font size in Reschedule link

- src/App.tsx
- src/components/PlantsPrimaryPage/index.tsx
- src/providers/OrganizationProvider.tsx
- allows us to share urls maintaining org context
- centralized handling so devs can create links in code without worrying about populating the org id
- some special handling for the welcome page alone as it switched between routing contexts
- also updated the plants primary page (used by observations, dashboard) to avoid redundant calls to get/set preferences, noticed this while debugging
> SW-2223 Keep state of current org in the url

- src/components/InventoryV2/BatchSummary.tsx
- src/components/NewSeedBank/index.tsx
- src/components/SeedBank/SubLocations.tsx
- src/components/accession2/edit/EditLocationModal.tsx
- src/components/accession2/properties/SeedBank2Selector.tsx
- src/services/SeedBankService.ts
- src/services/SubLocationService.ts
- I had originally created them under SeedBankService (since seedbanks alone referred to sublocations)
- move these functions into the newly created SubLocationService and update all callers
- plan is to use these functions in the nurseries details view updates
> Move sub-locations fetch/create functions into SubLocationService

- scripts/openapi-typescript-formatter.js
- src/api/types/generated-schema.ts
- src/components/Inventory/view/InventorySeedlingsTable.tsx
- src/components/NurseryWithdrawals/NurseryWithdrawalsTable.tsx
- src/components/People/index.tsx
- src/components/PlantingSites/PlantingSitesList.tsx
- src/components/Species/index.tsx
- src/components/seeds/database/Filters.tsx
- src/redux/features/plantings/plantingsThunks.ts
- src/services/FacilityService.ts
- src/services/LocationService.ts
- src/services/NurseryBatchService.ts
- src/services/NurseryInventoryService.ts
- src/services/NurseryWithdrawalService.ts
- src/services/PlantingsService.ts
- src/services/SearchService.ts
- src/services/SeedBankService.ts
- src/services/TrackingService.ts
- src/services/test/NurseryWithdrawalService.test.ts
- src/types/Search.ts
To avoid a circular type reference, we replaced the definition of
`SearchNodePayload` in `generated-schema.ts` with "any".
Unfortunately, "any" effectively causes type checking to be disabled, so there
was some search-related code that used the wrong types and TypeScript couldn't
detect it.
- Update the OpenAPI code generator so it replaces `SearchNodePayload` with a
real type, though one that still avoids the circular reference.
- Fix the incorrect types that become visible to the type checker once we've
stopped using "any".
- Introduce a stricter version of `SearchRequestPayload` that requires a search
query (it is optional in the API).
This shouldn't change any behavior.
> Clean up search API payload types

- src/components/Nursery/NurserySubLocations.tsx
- Added link from location view to inventory/batch view
- The batch view will have the facilityId and subLocationName in the URL as query params, we need to apply those filters and clear them from url (similar to seedbank location link)
- Updated PRs with info on filter, added a note in https://terraformation.atlassian.net/browse/SW-4384 to check SW-4434 for filter info
> SW-4434 Link Location->Nursery->SubLocation->BatchCount to inventory batch view with filters set

- src/components/InventoryV2/InventoryTable.tsx
- the table container had a negatve margin, eating into the nursery filter space (a subsequent padding essentially made that whitespace)
- fixes are to either update z-index on filter or add positive margin to container so it does not overlap the filter space
- here i added a positive margin (downside is there's some space above the table)
> SW-4456 Make nursery filter clickable in v2 inventory list

- src/components/PlantingSites/PlantingSiteCreate.tsx
- src/components/PlantingSites/PlantingSiteView.tsx
- src/utils/dateFormatter.ts
We're going to be replacing the admin-specified planting season start and end
months with a new user-editable planting season schedule. Since we won't be
bothering to set the start/end months given the new feature is coming up, stop
showing them in the UI.
> SW-4468 Remove planting season months from UI

- src/components/InventoryV2/InventoryTable.tsx
- src/components/InventoryV2/view/InventorySeedlingsForNurseryTable.tsx
- src/components/InventoryV2/view/InventorySeedlingsTable.tsx
- src/components/Observations/zone/index.tsx
- We use the [table ids to generate user preference names](https://github.com/terraware/terraware-web/blob/main/src/components/common/table/index.tsx#L54), to store table column ordering iff user changes the column locations (drag n drop)
- This table id design decision seems to be backfiring a bit now, we don't have any checks in place to ensure unique table ids (sigh)
- For now, fix the table ids to be unique (maybe we can keep an eye out for such changes going forward)
- Open to other ways of ensuring unique ids (maybe leverage some typescript magic?)
- Note that changing the column definitions would require changing the table ids (since preserved columns would no longer match the definition)
> Use unique ids for tables, ids are used to generate user preference names

- src/components/common/SpeciesSelector/index.tsx
- the new inventory / new accession forms were auto scrolling down when user typed in the species input
- this scroll was seen in FF not Chrome
- looks like this is a known issue and we have an 'option' to disable the scroll
- enabled the option and observed no auto-scroll in FF
> SW-4461 Disable auto scroll when typing into species dropdown selector

- src/components/SubzoneSelector/index.tsx
- planting zone/subzones are fetched from the redux store in the parent
- this data is read-only
- Subzone selector was sorting the planting subzones, sort is an in-place sort that returns a reference to the array, throwing an error (cannot modify read-only data due to in-place sort)
- See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort
- for now make a copy of the array prior to sorting
- checked the codebase for other such occurrences but in all cases there's a filter call prior to sort, which ends up returning a different mutable array
> SW-4513 Fix outplant withdrawal error selecting a planting zone

- src/components/InventoryV2/DownloadReportModal.tsx
- src/components/InventoryV2/FilterUtils.ts
- src/components/InventoryV2/InventoryFilter.tsx
- src/components/InventoryV2/InventoryListByBatch.tsx
- src/components/InventoryV2/InventoryListByNursery.tsx
- src/components/InventoryV2/InventoryTable.tsx
- src/components/InventoryV2/Search.tsx
- src/components/InventoryV2/view/InventorySeedlingsTable.tsx
- src/services/NurseryBatchService.ts
- src/services/NurseryInventoryService.ts
- Refactor InventoryFilter to be generic, pushing logic for the filter options into the Search component.
- Add SubLocation filter to Batch view
- Enable filtering by sublocation and by species, where appropriate
- Some [type-foolery](https://github.com/terraware/terraware-web/pull/1838/files#diff-2eae7c37411b0359763e941d4410e20f8198e0b617f3b6bf952c399bfab3068cR49-R52) to help prevent bugs
- Handle filter pill addition and deletion
> SW-4484 Enable Filter by SubLocation

- src/components/NewProjectFlow/flow/ProjectEntitiesFiltersPopover.tsx
- src/components/NewProjectFlow/flow/Search.tsx
- src/components/NewProjectFlow/flow/SelectAccessions.tsx
- src/components/NewProjectFlow/flow/SelectBatches.tsx
- src/components/NewProjectFlow/flow/SelectPlantingSites.tsx
- src/components/NewProjectFlow/flow/useProjectEntitySelection.ts
- src/services/NurseryBatchService.ts
- src/services/TrackingService.ts
- Create [ProjectEntitiesFiltersPopover](https://github.com/terraware/terraware-web/pull/1843/files#diff-eaa422306fd83884e1cbcc92bdf2ff8c4f71638dfc51096fd84ed984c81abbc9R58) which houses the entity specific filters, added to the `NewProjectFlow/flow/Search` component.
- Select Accessions has filters for statuses and projects
- Select Batches has filters for nurseries and projects
- Select Planting Sites has filters for projects
> SW-4489 Add new project entity filtering, entity specific and project multi-select filters

- src/App.tsx
- src/components/ProjectView/index.tsx
- src/constants.ts
- Add route for '/projects/:projectId' to ProjectView
- Stub out grid, name, and description in the new view
- Put the new route behind the feature flag
> SW-4490 Stub out ProjectView and routing

- src/components/Map/Map.tsx
- the focus code was picking the first geometry to zoom into
- fix code to fetch all geometries that match the focus criteria
> SW-4486 Fix map zoom for sites with multiple polygons

- src/components/accession2/edit/QuantityModal.tsx
- don't require notes when the quantity is being set for the first time
> SW-4567 Require notes only when the quantity is modified

- src/components/accession2/view/Accession2View.tsx
- Stub out project card behind feature flag
- Refactor the grid so it works as expected with variable summary card counts
**6 items**
**7 items**
> Refactor the accession summary grid, stub out project card

- src/components/InventoryV2/form/BatchDetailsForm.tsx
- src/components/InventoryV2/form/useAccessions.ts
- Add an optional `excludeUsedUp` parameter to `useAccessions`
- Add search criteria to service call to filter out used up accessions
> SW-4579 Exclude Used Up Accessions from Add Inventory Form

- src/components/LocationTimeZoneSelector.tsx
`LocationTimeZoneSelector` calculates the effective time zone of the location
(inheriting from the organization if needed) but doesn't expose that value;
callers have to calculate it themselves. Add an optional callback to expose it.
> Expose effective time zone from selector

- src/components/InventoryV2/form/BatchDetailsForm.tsx
- src/components/InventoryV2/form/useAccessions.ts
- Add a `speciesId` parameter to `useAccessions`
- In `BatchDetailsForm`, if origin is Species, send `speciesId` to
`useAccessions`
- Send selected species id, if selected
> SW-4581 Restrict Accessions Species if Adding Batch from Species Page

- package.json
- src/components/InventoryV2/BatchSummary.tsx
- src/components/InventoryV2/InventoryBatch.tsx
- src/components/InventoryV2/form/SubLocationsDropdown.tsx
- src/components/InventoryV2/view/OverviewItemCardSubLocations.tsx
- src/redux/features/asyncUtils.ts
- src/redux/features/batches/batchesAsyncThunks.ts
- src/redux/features/batches/batchesSelectors.ts
- src/redux/features/batches/batchesSlice.ts
- src/redux/rootReducer.ts
- yarn.lock
- Move SubLocationsDropdown functionality within summary to its own component, save sub locations against the batch when the multi select is blurred - https://github.com/terraware/terraware-web/pull/1898/commits/7c3c04c7f99287e423709f0a728016cc52995785
- [Implement batches state with fetch batch so we can update consumers of batches within state](https://github.com/terraware/terraware-web/pull/1898/commits/7b1ec6c98d0d0f214aacf29898034ab8d3a2b8f2)
- [Use redux for batch within the InventoryBatch view](https://github.com/terraware/terraware-web/pull/1898/commits/94af90eaadc4e5a4b73c66f865558beff7023135)
Depends on https://github.com/terraware/web-components/pull/447
> SW-4558 Add sublocation edit functionality to batch details view

- src/components/Inventory/withdraw/BatchWithdrawFlow.tsx
- src/components/Inventory/withdraw/flow/SelectPurposeForm.tsx
- src/components/InventoryV2/view/BatchesCellRenderer.tsx
- previously we were gating off totalQuantity (which does not include germinating quantity, as per requirements)
- include germinating quantity in decision whether to allow withdrawals (this is a valid use-case)
> SW-4607 Allow withdrawals on batches that only have non-zero germinating quantity

- src/components/InventoryV2/form/BatchDetailsForm.tsx
- Number('') is 0, which is why clearing 0 was not working, our onChange was setting the value as Number(value)
- fix is to allow the string value (it gets converted to number on the BE anyways)
- handle empty string during validation
> SW-4620 Allow clearing zero values in inventory create form

- src/components/InventoryV2/InventoryTable.tsx
- src/components/InventoryV2/view/InventorySeedlingsTable.tsx
- src/components/InventoryV2/view/InventorySeedlingsTableForNursery.tsx
- src/components/InventoryV2/view/InventorySeedlingsTableForSpecies.tsx
- src/services/NurseryInventoryService.ts
- src/strings/csv/en.csv
- also check germinating quantities before disabling withdraw button
- also add tooltips to seedlings table views when button is disabled
- enable bulk withdrawal in seedlings table views even with single selection for consistency (Chudo feedback)
> SW-4642 / SW-4586 Allow withdrawal of germinating quantities in inventory views + add tooltips

- src/redux/features/accessions/accessionsSelectors.ts
- src/redux/features/accessions/accessionsSlice.ts
- src/redux/features/accessions/accessionsThunks.ts
- src/redux/rootReducer.ts
- src/services/SeedBankService.ts
- Add accessions search functionality to redux, store accessions in state based on org ID and species ID requested
- Falls back to species ID '0' if we are requesting all accessions for an org
> SW-4623 Add accessions search functionality to redux

- src/components/common/PageHeaderWrapper.tsx
> SW-4645 Set PageHeaderWrapper width to 100% to fix inconsistency between Firefox and Chrome

- src/services/NurseryInventoryService.ts
CSV export of the "by nursery" inventory view was requesting the same set of
fields that are used to populate the UI, including IDs and raw numeric values.
The IDs weren't useful to users, and the raw numeric values were causing the
export to fail because CSVs need to be localized and thus can't include
non-localized fields.
Update the request construction code to only include the user-visible fields
when exporting the view to a CSV.
> SW-4652 Only export visible inventory-by-nursery fields

- src/components/InventoryV2/InventoryBatch.tsx
- contentRef was being set on the tabs container, most likely a mistake since the contentRef was also being set correctly on the content container of tabs and info cards correctly
- removed the extra contentRef (which adds a marginTop 200px during scroll up which triggers a static page header)
> SW-4616 Remove extra margin during scroll in batch details view

- src/components/InventoryV2/InventoryCellRenderer.tsx
- src/components/InventoryV2/InventoryViewForNursery.tsx
- src/components/InventoryV2/InventoryViewForSpecies.tsx
- Keep the query in the address bar when navigating to species, nursery, or batch from inventory list view
- Also in the "inventory by nursery|species" views
> SW-4617 Keep the query in the address bar when navigating to species, nursery, or batch from inventory

- src/components/Inventory/withdraw/BatchWithdrawFlow.tsx
- src/components/Inventory/withdraw/flow/SelectBatchesWithdrawnQuantity.tsx
- src/components/Inventory/withdraw/flow/SelectPurposeForm.tsx
- Add projects dropdown to withdrawal 'purpose selection' form
- Filter batches in the subsequent form that exist within the selected project
- Only show projects that exist within the available batches and are applicable to the selected nursery
> SW-4518 Add projects dropdown to withdrawal 'purpose selection' form

- src/components/InventoryV2/InventoryCellRenderer.tsx
- tab query param has different semantics across inventory and batch detail views
- tab value for inventory is persisted/retrieved using user preference
> SW-4663 Strip tab query param from inventory links

- src/components/InventoryV2/form/AccessionsDropdown.tsx
- src/strings/csv/en.csv
If there is no species selected, or no accessions for the species we disable the dropdown.  Also added a tooltip.
> SW-4661 Disable accession dropdown on inventory add form

- src/types/Accession.ts
- src/utils/viabilityTest.tsx
- previously `nurserySubstrates` function returned those applicable to viablity tests
- this was replaced with batch substrates as part of the nursery effort
- restoring old code but as a new function so we have separation between viability test and batch substrate values
> SW-4717 Use viability test substrate values when creating a viability test

- src/components/InventoryV2/InventoryListByBatch.tsx
- src/components/InventoryV2/InventoryListByNursery.tsx
SW-4742 Do not show empty batches screen when filters are applied
Add same fix for nursery inventory
> SW-4742 Do not show empty batches screen when filters are applied

- src/components/Map/EditableMapV2.tsx
- src/components/PlantingSites/editor/Zones.tsx
- src/types/Map.ts
- cleaned this up better, leveraging one entry point to initialize popups, this removes race conditions and ambiguity
- disabled interactive layers while polygon draw is active, the interactive layers enable map clicks to return clicked-on geometries, which we don't want while polygon is being drawn
- removed a bunch of unnecessary code
- UX is cleaner now where user can click across geometries to see popup info
- see screen/video attached
> SW-4760 Redo map click handling for popup info from multiple sources

- src/App.tsx
- src/api/types/generated-schema.ts
- src/scenes/AcceleratorRouter/AcceleratorAdminView/index.tsx
- src/scenes/AcceleratorRouter/NavBar.tsx
- src/scenes/InventoryRouter/BatchHistory.tsx
- src/scenes/TerrawareRouter/NavBar.tsx
- src/services/NurseryBatchService.ts
- src/services/UserService.ts
- src/services/test/CachedUserService.test.ts
- src/strings/csv/en.csv
- src/types/User.ts
- src/utils/renderUser.tsx
- src/utils/user.ts
- Read globalRoles from 'GET /me' API call to determine if the current user is an "accelerator admin"
- Only allow users who are accelerator admins to see the new admin area
- Add side nav button in base Terraware to the accelerator admin area
- Add side nav button in accelerator admin area back to base Terraware
> SW-4709 Add side nav button between base terraware and accelerator admin area

- src/scenes/InventoryRouter/BatchSummary.tsx
- src/scenes/InventoryRouter/InventoryBatchView.tsx
- Add project update card to batch summary
- Split summary view into 4 on top and 3 on bottom
> SW-4740 Add project update card to batch summary

- src/components/PlantingSites/DetailsInputForm.tsx
- the useEffect to call the create/update code was being triggered twice
- an unused state variable was being modified within the useEffect retriggering the useEffect
- this was ironic given the state variable was unused (left over from a refactor)
- removed the state variable and retrigger
> SW-4801 Fix duplicate planting site create/update requests

- src/components/ProjectView/index.tsx
- src/hooks/useProjects.ts
- src/redux/features/projects/projectsAsyncThunks.ts
- Populate projects in state within useProjects hook if state has not been populated yet.
- Refresh projects in state when deleting a project.
> SW-4737 Populate projects in state within useProjects hook if state has not been populated yet. Refresh projects in state when deleting a project.

- src/components/Map/EditableMapDrawV2.tsx
- src/components/Map/EditableMapV2.tsx
- src/components/Map/useRenderAttributes.ts
- src/scenes/PlantingSitesRouter/DetailsInputForm.tsx
- src/scenes/PlantingSitesRouter/editor/Subzones.tsx
- src/scenes/PlantingSitesRouter/editor/Zones.tsx
- src/strings/csv/en.csv
- visually mark where invalid subzones would be created (without creating them), same flow/utility as in zone validation
- remove the clearOnEdit temporary solution now that zones/subzones have control over this data which flows top down to the draw control
- add option to set the slice tool icon (previously piggy-backed onto clearOnEdit)
- refactor DetailsInputForm to continually validate after first error on save, this was removed during a bugfix last week because it was not separated out into a separate useEffect
> SW-4790 Validate subzone minimum size contraints

- src/scenes/AccessionsRouter/viabilityTesting/NewViabilityTestModal.tsx
We were running the validation of the number of seeds tested even when editing an existing viability test which was triggering false failures.  Do not validate number of seeds in viability test after the test has been created. 
Do not allow for editing number of seeds in viability test after the test has been created.  We don't allow editing previously withdrawn quantities elsewhere in the product.
> SW-4826 Viability test fixes

- src/components/Map/MapIcon.tsx
- src/components/common/VideoDialog.tsx
- src/scenes/PlantingSitesRouter/edit/editor/Exclusions.tsx
- src/scenes/PlantingSitesRouter/edit/editor/SiteBoundary.tsx
- src/scenes/PlantingSitesRouter/edit/editor/Subzones.tsx
- src/scenes/PlantingSitesRouter/edit/editor/Zones.tsx
- use an inline style
- add some top space for icon
> Fix video modal description text style when the text is too long

- src/scenes/PlantingSitesRouter/edit/DetailsInputForm.tsx
- src/scenes/PlantingSitesRouter/view/BoundariesAndZones.tsx
- src/scenes/PlantingSitesRouter/view/GenericSiteView.tsx
- src/scenes/PlantingSitesRouter/view/PlantingSiteDetailsTable.tsx
- src/scenes/PlantingSitesRouter/view/SimplePlantingSite.tsx
- src/services/MapService.ts
- src/types/Observations.ts
- src/types/PlantingSite.ts
- src/types/Tracking.ts
- src/utils/draftPlantingSiteUtils.test.ts
- src/utils/draftPlantingSiteUtils.ts
- renamed SiteDetails to MinimalPlantingSite (capturing common properties between PlantingSite and DraftPlantingSite)
- similarly renamed zone/subzone properties
- no functional changes
> Rename types to be more descriptive

- src/components/TopBar/AcceleratorBreadcrumbs.tsx
- src/components/TopBar/TopBarContent.tsx
- src/scenes/AcceleratorRouter/NavBar.tsx
This PR includes changes to add breadcrumbs in the `TopBar` component for the Accelerator Admin Console.
Note: There isn't room to show the breadcrumbs on mobile so I opted to leave the "Back to Terraware" link for mobile devices as a quick fix. Happy to adjust this if desired.
> SW-4858: FE - Remove side nav "Terraware button" and implement breadcrumbs at top of Accelerator global header

- src/scenes/PlantingSitesRouter/edit/PlantingSiteDraftCreate.tsx
- src/scenes/PlantingSitesRouter/edit/PlantingSiteDraftEdit.tsx
- src/scenes/PlantingSitesRouter/edit/editor/Details.tsx
- src/scenes/PlantingSitesRouter/edit/editor/Editor.tsx
- src/scenes/PlantingSitesRouter/edit/editor/Exclusions.tsx
- src/scenes/PlantingSitesRouter/edit/editor/SiteBoundary.tsx
- src/scenes/PlantingSitesRouter/edit/editor/Subzones.tsx
- src/scenes/PlantingSitesRouter/edit/editor/Zones.tsx
- src/scenes/PlantingSitesRouter/edit/editor/utils.ts
- src/scenes/PlantingSitesRouter/hooks/useDraftPlantingSite.ts
- src/scenes/PlantingSitesRouter/index.tsx
- src/scenes/PlantingSitesRouter/view/PlantingSiteDraftView.tsx
- src/strings/csv/en.csv
- updated code to use new types
- cleaned up properties that weren't needed
- added a hook to fetch draft site by id (for the edit and view components)
- this is still unfinished work, need to be able to create/save a draft, in a follow up PR
> SW-4849 Use new draft planting site types in site editor

- src/scenes/PlantingSitesRouter/edit/PlantingSiteDraftEdit.tsx
- src/scenes/PlantingSitesRouter/edit/editor/Details.tsx
- src/scenes/PlantingSitesRouter/edit/editor/Editor.tsx
- src/scenes/PlantingSitesRouter/edit/editor/Exclusions.tsx
- src/scenes/PlantingSitesRouter/edit/editor/SiteBoundary.tsx
- src/scenes/PlantingSitesRouter/edit/editor/Subzones.tsx
- src/scenes/PlantingSitesRouter/edit/editor/Zones.tsx
- src/scenes/PlantingSitesRouter/edit/editor/types.ts
- src/scenes/PlantingSitesRouter/hooks/useDraftPlantingSiteCreate.ts
- src/scenes/PlantingSitesRouter/hooks/useDraftPlantingSiteGet.ts
- src/scenes/PlantingSitesRouter/hooks/useDraftPlantingSiteUpdate.ts
- src/scenes/PlantingSitesRouter/hooks/usePlantingSiteCreate.ts
- src/scenes/PlantingSitesRouter/view/PlantingSiteDraftView.tsx
- src/services/DraftPlantingSiteService.ts
- extracted out and isolated create, update logic into hooks
- leverage these hooks in the editor
- created a placeholder hook for create planting site (follow up after BE has support)
- refactored existing code a bit to remove onChange property usage
- see attached video
> SW-4868 Enable create/update of draft sites

- src/components/TopBar/TopBar.tsx
This PR includes changes to add a colored bar to the top of the Accelerator Console.
https://github.com/terraware/terraware-web/assets/1474361/24b58f23-5c5a-4e4d-a487-fd0d142baf5c
> SW-4909: Add colored bar to top of Accelerator Console

- src/components/common/FilterMultiSelectContainer/index.tsx
- src/scenes/InventoryRouter/InventoryFilter.tsx
- src/scenes/InventoryRouter/Search.tsx
- src/scenes/PlantingSitesRouter/view/PlantingSitesTable.tsx
The multi select container was set up to only use numbers (for things that are filtered by ID), this allows it to use strings if desired.
> Make it possible to use string values within the FilterMultiSelectContainer component tree

- src/components/common/SearchFiltersWrapperV2/FeaturedFilters.tsx
- src/redux/features/deliverables/deliverablesAsyncThunks.ts
- src/scenes/AcceleratorRouter/AcceleratorDeliverablesList.tsx
- src/services/DeliverablesService.ts
- src/types/Search.ts
Pass the following through into the `requestDeliverablesSearch` call from the internal deliverables table:
- Fuzzy search
- Table featured filters
- Participant dropdown filter
This just shows the `SearchNodePayload` being created
> SW-4881 Search and filtering within internal deliverables table

- src/scenes/AcceleratorRouter/CohortEditView.tsx
- src/scenes/AcceleratorRouter/CohortNewView.tsx
- src/scenes/AcceleratorRouter/index.tsx
No need to disambiguate since these views will only exist within the AcceleratorRouter. No functional changes here.
> Rename the AcceleratorCohort* views to Cohort*

- src/components/DeliverableView/Metadata.tsx
- src/services/DeliverablesService.ts
- Update mock with HTML, render HTML directly in the deliverable Metadata component
- I am using `dangerouslySetInnerHTML` here which is generally frowned upon because it potentially creates XSS vectors, but this HTML is not from user input and can be considered sanitized. This may change in the future if we enable deliverable management in the admin UI, at which point we may want to implement a library like `dompurify` or guarantee that the input is sanitized in the BE, or both.
> SW-4904 Render HTML directly in the deliverable Metadata component

- src/redux/features/deliverables/deliverablesAsyncThunks.ts
- src/redux/features/deliverables/deliverablesSlice.ts
- src/scenes/AcceleratorRouter/DeliverableViewWrapper.tsx
- src/scenes/AcceleratorRouter/useUpdateDeliverable.ts
- src/services/DeliverablesService.ts
- src/types/Deliverables.ts
- Since `status` and `internalComment` will be modified through the same API, rename everything to be field agnostic.
- Add `internalComment` to mock deliverable and update it when the update request goes through
> Change the 'update status' flow into 'update deliverable'

- src/components/DeliverableView/Metadata.tsx
- src/scenes/AcceleratorRouter/DeliverableViewWrapper.tsx
- src/scenes/AcceleratorRouter/RejectDialog.tsx
- src/strings/csv/en.csv
This PR includes changes to rename "reason" to "feedback".
**NOTE:** Current changes include updating all instances of "reason" in the UI to "feedback" and all related code. There are a couple of potential changes I could also see making but wanted to confirm first:
- Rename “Reject Reason” to “Reject Feedback”?
- Change `Deliverable.reason` to `Deliverable.feedback` in the type for `Deliverable` and related mocks? (I’m not sure if the type for `Deliverable` is already defined in the BE API, and if so, if we want to update or leave as-is.)
> SW-4938: Rename reason to feedback

- src/scenes/AcceleratorRouter/DeliverablesList.tsx
- src/scenes/DeliverablesRouter/DeliverablesList.tsx
> SW-4943 Add some spacing so that dropdown active state outline does get cutoff

- src/scenes/AcceleratorRouter/DeliverableView.tsx
- src/scenes/DeliverablesRouter/DeliverableView.tsx
This PR includes changes to fix a layout issue that resulted in the Deliverable Rejected page message showing beside the rest of the page content on browsers with higher/wider resolution.
> Fix Deliverable page message layout issue

- src/services/DeliverablesService.ts
- src/types/Search.ts
- src/utils/searchAndSort.test.ts
- src/utils/searchAndSort.ts
I did my best replicating the Search API functionality locally without sacrificing the payloads that are normally sent. This means that we don't need to change the way that the `SearchFiltersWrapper` works, even if we aren't actually using the Search API. 
I don't think this is a bulletproof implementation, and things like `Range` and `ExactOrFuzzy` aren't implemented (although the latter sounds like it would be trivial). Hopefully the test coverage is adequate to cover the most common use cases.
> Create searchAndSort function which acts as a local Search API replacement that can use the same interfaces

- src/components/DeliverableView/Metadata.tsx
This PR includes changes to remove the redundant feedback section of the Deliverable View.
> SW-4950: Remove the 'Feedback' section that is part of the metadata

- src/scenes/AcceleratorRouter/DeliverableViewWrapper.tsx
This PR includes changes to support always showing the status buttons for deliverables, while disabling the button corresponding to the current status.
> SW-4954: Show status call to action buttons all the time, grey out button that matches current status

- src/App.tsx
- src/components/TopBar/TopBarContent.tsx
- src/providers/DataTypes.ts
- src/providers/UserProvider.tsx
- src/providers/contexts.ts
- src/scenes/TerrawareRouter/NavBar.tsx
- src/types/User.ts
- src/utils/acl.test.ts
- src/utils/acl.ts
- Create mechanism for easily adding and checking ACL as it pertains to a user's global roles
- Gate the accelerator console using this ACL checker
- Remove check for organizations for accelerator so user doesn't get redirected (https://terraformation.atlassian.net/browse/SW-4948)
TODO
[x] tests for the ACL mechanism
[ ] https://github.com/terraware/terraware-web/pull/2251/files#diff-26ad4b834941d9b19ebf9db8082bd202aaf72ea0ddea85f5a8a0cb3c729cc6f2R115
[ ] https://github.com/terraware/terraware-web/pull/2251/files#diff-26ad4b834941d9b19ebf9db8082bd202aaf72ea0ddea85f5a8a0cb3c729cc6f2R83
> SW-4944 Create ACL for global roles, plumb into the UserProvider

- .prettierignore
- .prettierrc
- package.json
- yarn.lock
The PR made changes to almost every file as part of reformatting. Please take a look at `.prettierrc`, `.prettierignore`, and `package.json`.
The imports are arranged via the following order:
- react packages
- third-party packages
- third-party packages initialed with \@
- paths initialized with src/
- relative paths
> SW-3877: Added prettier plugin for sorting imports

- src/redux/features/cohorts/cohortsAsyncThunks.ts
- src/redux/features/cohorts/cohortsSelectors.ts
- src/redux/features/cohorts/cohortsSlice.ts
- src/redux/rootReducer.ts
- src/scenes/AcceleratorRouter/CohortView.tsx
- src/services/CohortService.ts
- src/types/Cohort.ts
This PR includes changes to support showing related modules in the `CohortView`.
I'm not sure if there's an existing pattern for displaying a list of values as a form field, so I went the MVP route and just joined the text to create an inline list. I imagine we'd prefer to display this in a list at the very least and I'm happy to update, but I also imagine most of what's in this PR is incorrect/temporary and will be updated so wasn't sure if I should spend the time.
> SW-4953: UI to assign cohorts to modules

- src/api/types/generated-schema.ts
- src/redux/features/globalRoles/globalRolesAsyncThunks.ts
- src/redux/features/globalRoles/globalRolesSelectors.ts
- src/redux/features/globalRoles/globalRolesSlice.ts
- src/redux/rootReducer.ts
- src/scenes/AcceleratorRouter/PeopleView.tsx
- src/services/GlobalRolesService.ts
- src/types/GlobalRoles.ts
- Add new types from global roles API from BE
- Add redux for the global roles users search and user update
- Stub out the request dispatch / select within the accelerator `PeopleView`
> SW-4961 Global roles redux and service layer

- src/components/seeds/database/index.tsx
- src/utils/requestsId.tsx
- when we first load the page and it already has filters in the url (such as when visiting from the dashboard links), there are 
a bunch of requests in-flight in succession and existing mechanism to handle races is faulty
- applying another mechanism which we use across the board, not the most elegant but it works
> SW-4959 Handle race condition in accessions search when page is loaded with filters in the url

- src/components/DeliverableView/DeliverableStatusBadge.tsx
- src/components/DeliverableView/Metadata.tsx
- src/components/DeliverablesTable/DeliverableCellRenderer.tsx
- src/components/DeliverablesTable/index.tsx
- src/redux/features/deliverables/deliverablesAsyncThunks.ts
- src/scenes/DeliverablesRouter/DeliverablesList.tsx
- src/services/DeliverablesService.ts
- src/utils/searchAndSort.test.ts
- src/utils/searchAndSort.ts
- Implement `filterModifiers` and `searchAndSort` in the `DeliverablesTable` so the consumer can add additional instructions to change the filtering and search. This allows us to modify the "participant view" of the table in a clean way without changing anything about how the "accelerator view" interacts with the table.
- Add `modifySearchNode` function that will modify a specific node within a search node tree according to instructions, allowing us to easily change things about a search out at the consumer level without putting conditional logic lower in the service layer.
- Participant view for deliverables does not show "needs translation" status (it shows as "in review), and any deliverables with that status will show up when the "in review" status filter is applied.
- Accelerator …
> SW-4873 SW-4967 Hide 'needs translation' status for participants

- src/api/types/generated-schema.ts
- src/services/DeliverablesService.ts
- projectId is back in the payload, removed from path
> Update types for deliverable document upload API and update the service call

- src/components/DeliverableView/useFetchDeliverable.ts
- src/redux/features/deliverables/deliverablesSelectors.ts
- src/redux/features/deliverables/deliverablesSlice.ts
The deliverable refresh was broken when I had to modify the fetch to use deliverableId and projectId because the flow was changed to using the asyncThunk requestId for retrieving out of state. This additionally stores the deliverable at a predictable location so consumers unaware of the request ID can be updated when the deliverable is updated in state.
> Fix deliverable refresh on update

- src/redux/features/asyncUtils.ts
- src/redux/features/deliverables/deliverablesSelectors.ts
- src/redux/features/deliverables/deliverablesSlice.ts
- Allow passing in of a composite key creator to the `buildReducers` function, which allows a slice creator to additionally store a thunk's result in state at a composite key. This allows for the `useArgAsKey` feature to work with multiple arg properties.
- Implement into the `deliverablesSlice`, storing the result at both `requestId` and `d$deliverableId-p$projectId` in state.
> Enhance useArgAsKey functionality for composite keys

- src/components/TopBar/AcceleratorBreadcrumbs.tsx
- src/components/TopBar/TopBarContent.tsx
- src/hooks/useAcceleratorConsole.ts
- src/scenes/OrgRouter/NavBar.tsx
- src/strings/csv/en.csv
- Move link to accelerator to top bar breadcrumbs
- Rename 'Participants' to 'Accelerator'
- Rename 'Accelerator Admin' to 'Accelerator Console'
- Remove 'accelerator admin' from strings
- Leaving 'Participants' in strings because we are using it later
> SW-5026 Admin -> Console, move link to top bar

- src/scenes/AccessionsRouter/edit/EditState.tsx
Previously there would be a large blank space saved in this modal in case the user updated the status.
> SW-2359 Remove extra space in accession change modal

- src/components/AddNewOrganizationModal.tsx
- src/scenes/InventoryRouter/form/useAccessions.ts
Previously the selected accession would stay unchanged leading to incorrect withdrawal behaviors
> SW-4683 Reset selected accession when species changes

- src/components/AddNewOrganizationModal.tsx
Previously if you were on a different page prior to creating an org the banner would not show up because it the redirect would happen after the banner was drawn.
> SW-4529 Show org creation success banner after page change

- src/scenes/AccessionsRouter/Accession2View.tsx
Since performing a viability test does a withdrawal, we need to have a positive quantity or estimated quantity in order to add a test.
> SW-4916 Require accession quantity to do a viability test

- src/components/DeliverablesTable/index.tsx
- updated to `projectName` from `project_name`
- the search results are still fuzzy, not sure if the jira ticket will be addressed completely
> SW-5054 Update project name property in search fields

- src/components/DeliverableView/InternalComment.tsx
- src/components/DeliverableView/Metadata.tsx
- moved text below the heading
- using text area to show paragraphs
> SW-5052 Deliverables Internal Comments layout changes

- nginx/default.conf.template
We need to support uploads of larger deliverable documents, e.g., zipfiles with
collections of smaller files. Increase the request size limit to 200MB.
> SW-5059 Increase request size limit to 200MB

- package.json
- src/components/DeliverableView/DocumentsUploader.tsx
- yarn.lock
We don't want to restrict which types of files users can send us
for document deliverables. Remove the restricted list of MIME types
on the file chooser.
> SW-5066 Allow all file types in document upload

- package.json
- src/components/TopBar/AcceleratorBreadcrumbs.tsx
- src/components/TopBar/TopBarContent.tsx
- yarn.lock
- Use default Separator height (32px)
- Change color for logo separator to `tw-clr-brdr-tertiary`
> SW-5026 Fix separator height and color

- src/api/types/generated-schema.ts
- src/redux/features/votes/votesAsyncThunks.ts
- src/scenes/AcceleratorRouter/Voting/VotingProvider.tsx
- src/services/HttpService.ts
- src/services/VotesService.ts
- src/types/Votes.ts
Screenshots: 
Steps to test out screen:
1. Create users to be voters (or use existing users). Make sure you know their `id`.
2. Create project and add project to a participant. Make sure participant's cohort is in Phase 1
3. In the `project_votes` table, add (project, phase, user) entry.
4. Then, the `/accelerator/projects/{project_id}/votes` endpoint should show the voters. Edit their option and hit submit.
> SW-5053 Updated voting screens to use API data 

- src/scenes/AcceleratorRouter/Scoring/PhaseScores/LastUpdated.tsx
- src/scenes/AcceleratorRouter/Scoring/PhaseScores/index.tsx
> SW-5091 Fix the vertical sizing of the phase score header when there isn't a 'modifiedTime'

- src/components/DeliverablesTable/index.tsx
This PR includes a fix for an issue that resulted in an incorrect label value for the projects filter pill in the deliverables list table.
> SW-5095: Deliverables list table projects filter pill label is incorrect

- src/hooks/useAcceleratorOrgs.ts
- src/hooks/useCohorts.ts
- src/hooks/useParticipants.ts
- src/redux/features/cohorts/cohortsSelectors.ts
- src/scenes/AcceleratorRouter/Participants/OrgProjectsSectionEdit.tsx
- src/scenes/AcceleratorRouter/Participants/ParticipantForm.tsx
- src/scenes/AcceleratorRouter/Participants/ParticipantsList.tsx
- src/scenes/AcceleratorRouter/Participants/ParticipantsNew.tsx
- src/strings/csv/en.csv
- added 'Add Participant' action menu in participants list (for non-empty state)
- added hooks to fetch cohorts and accelerator orgs
- added ParticipantForm (leveraged CohortForm as a template)
- implemented the sections for org/projects selection
- plumbed save back to ParticipantsNew component
- ParticipantForm can be reused for edit Participant
- TODO: sync with BE types when ready (follow up)
- TODO: add permission checks in the UI (follow up)
> SW-5086 Add participant workflow with mock data

- src/scenes/AcceleratorRouter/Cohorts/CohortListView.tsx
- src/scenes/AcceleratorRouter/index.tsx
- kept the nav since Overview nav was always being shown
- also fixed the + Add Cohort button which was allocated less space
> SW-5111 Gate overview/people views with 'Console' flag

- src/scenes/AcceleratorRouter/Participants/DownloadParticipants.tsx
- src/scenes/AcceleratorRouter/Participants/ParticipantsList.tsx
- src/services/ParticipantsService.ts
- created a download service function currently serving mock data, to be integrated with BE at some point
- Mostly boiler plate code to show the export modal and plumb it through ParticipantsService.download
> SW-5088 Export participants list with mock data

- src/api/types/generated-schema.ts
- src/hooks/useAcceleratorOrgs.ts
- src/redux/features/accelerator/acceleratorAsyncThunks.ts
- src/scenes/AcceleratorRouter/Participants/OrgProjectsSectionEdit.tsx
- src/scenes/AcceleratorRouter/Participants/ParticipantForm.tsx
- src/services/AcceleratorService.ts
- src/types/Accelerator.ts
- src/types/Organization.ts
- updated with BE PR branch 'accel-org'
- org role property in org payload is now optional, updated code to handle that
- updated accelerator org service/redux and participant form to use updated properties
- this will need to go in after BE PR is merged
screenshot with real data
> SW-5110 Update accelerator org service and components to use new types

- src/scenes/Species/SpeciesListView.tsx
- src/scenes/Species/index.tsx
- search was also populating filters and showing the spinner for a tiny fraction of a second, causing the flashing
- we don't need to show a spinner for these quick searches to populate filters, removed that spinner
- also fixed the flashing of empty state before we get species data
> SW-5120 Fix flashing of app when searching for species

- src/scenes/AcceleratorRouter/Overview/index.tsx
- src/utils/useStickyTabs.ts
- Tab state is stored in the hook
- Exposes a function to pass into the tabs when the tab changes, along with the active tab
- Stores the last viewed tab in session storage
- If the tabbed view is entered without a tab, we first try to use  the tab stored in session, otherwise fall back to the default tab passed in to the hook.
> SW-4982 Create hook for centralizing "sticky tabs" logic

- src/scenes/AcceleratorRouter/Cohorts/CohortForm.tsx
- src/scenes/AcceleratorRouter/Cohorts/CohortView.tsx
This PR removes commented meta info components that show created & modified times from Cohort views, as Product confirmed they were not included in the PRD and are not required for MVP.
> SW-5121: FE - Uncomment meta info in Cohorts Views when createdTime & modifiedTime are available from BE

- src/scenes/AcceleratorRouter/Cohorts/CohortView.tsx
This PR includes a fix for an incorrect breadcrumb link in the Cohort View.
Just realized I missed this when moving Cohorts into the tabbed views on the Overview page.
> Fix Cohorts breadcrumb link

- src/utils/search.test.ts
- src/utils/search.ts
- src/utils/searchAndSort.ts
For testing `searchAndSort`, I navigated to deliverables. Searching for `company formation` includes matches with `information` as expected with Fuzzy search functions. With double quotes `"company formation"`, only `company formation document` is returned.
> SW-5140 Added double-quotations for Phrase Match search

- package.json
- yarn.lock
This PR adds a package resolution for `@babel/traverse` @ `7.24.1` to resolve a [critical vulnerability](https://github.com/terraware/terraware-web/security/dependabot/64).
I attempted to manually update any packages that depended on an older version but there are many packages that required updating including multiple packages for both babel & storybook. Didn't want to go down a rabbit hold with updating too many dependencies, but will re-visit if we think it's necessary. I decided to check the changelog for breaking changes and didn't find any between the oldest and latest versions of `@babel/traverse` being used (`7.1.6` & `7.24.1`). Since there are no breaking changes adding this package resolution should be safe.
Happy to re-visit updating all packages that depend on …
> Add package resolution for @babel/traverse @ 7.24.1

- package.json
- yarn.lock
Looks like the dep tree was `react-scripts` -> `webpack-dev-server` -> `webpack-dev-middleware`. We are currently at the latest version for `react-scripts`, so I added `webpack-dev-middleware` as a dev dependency and bumped the version to `^5.3.4` (next acceptable minor version from the [vulnerability report]())
> Upgrade webpack-dev-middleware to ^5.3.4 per CVE-2024-29180

- src/api/types/generated-schema.ts
- src/scenes/AcceleratorRouter/ParticipantProjects/ParticipantProjectProvider.tsx
- src/scenes/AcceleratorRouter/ParticipantProjects/index.tsx
- src/scenes/AcceleratorRouter/Voting/VotingProvider.tsx
- src/scenes/AcceleratorRouter/Voting/index.tsx
- The `VotingProvider` forwards back to the projects page if the votes that come back from the voting API don't match up with the "default" Phase (phase 1). 
- Use the project's `cohortPhase` as the next fallback in the provider if there is no `phase` query param.
- Wrap the usages of the `VotingProvider` with the `ProjectProvider`
> Use the project's cohort phase to determine the active votes

- src/scenes/AcceleratorRouter/Participants/ParticipantForm.tsx
- If the list of unassociated accelerator org/projects are [{org: ABC, projects: [DEF]}]
- and
- If the participant had an org/project association [{org: ABC, projects: [XYZ]}, {org: ...}]
- we merged the ABC org's projects list to contain both DEF and XYZ (for the multiselect)
- The projects array from redux is immutable, hence the crash (and also not wise to edit redux store data)
- Updated code to make a copy instead.
Original error:
```
Cannot add property 1, object is not extensible
at Array.push (<anonymous>)
at ParticipantForm.tsx:65:29
```
> SW-5145 Fix participants edit crash

- src/scenes/AccessionsRouter/edit/QuantityModal.tsx
- description should not be initialized to any existing value, should be empty by default
- intention is to capture 'quantity changed' description when quantity changes
- was erroneously initialized to the 'notes' values (plant description), result of copy/pasta, leading to some ux issues
- edit/save and history values still work as expected
> SW-5144 Fix initial value for accession remaining quantity changed description text

- src/components/ProjectNewView/flow/SelectBatches.tsx
- src/components/ProjectNewView/flow/SelectPlantingSites.tsx
- src/components/TableWithSearchFilters/index.tsx
- src/components/common/FilterGroup/filters/FilterSearch.tsx
- src/scenes/InventoryRouter/view/InventorySeedlingsTableForNursery.tsx
- src/scenes/InventoryRouter/view/InventorySeedlingsTableForSpecies.tsx
- src/scenes/NurseryRouter/NurseryWithdrawalsTable.tsx
- src/scenes/PeopleRouter/PeopleListView.tsx
- src/scenes/Species/SpeciesListView.tsx
- src/services/FacilityService.ts
- src/services/NurseryBatchService.ts
- src/services/NurseryInventoryService.ts
- src/services/ProjectsService.ts
- src/services/SearchService.ts
- src/services/SpeciesService.ts
- src/types/Search.ts
- src/utils/search.ts
Every instance we have a searchbox, where user can specify an input. We will try to `removeDoubleQuotes` and use PhraseMatching. Most file changed here are just wholesale changes to implement this behavior.
> SW-5142 Parsed search terms to use PhraseMatch when double-quoted

- src/providers/Project/ProjectProvider.tsx
- there was a race condition where the project id is -1 and then a valid value, the voting provider fetches votes for project -1 and fails on subsequent views
- On first visit vote request for -1 and actually project both have network latency and we had enough time to transition from project id -1 to valid project id
- On subsequent visits, the result for project id -1 votes is already in redux store and is processed right away before the transition to real project id
- added a guard in the project provider to wait until we have a valid project
- added another redirect guard in case someone actually visits a project id of -1 in the url (so we aren't spinning forever)
- tested ok for first and subsequent views (assumption here is there really are votes in the db)
- Note: I had initially …
> SW-5159 Fix participant project view redirecting back to participant project list even when there are votes

- src/components/common/SearchFiltersWrapperV2/FeaturedFilters.tsx
- apply the generator on relevant filter only
- other filters will keep their existing search node payloads
> SW-5126 Fix use of featured filter's search node payload generator

- src/redux/features/scores/scoresSelectors.ts
- src/scenes/AcceleratorRouter/Scoring/EditView.tsx
- src/scenes/AcceleratorRouter/Scoring/ScoresView.tsx
- src/scenes/AcceleratorRouter/Scoring/ScoringContext.tsx
- src/scenes/AcceleratorRouter/Scoring/ScoringProvider.tsx
- src/scenes/AcceleratorRouter/Scoring/useScoresUpdate.ts
- added a `hasData` property on the context which checks if there is data
- in read-only view, redirect to edit if there is no data
- in edit-view, redirect to project details on cancel if there is no data (to avoid ending up back in edit view)
- since we need to deterministically identify if there is no data, added blocking checks in the update code to wait until the refresh list completes
- this is a tad ugly but needed, otherwise redirecting back to read-only view after save will only end up back in edit view (hasData hasn't had a chance to update)
- also fixed bug 5169 where a new score entry only keeps the latest edit (was using originalScore as copy instead of updated score), fixed that
> SW-5152 / SW-5169 Redirect to score edit if there is no scores/qualitative data

- src/components/Page/index.tsx
- src/components/common/PageWithModuleTimeline/index.tsx
- src/components/common/TfMain.tsx
- The TfMain construction padding was reduced, to be consistent with other crumb layout views
- A cleaner option would be to support the timeline equivalent layout within the Page component as it assumes that TfMain is the root level component of the page
- I can take a look at that later
> SW-5163 Fix top/left padding on page with module timeline

- src/components/ParticipantsDropdown/index.tsx
- src/scenes/AcceleratorRouter/Deliverables/DeliverablesList.tsx
- src/services/ParticipantsService.ts
-  Cast the search result IDs to numbers 
- Changing the dropdown to reference the record's `id` instead of `participantId` because that is the property on the participant record
> SW-5147 Fix participant dropdown

- src/services/NurseryWithdrawalService.ts
When withdrawnDate of different withdrawals is the same, order them by createdTime as second parameter, so we can show most recent withdrawals in the top
> SW-4787 Fix withdrawals date sorting

- src/services/NurseryBatchService.ts
Withdrawn column was not populated because we were not requiring the value in the search request
>  SW-5186 Batches at Nursery table view: Withdrawn column is not populated

- package.json
- yarn.lock
> SW-4795 Bump web-components version to correctly show right-aligned table headers

- src/components/BatchWithdrawFlow/flow/WithdrawalBatchesCellRenderer.tsx
Align inputs to the right in right-aligned columns, and also text inside input:
> SW-4795 Fix withdrawal tables right alignments

- src/scenes/AccessionsRouter/edit/Accession2EditModal.tsx
- src/scenes/AccessionsRouter/view/DetailPanel.tsx
- we were using three different labels, reconciled them to use same label (as per latest requirements)
- we do have 2 unused labels at this point
> SW-5176 Reconcile 'accession collecting site' labels across create/edit/view flows

- src/scenes/AcceleratorRouter/ParticipantProjects/EditView/index.tsx
- src/scenes/AcceleratorRouter/ParticipantProjects/SingleView.tsx
This PR removes the Deal Stage field from the Participant Project View & Edit Views, per a request from Jennifer. See [Jira ticket](https://terraformation.atlassian.net/browse/SW-5175) comments for more info.
> SW-5175: Project: Deal Stage field should show "Phase 1" instead of N/A

- src/scenes/AcceleratorRouter/ParticipantProjects/CellRenderer.tsx
- src/scenes/AcceleratorRouter/ParticipantProjects/ListView.tsx
- src/services/ParticipantProjectService.ts
- src/types/ParticipantProject.ts
This PR includes changes to fix the crash that was occurring when sorting by column in the Console Overview Projects table.
I removed some mapping that looked like it was in-place to replace long/awkward keys and possibly reduce the differences between `ParticipantProject` and `ParticipantProjectSearchResult`, but that mapping seemed to be what was causing the crash as the updated field names weren't recognized by the BE when performing the sort function.
I'm not sure if there was another way to fix this crash without removing the mapping, but I'm happy to make changes if there's another way we'd prefer to approach this issue.
https://github.com/terraware/terraware-web/assets/1474361/f64b3a72-bbd9-4ff3-a28c-402e1eb9d1c5
https://github.com/terraware/terraware-web/assets/1474361/10047fc1-b38 …
> SW-5191: Sorting Project tables in Console Overview crashes

- src/providers/Participant/ParticipantContext.tsx
- src/providers/Participant/ParticipantProvider.tsx
- src/scenes/Home/index.tsx
- src/scenes/OrgRouter/index.tsx
- Create `ParticipantProvider` used in the Terraware frontend for retrieving participant data for an org
- Use it to determine if a user should see the regular Home page or the Participant Home page
> SW-5122 Create ParticipantProvider

- src/components/common/table/index.tsx
- previously the preference name was `<table-id>-columns`
- this was problematic if 
1) two tables shared the same id (which is currently not prevented at compile or run time), if one of those tables had its columns shuffled, the value of the order would be picked up by the other table, which would end up rendering incorrect columns
2) another failed case is if one of the table's had it's columns refactored/updated and was previously shuffled by the user.. it would end up rendering incorrect/stale columns
- the new approach now generates the preference name based on the table's column names
- this protects from rendering incorrect data for either of the cases described above
- if a table had it's columns refactored (added/removed, etc.) the table would now use a new preference name
- if 2 …
> SW-4591 Update OrderPreservedTable user preference name that stores columns ordering when shuffled by user

- src/components/BatchWithdrawFlow/flow/SelectPurposeForm.tsx
- there are 2 dates in this flow, 'withdrawnDate' and 'readyByDate'
- common date validation for both these dates was preventing future dates
- the future date check only applies to 'withdrawnDate', whereas 'readyByDate' can be in the future and most likely will
- updated validation code to support a 'allowFutureDates' option, set option to true for 'readyByDate'
> SW-5225 Fix date validation for 'readyByDate' in nursery transfer withdrawals

- src/scenes/NurseryRouter/WithdrawalLogRenderer.tsx
In withdrawal log, undone withdrawals need to be crossed off, instead of withdrawals with purpose "undo"
> SW-5193 crossed off undone withdrawals

- src/redux/features/accelerator/acceleratorSlice.ts
- src/redux/features/accessions/accessionsSlice.ts
- src/redux/features/appVersion/appVersionSlice.ts
- src/redux/features/batches/batchesSlice.ts
- src/redux/features/cohorts/cohortsSlice.ts
- src/redux/features/deliverables/deliverablesSlice.ts
- src/redux/features/draftPlantingSite/draftPlantingSiteSlice.ts
- src/redux/features/globalRoles/globalRolesSlice.ts
- src/redux/features/message/messageSlice.ts
- src/redux/features/modules/modulesSlice.ts
- src/redux/features/observations/observationsSlice.ts
- src/redux/features/participantProjects/participantProjectsSlice.ts
- src/redux/features/participants/participantsSlice.ts
- src/redux/features/plantings/plantingsSlice.ts
- src/redux/features/projects/projectsSlice.ts
- src/redux/features/reportsSettings/reportsSettingsSlice.ts
- src/redux/features/scores/scoresSlice.ts
- src/redux/features/snackbar/snackbarSlice.ts
- src/redux/features/species/index.ts
- src/redux/features/subLocations/subLocationsSlice.ts
- src/redux/features/tracking/trackingSlice.ts
- src/redux/features/user/userAnalyticsSlice.ts
- src/redux/features/user/usersSlice.ts
- src/redux/features/votes/votesSlice.ts
- src/redux/rootReducer.ts
- export reducers from the xyzSlice files
- xyzSlice files will now own semantics of redux store key names
- rootReducer will simply import and spread the reducers, no context of redux store key names
- typescript will handle key errors so we are good there
> SW-5194 Clean up redux/rootReducer

- src/components/TopBar/AcceleratorBreadcrumbs.tsx
- adjusted the line height for the link
> SW-5267 Fix horizontal alignment of accelerator console link

- src/types/Species.ts
This was already done, it was not working maybe because the error message changed
> SW-4594 Display error for duplicate species addition

- src/scenes/InventoryRouter/InventoryBatchView.tsx
This PR includes a small change to always show the "Withdraw" button in the Batch detail view as long as there is a non-zero quantity.
> SW-5222: Batch detail view should have withdraw button as long as there is a non-zero quantity

- playwright/e2e/suites/inventory.spec.ts
- src/scenes/NurseryRouter/NurseryReassignmentView.tsx
- src/scenes/NurseryRouter/NurseryWithdrawals.tsx
- src/scenes/NurseryRouter/NurseryWithdrawalsDetailsView.tsx
- src/strings/csv/en.csv
- src/strings/csv/es.csv
This PR includes a quick fix to update "Withdrawal Log" to "Withdrawal History".
> SW-5239: Withdrawals: List View is titled "Withdrawal History" but breadcrumb says "Withdrawal Log"

- src/features.ts
- src/services/SpeciesService.ts
- src/types/Species.ts
This PR adds mocked data to species in the `getSpecies` and `getAllSpecies` methods of the `SpeciesService`. The mocked data includes new additional fields to support species deliverables. The mocked data is only appended when a new "Mocked Species" feature flag is enabled.
I'm sure the new property names added to `Species` aren't quite right, will get these updated as soon as we know what they will be on the BE.
> SW-5276: FE: Setup mock data for new species

- src/redux/features/participantProjectSpecies/participantProjectSpeciesSelectors.ts
- src/redux/features/participantProjectSpecies/participantProjectSpeciesSlice.ts
- Tell the `buildReducers` redux util to use the passed in project ID as the key for selecting the results from state
> Fix reducers for listing participant project species

- playwright/e2e/suites/species.spec.ts
- src/api/types/generated-schema.ts
- src/features.ts
- src/scenes/Species/SpeciesAddView.tsx
- src/scenes/Species/SpeciesDetailView.tsx
- src/scenes/Species/SpeciesDetailsForm.tsx
- src/services/SpeciesService.ts
- src/types/Species.ts
- Sync with backend types that have the new fields that were mocked
- ~Remove opt-in flag for mocked data~ leaving this for now since we are using the flag to show mocked deliverable data
Depends on `terraware-server` PR  https://github.com/terraware/terraware-server/pull/1893
> SW-5280 Sync with BE that has other new species fields

- src/providers/Participant/ParticipantProvider.tsx
- src/redux/features/modules/modulesSelectors.ts
- src/redux/features/participants/participantsAsyncThunks.ts
- src/redux/features/participants/participantsSlice.ts
- src/services/ParticipantsService.ts
Also removed Participant with Current Module since active module ID is not part of participant data and going forward we may need to support multiple active modules.
> SW-5234 Used cached selector for active modules to not cause infinite renders

- src/api/types/generated-schema.ts
- src/components/SpeciesDeliverableTable/AddSpeciesModal.tsx
- src/components/SpeciesDeliverableTable/EditSpeciesModal.tsx
- src/components/SpeciesDeliverableTable/RemoveSpeciesDialog.tsx
- src/components/SpeciesDeliverableTable/index.tsx
- src/redux/features/participantProjectSpecies/participantProjectSpeciesAsyncThunks.ts
- src/redux/features/participantProjectSpecies/participantProjectSpeciesSelectors.ts
- src/redux/features/participantProjectSpecies/participantProjectSpeciesSlice.ts
- src/scenes/DeliverablesRouter/SpeciesDeliverableStatusMessage.tsx
- src/scenes/DeliverablesRouter/SpeciesDeliverableView.tsx
- src/services/ParticipantProjectSpeciesService.ts
- src/types/Deliverables.ts
- Sync with BE types for new Participant Project Species APIs
- Update all redux, services, components, etc... with backend types
Dependent on this `terraware-server` stack https://github.com/terraware/terraware-server/pull/1937
> Sync with BE types for new Participant Project Species APIs

- src/components/DeliverableView/DeliverableStatusBadge.tsx
- src/scenes/DeliverablesRouter/RejectedDeliverableMessage.tsx
- src/strings/csv/en.csv
- src/types/Deliverables.ts
This PR includes changes to update the deliverable status label from "Rejected" to "Not Accepted" for participant users.
> SW-5339: Deliverables: Status - change "Rejected" to "Not Accepted"

- package.json
- yarn.lock
This is a quick PR to bump the version of `web-components` to pickup recent style changes.
> Bump web-components to pickup style changes

- src/scenes/Species/SpeciesDetailView.tsx
- src/scenes/Species/SpeciesDetailsForm.tsx
- src/scenes/Species/SpeciesListView.tsx
For non participants, hide projects column and featured filter in species list view, and hide the projects table in the species detail and edit views
> Hide projects related features for non participants

- package.json
- yarn.lock
A quick PR to bump the package version of `web-components` to pickup changes.
> Bump web-components package version to pickup changes

- src/services/ParticipantProjectSpeciesService.ts
- src/types/Deliverables.ts
- Use the Search API to get the participant project species through the project deliverables prefix so we can get the deliverable, project, and species data in one call.
> Use the search API to get deliverable info about participant project species

- src/components/common/TextWithLink.tsx
- src/scenes/ContactUs/index.tsx
TextWithLink with external links was broken.  Update it so that it uses MuiLink rather than the React router link in order to properly handle external links
> SW-5384 Make TextWithLink work with external links

- playwright/e2e/suites/accession.spec.ts
- src/scenes/AccessionsRouter/Accession2CreateView.tsx
- src/scenes/AccessionsRouter/edit/Accession2EditModal.tsx
- src/scenes/AccessionsRouter/properties/CollectionSiteName.tsx
- src/services/SeedBankService.ts
This PR changes the Collection Site Name field for Accessions, from a standard textfield to a textfield with a dropdown of previously entered values.
> SW-5074: Accessions: Collection Site dropdown menu

- src/components/SpeciesDeliverableTable/index.tsx
This PR includes a change to disable the "Add Species to Project" button in the `SpeciesDeliverableTable`, if the deliverable is not "current".
> SW-5428: Saving while adding Project to species fails with 404

- src/components/ProjectField/TextAreaDisplay.tsx
Grid entry wrapper requires a height.  Use a regular Grid item instead with a minHeight to ensure we can grow vertically with additional text
> SW-5470 Don't overflow container if text is too long

- src/scenes/Species/SpeciesProjectsTable.tsx
This PR includes changes to disable the "Add to Project" button in the Species Add/Edit views.
> SW-5428: Saving while adding Project to species fails with 404 (#2)

- src/scenes/Home/ParticipantHomeView/ToDoCta.tsx
- src/scenes/ModulesRouter/CurrentTimeline.tsx
- src/scenes/ModulesRouter/ListModulesContent.tsx
- src/scenes/ModulesRouter/ModuleEntry.tsx
Changes:
1) Use secondary button color
2) Module Timeline mobile + tablet breakpoints: 
3) Module list view breakpoints
> SW-5419 Mobile UX improvements for Module lists

- src/scenes/ContactUsRouter/AttachmentRow.tsx
<div class='graphite__hidden'>
<div>🎥 Video uploaded on Graphite:</div>
<a href="https://app.graphite.dev/media/video/NOxkRPuhAfT4F7nmdXtG/1960ff05-bb8c-479e-9b47-fc3103165ad0.mov">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/NOxkRPuhAfT4F7nmdXtG/1960ff05-bb8c-479e-9b47-fc3103165ad0.mov">Screen Recording 2024-06-04 at 1.54.38 PM.mov</video>
Issue was previously caused by useEffect and onChange causing an infinite re-render loop, since onChange will modify the attachment status, and useEffect gets called in an AttachmentRow.
Also fixed an issue on small screen, where an attachment button is taking up all the space.
> SW-5477 Fixed scroll bounce on Support Forms

- src/services/NurseryBatchService.ts
- src/utils/search.ts
If the user enters an exact batch number or species name in the nursery inventory
batches view, only show the batch with that exact number, the same way we do with
accession numbers on the accessions page.
> SW-4682 Use exact-or-fuzzy search for batch numbers

- src/api/types/generated-schema.ts
- src/redux/features/user/usersAsyncThunks.ts
- src/services/PreferencesService.ts
- src/services/UserService.ts
This PR includes changes to support getting/setting the current user's cookie consent preferences.
**NOTE:** Cookie consent preference is returned as properties of the user object, so all that was required to get the user's cookie consent preference was to update the `getUser` method to include the new properties. We also need a way to set the user's cookie consent preference, so changes are included to support that.
> SW-5502: FE - Create utility to check users consent status

- src/components/seeds/database/EditColumns.tsx
- src/components/seeds/database/TableCellRenderer.tsx
- src/components/seeds/database/columns.ts
- src/components/seeds/database/index.tsx
Allow users to add a "Latitude, Longitude" column to the accessions table to show
the list of GPS coordinates from the seed collection. This column will appear in
exported CSV files, with newline-separated values in the case of multiple
coordinates for an accession.
> SW-5437 Add accession GPS coordinates to table view

- src/scenes/AcceleratorRouter/index.tsx
The router path needs to be a catchall in order to work correctly with nested `Route`s.
> Fix the router path used for the document producer

- src/components/ProjectField/TextAreaDisplay.tsx
Display explicit line breaks in participant project profile textarea
fields so multi-paragraph values aren't folded into a single long
paragraph.
Wrap long words (URLs, etc.) to prevent them from overflowing into
other parts of the UI.
> SW-5528, SW-5529 Line breaks in profile fields

- src/scenes/DeliverablesRouter/SpeciesDeliverableStatusMessage.tsx
This PR includes a change to display feedback for rejected species within a species deliverable list, when available.
> SW-5535: Feedback for Rejected species does not display

- src/components/SpeciesDeliverableTable/AddSpeciesModal.tsx
This PR includes changes to ensure the native field is required in the add species modal, as well as updates to improve the error UX for other form fields.
> SW-5539: Native/Non-Native is marked required but adding a species without a value is allowed

- src/scenes/Species/SpeciesProjectsTable.tsx
This PR includes changes to resolve an issue that was preventing adding a species to a project from the species detail view.
Context: The previously available projects included projects without a species deliverable, but that is a requirement from the API when adding a species to a project.
> SW-5533: Can't add Species to Project (from Species page) even when Deliverable is active

- src/components/DeliverablesTable/index.tsx
This PR includes a fix for the projects filter not working in the deliverables table for the accelerator console.
> SW-5541: Filtering for AC Deliverables table not working properly

- src/components/SpeciesDeliverableTable/EditSpeciesModal.tsx
- src/scenes/Species/AddToProjectModal.tsx
I missed a couple of instances in my initial PR to resolve this issue, this PR includes changes to cover those additional instances.
There's one additional change included to only display the bottom border separator when there's more than one entry.
> SW-5539: Native/Non-Native is marked required but adding a species without a value is allowed (follow-up)

- src/scenes/AcceleratorRouter/Deliverables/DocumentDeliverableView.tsx
The deliverable was refreshed correctly, but actions where inside useMemo without the correct dependency array
> SW-5545 Document deliverable approve button should be disabled immediately after approving

- src/components/SpeciesDeliverableTable/TableCellRenderer.tsx
This PR includes a fix to disable Approve/Reject buttons when a species deliverable has already been approved/rejected.
> SW-5543: Approve/Reject... buttons states not affected by species status

- src/scenes/Species/SpeciesProjectsTable.tsx
Reverts terraware/terraware-web#2757. The referenced PR seems to have reduced the list of projects available in the projects filter dropdown to a subset that is missing options.
> Revert "SW-5533: Can't add Species to Project (from Species page) even when Deliverable is active"

- package.json
- yarn.lock
This PR updates `web-components` to pickup a [fix](https://github.com/terraware/web-components/pull/610) for an issue where the `DialogBox` component was stopping click event propagation which was preventing the `Dropdown` component from functioning correctly when rendering within the `DialogBox` component.
> SW-5532: Can't click out of native/non-native dropdown without selecting an option first

- package.json
- yarn.lock
This PR updates `web-components` to pickup changes to the `Badge` component to allow nesting within paragraphs.
Currently in `terraware-web` there are two very large warnings that take up most of the console, these changes will resolve those warnings and clean up the console.
> Fix invalid DOM nesting warnings in console

- src/redux/features/documentProducer/values/valuesSlice.ts
- src/redux/features/documentProducer/values/valuesThunks.ts
- src/redux/features/documentProducer/variables/variablesSelector.ts
- src/redux/features/documentProducer/variables/variablesSlice.ts
- src/redux/features/documentProducer/variables/variablesThunks.ts
- src/scenes/DeliverablesRouter/QuestionsDeliverableView.tsx
- src/services/documentProducer/ValueService.ts
- src/services/documentProducer/VariableService.ts
- src/types/documentProducer/Variable.ts
- I plumbed it into the `QuestionsDeliverableView`
- The two requests are dispatched separately and are stitched together with a cached selector. This is generally how we should be selecting this stuff since there are some functions that combine the two, which (I believe) all the components that consume this data are expecting.
> Add cached selector for fetching deliverable-specific variables and values for a given project

- src/api/types/generated-schema.ts
- src/types/documentProducer/VariableValue.ts
We have recently removed some API endpoints on the server side; update the
generated types on the client side to reflect those removals.
> Update generated types to reflect endpoint removals

- README.md
- dump/README.md
- package.json
- remote-backend/README.md
- scripts/launch_server.sh
- scripts/preparedb.sh
- scripts/resetdb.sh
This PR migrates the repo to Docker Compose v2 for compatibility with the latest version of Docker Desktop `4.32.0`:
- Replace `docker-compose` with `docker compose`
**Background:**
After upgrading to the latest version of Docker Desktop `4.32.0` (`157355`) today, when I attempted to run `docker-compose up -d` I ran into the following error: `zsh: command not found: docker-compose`.
Dropping the dash from `docker-compose` resolves the issue.
> Migrate to Docker Compose v2

- src/components/DocumentProducer/DeliverableVariableDetailsInput/index.tsx
- src/components/DocumentProducer/VariableDetailsInput/index.tsx
This PR fixes an issue that resulted in text fields not rendering for text variables with no value yet.
> Fix text variables not rendering text fields when editing Questions Deliverable

- src/scenes/AcceleratorRouter/Documents/DocumentView/DocumentVariablesTab.tsx
- Fix the instance count for variables within the document
- Remove component state for sections since they are handled by 'document variables' now
> Fix the instance count for variables within the document

- src/scenes/DeliverablesRouter/QuestionsDeliverableEditView.tsx
This PR includes changes to adjust the vertical spacing between questions in the Questions Deliverable Edit View, to align with [designs](https://www.figma.com/design/zmJYSYt317qXCMUNaLvjxW/Deliverable---Questionnaire?node-id=4200-139562&t=raRwXX0Wize9bMJk-0).
> SW-5687: Spacing in edit view of Questionnaire deliverable is off

- src/scenes/AcceleratorRouter/Deliverables/QuestionsDeliverableView.tsx
This PR fixes an issue where edit mode would become disabled when the mouse is not hovering over the question.
> SW-5692: Edit mode in Console should stay open even if the user removes the hover

- src/scenes/AcceleratorRouter/Deliverables/RejectDialog.tsx
This PR includes a change to make the feedback text field required in the dialog when rejecting a variable.
> SW-5694: Display required * for Feedback when rejecting a variable

- src/scenes/DeliverablesRouter/QuestionsDeliverableEditView.tsx
- src/scenes/DeliverablesRouter/QuestionsDeliverableView.tsx
This PR includes changes to resolve an issue that caused the Questions Deliverable Edit View to always auto-scroll, regardless of how much of the view has been viewed/scrolled.
Changes include:
- Only auto-scroll when the document is scrolled beyond the viewport height
- Remove default option values for `element.scrollIntoView` method (they were previously included unnecessarily)
> SW-5689: Auto scrolls down when going to edit view from Participant View

- src/scenes/AcceleratorRouter/Deliverables/QuestionsDeliverableView.tsx
This PR includes a fix for an issue that caused Questionnaire Deliverable question status updates to require a manual page refresh to reflect the updated status.
> SW-5688: Have to refresh to see status update in Console (and feedback when applicable)

- src/components/DocumentProducer/DeliverableVariableDetailsInput/index.tsx
- src/scenes/DeliverablesRouter/QuestionsDeliverableEditView.tsx
- src/scenes/DeliverablesRouter/QuestionsDeliverableView.tsx
This PR includes changes to show status badges on the participant side of questionnaire deliverables.
> Show status badges on the participant side of questionnaire deliverables

- public/preview.css
- public/preview.html
- src/scenes/AcceleratorRouter/Documents/PreviewView/PreviewDocument.tsx
- src/scenes/AcceleratorRouter/Documents/PreviewView/PreviewSection.tsx
- src/scenes/AcceleratorRouter/Documents/PreviewView/PreviewTable.tsx
- There is some code that mutates the table and image variables to add the "figure" number, it had to be updated to match the new split variable schema
- Updated some styling in the preview
> Fix the collection of variables for tables, modify styling to match designs

- src/components/common/ExportCsvModal.tsx
If an exported CSV contained a `#` character, the file would be cut off because it
was treated as the anchor part of the generated `data:` URL.
> SW-5732 Allow hashmarks in exported CSVs

- public/preview.css
- public/preview.html
- src/scenes/AcceleratorRouter/Documents/PreviewView/PreviewSection.tsx
I was unable to get the citation number to be superscript within the footnotes. This seems to be because of the fact that PagedJS renders these using the `::marker` pseudo element, which does not allow for properties such as `vertical-align: super;` or
`font-variant-position: super;` because it is displayed with `display: static` and can not be overridden. 
I also tried to see if there was a way to wrap the actual marker with a `<sup>` tag, but this also seems to be impossible since the content of the element is populated within the CSS, which does not allow for HTML tags.
Hopefully this is good enough for now and we can attempt to style it differently if we need in the future.
> Update the citations display in the document producer preview

- src/scenes/AcceleratorRouter/Documents/DocumentView/DocumentVariablesTab.tsx
- src/utils/searchAndSort.ts
The trigram word similarity is how we do fuzzy matching for in-runtime filtering of search results.
> SW-5670 Use trigram word similarity for fuzzy match in document producer variables tab

- src/scenes/AcceleratorRouter/Deliverables/QuestionsDeliverableView.tsx
This PR includes changes to **not** show the action buttons (edit, reject, approve, more options) when a question is in edit mode on the console side.
> SW-5722: Cancel & Save should be only actions available in Edit mode

- src/scenes/AcceleratorRouter/Deliverables/QuestionsDeliverableView.tsx
This PR includes changes to support only showing action menu items on hover (edit, reject, approve, more options) when there is no question currently in edit mode.
> SW-5721: Edit mode should only be available for one question at a time

- src/components/DeliverableView/QuestionsDeliverableCard.tsx
When an answer is updated, its status changes automatically to "In review". Only show feedback when status is "Rejected"
> SW-5693 Feedback should be hidden when the user updates their answer

- src/api/types/generated-schema.ts
- src/scenes/ModulesRouter/ModuleEventSessionView.tsx
- src/strings/csv/en.csv
- src/types/Module.ts
The event session view for recorded sessions needs to look a bit
different from the views for other event types, mostly because
there is no live video call, just a recording.
> SW-5704 Customize event display for recorded sessions

- src/scenes/ModulesRouter/ModuleEventSessionView.tsx
Make the action button on the event session page larger and give it primary
priority.
> SW-5704 Use large primary button for event action

- src/components/DeliverablesTable/index.tsx
- src/components/TableWithSearchFilters/index.tsx
- src/components/common/SearchFiltersWrapperV2/FeaturedFilters.tsx
- src/components/common/SearchFiltersWrapperV2/index.tsx
- src/scenes/AcceleratorRouter/ParticipantProjects/SingleView.tsx
- src/strings/csv/en.csv
- Modified the TableWithSearchFilters component to allow having a filter applied from the creation of the table.
- Added the projectName filter to the DeliverablesTable, when coming from the link in the Participant Project page
> SW-5579 Link to a Project's Deliverables from Project Profile page

- src/components/common/PageWithModuleTimeline/ModuleTimeline.tsx
- src/hooks/useCohorts.ts
- src/redux/features/cohorts/cohortsAsyncThunks.ts
- src/scenes/AcceleratorRouter/Cohorts/CohortView.tsx
- src/services/CohortService.ts
Allow cohort view to show the modules stepper. Since the name of the modules come from the project (and there is no project in this view) this is how the stepper looks:
> SW-5744 Add module stepper to cohort detail view

- src/scenes/ApplicationRouter/portal/Prescreen/index.tsx
Removes what appears to be debug logic so the submit pre-screen button is correctly disabled when appropriate.
> SW-5788: Disable submit pre-screen button until sections are complete

- src/scenes/AcceleratorRouter/ParticipantProjects/SingleView.tsx
Use `undefined` rather `false` as fallback value so `ProjectField` will display N/A when there's no value.
> SW-5759: When Min/Max Carbon Accumulation is not filled out, put N/A to match other fields

- src/scenes/AcceleratorRouter/Applications/ApplicationReview.tsx
- src/scenes/AcceleratorRouter/Applications/ApplicationReviewModal.tsx
- src/types/Application.ts
- src/utils/acl.ts
This PR includes changes to limit app application review for two application statuses, aside from an exception to allow admins to create/update internal comments only.
> SW-5798: Limit status options for review application in console

- src/providers/Participant/ParticipantProvider.tsx
- src/redux/features/modules/modulesAsyncThunks.ts
- src/scenes/ModulesRouter/Provider/index.tsx
- src/services/ModuleService.ts
- src/types/Module.ts
- Change deliverable search request signature to take in an array of module IDs instead of a single module ID. 
- Add `moduleStartDate` and `moduleEndDate` to the deliverable search fields and response hydration. 
- Add ability to pass in specific search field node into deliverable search request.
> SW-5672 Modify deliverable search request

- src/components/SpeciesDeliverableTable/AddSpeciesModal.tsx
- src/components/SpeciesDeliverableTable/index.tsx
- src/strings/csv/en.csv
- Pass `hasActiveDeliverable` and `hasRecentDeliverable` flags into Species deliverable Add Species modal with specific messages for each.
Here's what it looks like when there is no active species list deliverable but there is a "recent" one.
Here's what it looks like when there is an active deliverable:
> SW-5672 Add messages to add to species dialog depending on active/recent deliverables 

- src/components/SpeciesDeliverableTable/index.tsx
- src/providers/Participant/ParticipantContext.tsx
- src/providers/Participant/ParticipantProvider.tsx
- src/scenes/Home/ParticipantHomeView/CurrentModule.tsx
- Add loading state to the `ParticipantProvider`, this is used in `SpeciesDeliverableTable` so we can wait until we know if there is an active deliverable or not before checking for recent deliverables. 
- If there is an active deliverable, no point in checking for a recent one. Also rename a few things in the provider for consistency.
- Change up a few variable names in `ParticipantProvider` for consistency
> SW-5672 Optimize checking for active and current deliverable

- package.json
- src/api/types/generated-schema.ts
- src/scenes/ObservationsRouter/schedule/ObservationSubzoneSelector.tsx
- src/scenes/ObservationsRouter/schedule/ScheduleObservation.tsx
- src/scenes/ObservationsRouter/schedule/ScheduleObservationForm.tsx
- src/strings/csv/en.csv
- yarn.lock
- Implement new version of web-components with indeterminate checkbox
- Create `ScheduleObservationForm` with zone and subzone rendering and selection
Subsequent PRs:
- Auto check for subzones that have plants
- No plants icon
Depends on https://github.com/terraware/web-components/pull/628
> SW-5761 Add subzone selection for observation scheduling

- src/api/types/generated-schema.ts
- src/redux/features/observations/observationsUtilsSelectors.tsx
- src/scenes/ObservationsRouter/schedule/ObservationSubzoneSelector.tsx
- src/scenes/ObservationsRouter/schedule/ScheduleObservation.tsx
- src/scenes/ObservationsRouter/schedule/ScheduleObservationForm.tsx
- src/types/Tracking.ts
- Create new selector that merges the plant reporting data into the planting sites used in the schedule observation form
- Auto select subzones that have plants
- Render warning icon for subzones that have no plants
**The warning icon will change when we get a new one added to zeroheight**
> SW-5761 Automatically check boxes for subzones that have plants

- src/scenes/ApplicationRouter/portal/ApplicationPage.tsx
- src/scenes/ApplicationRouter/portal/Prescreen/FeedbackMessage.tsx
- src/scenes/ApplicationRouter/portal/PrescreenResult/index.tsx
This PR includes several fixes for visual issues:
- Increase vertical spacing between rejected message and content card
- Remove redundant "View" from "View View Pre-screen Submission" copy
- Don't show redundant feedback message on pre-screen result page
> SW-5829: Visual bugs for Prescreen module details page & rejected page

- src/scenes/ObservationsRouter/schedule/ObservationSubzoneSelector.tsx
For some reason `column-count: 2` breaks if there are a lot of items in the underlying table. This forces each item to take up 100% of the column, which forces the next item to the next row.
Before
After
> Fix a bug with the columns in the subzone selector

- src/scenes/ObservationsRouter/schedule/ObservationSubzoneSelector.tsx
- src/scenes/ObservationsRouter/schedule/ScheduleObservationForm.tsx
- The reschedule payload doesn't allow for requested subzones, so it must be hidden
- Also auto apply the initially selected subzones in the parent container
> Hide the observation subzone selector for observation rescheduling

- src/scenes/ApplicationRouter/portal/Overview/index.tsx
This PR includes a change to wait to render the application timeline until the application status is available.
> SW-5844: Application timeline renders multiple times with different statuses

- src/scenes/AcceleratorRouter/Applications/ApplicationReview.tsx
- src/scenes/AcceleratorRouter/Applications/ApplicationReviewModal.tsx
- src/utils/acl.ts
This PR includes some adjustments to the user permission checks before allowing a user to update application status, feedback, and/or internal comments.
> SW-5834: Application in Console: Application Status field value should be able to be changed for failed pre-screens

- src/components/common/PageCard.tsx
- src/scenes/ApplicationRouter/ApplicationsList.tsx
- src/scenes/ApplicationRouter/NewApplicationModal.tsx
- src/scenes/Home/TerrawareHomeView.tsx
- Move the navigate functionality into the dialog since it is also handling all requests, state, etc...
- Add an `onClick` handler override prop to the `PageCard` component so the parent container can handle click state
- Add the `NewApplicationModal` to the home page with the new application card\
> SW-5807 Add NewApplicationModal to home page and open when the new application card CTA is clicked on

- src/components/DeliverablesTable/index.tsx
- src/scenes/DeliverablesRouter/DeliverablesList.tsx
- If sort order is by status, sort results in the FE by status and then by due date
- Change default order from deliverable name to status
> SW-5345 Status column sort behavior

- src/components/common/PageCard.tsx
- src/scenes/Home/TerrawareHomeView.tsx
This PR includes changes to make it so the entire "Apply to Accelerator" card is NOT clickable.
> SW-5805: [Visual] Entire card for "Apply to Accelerator" shouldn't be a click target

- src/components/AcceleratorDeliverableView/QuestionsDeliverableCard.tsx
- src/components/Variables/VariableInternalComment.tsx
This PR includes changes to fix an issue that caused feedback and/or internal comments values to get wiped erroneously while "updating variable workflow details" (status, feedback, or internal comments).
I also included several changes to improve the UX of the Internal Comments field:
- Internal comments dialog should not close prematurely when a user deletes all of the text in the textarea
- Internal comments should be reset to the original value when the user presses Cancel in the dialog
- Internal comments should not update the value under the dialog until the user presses Save in the dialog
> SW-5849: Console: Internal Comments should display regardless of variable's status

- src/components/DeliverableView/FileUploadDialog.tsx
- src/redux/features/deliverables/deliverablesAsyncThunks.ts
- src/redux/features/deliverables/deliverablesSlice.ts
- src/services/DeliverablesService.ts
- src/strings/csv/en.csv
If the server indicates that a deliverable document upload failed in such a way
that a support ticket has been generated, tell the user about it.
> SW-5553 Customize error on document upload failure

- src/scenes/ApplicationRouter/portal/Prescreen/index.tsx
My [first PR](https://github.com/terraware/terraware-web/pull/3010) didn't correctly resolve the issue, this one does.
Changes include:
- Reset request ids on reload
- Remove redundant navigation to the Pre-screen view (this is that view)
- Add `submit` param to `onReload` to be explicit rather than relying on checking application status
> SW-5822: When the user restarts a prescreen they should end up on the prescreen module details page

- src/scenes/ApplicationRouter/portal/MapUpdate/index.tsx
This PR adds a loading indicator while saving a proposed site boundary.
https://github.com/user-attachments/assets/3c06ef81-d597-49ed-9cb4-ac4720c8d5d6
> SW-5815: Add loading indicator when saving site boundary

- src/components/AcceleratorDeliverableView/QuestionsDeliverableCard.tsx
This PR includes a change to always exit edit mode when the Save button is pressed, regardless of whether there are pending changes or not.
> SW-5830: Question Edit View: Allow user to exit Edit mode of question using either "Save" or "Cancel" button when only Internal Comment is added

- src/scenes/DeliverablesRouter/DeliverablesList.tsx
When sorting by status (default order), the filters were not being applied on the FE.
Add the generic "search and sort" before applying the custom status order
> SW-5865 Fix deliverables filters not working

- src/components/DocumentProducer/DeliverableVariableDetailsInput/index.tsx
- src/components/DocumentProducer/VariableDetailsInput/index.tsx
Remove the "rounded to the nearest thousandth" message from number
variable inputs. Not only does it add visual noise, but it's usually not
correct since we ask for a lot of integer values.
> SW-5874 Remove rounding helper text

- src/scenes/AcceleratorRouter/ParticipantProjects/EditView/index.tsx
- src/scenes/AcceleratorRouter/ParticipantProjects/SingleView.tsx
Remove the "number of communities within project area" field from the project
profile in the accelerator console.
> SW-5871 Remove communities from project profile

- src/components/DocumentProducer/EditVariable/index.tsx
- src/components/DocumentProducer/EditableSection/Container.tsx
- src/components/DocumentProducer/EditableSection/Edit.tsx
- src/components/DocumentProducer/EditableSection/EditVariableModal.tsx
- src/scenes/AcceleratorRouter/Documents/DocumentView/DocumentTab.tsx
- src/scenes/AcceleratorRouter/Documents/DocumentView/DocumentVariablesTab.tsx
In preparation for fetching variables by document ID rather than manifest ID, remove some prop-drilling for a `manifestId` variable that is unused in the entire tree
> Clean up unused prop

- package.json
Use a different Docker Compose command that removes the containers from the
filesystem, which should cause the server to use the most recently pulled image
when it is restarted.
> Make yarn docker:stop remove containers

- package.json
- yarn.lock
This PR bumps `web-components` to pickup @nickgraz's fix for **Fix the issue with Chrome > 126 blurring when focusing on child elements**.
> Fix the issue with Chrome > 126 blurring when focusing on child elements

- src/components/DeliverablesTable/DeliverableCellRenderer.tsx
On the deliverables list page in the accelerator console, we show a
column that has the cohort-module-specific module title (which is
usually something like "Module 1") followed by the module name. For
document deliverables whose documents were imported from PDH, there
won't necessarily be a cohort module, and thus there won't be a module
title.
Update the rendering code to show just the module name in that case, so
it doesn't show up like "undefined - GIS".
> SW-5800 Don't show "undefined" as module title

- src/components/DeliverablesTable/index.tsx
- src/scenes/AcceleratorRouter/Deliverables/DeliverablesList.tsx
Deliverable documents imported from PDH may belong to projects whose organizations
don't have the Accelerator internal tag. People will still want to be able to
filter for those projects in the deliverables table. Change the filter dropdown
so it includes all the projects whose deliverables are shown.
> SW-5800 Deliverables list for non-accelerator projects

- src/scenes/AcceleratorRouter/Documents/DocumentView/DocumentVariablesTab.tsx
This PR includes a fix for an issue that results in Terraware crashing sometimes when viewing the Variables tab of a Document in the Doc Producer.
> Fix doc producer document variables tab crashes terraware sometimes

- src/scenes/AcceleratorRouter/Documents/DocumentsAddView/index.tsx
This PR centers the Add Document form.
> SW-5881: [Visual] Document Producer - Add Document form not centered

- src/utils/searchAndSort.test.ts
- src/utils/searchAndSort.ts
The Exact search condition in the front-end was executing an includes (not exact condition) instead of an equals
> SW-5877 Filtering for "Accepted" Applications also pulls up "Not Accepted"

- src/components/ModuleDetailsCard/index.tsx
- src/scenes/Home/ParticipantHomeView/CurrentModule.tsx
This PR removes the "See All Modules" link from the Module Overview Card on the home page.
> SW-5843: Remove "See All Modules" link from Module Overview Card on home page

- src/components/ProjectField/index.tsx
This PR truncates project display text values when they overflow their parent container.
> SW-5831: Projects File Naming field: truncate the value in the filed when the browser shrinks the field size

- src/components/DocumentProducer/DeliverableVariableDetailsInput/index.tsx
This PR fixes a regression from my [previous PR for SW-5825](https://github.com/terraware/terraware-web/pull/3064), where I missed adding an empty fallback value for text variables without pre-existing values. This update corrects that oversight.
> SW-5902: Full application questionnaire deliverables inputs missing

- src/components/common/TextTruncated.tsx
- src/scenes/AcceleratorRouter/ParticipantProjects/SingleView.tsx
This PR includes changes to adjust the font weight for the land use model type field on the project details page.
> SW-5758: Project Details page - Land Use Model Type font weight should be 600

- src/api/types/generated-schema.ts
- src/scenes/AcceleratorRouter/Cohorts/CohortEditView.tsx
- src/scenes/AcceleratorRouter/Cohorts/CohortForm.tsx
- src/scenes/AcceleratorRouter/Cohorts/CohortNewView.tsx
This PR includes changes to add created and modified by users & timestamps to the Cohort Edit View.
> SW-5745: Add created and edited timestamps to cohort edit view

- src/components/ProjectField/Meta.tsx
- src/scenes/AcceleratorRouter/Cohorts/CohortForm.tsx
This PR includes a quick fix for an oversight in [my previous PR for SW-5745](https://github.com/terraware/terraware-web/pull/3090): the URI placeholder `:userId` should be `:personId`.
> SW-5745: Add created and edited timestamps to cohort edit view (Follow-up #1)

- src/components/DocumentProducer/DeliverableVariableDetailsInput/index.tsx
- src/components/DocumentProducer/VariableDetailsInput/index.tsx
This PR updates multi-line text variable inputs to render as a `textarea`.
> SW-5912: FE display multi-line text variable inputs as a large text area

- src/redux/features/documentProducer/documents/documentsSelector.ts
- src/redux/features/user/usersSelectors.ts
This PR includes changes to populate the "Edited By" column in the document history table.
> SW-5913: "Edited By" column in document history table is not populated

- src/components/DeliverableView/QuestionsDeliverableEditForm.tsx
- src/utils/documentProducer/variables.ts
The replace Regex is likely not required, but put in because of a mistake in the spreadsheet.
The behavior in console remains unchanged, since it does not allow editing of multiple inputs at once anyways.
> SW-5901 Used pending values to determine dependencies on edit view

- src/components/DeliverablesTable/index.tsx
This PR includes changes to replace all deliverable type values of "Questions" with "Questionnaire".
This PR approaches this via the shortest path: massaging deliverables data in the FE to update the `type` value. Alternatively, we could approach it more holistically and update the deliverable type value across the BE & FE.
> SW-5875: "Questions" type should be "Questionnaire" type for Deliverables table and "Type..." should be "Type"

- src/components/DocumentProducer/EditableSection/Container.tsx
- src/scenes/AcceleratorRouter/Documents/DocumentView/DocumentOutlinePanel.tsx
- src/scenes/AcceleratorRouter/Documents/DocumentView/DocumentTab.tsx
- Previously, we where checking if the section header was in the viewport to scroll into it or not. Since we always want to center that section, this validation was removed.
- Also, some sections didn't have id, so it was impossible to scroll into them. Added ids to those sections
- Finally, the scroll was not correct because the header of the page was interfering with the position. Added a gap to scroll into the element, taking the header space into account
> SW-5919 Document outline should navigate through document on click

- src/scenes/AcceleratorRouter/Documents/DocumentView/DocumentHistoryTab.tsx
This PR includes a follow-up change to request user data for all users listed in the "Edited By" column.
> SW-5913: "Edited By" column in document history table is not populated (Follow-up #1)

- src/components/AcceleratorDeliverableView/QuestionsDeliverableCard.tsx
- src/components/DeliverableView/QuestionsDeliverableEditForm.tsx
- src/hooks/useProjectVariablesUpdate/util.ts
Adding rows to table variable values and editing existing table cells
wasn't working for two reasons:
* There was an optimization that skipped saving the value if it
looked like the user hadn't changed anything. But that check was
only looking at changes to simple variables like text and number
fields, and was ignoring changes to other variable types such as
tables and images. The code that assembles the server request
already has logic to skip the request if it would be a no-op,
so the optimization wasn't needed anyway; it's gone now.
* The code that assembled the server request was comparing the
initial cell values with themselves and thinking that edited
cells hadn't changed. Now it compares against the values from
the edit form.
Also fixes SW-5933.
> SW-5851 Save modified or deleted table cells

- src/scenes/ApplicationRouter/NewApplicationModal.tsx
This PR includes a fix for an issue that caused new projects to not be recognized/available as an option when starting a new application.
> SW-5931: Existing Project not recognized when Starting New Application

- src/components/DeliverableView/QuestionsDeliverableEditForm.tsx
- src/hooks/useProjectVariablesUpdate/index.ts
This PR includes:
- A fix for an issue that was preventing saving questionnaire deliverables (modified or not)
- A fix to return to display mode when pressing save with no pending changes in questionnaire deliverables
> SW-5978: Saving an unchanged questionnaire deliverable should return the user to the view display mode

- src/hooks/useProjectVariablesUpdate/util.ts
This PR includes a fix for a `400` error that occurs when a user enters text and then deletes it before pressing save, for a text variable question with no previous value within a questionnaire deliverable.
> SW-5976: Optional question preventing questionnaire saving

- package.json
- yarn.lock
This PR includes a change to bump `web-components` to the latest version (`3.3.4`) to pickup a fix for an issue that results in an extraneous asterisk on required fields with no label defined.
> SW-5973: Remove extraneous asterisk

- src/components/DocumentProducer/DeliverableEditTable/index.tsx
This PR includes changes to auto-add an initial empty row to tables with no rows, when editing a Questionnaire Deliverable.
> SW-5970: Questionnaire Deliverable table fields don't display a row by default

- src/components/DocumentProducer/EditVariable/index.tsx
This PR is a follow-up to fix an issue preventing citation edits from being saved when modifying text variables.
> SW-5918: Doc producer - Missing section display mode variable popover

- src/components/ProjectsDropdown/index.tsx
- src/providers/Participant/ParticipantProvider.tsx
- src/scenes/DeliverablesRouter/DeliverablesList.tsx
This PR includes updates to the projects filter in the deliverables list:
- Enable auto-complete functionality
- Sort projects by name
> SW-5948: Deliverables list view - Projects filter should be an Autocomplete

- src/components/AcceleratorDeliverableView/QuestionsDeliverableCard.tsx
- src/components/DeliverableView/QuestionsDeliverableCard.tsx
This PR includes changes to support showing an asterisk (`*`) beside field labels in display views, rather than just edit views.
> SW-5992: Show asterisks for required fields in Detail Views

- src/components/TopBar/TopBarContent.tsx
- src/mixpanelEvents.ts
- src/scenes/Home/ParticipantHomeView/ToDoCta.tsx
- src/scenes/OrgRouter/NavBar.tsx
- Extract list of mixpanel events into a single list. 
- Send events for clicks into the To-Do and Upcoming list of items. 
- Send events for participant clicks on Deliverables & Modules in the left nav.
> SW-6010 Add Mixpanel events for accelerator nav

- src/scenes/AcceleratorRouter/ParticipantProjects/EditView/index.tsx
Because the requestId was not reset after an error, the error snackbar was appearing again when assigning another TFContact
> SW-5870 Reset assign request after error

- src/scenes/ObservationsRouter/org/OrgObservationsListView.tsx
- src/scenes/ObservationsRouter/org/OrgObservationsRenderer.tsx
We were changing the value to show in the renderer, but the sort function uses the actual value of the row. 
The fix is using a new column that has the same value in the row and the renderer
> SW-5845 Sorting observations table doesn't sort by date

- src/scenes/PeopleRouter/PeopleListView.tsx
The search was only checking search terms against the user's first and last name, this adds the email. I ended up hard-coding the `type` to `Exact` because otherwise every email with the same domain would show up.
Before
After
> SW-5014 Fix email search in people dashboard

- src/api/types/generated-schema.ts
- src/constants.ts
- src/scenes/ApplicationRouter/portal/MapUpdate/index.tsx
- src/scenes/PlantingSitesRouter/edit/editor/utils.ts
- src/scenes/PlantsDashboardRouter/PlantsDashboardView.tsx
The plants dashboard shows the number of hectares covered by the most recent
observation. Use the actual sizes of the monitoring plots as returned by the
server so that the total will be correct once we start supporting variable
plot sizes.
> SW-6186 Calculate observed hectares from plot sizes

- src/scenes/Home/TerrawareHomeView/PlantingSiteStats.tsx
- src/scenes/Home/TerrawareHomeView/StatsCardItem.tsx
- src/scenes/Home/TerrawareHomeView/index.tsx
This PR includes a couple of follow-up adjustments:
- Reduce vertical height of Planting Site Card
- Adjust access to CTA buttons based on user role
> SW-6092: Home page dashboard (Follow-up #1)

- src/constants.ts
- src/scenes/AcceleratorRouter/Modules/CohortModulesCellRenderer.tsx
The accelerator console has a module details page now, so use it instead of the
admin UI when linking to a module from the cohort's modules list.
> SW-6031 Stop linking to admin UI's module details

- src/scenes/AcceleratorRouter/Documents/DocumentView/DocumentTab.tsx
Within the document producer, when updating a variable within a section, by reloading the document producer provider's variables only, we can avoid losing changes within the editable section.
> SW-6169 Only reload variables when updating variable within section

- src/hooks/useListModules.ts
The useListModules hooks was executing the listModules function **always**, but this is not necessary, because the listModules is a function exported in the hook, then it can be called when it is required.
For example in the home page it is called explicitly in the [ParticipantProvider](https://github.com/terraware/terraware-web/blob/main/src/providers/Participant/ParticipantProvider.tsx#L85)
> TSW-6237 Terraware Server Error: No Permission to read cohorts

- src/scenes/AcceleratorRouter/Documents/DocumentView/index.tsx
This PR fixes the component state and some checks to make sure that the upgrade modal is only visible when a yet-to-be-completed upgrade is available for the current document.
Although this can be deployed on its own, [this](https://github.com/terraware/terraware-server/pull/2612) PR needs to be merged to QA the ticket.
> SW-6162 Fix document upgrade modal visibility

- src/components/TableWithSearchFilters/index.tsx
- src/components/common/SearchFiltersWrapperV2/index.tsx
- src/components/seeds/database/index.tsx
- src/scenes/AcceleratorRouter/Applications/ApplicationsList.tsx
- src/scenes/InventoryRouter/InventoryTable.tsx
- src/utils/filterHooks/useSessionFilters.ts
If default filters and sticky filters are both provided. Make sticky filters take priority.
Session filters are set to be nullable to distinguish loading states.
> SW-6184 Make table with search filters wait and get overridden by sticky filters if applicable

- src/utils/useMapboxToken/index.ts
- src/utils/useMapboxToken/storage.test.ts
- src/utils/useMapboxToken/storage.ts
- Move `useMapboxToken` to its own folder
- Add util functions for getting and setting the mapbox token to session storage
- I used 30 minutes for the default expiration time since that is [what is used](https://github.com/terraware/terraware-server/blob/main/src/main/kotlin/com/terraformation/backend/config/TerrawareServerConfig.kt#L319) on the server side. 
**Before**
Here you can see what happens when the token is not stored in session:
As you can see, a page refresh causes the FE to retrieve another token, which requires the previously cached Mapbox image to be ignored
**After**
Since we are pulling the token from session, we do not get a new token and the Mapbox asset is pulled from browser cache:
> SW-6232 Add mapbox token to session storage with 30 minute expiration

- scripts/openapi-typescript-formatter.mjs
- src/api/types/generated-schema.ts
- src/components/DocumentProducer/EditableTableModal/index.tsx
- src/hooks/useProjectVariablesUpdate/util.ts
- src/types/documentProducer/VariableValue.ts
Recent server upgrades have changed the OpenAPI schema in
ways that caused type errors in the generated code.
Override one of the generated types which is flat-out wrong
by default, and update the code to use more precise types
in places where there would otherwise be type errors.
> Use updated generated types from server

- .github/scripts/deploy.sh
The deploy script wasn't exiting with a nonzero exit code if the command to list
EC2 instances was failing. Set the "pipefail" option to fix that.
> Make deploy script fail if any step fails

- src/api/types/generated-schema.ts
- src/components/DocumentProducer/DeliverableDisplayVariableValue/index.tsx
- src/components/DocumentProducer/DeliverableVariableDetailsInput/index.tsx
- src/components/DocumentProducer/EditVariable/index.tsx
- src/components/DocumentProducer/EditableSection/DisplayVariableValue.tsx
- src/components/DocumentProducer/EditableSection/EditVariableModal.tsx
- src/components/DocumentProducer/EditableSection/helpers.ts
- src/components/DocumentProducer/VariableDetailsInput/index.tsx
- src/components/Variables/VariableHistoryTable.tsx
- src/hooks/useProjectVariablesUpdate/util.ts
- src/scenes/AcceleratorRouter/Documents/DocumentView/DocumentVariablesTab.tsx
- src/types/documentProducer/Variable.ts
- src/types/documentProducer/VariableValue.ts
- src/utils/documentProducer/variables.ts
- src/utils/email.ts
Add support for variables representing email addresses. These generally work like
text variables, but they have additional input validation in the questionnaire
deliverable UI.
> SW-6339 Add email variable type

- public/js/table-of-contents.js
- public/preview.css
I am not exactly sure how this stopped working... but the moving the `overflow: hidden` to the element displaying the TOC text (as opposed to the container) solved the issue.
> SW-6318 Fix the CSS that was hiding the TOC contents

- src/scenes/AcceleratorRouter/Documents/PreviewView/PreviewSection.tsx
- src/scenes/AcceleratorRouter/Documents/PreviewView/util/markdown-table.test.ts
- src/scenes/AcceleratorRouter/Documents/PreviewView/util/markdown-table.ts
A new example needed for this functionality includes a table cell that has both text and variable references. This PR makes that possible. See tests for more info.
In the editor
In the preview
> SW-6302 Make it possible to have cells with any number of section text and variable values

- .github/scripts/set-environment.sh
Because the short commit hash has a chance at producing a number (for example 8774464e947), it can break the "app version checker" in staging. Production builds are always prefixed with a "v". 
This adds an "x" to the staging app version, so a number can never be produced.
> Prefix staging build app version with "x"

- src/redux/features/observations/observationsSelectors.ts
For abandoned observations, [this variable](https://github.com/terraware/terraware-web/blob/main/src/scenes/ObservationsRouter/details/index.tsx#L95) came back `undefined`, which caused the page to either navigate back to the observation list or appear blank.
This PR adds the "Abandoned" state to the observations selector so the variable comes back defined.
> Allow for "Abandoned" observations to be selected from state

- renovate.json
Tell Renovate to add the `MAJOR-UPDATE` label to the other labels for major
package updates, rather than replacing the default list of labels.
In addition, Renovate renamed the preset with the recommended settings from
`base` to `recommended`, so change the config to use the new name.
> Fix Renovate labels on major updates

- src/scenes/Home/TerrawareHomeView/index.tsx
After first Nursery or Seed Bank is setup, "Set up Nursery" and "Set up Seed Bank" CTAs still appear for Owners and Admins
> SW-6358 Home Dashboard fix CTA for Seedbank and Nursery

- src/redux/features/observations/plantingSiteDetailsSelectors.ts
- src/redux/features/observations/utils.ts
- src/redux/features/tracking/trackingSelectors.ts
- src/scenes/ObservationsRouter/plot/index.tsx
- src/scenes/ObservationsRouter/replacePlot/ReplaceObservationPlotModal.tsx
- src/scenes/ObservationsRouter/zone/ObservationPlantingZoneRenderer.tsx
- src/scenes/ObservationsRouter/zone/index.tsx
- src/scenes/PlantingSitesRouter/view/BoundariesAndZones.tsx
- src/scenes/PlantingSitesRouter/view/PlantingSiteSubzoneView.tsx
- src/services/MapService.ts
- src/services/ObservationsService.ts
- src/services/TrackingService.ts
- src/types/Tracking.ts
Explicitly use monitoring plot numbers rather than relying on the API to populate
monitoring plot names with the plot numbers for backward compatibility. This will
pave the way for removing the backward-compatibility fields from the API.
There should be no change in user-visible behavior here.
> SW-6389 Stop using monitoring plot names

- src/scenes/Species/SpeciesEditView.tsx
If the user tries to rename a species and the scientific name already
exists in the organization, show an error message to that effect
rather than the generic "an error occurred" one.
> SW-6402 Better error on species rename conflict

- src/components/ProjectAssignModal/index.tsx
When unassigning the project label on batches or accessions the ID is undefined.
> SW-6331 Allow project labels to be unassigned

- src/scenes/PeopleRouter/PeopleListView.tsx
A previous PR removed the checkboxes for non-admins, but the rows were still clickable.  Remove that functionality as well.  Checkboxes still work for admins.
> SW-6396 Disable clickable rows in people table

- README.md
The confluence docs were out of date, and the readme was missing playwright install notes. Can also remove the link to confluence if that is preferred
> Updates to readme for first-time setup

- package.json
- src/components/AddNewOrganizationModal.tsx
- src/scenes/OrganizationRouter/EditOrganizationView.tsx
- yarn.lock
The type details field that's required when users pick an organization type of
"Other" has a server-side limit of 100 characters but we weren't limiting the
inputs in the UI. This caused organization creation/edit to fail if the user
entered more than 100 characters into the field.
> SW-6577 Limit organization type details to 100 characters

- src/scenes/PlantsDashboardRouter/components/NumberOfSpeciesPlantedCard.tsx
- src/scenes/PlantsDashboardRouter/components/PlantingSiteDensityCard.tsx
- src/scenes/PlantsDashboardRouter/components/PlantsAndSpeciesCard.tsx
A few of the numbers on the plants dashboard were being displayed in raw form
rather than formatted with locale-appropriate separators. Wrap them in
`<FormattedNumber>` to make them more human-friendly.
> SW-6579 Format numbers on plants dashboard

- src/scenes/Home/TerrawareHomeView/index.tsx
The numbers (total seeds, etc.) on the home page weren't
being localized. Use the correct formatting for the active
locale for all of them.
> SW-6580 Use localized numbers on home dashboard

- src/scenes/Home/TerrawareHomeView/PlantingSiteStats.tsx
Use the correct number format for the current locale to
format the numbers in the "Plants" card that's shown on the
home page if the organization has planting sites.
> SW-6580 Format home page plants card numbers

- docker-compose.yml
Use PostgreSQL 17, rather than 13, for the local server+database
stack that's used for Playwright tests and sometimes for local
development.
This uses a custom image that includes the extensions that will be
needed by the server for some upcoming features. The image supports
both ARM and x86, replacing the x86-only PostgreSQL 13 image we
were using; in ARM dev environments, this should give a slight
performance increase.
Note that the new version isn't compatible with data files from the
old version. People with existing database files in their local
environments will need to either dump the existing data and restore
it, or remove the data files so they start from a clean slate.
> SW-6561 Use custom PostgreSQL 17 image

- src/components/Tables/ClientSideFilterTable.tsx
Create a `ClientSideFilterTable` component to replace `TableWithSearchFilters` when it is used without server side filtering/sorting. 
A few notes:
- This component can also be renamed to `ClientSideDataTable` or something else
- Renamed `defaultSearchOrder` to `defaultSortOrder` to be more correct
- It removes the need to specify a `dispatchSearchRequest` and assumes the implementer is doing the data retrieval and passing in the data to the `rows` property
- It keeps the rest of the same optional interface as `TableWithSearchFilters`, including:
- `extraTableFilters`
- `featuredFilters`
- `filterModifiers`
- `fuzzySearchColumns`
- `rightComponent`
- `title`
- `clientSortedFields`
- `onFilterApplied`
- `stickyFilters`
- `iconFilters`
> Create Client Side Filter table

- src/utils/searchAndSort.test.ts
- src/utils/searchAndSort.ts
Happy to add additional test cases if anything is missing.
AI Summary:
Added support for nested property filtering in the searchAndSort utility.
- Enhanced the `searchConditionMet` function to support filtering on nested properties using underscore notation
- Added support for:
- Filtering on array subsets (e.g., `subsets_id`)
- Filtering on nested objects (e.g., `subObject_id`)
- Filtering on deeply nested properties (e.g., `subObject_deepNestedResult_subsets_name`)
- Preserving fields that actually contain underscores in their names
- Added test cases for new filtering capabilities
> Add Nested Object filter support

- src/redux/features/funder/fundingEntitiesAsyncThunks.ts
- src/scenes/AcceleratorRouter/FundingEntities/index.tsx
- src/services/FundingEntityService.ts
Change Funding Entities table to new `ClientSideFilterTable` component
Add Projects filter dropdown. Utilizes new nested object filter support that was added up-stack.
> SW-6642 Add Project filter dropdown and Client Side table

- src/components/AcceleratorReports/AcceleratorReportCellRenderer.tsx
- src/components/AcceleratorReports/AcceleratorReportsTable.tsx
This PR includes a fix to remove an unnecessary "Q" prefix being applied to report quarters in the accelerator reports table.
Result: "QQ1" --> "Q1"
> Accelerator Reports follow-up

- src/scenes/FunderRouter/index.tsx
There appears to be an occasional issue with react-router where it sometimes will not do a double redirect when using the Navigate component. 
Currently, `/funder` redirects to `/welcome` if the user is not a funder. For users with an organization, `/welcome` then redirects to `/home`. For users without an organization, both `/welcome` and `/home` display the same welcome component anyway.
In this instance, we didn't really need to redirect to `/welcome` instead of `/home`, so this PR just changes the redirect from `/funder` to `/home`.
> SW-6724 Fix Redirect issue

- src/components/AcceleratorReports/AcceleratorReportsTable.tsx
- src/scenes/AcceleratorRouter/ParticipantProjects/Reports/ReportView.tsx
- src/scenes/AcceleratorRouter/ParticipantProjects/Reports/ReportsView.tsx
- src/scenes/Reports/AcceleratorReportView.tsx
- src/scenes/Reports/AcceleratorReportsView.tsx
- src/utils/useStickyTabs.ts
The status filter was already kept. The year filter, since it's not a real filter, was not. So added a query param to keep it
> SW-6734 Clicking back to Reports page from a Report should keep table filters

- src/scenes/ObservationsRouter/common/MergedSuccessMessage.tsx
- src/scenes/ObservationsRouter/details/index.tsx
- src/scenes/ObservationsRouter/index.tsx
- src/scenes/ObservationsRouter/plot/AdHocObservationDetails.tsx
For assigned observations, we let users match the "Other" species
with ones on the organization's species list. Add the same
functionality for ad-hoc monitoring observations.
> SW-6707 Match "Other" species on ad-hoc observations

- src/components/AcceleratorReports/AcceleratorReportCellRenderer.tsx
- src/scenes/AcceleratorRouter/ParticipantProjects/Reports/ReportView.tsx
- src/scenes/AcceleratorRouter/ParticipantProjects/Reports/ReportsView.tsx
The breadcrumbs for the View Report page weren't replacing the project id in the url so this fixes that, and adds the other accelerator breadcrumbs that were available on the reports list page.
> SW-6737 Fix Reports Breadcrumb not working

- src/scenes/AcceleratorRouter/ParticipantProjects/Reports/ReportView.tsx
- src/scenes/Reports/AcceleratorReportView.tsx
This PR refactors the render functions for accelerator reports to use a single `.map` for metrics.
> Refactor Accelerator Report render to use a single .map for metrics

- src/scenes/ObservationsRouter/BiomassMeasurementsDetails.tsx
We never implemented the code to calculate the elevation for a
biomass observation monitoring plot; we put a placeholder value in
the UI and then lost track of needing to replace it with a real
number. Remove the field from the UI for now rather than showing an
incorrect elevation.
> SW-6632 Remove elevation from biomass details

- src/scenes/ObservationsRouter/map/ObservationMapView.tsx
Use completed time instead of completed date, so same-day observations can be displayed
> SW-6764 Multiple observations with the same start/end dates cause only one to be drawn in the map view

- playwright/e2e/suites/locations.spec.ts
- src/components/OrganizationsDropdown.tsx
- src/components/SmallDeviceUserMenu.tsx
- src/providers/OrganizationProvider.tsx
- src/scenes/Home/OnboardingHomeView/index.tsx
Fix redirect so that it goes to the new org's home page after user creates a new org.
Also add a couple related explicit search fields in to prepare for react router 7.
> Fix redirect when creating a new org

- src/services/ObservationsService.ts
The biomass observation list CSV export was exporting
the wrong column for the plot description.
> SW-6242 Export correct description column in CSV

- package.json
- src/scenes/Home/CTACard.tsx
- yarn.lock
In development, the following error showed up on several pages, because of `CTACard`'s title and description `Typography` components:
```
<div> cannot appear as a descendant of <p>
```
This error annoyed me so I decided to create a PR to fix it.
> Fix react nesting warning

- package.json
- playwright/e2e/suites/inventory.spec.ts
- playwright/e2e/suites/species.spec.ts
- src/App.tsx
- src/index.tsx
- src/scenes/TerrawareRouter/index.tsx
- yarn.lock
Update to latest version of react-router 6.
Add future flag of `v7_startTransition` to prepare for react-router 7. 
Remove `React.lazy` imports since react-router 7 does not support them with it's useTransition logic - [Upgrade Docs](https://reactrouter.com/upgrading/v6#v7_starttransition) and [Changelog](https://github.com/remix-run/react-router/blob/main/CHANGELOG.md#futurev7_starttransition)
Note that this PR should not be merged until right after a release so that it sits in staging for a week for issues to be found.
> SW-6773 Update to latest react-router 6, add startTransition future flag

- src/index.tsx
Uncomment `v7_relativeSplatPath` future flag.
It seems that we are not using relative paths at all, so this future flag shouldn't actually affect us, but this ensures there are fewer surprises when actually upgrading to react-router v7.
> Add relativeSplatPath react-router future flag

- src/scenes/ObservationsRouter/BiomassMeasurementsDetails.tsx
- src/services/ObservationsService.ts
Change the filename for the observation details CSV to use the word
"monitoring" instead of "measurements" and move the "Field notes"
column to the end, per feedback from QA of the feature.
> SW-6242 Minor biomass CSV export fixes

- src/constants.ts
As part of the upgrade to react-router 7, they changed the behavior for relative navigation. Navigating to a non-fully qualified path could end up adding the new path onto the existing path depending on how the router was setup. 
In this case, navigating from any page in the console to the organizations page was appending `accelerator/organizations` to the current path, instead of going to `/accelerator/organizations`. This PR fixes that by adding `/` to the app path. 
All other enums in APP_PATH were already fully qualified.
> Fix organization navigation

- src/scenes/Reports/index.tsx
- src/utils/acl.ts
This PR includes some follow-up updates to the initial PR:
- Adjust permissions required to read reports
- Only render routes for Accelerator Reports if feature flag is enabled and user has required permission, otherwise redirect user to Home
> SW-6761: Reports page should not be accessible by Contributors & Managers (Follow-ups)

- src/components/AcceleratorReports/AcceleratorReportTargetsCellRenderer.tsx
- src/utils/acl.ts
This PR includes changes to allow org admins to edit report targets.
> SW-6807: Project Org Admin should be able to edit metric targets

- src/scenes/AcceleratorRouter/ParticipantProjects/ParticipantProjectProvider.tsx
Only set the ParticipantProjectData if a dependent value changed.
After saving edits to Project Details, occasionally this would cause an infinite re-render, never making it back to the view Project Details page without navigation to a different page or refreshing. This PR fixes that.
> Fix occasional infinite re-render on project profile edit page

- package.json
This PR uses `overrides` in `package.json` to use the commit from the [PR that was submitted to the http-proxy package](https://github.com/http-party/node-http-proxy/pull/1666).
Summary:
- Root issue is a deprecated Node API (`util._extend`) is being used by a dependency that hasn't been updated in multiple years ([http-proxy](https://github.com/http-party/node-http-proxy/))
- A [PR was submitted to the http-proxy package](https://github.com/http-party/node-http-proxy/pull/1666) but not been merged yet
- [Open issue in http-proxy-middleware](https://github.com/chimurai/http-proxy-middleware/issues/1017) discusses the issue and links to the PR in `http-proxy`
> Fix node warning in console: `util._extend` API is deprecated

- package.json
- patches/http-proxy+1.18.1.patch
- yarn.lock
This PR reverts the change made in the [previous PR for this issue](https://github.com/terraware/terraware-web/pull/3875) since it didn't actually silence the node warning and instead directly patches the `http-proxy` package.
> Fix node warning in console: `util._extend` API is deprecated (Follow-up)

- src/components/ListMapView/index.tsx
- src/components/common/FormattedNumber.tsx
- src/scenes/AcceleratorRouter/ParticipantProjects/ProjectProfileView.tsx
- src/scenes/Home/TerrawareHomeView/PlantingSiteStats.tsx
- src/scenes/Home/TerrawareHomeView/index.tsx
The `useNumberFormatter` hook added `supportedLocales` inside it a while back, but some usages of `numberFormatter` were still passing in `supportedLocales`. The function doesn't use the passed in value anyway, so this PR removes it.
> Remove unnecessary supported locales to numberFormatter

- eslint.config.mjs
- src/components/AcceleratorReports/ChallengesMitigationBox.tsx
- src/redux/features/reports/reportsThunks.ts
- src/scenes/Reports/AcceleratorReportEditForm.tsx
Fix an issue where deleting the last character in a challenge or mitigation plan textbox causes that row to disappear.
Fix an issue where react cycled through an infinite render loop if the user types too fast (including holding down backspace).
> SW-6841 Fix Challenge/Mitigation box for participant reports

- src/components/DeliverablesTable/index.tsx
This PR includes a quick fix for a duplicate variable (`projectId`).
> Fix duplicate variable definition (projectId)

- src/scenes/AcceleratorRouter/ParticipantProjects/ProjectDeliverablesView.tsx
- src/scenes/DeliverablesRouter/DeliverablesList.tsx
This PR adds follow-up changes to dynamically adjust the content wrapper and title component, fixing rendering issues and ensuring consistent styles for tab/table headers.
Context: There were two `TfMain` & `PageHeaderWrapper` components being rendered in the Deliverables Tab of the new Project Profile Page.
> SW-6812: Add Deliverables tab to Project Profile in Console (Follow-up)

- eslint.config.mjs
- package.json
- src/services/HttpService.ts
- src/services/SearchService.ts
- src/types/Map.ts
- src/utils/searchAndSort.test.ts
- src/utils/searchAndSort.ts
Fix `jsdoc-indentation` linting issues.
Enable `naming-convention` rule to match old tslint config.
Updating `lint` command to remove unnecessary flag.
Also add test files back to being linted.
> Fix jsdoc-indentation linting issues

- src/components/TopBar/TopBarContent.tsx
- src/components/UserMenu.tsx
- src/providers/FundingEntityProvider.tsx
- src/providers/contexts.ts
- src/services/FundingEntityService.ts
- src/services/ParticipantProjectService.ts
- src/utils/numbers.test.ts
Fix `no-empty-function` and `no-empty-pattern` for objects.
Fix `object-shorthand` using `yarn lint --fix`.
A missing semicolon also got included with an automatic prettier fix.
> Fix empty-function, empty-object, object-shorthand linting issues

- src/components/DeliverablesTable/index.tsx
This PR fixes an issue where the Deliverables Table showed zero results when `selectedOrganization.id` was set. The `selectedOrganization.id` isn't set after a refresh on a console page, but is automatically set when a non-console page is viewed.
> SW-6812: Add Deliverables tab to Project Profile in Console (Follow-up #2)

- src/components/Map/Map.tsx
- src/components/ProjectField/ProjectMap.tsx
This required adding a `setTimeout` on the initial render of Map, which is only used in a few places:
- Application Map Card
- Planting Site Map
The timeout was only 200ms, which seemed minimal since it takes longer to retrieve the satellite images inside the map.
> SW-6820 Make Project Map be the same height as the Project Image

- src/components/Map/Map.tsx
- src/components/ProjectField/ProjectMap.tsx
- src/types/Map.ts
Add ability to disable zoom on Map component.
There's no need to be able to zoom the map when the project's country map is displaying, so disable the zoom for it.
> Disable project map zoom for country map only

- src/components/ProjectField/LandUseModelTypeCard.tsx
- src/components/ProjectField/Textfield.tsx
- src/scenes/AcceleratorRouter/ParticipantProjects/EditView/ProjectProfileEdit.tsx
- src/scenes/AcceleratorRouter/ParticipantProjects/ProjectProfileView.tsx
Add display of land-use model hectares when the type is selected but there was no value input for that land-use type.
Also allow setting of hectare value to 0.
> SW-6872 Add Empty State for Land Use Model Hectares

- src/components/Units/Co2HectareYear.tsx
- src/scenes/AcceleratorRouter/ParticipantProjects/EditView/ProjectProfileEdit.tsx
- src/scenes/AcceleratorRouter/ParticipantProjects/ProjectProfileView.tsx
If a land-use model type is deleted but there was a hectares value for it, don't delete model hectares until save. This allows the user to add it back in and still have the value from before.
Always display reports link.
Adjust spacing of "Last Submitted Report" and divider.
> SW-6873 Update handling of deleting model use types

- eslint.config.mjs
- src/components/PlantsPrimaryPage/index.tsx
- src/scenes/AcceleratorRouter/Cohorts/CohortForm.tsx
- src/scenes/Home/TerrawareHomeView/index.tsx
- src/scenes/ObservationsRouter/adhoc/AdHocObservationDetails.tsx
- src/scenes/ObservationsRouter/adhoc/index.tsx
- src/scenes/PlantsDashboardRouter/components/ZoneLevelDataMap.tsx
This drops the lint problem count from 1971 errors to 184 errors.
> Disabled no-unsafe-* linting rules and removed manual disabling of them for lines

- src/components/AcceleratorReports/EditAcceleratorReportTargetsModal.tsx
This PR includes the following changes:
- Determine `disabled` status for each report target input field and memoize the values
- Revert [change in previous PR](https://github.com/terraware/terraware-web/pull/3973) to exclude unchanged metric data
> SW-6807: Project Org Admin should be able to edit metric targets (Follow-up #3)

- src/components/AcceleratorReports/AcceleratorReportTargetsTable.tsx
- src/components/AcceleratorReports/EditAcceleratorReportTargetsModal.tsx
This PR includes a follow-up change to only send requests for modified reports.
Most of the diff is indentation, the only change is the addition of the `.filter` and if/else clause to handle closing the modal when there are no changes.
> SW-6807: Project Org Admin should be able to edit metric targets (Follow-up #4)

- src/components/ProjectField/ProjectSdgDisplay.tsx
Previous order was non-deterministic because the server represented the list with a set.
Before:
After:
> SW-6918 Fix order of sdg list

- src/components/AcceleratorReports/EditAcceleratorReportTargetsModal.tsx
This PR fixes an issue where requests were sent for unchanged targets with no previous value.
If `target` was `undefined` before and after edits, it was omitted in the API response but still set in the report copy, causing the `isEqual` check to return false despite both copies having `undefined` for `target`.
> SW-6807: Project Org Admin should be able to edit metric targets (Follow-up #5 🫠)

- src/hooks/useOrgTracking.ts
This hook isn't used by anything yet, but it was merged early to unblock PlantDashboard development. Found a bug to patch.
> Fixed dispatches in useOrganization hook

- src/scenes/ObservationsRouter/details/exportObservationResults.ts
The observation results export was using the server-calculated "total plants"
value, but that total doesn't count dead plants and includes pre-existing plants
from previous observations, whereas we want the results CSV to just be the total
of the live, existing, and dead plants from the observation in question.
> SW-6840 Calculate total plants from raw numbers

- src/scenes/Home/index.tsx
If the org has modules, we don't need to check the org has species condition
> SW-6933 If Accelerator project does not have any species, accelerator home page does not show

- eslint.config.mjs
- package.json
- yarn.lock
Adds 10 new errors (fixed in [next PR](https://github.com/terraware/terraware-web/pull/4030)), and 388 warnings. 
Specifically, all 388 of those warnings are `react-hooks/exhaustive-deps`, which is potentially causing render issues on some of our pages (e.g. things not rerendering when they should be).
The 10 new errors are all `react-hoks/rules-of-hooks`.
> Add react-hooks lint plugin, use recommended settings

- src/scenes/AccessionsRouter/Accession2View.tsx
- src/utils/useStickyTabs.ts
Fix browser back button on View Accession page by adding an optional `replace: true` to `useStickyTabs`
> SW-6249 Fix accessions back button

- package.json
- src/components/BatchWithdrawFlow/flow/SelectPurposeForm.tsx
- src/scenes/InventoryRouter/InventoryCellRenderer.tsx
- yarn.lock
Some console errors were making playwright output harder to parse. Fix them.
The 2 console warnings:
- Nested `<p>` under `<p>`
- Grid element cannot have `xs` without `item`
> Fix 2 console warnings during playwright tests

- src/components/AcceleratorReports/ChallengesMitigationBox.tsx
Fixing the exhaustive-deps linting issue caused an infinite render on the challenges/mitigations in reports. Fix the infinite render.
> Fix infinite render on challenges

- .github/workflows/workflow.yml
- eslint.config.mjs
This rule currently adds over 1500 new errors. We want to start moving away from lambdas in jsx props, so enabling this rule to help us not use them moving forward. 
Also disable the rule in the github actions workflow comment, so that when we do enable linting in CI this rule doesn't keep us from seeing the rest of the issues.
> Enable jsx-no-bind linting rule, prepare to remove it in CI

- src/scenes/PlantsDashboardRouter/components/HighestAndLowestMortalityRateSpeciesCard.tsx
- src/scenes/PlantsDashboardRouter/components/HighestAndLowestMortalityRateZonesCard.tsx
We only mark a species as lowest mortality rate if its value is lower than the previous (not equal). If it is equal we don't mark it, so in case we have 2 species with same value, the last one can be set a highest, and the first one as lowest
> SW-7009 If multiple species have the same mortality rate, we incorrectly show only one species with mortality

- src/providers/Tracking/PlantingSiteProvider.tsx
- src/redux/features/tracking/trackingThunks.ts
- src/services/TrackingService.ts
This updates the provider to use a request ID to track planting site states, so that new data are guaranteed to be read on org changes.
> SW-6990 Used planting sites dispatch requestId

- playwright/e2e/suites/accession.spec.ts
- src/scenes/AccessionsRouter/withdraw/WeightWithdrawal.tsx
This PR includes a change to allow decimal values for the withdrawal quantity when withdrawing accessions.
> SW-6925: Accessions: Cannot withdraw in mg if collection is in grams

- src/components/PlantsPrimaryPage/PlantsPrimaryPageView.tsx
- src/components/PlantsPrimaryPage/index.tsx
For the plantingSites array that we use in PlantsPrimaryPageView, we have the "all sites" option when we have more than one planting site for that project. If the project only have one, we don't have the "all sites" option, so for the "hasSites" check we have to check lenght > 0 instead of > 1
> SW-7041 Console: Plants dashboard does not load

- src/scenes/AcceleratorRouter/ParticipantProjects/ProjectProfileView.tsx
Previously the data displayed for the most recent report on the project profile page was determined by the time the report was submitted (console) or published (funder). 
This caused issues in situations like this:
- Q1 published
- Q2 published
- Q1 re-published because of updates
In this situation, the data displayed should have been from Q2 but was instead displaying Q1's data because it was published most recently.
Change to using endDate for both console and funder portal.
> SW-7055 Fix Last Report used for data

- src/components/PlantsPrimaryPage/PlantsPrimaryPageView.tsx
- src/scenes/PlantsDashboardRouter/components/NumberOfSpeciesPlantedCard.tsx
Two things were done to improve spinners:
- Create a new delayedPlantingSiteSet, that is just the value of plantingSiteSet but with a second of delay, to give time to the "isLoading" flag from the provider to set to "true" when the planting site changes, and avoid showing charts for one second and disappear again when "isLoading" changes again.
- Memoize SpeciesPlanted labels to avoid re-renders on those charts
> SW-6932 Improving plants dashboard spinners

- package.json
- playwright/e2e/suites/inventory.spec.ts
- src/components/SeedFundReports/ReportsView.tsx
- src/scenes/AcceleratorRouter/Applications/ApplicationListView.tsx
- src/scenes/AcceleratorRouter/Documents/DocumentView/DocumentVariablesTab.tsx
- src/scenes/AcceleratorRouter/Documents/DocumentView/index.tsx
- src/scenes/AcceleratorRouter/Modules/ModuleView.tsx
- src/scenes/AcceleratorRouter/Overview/index.tsx
- src/scenes/AcceleratorRouter/ParticipantProjects/ProjectPage.tsx
- src/scenes/AcceleratorRouter/ParticipantProjects/Reports/ReportsView.tsx
- src/scenes/AccessionsRouter/Accession2View.tsx
- src/scenes/FunderHome/index.tsx
- src/scenes/InventoryRouter/InventoryBatchView.tsx
- src/scenes/InventoryRouter/InventoryCellRenderer.tsx
- src/scenes/InventoryRouter/InventoryV2View.tsx
- src/scenes/NurseryRouter/NurseryPlantingsAndWithdrawalsView.tsx
- src/scenes/NurseryRouter/NurseryWithdrawalsDetailsView.tsx
- src/scenes/ObservationsRouter/ObservationsHome.tsx
- src/scenes/Reports/AcceleratorReportsView.tsx
- src/scenes/Settings/SettingsPage.tsx
- src/utils/filterHooks/useSessionFilters.ts
- src/utils/useStickyTabs.ts
- yarn.lock
This PR fixes an issue where the back button failed in some scenarios.
Previously, active tab state was managed by both React state and query params. When navigating back to a page with sticky tabs, replacing the URL triggered a new history stack, causing the previous history to be lost.
Note: The `tab` query param can still  beused to indicate a tab to load and if set, will override the tab stored from the previous session.
> SW-6955: Browser back button doesn't work on some pages

- src/scenes/ApplicationRouter/ApplicationsList.tsx
- src/scenes/Home/OnboardingHomeView/index.tsx
- src/scenes/Home/TerrawareHomeView/index.tsx
- src/scenes/Home/index.tsx
- src/scenes/OrgRouter/NavBar.tsx
- src/utils/organization.tsx
The helper functions to check the user's role in an organization
accept undefined organizations and return false in that case, so
there's no need for calling code to also check that the
organization is defined.
> Add type guards to org membership functions

- src/scenes/PlantsDashboardRouter/PlantsDashboardView.tsx
With the old condition we were not updating the acceleratorOrganizationId when the organizationId changed.
> SW-7082 Plants Dashboard in Console does not load correctly if I viewed another project's plants dashboard in the same session

- src/scenes/ObservationsRouter/adhoc/AdHocObservationDetails.tsx
- src/scenes/ObservationsRouter/adhoc/index.tsx
- src/scenes/ObservationsRouter/common/AggregatedPlantsStats.tsx
Commit 6bacecb9 added a tooltip to the titles of the live
plants graphs in observation detail views, but it should have
put the tooltip on an icon, not on the text of the titles.
> SW-7020 Add tooltip icon to live-plants titles

- package.json
As the code base grows, `yarn format` takes longer and longer
to run which is annoying. Add `yarn format:changed` to reformat
only the files that differ from the main branch.
> Add format:changed target

- src/scenes/AcceleratorRouter/ParticipantProjects/ProjectProfileView.tsx
We previously had a decimal count of 1 for Total Planted because I assumed it would be over 1000 most of the time, and chose to display that as 1.2k, 2.4m, etc. Remove the decimal when count is under 999 but leave it for 1000+.
> Remove decimal when total planted under 999 in project profile

- src/services/ObservationsService.ts
Include the monitoring plot number in the two exported CSVs for
biomass observations that didn't already have it. The plot number
is the same on every row in those CSVs since biomass observations
are always single-plot, but if people combine multiple CSVs from
different observations, this will help them tell which data came
from which plot.
> SW-7086 Add plot number to biomass CSVs

- src/components/common/PlantingSiteSelector.tsx
- src/providers/Tracking/PlantingSiteContext.tsx
- src/providers/Tracking/PlantingSiteProvider.tsx
- src/redux/features/observations/observationsSelectors.ts
- src/redux/features/plantingSite/plantingSiteThunks.ts
- src/redux/features/tracking/trackingSelectors.ts
- src/scenes/Home/TerrawareHomeView/index.tsx
- src/scenes/NurseryRouter/PlantingProgressList.tsx
- src/scenes/NurseryRouter/PlantingProgressTabContent.tsx
- src/scenes/ObservationsRouter/index.tsx
- src/scenes/OrgRouter/index.tsx
- src/scenes/PlantingSitesRouter/edit/PlantingSiteCreate.tsx
- src/scenes/PlantingSitesRouter/edit/editor/Editor.tsx
- src/scenes/PlantingSitesRouter/hooks/useDraftPlantingSiteCreate.ts
- src/scenes/PlantingSitesRouter/hooks/useDraftPlantingSiteFinalize.ts
- src/scenes/PlantingSitesRouter/hooks/useDraftPlantingSiteUpdate.ts
- src/scenes/PlantingSitesRouter/hooks/usePlantingSiteCreate.ts
- src/scenes/PlantingSitesRouter/hooks/usePlantingSiteUpdate.ts
- src/scenes/PlantingSitesRouter/hooks/usePlantingSiteValidate.ts
- src/scenes/PlantingSitesRouter/index.tsx
- src/scenes/PlantingSitesRouter/view/PlantingSiteView.tsx
- src/strings/csv/en.csv
This fixes some unwanted behaviors around editing of planting sites and draft planting sites. 
Previously some of the calls were made directly using async calls, which lead to state changes not handled and reloading not happening correctly.
> SW-7038 Updated planting site edit and create to use hooks

- src/scenes/AcceleratorRouter/ParticipantProjects/EditView/ProjectProfileEdit.tsx
When an external project profile link is missing a protocol, automatically add `https://` to it. If it already has a protocol (https or http) then do nothing.
> Add protocol to external project links when missing

- src/scenes/ObservationsRouter/common/AggregatedPlantsStats.tsx
Rather than removing the mortality rate chart entirely when the
current observation has no completed permanent plots, show an empty
version of it.
> SW-6774 Show empty mortality rate chart

- .github/workflows/workflow.yml
- src/components/common/Chart/emptyDoughnutPlugin.ts
- src/scenes/PlantsDashboardRouter/components/htmlLegendPlugin.ts
Both of these are in chartjs plugins. It seems to be working fine as arrow functions instead. Tested on plants dashboard.
> Fix prefer-arrow-functions lint errors

- package.json
- playwright/e2e/suites/fundingEntities.spec.ts
- src/scenes/AcceleratorRouter/FundingEntities/MultiProjectsEdit.tsx
- yarn.lock
Bring in web-components v3.4.28 to include larger dropdown height for all dropdowns.
Add autocomplete to Funding Entities form for selecting projects to simplify.
> SW-7106 Update web-components and make funding entities project dropdown autocomplete

- .github/scripts/set-environment.sh
- .github/workflows/workflow.yml
For prod and staging deploys, if the repo has variables whose names are
the tier name followed by `_ECS_CLUSTER` and `_ECS_SERVICE` (for
example, `STAGING_ECS_CLUSTER`), deploy to that ECS cluster/service.
For now, we deploy to the EC2 instances whether or not we deploy
to ECS. This will let us test ECS deployment without disrupting the
existing prod/staging environments.
> SW-7119 Add support for ECS deployment

- .github/workflows/workflow.yml
- src/redux/features/appVersion/appVersionSelectors.ts
`vercel build` resets `REACT_APP_TERRAWARE_FE_BUILD_VERSION` and regenerates `build-version.txt`. This step was unintentionally modifying both before the release build. Moving the Vercel steps to the end of the job avoids blocking the release; a separate job would be a longer-term fix. Will address the longer-term fix in a follow-up PR.
> SW-7139: "Refresh to use the latest version" does not go away

- src/services/NurseryBatchService.ts
Remove some duplication of search field lists and make the
return type of `getBatches` more precise.
> Tidy NurseryBatchService

- src/scenes/HelpSupportRouter/ContactUsForm.tsx
- src/scenes/HelpSupportRouter/HelpSupportHome.tsx
- src/types/Support.ts
This implementation passes the new `strings` object into the helper functions in `Support.ts`. If another method is preferred this can be updated.
> Update HelpSupportHome and Contact Form to use strings from useLocalization hook

- src/scenes/NurseryRouter/NurseryWithdrawalsTable.tsx
If a seedling batch was deleted before we added the server-side
logic to detect deletion of batches with existing withdrawals,
its withdrawals were showing up in the withdrawal log with
quantities of 0 and a species name of "<deleted species>".
Update the search criteria to filter those withdrawals out
since they are misleading and we can't show anything useful
about them.
> SW-7037 Hide withdrawals from deleted batches

- src/scenes/AcceleratorRouter/Participants/OrgProjectsSectionEdit.tsx
- src/scenes/AcceleratorRouter/Participants/ParticipantForm.tsx
Disable Org select for existing participant projects.
Remove "Remove Project" button if only one participant project is in the form.
Fix issue where removing then adding a project would cause updates to impact multiple projects.
> SW-7094 Fix participant form issues

- src/scenes/PlantingSitesRouter/view/BoundariesAndZones.tsx
This PR removes "Monitoring Plots" information from the Zone & Subzone popovers that display in the Planting Site map.
> SW-7084: Planting Sites: Maps - remove "Monitoring Plots" from the zone and subzone popovers

- playwright/e2e/suites/accession.spec.ts
- src/scenes/AccessionsRouter/withdraw/CountWithdrawal.tsx
- src/scenes/AccessionsRouter/withdraw/WeightWithdrawal.tsx
- src/scenes/AccessionsRouter/withdraw/WithdrawModal.tsx
The withdrawal modal would send incorrect units, depending on the order of operations in the dialog. 
This is a pretty hefty change to this modal, and thorough testing should be completed around this (Alex is working on this).
> SW-7165 Fix withdrawal modal sending incorrect units sometimes

- src/scenes/AccessionsRouter/withdraw/WeightWithdrawal.tsx
The "Exceeds Remaining Quantity" was missing on the withdrawal modal when By Weight was selected, if the original quantity was in a unit other than Grams. This was corrected when the user selects and deselects `Withdraw All`, but it needs to work all the time. 
Set the units equal to the original quantity so that this message works correctly.
> SW-7175 Fix withdrawal modal's Exceeds message missing

- src/scenes/ObservationsRouter/common/AggregatedPlantsStats.tsx
- src/strings/csv/en.csv
This PR includes a follow-up change to add a tooltip and a couple of other minor changes:
- Add tooltip for newly added label "Live Plants"
- Get `strings` from `useLocalization` hook
- Adjust casing: toolTip --> tooltip
> SW-7013: Observations: Add total number of "Live Plants" to Plant Monitoring Observations (Follow-up)

- src/scenes/ObservationsRouter/exportAdHocObservations.ts
This PR includes some follow-up changes to fix a couple of issues discovered during QA:
- Use empty string rather than hyphenated empty value placeholder
- Fix Total Plants & Total Species values are always zero when exporting Ad Hoc Plant Monitoring Observations Table
> SW-7198: Observations: Ability to download Ad Hoc Plant Monitoring data (FOLLOW-UP)

- src/api/types/generated-schema.ts
- src/components/TooltipLearnMoreModal/index.tsx
- src/types/Species.ts
The "Shrub/Tree" species growth form is being removed on the
server side; stop referring to it in the web app.
> SW-6240 Remove Shrub/Tree growth form

- src/components/NewMap/MapLegend.tsx
[Screen Recording 2025-08-21 at 2.06.26 PM.mov <span class="graphite__hidden">(uploaded via Graphite)</span> <img class="graphite__hidden" src="https://app.graphite.dev/user-attachments/thumbnails/572c4be7-0b3f-4991-9c9e-898be3562509.mov" />](https://app.graphite.dev/user-attachments/video/572c4be7-0b3f-4991-9c9e-898be3562509.mov)
This fixes an issue with legend resizing during drawer open/close
> Fixed legend sizing

- scripts/generate-strings.js
- src/strings/csv/es.csv
- src/strings/csv/fr.csv
- src/strings/export.js
Change the JavaScript strings file generation step in the CI workflow
to not default to English text for any strings that are missing
translations. This will cause a build failure since the list of
keys in English won't match the lists in other languages.
In dev environments, output warnings about missing translations, but
continue to default to English to avoid showing build failure errors
before autotranslate has finished generating translations.
> SW-7088 Fail CI on missing translations

- src/scenes/ObservationsRouter/adhoc/AdHocObservationDetails.tsx
- src/scenes/ObservationsRouter/exportAdHocObservations.ts
The exported species list CSV for an ad-hoc observation only
included names that were added as custom species during the
observation, not names that were already on the organization's
species list.
> SW-7376 Include species names in ad-hoc observation CSV

- src/scenes/AcceleratorRouter/ParticipantProjects/EditView/ProjectProfileEdit.tsx
Users that haven't set up their account yet will not have a first name, and thus show up in the list of available Terraformation users in Project Profiles as `undefined undefined`. Remove these users from the list.
> SW-7369 Remove users without first name from internal list

- src/scenes/Settings/SettingsPage.tsx
The `Edit Account` Button and the 3 dots were displaying on the `User Access` tab in the funder portal, but they don't do anything on that page. 
Only show them on the `My Account` tab.
> SW-7388 Only display Edit Button when on My Account tab for funders

- src/scenes/PlantsDashboardRouter/PlantsDashboardView.tsx
- src/scenes/SurvivalRateSettings/EditSurvivalRateSettings.tsx
- src/scenes/SurvivalRateSettings/index.tsx
A server error showed up for a -1 planting site, and was traced back to the plants dashboard's request for t0 data for survival rates. This was incorrect for 2 reasons:
1. Survival rates isn't enabled in prod right now
1. We shouldn't be requesting data when a planting site id is -1. 
Fix this so that the plants dashboard only queries t0 data when survival rate calculation is enabled, and only query t0 data when `plantingSite.id !== -1` (in more pages than just the plants dashboard.
> SW-7407 Don't request t0 data if no planting site

- src/scenes/ObservationsRouter/PlantMonitoring.tsx
- Grayed out for Planting Sites without any Assigned Plot Plant Monitoring Observations
- Shouldn't be showing for adHoc observations
> SW-7423 "Survival Rate Settings" should be grayed out

- src/components/ActivityLog/MapSplitView.tsx
- src/components/NewMap/MapBox.tsx
- src/components/NewMap/index.tsx
- src/components/NewMap/types.tsx
- src/components/NewMap/useMapUtils.ts
- src/components/NewMap/utils.ts
- src/scenes/PlantsDashboardRouter/components/PlantDashboardMap.tsx
This enables map to be reactive without needing a page reload.
[Screen Recording 2025-09-29 at 2.12.58 PM.mov <span class="graphite__hidden">(uploaded via Graphite)</span> <img class="graphite__hidden" src="https://app.graphite.dev/user-attachments/thumbnails/f80ff1c0-5c74-4775-b40f-52ab8273bf25.mov" />](https://app.graphite.dev/user-attachments/video/f80ff1c0-5c74-4775-b40f-52ab8273bf25.mov)
This will work for MVP but we can include pan speed and other options if needed in the future.
Marker updates:
[Screen Recording 2025-09-29 at 4.24.09 PM.mov <span class="graphite__hidden">(uploaded via Graphite)</span> <img class="graphite__hidden" src="https://app.graphite.dev/user-attachments/thumbnails/8de2b2a3-3b6f-4bd8-9506-a1ecba009b28.mov" …
> SW-7447 Added map utils to fly or fit bounds, and updated visible marker behaviors

- src/components/emptyStatePages/PlantsDashboardEmptyMessage.tsx
- src/utils/acl.ts
An organization Manager went to the plants dashboard for an org that didn't have a planting site. The dashboard displayed the Add Planting Site button and the user tried to create a planting site but it threw a server error because only org admins can create planting sites. 
Remove the button from the dashboard if the user doesn't have permission to add a planting site.
> SW-7456 Remove Add-Planting-Site button when user is missing permission

- src/components/ActivityLog/ActivityDetailsForm.tsx
This PR includes a small adjustment to the activity media sort in Create/Edit views: remove cover photo is always first.
> Activity Create/Edit: Remove cover photo is always first from activity media sort

- src/components/ActivityLog/MapSplitView.tsx
- src/components/NewMap/MapBox.tsx
- src/components/NewMap/index.tsx
- src/components/NewMap/types.tsx
- src/components/NewMap/useMapUtils.ts
- src/components/NewMap/useStickyMapViewStyle.ts
- src/components/NewMap/utils.ts
- src/hooks/useNavigateTo.ts
- src/scenes/AcceleratorRouter/Applications/ApplicationReview.tsx
- src/scenes/PlantsDashboardRouter/components/PlantDashboardMap.tsx
This PR implements live update of lat/lng/zoom on search params when using the map on activity views. This allows further navigation to keep the map view state. An added benefit is that user is now able to share exactly the map location to other users via the URL as well.
This also implemented sticky map view style using session storage for a more seamless experience.
A note is that, all activity navigation needs to implement preserving search params to ensure the sticky location works correctly.
Also fixed another issue with token not being defined yet, causing a brief error.
> SW-7450 Make map location sticky and map view style sticky
